---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: datastore
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: datastore-server
  policy:
    semver:
      range: 0.2.x

