---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-redis
spec:
  selector:
    matchLabels:
      app: datastore
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
      - name: redis
        image: redis:6.2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
        envFrom:
        - configMapRef:
            name: datastore-db
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-redis
  labels:
    app: datastore
spec:
  type: NodePort
  ports:
  - port: 6379
  selector:
    app: datastore
