apiVersion: v1
kind: ConfigMap
metadata:
  name: jump-diffusion
data:
  APP__INITIAL_EQUITY: "25000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volatility-harvesting
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: volatility-harvesting
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/volatility-harvesting:v1.1.0 # {"$imagepolicy": "flux-system:volatility-harvesting"}
