apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgBvcCqArSIyG8mVXRefYB6JRXegPxg9th0zmCh8ZLLNGNqCW5wwqaaQgppGZ8dfLV2xOiWgSgU40jxx9TiWfgYnewmhPWR2cbDJeCQg8KzMH8rsO05G8OSsSVbNNEvdKbxL5Q0iPAO8ih5mqeNjtfNERQAVpk3l654zmxpQkt4XtAObmolCIyWLNilV5JSMs3mSy8b6iit+rMkd4O9u7AfJWzq7WH3uYquGxgH3pcFrmZZcYiL0ue2bKGE2hvxjIVk3i+HYUq3wk8ywKORzC6WvsKRIGnSXgexacxAt2jfKCzphAwuksteLKz/fbX4rgUs32zBCOzEUoGxMhwsA2sKDYInpKM0Ijv0DkIfNFpZHahnvSgkO8169yFCL6JY1l4ZgMosPtRFndiiQ06yBzcvT1FTteWBeNTTBwLfzzfJHndmVNYP1yNEDzWDYDnVLEfIdMA+AG/cysYAuBEsd8V7bt/c9thLx2fxJYwNFIDOSG1AWuZBP8CJP+v1Mw/lr1GrTFKU1NksOhFZewzt6DT/Gt8hjVOX5gkt7Bo/WodVEsIJ7Ojdf7Beu8+L3e+GzrXnqt0zNhOvupSvQM004k3Qh2EvOqVqeuzCGG0KrRD1/K1SGsawoKnmQFDJQ8XpOYpnkowITSBwFVuZ3etzPaxgPwdfHlwObOQug4+8GR8d+IQ147bUq6hjxWFESNIw6c37Vy4B11CYEQANRb6tl8uTIboRVQA==
    ALPACA__SECRET_KEY: AgAhc//3Mc+bzhhIMLbGV8pAHK/s3V1XOf5U0P9AkH7BU/TQ/FFmljGd8w/2sZs5TaEHqs7hBzny7YAuaSzay2HbO/YN+1vZOpMyjZwFKYfAriBdH1lb9fTUCmf652HoelkxHdcWflG5rbm/aNR8CuMvjccc3ME4a+XybtF/wTdGeDy1rzXw8bR31ot1aXPP0XRXPMQjRpqpJjZLC5SEzu6RkcVvYG3IJ4Cl+a0vsXDzk96ZUZyQUOPW8jLvjZAdbkIg/LEa5cRg8cSR4D6YrJZ3gweDBvQyuN0/XrN3FCDyGqickq1AfVeShlDkjxZlFzY8Yhzz97RBD6XBmGvCYijQsAWMkhx5hV4xQFghFMf9RNMf9qnBGWlCVWbLWqK0T9eBXwc4JECoVRSdYzY3lmIkRTyelWwKEXNmUEH65bfbLEXtgO+aXWQLO2PDWswIOUlKvMPVAvA9x9pBsSrNb9yazjP7bTW4nEgfRYqMBLQ2yTtjXeIv/cSFqHA2C726wV/ENYoZzFan3mwsCJ6yfqTDNg8nDnbZ+TVL3d27C5XQERYTAZlxmzcaHsQGV+nm6GixYZapq6rU3D0zkZgLBiCzX3Ajm6cKvb0G/BLGmYiXGgp3z4x2oW8ebzLPTmzWH8/IclCrkz0zwQ5kAmKx3pVtkc84CbkA2pAXGjEwvko1H8jrGWatZ52y3lWzj33GEKxW4PkLbUCh0k1uBR7McD4XDF56HY5BAxzzjDltjG32CU3DOH8oqBeI
  template:
    metadata:
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

