apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgAcqCn3wu92CxFdnVMqC8eIcWfWZJ0HgY37dBM0dDEt+5pjx5D1d2mpNl/cgtIjoDifkbpOZasx2IJD+5IfoAkeywmJQSByOYSxEHu+9yMtt7Z4bKKH1GpAfTTnQxwQu2Q7kw3Ltfx+ptAh2oVN+yrkjc1LLNl+f9yDpsJptvqEwKoac7ddaDcaU9QOgZ4S+4+GJOTPdHsTmbkMG9dUDHhclmBachiIHDMzVoiYfHJKBBS7r+Mo4V16SS3ISV4UEgbA2fagj2wJKbpIgEls/6EVMrw4YYuu9YeWAC3mv4O2/trc2dKjSR46lJF9Ug51kwUA5ovSaaW2xz1SAhheoTlRD0rbCD/aRQYiTQSiN48Y5HDYHOLjbb3jwbV4Po54heqSMkenO2E5Pk1eux+dXYyPvm7OIpiykbuPWdO3nh4kh24EJgkiDNkw8CfOBtpB84mWjR7dhAH/93N4BJ+TNBRW5xKdiP+q0TvIYl8XWg04Qo5VIdJn1FCrCY22FOfMt8S8pJYWN8quCWDmdWandjmI845u9ogYYPRWJuyMuzY3YpptM2Iw1n2FEHy858ldPGlLgk2urqy69M5t6G5+JCZCLC8Jr78xXYn8SwgY/OzZl/xhE5GUa7uvASLEP92Gfk9BgwpKiTw0VpWcbgB+G2we985MiAYdoHdh1jPm1Lv0FWJ9LpJ90QEOm77kvO2S4Oib2G4KK8p30cnezsv8a5FZU1rcpg==
    ALPACA__SECRET_KEY: AgCndquCs8ZYHNegaRs8Sv+7x9eYV3CN7YA1ERLbdpMMjlLeDMESIsW7542PMwkO7e1HDVppF3H601yyo/21QDEtFhSe0JRnd45NqRxmAd3z/LO1JU0ro/uG7xEi7/jzpMaESqjhQ7oxeJ0oVkQNj2hXWQr+E2yOf4pU8SdsEr4/SB/ECA/q9yWooICY3FwAoX0bG8JRlKLnjh3ehZaISkZf90bnUPo/Itu4lEhjtJBZpwAJTio2K5L6dhI29ciPzutbrtJN2+8w9i31hSHoyU9VEcPd9vel9YdwbnO/X1qa5Os/9GaZcNrYgD6aoQmQzqF9Ktfjq0rLvaAmgv8X49QdegpZwJxfprwn+HJwMH3jBtUYOjdy4ev22D13l2yI++rhuH8UDBccw6gcuGwH7HAubcXrj11PQDeFXqiuLRN0JKCLBQ/rvBKDMmh5dGGaS6hgXLLdYDdhagJJw41PuuRQdsSz+VvjzWjRwKbwR3lUCHNB5P7vtE3SRPLV7y76uXz4ZLVlcPsUZP2HJ8aaaGU0uHqPegJd9iRfuX37+vQdR+hHXxN9Z73HGpLBUfdbTDBdR5P7FfI/Q8wiuyZpDUeFOXAs3cI+Z5gpG+TuRuOsPF0Lmi/4Pa5Amj6YY1ZyIODT8cDZRLLKCwu6f9rTHuGTGwJXNnpCHnrIgv/62ReHVKzjcPq9sRaY8lx2yMfCqEq8i8aQGFdMVaFcCP7nJjdynvuDBDl/vvynJmrcmvJ9QJXiSkI8v168
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

