apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo
  namespace: default
spec:
  encryptedData:
    MONGO__URL: AgDZ/w9pnTq8Pbj0ehAb90vOBpnKYq260WvyaQ9g8DU2TYDBC73kbHe1PV6qgW1hckrq/esaLpmDkhlWTVHjd+kN3W6H2iLNifdNdjmc9PgBaBUE9c35Bh5BrnsNGGBwAfJt6xZL5uhNMB0BGSvddD3Mh4mHxWyM2j69emqXjzh6095EgMypLNgkhRI2LdAw4PaGfPk0fW9kcC9TBqsHSgFTajY/Hirr3jBnUEtcn9kLET43MDLIBNaHM1m/kIfsgmujZehQmm8fcuddyPbz66klnzVQ3iI9qkXW+zsDJq7xnYM/ZiOKH4JFsH1J4gN5FKJHeD0SVjTibuOY8fTl8VlzlcrHpdM/0WxG7EHnFAlSq15gjx+EpIAkZ+CRj4erlSgrDScNPwvRuPJ+9LZ3JUMej+wLD5iTpYJ8SK7OK0tZKVkov26JabDZUwinzvADj3BXpk0oj/weaOmAv5b/3qD0AlZAljc3q2omysvn2UkGw/25S0CHZv2wgH5VSZg56JCc/hIM6IHA7yUmfOu/x2j9WqaI9RjtvMcf1bChjWayLCopJpzfuzbCjVnUoZXOyP7S3c7TfurpuxBh9R6W9KdZMVw+S/w1j9Pg9aAxRxFeOlRyzdCWqAP6cI3vS9O8++OiW9v0OovENqm+daeXQlezXkvbxTx/YDz6u3JgTUrNE1AhPO7+uAtXDs22DCsXuiWE8pgH83hAoJCFuckNXmY8J5czRUFxezA2svcysC9bU/eu2Tn7m/u1HLDrQkMePFokC9rW8myam3uI8NcrMN87b6M/M7qoLL7514fgKCyqTOK6U09oN6I21dU82/vE9X6hZdJv
  template:
    metadata:
      creationTimestamp: null
      name: mongo
      namespace: default
    type: Opaque

