apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGO__URL: AgCku7SQQONZFNeA/zjxuoSwahQq7zECwZlRTK9NusKiIu3IeHpLtvmu7s8flj19RvVS/L4M2zbqC0iONfmUxiHd/+xpg+kw2t/AaA6fc+T4yMMRtpMSNhVIuTncYEdyV8P0pe4D432/KPS0EEz8BAsD+WO9v/c95A3upLPu0WDegS4KLGpezvBSZJerCM0uD/EpEdMbCyV3X48TB5zy8zG6gifQs1fB3t5p94AfEA4SgSe4sTxvUSxjcZZl7HZ7+7UC/RB53GCUiZvJ6ss5dZ1rArOB9S/2mizlpltgcW57Tqft/hgXxSwGq59dQVtTGp7Iun/fpT/WoUYCWpzSBKutiLu4ZlfFhvyqyfiXwoWm8z4QOBKCuLmw3koqiafuiXSLb+SL5rEjfCVnH4q2vkf+vrUTmbX847WRefTMUwIJV0qlrPyDoghJMFTvB5pzpQGC/a2Jc1eFtI7NwZltqG7yYImSdC3b1LE4KWKbzJqXYF4m7/4VBRZJIrMdY/++D1XB8+teDQXQ5KLzYUEla/xiPLnWQsApCcr1JJm+YR82shtLAuffWzQaq6wHgR/fa5Cabuau4AduMb7lqNAcS8Z9jZwmAnHqVIOT41BhJ3Lrw0NmypPyTGK5WoCu1Mx9CrPynG+gZ/rvhu4TpUUh+QSDvRR5OhTVunq+LGehGrRLFy5lw/MWyA08aGWlaDXRDOgfYCXCSdSqvVzkoggxm/AmSZ7ZRHgyRsWkuCa6yW9p46Oi1kiy+WAfCxmexfWblWYceQQFyqjwQ70XE8serExv1BhUu7hoGzAwzTaFjy2CuTA6ThaMCREaRJPGtoPU52OzDdCX
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque

