apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAsQt6Vo5wrjmSIONDZ5f3esp9AcHm99mPl1oj8QGE8MoWq3PnAJ8y2Hw9swiPU4YLP1LXFMQcl05I4MlVd1NndSrSVCwHEC/lR9pF6btIwQ9q10QxpnK6N2mz7NcSm2QMmMCPznFs6Ze//NiGBEnd+5lcQH0TOKvGGnuEHcPSw7pEBcxP8twOA+CLEWwwOzWkdz+XlVkWJLJdTqiaDcw+nXI7vcgZTDx4brVd63Cw+B6IDvsOnhEBka/NWVoHvglO/MRFCrcOxH2VBKH2xbG7qXg57dETN6intmfDVO52D+qJdM54uxNIXWAOdPI3GHN/EiklZjJpyX8R7w6Kaz9j0VSL/2tzxeTSnvCjmNyFbnV0OcF6xUvCCq4efXdFzGuklsai2g/miSe5BtAK4hcOejQhNaW4l/ggRBeOHSug9bm4MCeGsNaDOmvK/rlhEzDKL/wkXBiaL8J+cqhTN4VVL9Anmn9HbrLYdDUdSmvCDnAZTEsxyDU0R8S6AeySJiy91wLv3vn7VNJR1dawTCcGHb5oZqiZIFxKNEcgvsptJpswwZCWo+qrqeaknmnJDrKUo0rqTQDWrAOmlyHdkR5OKavpFNVTpQHFUVVWyO1+VnMxnj8iFI452RA35+fCN07XDVG7V09DSUPUvZXLxB7NIefb7VBn0IBqI+qzxNrahqNMYRnMRD4Yj6fXJI9ksYLWRMrjk7cIq/yNVVQYqHPQcEWQ/WecvenGwGn5naHzalnL+nE3EvTJUus8irdy1lmfdFbfnbTk+JSIwBSE2FGuNyDT1wAXMDMGMpxRpLKzvbe4=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

