apiVersion: apps/v1
kind: Deployment
metadata:
  name: tca
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: tca
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/tca:v1.2.0 # {"$imagepolicy": "flux-system:tca"}
