{
 "title": "Trading",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of trades",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(num_trades)" }
   ]
  },
  {
   "title": "Gross amount traded",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gross_trade_amount)" }
   ]
  },
  {
   "title": "Net investment amount by Strategy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(net_investment_amount) by (strategy)",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "Net investment amount by Ticker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(net_investment_amount) by (ticker)",
     "legendFormat": "{{ticker}}"
    }
   ]
  }
 ]
}