apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-data-relay
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: alpaca-data-relay
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/alpaca-data-relay:v1.3.1 # {"$imagepolicy": "flux-system:alpaca-data-relay"}
