apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-data-relay
spec:
  template:
    spec:
      containers:
        - name: alpaca-data-relay
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/alpaca-data-relay:v1.3.0 # {"$imagepolicy": "flux-system:alpaca-data-relay"}
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: alpaca-data-relay
  namespace: flux-system
spec:
  policy:
    semver:
      range: 1.3.x
