apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgBMEM0ZQMNIViIEoDHnajZyKdwnmQ7sIZHWYLtHbrLwGkWqqFIuQ22I2zq3Oyv51IuE4D+hpATHnIUZoIoDMCnDNuAcoEsucUyptNFVwvrUArxDx787v3q7MV+GBLu166wOe7aYzS30cdOstJIUuE0mOQrJBE6Ih/+Tw628wBY1NElmg91XuPpAnSvtaLby1NrWIPAynZxXHC496hG2y+BKZuCLirBmRwBg2NEUABYkmBjmv5IJRrTFDv3VRw2AStVSRlfnNq1brvq7uTdaAxo/RNawuaCAOB9px4HlI8bmenRPKweWeu4pTavK/LEpSGxXfoPGlKuSi09GTijN15bZu9UeyXTXYUF3N0VNAqmK6qcX8gJL/Fa832A17GThNvklmFMyN/A8uUpKrWUjmu2aKfpyb9Z8w0gDfX9rB7TkDVDmTzwBhEPOVqziRI2aG1J0apsyWnm9B86P7lQUQPegTte002ihe18tNjJdFJ8I48OMgrG+HyvMFbhQIzmF94LODIdLckKZwGVPdD81HamwEEBTFgQyFJO4fGLskNIQzzlPJ72tE1rRuu/dm25fC0n0zwyEZ5bHasmzQsqmDNCT1SB0iUBCJd7DEBnQQ09RvQj/dx53Vu+IKxOQMjFKPbND7XMDEcEP15oYsi2rmDiOYJZGg4X/0a/63ezFrmn7NoCB8qccBXgmgjnJRk6T0TJvtmpzvqKhWTHn7yZVpg5I8Fgvig==
    ALPACA__SECRET_KEY: AgBeCFPiYwPvZoi2H+stj7s1sJM1wtY7UqmL1MYiVY04OOqxUSBWdVOsjddde3aRJgTO1d0cK5CrVW/vwGLCAJjMnfuTskYyCV95C1iAOLMG1VRIZIbbt9YqbOIcMn7SPuPBAbjlqjYXbESMzQw6/HKpbgZclSAlX9qxTK7epIeCHskJg8JxTbkcDfsGZKvL5XQAwmFIet55nle6dmX6OLwdpCMz0XE3mxwMf8foYwhV2ebcWz/mIHtkbTv8tWN/EnCGU1t7JDuRq804S+Y1Um+x9OjbXLVa5pPGsQUHQlDi7r+hXzfUTs4j08wMJbz2bXJxQxiQgJqlpnykl2nCQweL200KGW/2w8zsBes/vwpn//9HwdCky0chA2V41AwgBwGGzXDEP2U3XSaMXklBi197LITK4A61ALj4GdM8xFHr7GQlC5tgny6ytm1YrbHyYcgzuB0muDFoYRwN/hwD3qEgTaqK+J0tZKuAt0hK6zIzrkoiC8zuLqLEEw7C9o94JG3Bk0THp2Z3BtxUvdTqbXOqf9sU80F5vO93Y9BdIQqPZ/aEUNn+6TeJ6w11rocTD0aVAJG3kLImSNpf3JmLdQV22vAnUa/pNb0lYLmDjIU8Ql0x5GJckIhBr43pO+3n0qsYC6D4t8M30uIcm8Ohvm6veSNkb4YBSsvrdPfjdqWjJxLQ3wqVr5FhojT0SSHYYQVkuGnQUkZwTPLAYrcYJIoiIuqtT/BgczkaCds5U9E3sQslc4+hAazU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

