apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgDbn7SoHUujTlaavZP+fUgLewOjaJBraAxCzl3wZDMZEnN1Sz0J/LBMpJv99Z/PN3K4wz3fwHk6nbGhO+rTwEyrEAWRNLa91wfxEidf9Xc2n4kbbARitoYNzM3e+hJjkeHCrfoirwOrLahnJ4p6YWGz/fdX3qWsPz+LRR59fzQ4UpFqtAaTK+jVO+D1oYOooGUza0UrhSvfjmigLRQZ8HMat5K7VE2UdzbZbChkbt+4W+C6Zr0+bQ+spZa3ATVLTtGrYRjrEvAnpESd/USSWhLvxsVh+CqwTscddXhiDKZKFN9aEO2Yc28tzAVFvnItTJ65zoTBQ+P102RKC1yeVUZc183kIRcUWI36on54oPdHIJZbHO8ELiCwY3az0v/iigjObB40TiAe0Cyl7X89GaOAWLt/HdPjBsSNkz/RqPzbJz4Vrx6gGU2Dzzm1b6LyOVkaffyk/SbiT+VY1N37ZXgsLluHmuRB+ajjBhzSNdmOuL482UkaoabhwPmTHI+RHl2rB2XqAkZh5nI+flydVkeuPd13oTV+k7QWFu6thXHE4N1nOdiy2dWcxcUDQo2bpT2pREx7zdaFqI6l1cc5h3Dl1YSyR+f2flxw1yz0GyqkDaD+NLcGwvQeYP49LpkJn4kC/Gjit+wt4kwBeYXZay0IOg160y4qJIXsLKT8nE78yzMhTUtrb5N2XEqXcyx/kpdJ9coyPQb4+RgyZIagjel1+YkR8A==
    ALPACA__SECRET_KEY: AgCyV+q1+lR4lmgFnAPtUs6iGmpyxNlFh1eV+ce8xp2LfqWfGu9PMow5M2x0RmqZ/JjGm+yHSZTtbwQnkhaakk+vjX0k51vD19vk7BrBRolw1grM7/d4UlssYnppLh4s/dy1JogcNMy3qG8hMdroAixQb5Af+5tuSsouKhuFXNEG1vgenJw72w3mMmUwcv8o7hAjJanc5Q1fAdxy+lkS53q2ulhPYo4kD9aA9yPcOolZtUrbmw5J/YrFzA33+jl0p1sD3OBa5z4J/LvUzn/c6nKSKAxB0IZ1AZ2/6tRj95uUmeGmhZdumohlC90emmfXqrLPUCfRRtu+ur1LGDlbAmAqWcaHt6DMNz8AknPxYCmdlOUPRRzhgdZ3yTLHHuXGq69EbzVt4XmbBog6K3RgPnZcmEXgZlS6tGeNHWhbyVnXOxnYAZ9nz7Jdh7cGwswV4Eb/mtaE3jym/xyA9fhV83Dwxn9YDlnPJ4BjMhyyRLzUFWtdZ0+rM1y4/KrF955Hj3AJ0uSwYv2lVFTDaahc9OKy8zufTxKyywT+hyeyjxy7HYfY+vEkNio6DPB/O4543Zwzpqe1gQpz7Dh/VqcuNirh55t8xRQClV7mZ7QM46R+273T0/+F+NoTst2zmRnVOrMblbIZvCSUcLHXmrVDEyYmseX10SdInSi4rHP5XOf1nOZkdFCk582Q2EEzv0Yr3L7n+N/Ef9GuhxTWgYucnkj6OX0a+Kw5DE4ua3aS0EkGTPJlKeGxNv1c
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

