apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgBUa8Sr+fXQ3A1NXX/EEjdp1NBrsTrtZFeyV0KOgyadOzBM1a2ormtmtyF/xgzS8Jdpr6Z223CdXsjYkDbG7NMExR50WDwSSil81TUR9C7MH0CdRhHjp+3IJ0UHCWUpfhCnyHVEMoaCj3iLGIzBsrSwUqeHGypy+4T16RbEDfvWanyToCAXuHqN8gCVMESxM4e3WY6KyytxHf4hEwdhzCmUBIZ3INABcvic8Ly2f6wCT2QKqpJH8tPwEmuqrAQVUUU/qME/GXu9+babcuo0ib86QGhGSZOmqggJYT64su1LzWxEVC845MSHGuVchiLF4ObMnlj+2edL9/l5pzYndz0A2FmuFAmFiHRsmmiUA7z68WHyQHRsR4lF/wTfzysRE5htsWeOTnux6lLByUnr2vcvZGSjyGhcYQAtYYBXM8q0qtMCzWOo+Ol/8Uz4U6BpS2lQNmqnlSX1TRVTd+ET/7cAVNAp2tfr14H04irJDCysTVtvR/rR4t+De73dnJt7j1XSSxt3XM/XZGTgsHoQPDsem5n1ANKPn/y40oLHzdJURcfCajW+yJuoa/HbOcJwzxvxQwW9Gn8+y0HpChFB7sIGAR/3pfjxrAKXDR2q6bilDfpKrL9OIgpEC8c78KlJ40+upuuXnT/xO2y5DV0UJ6GGIbCAfTeqX9wn2ZV5fnRIPS1vBwRmssdI+9UjBFl8A6og6/GTQRSJa596jChXo8P11yN/Sg==
    ALPACA__SECRET_KEY: AgB+IvO8rKS0I5hC3ozFbmUyxgkXW6k6wHhS2ctKBF8PERfqhrLkmllkUzp5JQHIEHCmfICrZNR0tljY9m8JcImNg8R9XQRxrcY7/pjUpTWfb7kRduX0LCA8BdbiidQX7/MqnhIDXuopi1J86/qDMx3aQ7XrSA8EN8Q6+C7KXlHaz/MjClbkVQbxZfWQrc8qrbegUZY/F5/kOLbC4JpSgaCI1gR7RAO03fuQ3UOq3XW5rUm3Tot4oLaOa5YwyglZwWlMjM0nhTdCLgcRTrtZV4XtvdvMfrgIFc5azbIPEBzUVFSqvBnQZucCvDWJojlF2QcK7678UNp4Cuf78xD8pZhTCAmjw7C0EB51xKAZPCSpMn/h5NHZ3M3fXs4f+GIjEHobQmz0okMtW2Hok+4oRU4ch3yKK5FJ6ppvKWVXigr8Lf0G7lkftLH6eHSXE7rqVd5HQneinfvyDUsyOUe5XsWoTw+8ZHE0BrDpziry3KMrgXylZma1/MyyxIAL2tGmBTdIWmS6Mj2LD5tyvfAOEad9BEYp0W3mYFsQ8FIfoQ6BN5ohXOeo175YkXou0Zte40XbiL313aTK1qwp/ALhLEuAV+cD2xZ7Sju3jE7pFIEcalOHtDYfLVNIudVRsuv3uYs8Qrrqm46n45Xnnl6XbAO78mQVz63UQ5UX+j6Jw+hurtGkDPUqvTZfJvNv3ENmnILSNeXZ5SxzQrJYIHVR0KZk9c6hZ73eRmzxlhDfyBX6rTwhgO0/OWCt
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

