apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgCKnnhMvNn+G9GxIKdzfstUvQ3r/XcwJmfrxqA761HVQeAxHpKGAGmP48iFEIqfxv/CJ6eH5IWgAY/hw7zNVQQTblcFTZ3o5MfpmnrahS9OjcbomEwrjVwWOKeDUno5BzIHHQ6o1fN2fxb2FNX4v+6cJuHc6RnmEjFe854/j+zwPa5aaZRYSdrBHI5j0Oer36CNiW7HosZZ5Eb8qffHu2w0uFc3A70sADIyk1COf0Gr8LETIUe65LYM8uXAHDRsg8xfsAiZfoNNq1TXlfq61wk9ymiJfiZbxvuSYOmAg8gkri9fmxF2cXxkAQRBzjT8TMr1k6JH9RAYNCq5ojE+VukVuT6foi5XYF/IBjrAJZNNEGWOiuVCctOvTkFVi24bIRojEib+ctK9Q09EOvzM32rzhN6uswSB/x2KFgzfpeYV+JzIpmXDBkMSDSksVp40qBKLL62HgVym96bWliZTDPxzkGVvfer8xf8mQFlvRCmABDVjU9n6vHP7T5exuNlKSeriqXlH9QOjkRzvaicaqAX+wR+Y1WEVzlZbM7a0MYYKhvo8/9pTHCCLApG0UsFjW80bBuyWKehs1wzRaMv8HOdGRZq3/Oq8jkj0N1YsR1axJGZwVksWhZWQ5DEBHo8WK9QfIPSJnbzw7/JlhLz7twZXnFfAygfVzt77fcrwcWRfRaUcHBQ+IhQ9kIzec1YjDzYAoKuHMgdU5rr9tIalmDKdwaapSg==
    ALPACA__SECRET_KEY: AgCBGyvkQrRIZ5UOX0Jc+EwsW6sfFaSwzl2YkaxQ1gEr8Y6FLcPSw70lEFJyL1TSPBiJHBI9ZxeQj3INC/jScR5DAMEvS89BycCMGSvDoTaDIJ6wumWcFSJOPhLsFdj2vOm8R+360THxWlCLI6qFKlj5Dd5VkEgbM7f7eSbWfVWkqZ/AcYzv0mtPCSow7v4+57MZqsgYp+VPXdMVTe6ovwfU21V+IHvZfx5dgY5kNM8um6Yu4ckXWiO3AwwFzKTZbIjCRMfFtI6CJNXnD7XHkjl/Q+P91MY4d6txgUOXPHsdp+OTfJa8UEyXG32WciS01oFYj1ubHB/hcEE7hav8xdYqhtD9YDFQCeus+sMLGwC1JxDWduYgx47k5uc9u9PrrmyhQg3zYGxJl6XbBgjvxkxuu8A7pfthNnLuTRqhoAr8X7+dptNebovp1neTB23EgeJTQRphPaHZmDIbDYjqUZJeCD8IQK966wPNv95NEsyS6eEf0bzllqkADBLtoeq952XVF7/i+znUQPyUT+VdFIP3CQBFqg2jqBzxu9QmcDHDJpYa6XLrKuumzl4O8oJLRsyc5ESlV8/KKM7t0tMSFCn4DEkjUvqUtZvB2OBJCLvj7QkTTasIEgXWl7caMrPoTzyM0ucAXex/sozYW2jvN9ZdlrurjfTd17Zj4WrKSP66G4vwd4kwTn6JgemR880OzSbgwIGTnupsDgGbRc8XOoza1e1Tdg/Yo1Yu3C6s7zx9dOqKVYdw3hCx
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

