apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgAl9rvhP7JFCHWhDc5fbAB1sCzrtfjn4Hd4VdR1L2p9PqiCU00qQEFuIBXy2KuJSLfEP8iaBU3lzxtk7bbF8b5A/2gpXG6YrIXiC88Wm6BEre5doI+b3e9wsPoMuMqxoHPQT9JeaPAJNydYv8aE1cjLYXZj+vs0flzP8sXgRREJYgxbzlWTisPghYtPiDpYC3MtNJGvmyNnIg+kCxhdxi6EJhBOozmuzKPRzq5xDnh1n4JZFDHAOOro2v5uKl9EflEc5t0mt0Wne3o+09R8oOSc52b9OsRuoht2/trIUsRAmPY/DsXpLAYI7rPxEu6WJlwQafxszFA4evTB04l78HNfYOxQLv2M/JkzB3C5OchUhYSI5MewpBDpv8riEebGdc9EZwmTJ2GFs8mZYw8gA7K49J/H0UaWKQ69I4mWp+c15VCn+qir6d0khE6G8TpFrJrYlXC6IvJe2qfMXzj5vHWHIVtK+6y3gWRJnkPVSv4iJ/nUl9EiG8e8Z7EBZjx3aiEo6hJuF1VM/NoF3kOQk6d0HbTAQiWcUqG6zbCSdvcy+JHK+cpfCU8RsMtfkm/GW46MU7WTSV9gj3pubjU9vdcMQjcG1Zu+7pWs9DqrShGFoGnJ33vUb3v8ORNosTpnSxQMiQKBfMGqEao8pfMZzM50ZfUbmfoqJFzXcLsI7hugMC8u7ly+jV06E2rDa9nBUiiW1BcJr9oGXsA6yYw6OxV+fC9xQg==
    ALPACA__SECRET_KEY: AgBjFR/0A0wEunSxwg9YbxRd1GcvVxzcx9bh5t1RG9Oz8L/Brv4gxhJ/rK2bdfNBFr75WAB7GppXv2vBwDXkMEyESqmWmDpVQymRTNF/gktFO1AvSR0i1gGTtC4tIn2z7nYHYyVN9qoPytlWEwzRpelTPIYKUlMtIPJ3RviRIfiBlmySs9WaVBD9ipwz7WR9XUIlYvf4OtCe9oo+QSW0GG5ucLB+H5JRUF8RbCaam/F938W8uGY6aREQYAViAoIF6+PFiHQ3vruHzSZhOC//3mqCkbae1HOlyh9NhtkKYaX492gf5JkDz2dKnf2ICKESkZQ6ro1hL/NVbTVNRtOG1E9u4LoCFRxUvq0myRfCRt4KlHjZxNFrmNNV4VUvMdnHcXhMcsLuNAVZ42cbwZvDEdlHvv9pNgJ86nkzCNQPA9hZeWGPcdEQ6fNxJcRsfIThGKPBWy7gPXuZxL/kQ2zJ16JGUeFXumezsywbbRyL0uIqt6NbLnQvdMqmITiRO03X5vdQ8jfM9wG8ZNh0LZqiUoqG0i1KNmKyze3/ntAKf835CSsL8pNpzwZBa79EgEhPk5sVWJJmiwpi+pEoSl+ejI4WOPONPx4ClWuhrqmsdyjkZLXX3vCvLoxmWApZngNeraX+N2+1lLWnjaB+fT8EM41kzlbfRXGbiT4mflYGPP+8Y8D9jrR/WtcmNkTh20fKuIZxgRaxz9sIFktes60MBwFQKhfZ54QjoySsiHWmYY7viV8pwgCP7/EY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

