apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgBBEKC34ebgm49d7vJHjbbHXjXWfcNsa97A97WLacHRCYvVhH0Gu+RhgjsqS9Uy1ILdXyahbnL0clt2Za84dmiXkLEitEd+S2ecpLgEBmxriQ3RTBrN1vzXpAuSkRMKErXhKL81p6A3Fyg2EtdUhpcXCfDaGq3nSvREAeuTjvmfQTqja10W56x7JCVb08RXSg9HbBecLqjbajFzR09wMBY92IRi638m7tKhOlMg4CYqwu54JdemsDpdXAJCD4rEp7E5RjD716l59ynecMjOg8hTstdIfVOG1RA66l8/hNfiWCAvk7VequmZ0+3AHwb3X+lA5icOPsG3DRuuo/cMFCOBTiuKPp65KqSoDf2gPrdt/pbHfyGfhgIcKxR2egK1GRpL7If33YagxYimIrYoyzNdJGctgNzMnacw6Kwa+MAukkWBWmkokHVwpO60fDhHUF6y6c1ZS0yyBwQuHMMVuSjZf/Wi6N+A3qh86W5V+OL6AddDB8ac6w3WV8PHNuH+DODiWzLHW5LRY3zaEmw7/TnKk9p+MPGD2ScG9daO+iZ2vvx1iGrxKJEY5sRlp0QWI0Zz213gq3ukmSSJG9RnfcaSxWnbEuUbhJ3HrE0i3g7gzrFpMd3jEiRUc1o8tA0PBjx8236iy1hQa9Svdc60a7tToRW/DmgJiNlc4lM4Dc14ideckqDzPcZItNI6YlQVpRnE/gDVKInPhUOk3DJTtaiJ9GwExw==
    ALPACA__SECRET_KEY: AgDZEpIMT106RkLA0u3SVUnC7zASDkFLZIl/YVjqHGJlBWT1qdNwdAQnAOyui1CjMXhzbAqxeUTNyMsJFbY7YF7yeXEaBgiTaM9g/sqMOSGSEIM+hPBtWldsGl2CEC4oIQzB4+bRtV9juyGSf3dc6N5a0prBBt8qt8FmSsObTmha9C/pIQCceT7f4SCCAE02pD0OfsbshrRJnp2Z78ZgJ8vZwTjYzXjbRbKKEkPjS/rNcfTTONvB/fECE/40WSaFY3shaKdKeYqwIdB0UOM5XQKrLE/n8yHmuDuLdS9D0yxTuIWAWgt0d1buwUSnZa3rRjPhutmx1VWBIuN51zvS6RXZy7une6HoXBoirD4CWHGZKBEnISEKRG0B/OA0BM7HpL+SVhHZCs+e22Yc7Tb0WQ1w7AsqME2+TZHiKbBOl0B6o1P/vARLqYPPiD6e/w4aJXNjX1XLH9jdQWhMIIynHLaDVhFH3HxqXRp/hHSgu0hc7Lqr9IbbeRYUVHOaSqPhaQWrpQurBT/CauSK6l1fjRlWg8kW64/OJtdFp0pi8kmwbN3vIzlo86YSGoXo8raZDRg8woSskL5yG8XNiVDZ/fxokTY7EA2EjhFlN8U+/2CJHT7Csyo0STavnYBicYrjmD1N0KL7M82BM1lbZdgxKzb6SwJutpJZBg9PMK1fSt4CikaLB9ev9EcmNgf1elvrsvvuA+n0T3h3HvyclS4QGLAMc+ckiDyeqLbf7t4htPtycLD4HVe2m+ZZ
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

