apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgAN8KOIK+qsQibFqNlLQLElKXV6slIF4ZIjPdzvLJmGbMbgFmS7E/WAOJlHtzCQH8u/l3rVQZE4yHsDWKiNRATnBf487e5YA9USicKSk/wO93g290q2eg/FGIlgffvJFXFc8c71H0ks5mY7oDMFx4BvJqtHJ9HSxHZnCEuo1nuNerPxu4vOWmpgVBpYkIo/8RuHziS3cORMJWteS+DfblroBzZo5t1MQgnDNjFYV13ZHSWYLjvZdz5vcV7UIOiMOEbVdMZJgVybLrSTwSI2YTlzft7eTPipiIqQSoTsLvo29V9OLV1jw1c70QASVZpGmFIFRKedJ/UkXWMYetC2+5nn2nF3U2vhgk8xXTX7l/q94Y9oQrcBO3SVeeAaD5yiao5s5exxvz4LDwRqhcpHY4uN3zAQZ/A3yKGkGLsucyAo3VNCuZUM3+Mqh/b7l6ipolBqUtvQ8S4zp0sdeiindzCpWWBJvB6PFTnNIyQ7Ah4iYwnFKNksmx+DT9D1RK9WOpxe9mEcox7vWA0RrU/SJSIE58nO5R1I4J9sL8oEw13cAL9Baij9bPR71KNBK4Kd7rG9TsX3KSUXHGaA9I6gH8M6MJks8sSe5HsEpsW+cAm7aMj8t0aX965m0nwwyGaL9+mbPy3BfV7Oo17P2jplLbVT9DzPetlULaFa2i7/yRhK3kqStgqB6tZ2+VqhyBxti7qZrOz54XwtnaHjqhwbNcpHpiCVBQ==
    ALPACA__SECRET_KEY: AgBhKZ2SF3KCl8ZQcEpxUoLEEbHuVR41xMaMjXhCAF864Vt6Yj5QsPkIyDAnrZJBZXL9Xwk81jcCEMFa8XZwquDRu0VTzIEReQtsmlV6NgHe1n4fIF+wJeqTA80abI3g5c0ccnpkd1Cc/RozjhaXozbfCnJv/lUHjFOug3efGK6xaWLUJQCWSMYT7av41K/fXkUwb5g//bZ/suf+NI0bKVNjKZJRJMsEXZb74k5ZdOacHZIMPEyh0f+V8cPI1V7UMz6BSvlyKdRSeCpeQaclSdu1onmFZqAYXFlIZT+WV0sRmCDrHA+djPblyjUFJnJsWgoQrddd+o7UuT0wd5cow+SKRixWbtklyifqvoy6aU7mHjly0UJsNC/ipxKKmdG1XSAIu9jX0y8S5fYWdwzdsN4O6u0Yrz1rF8X0fOZaIYWNih8KdmbP3W2NodEiI1+wsAJqSlmLEJi1uXp/zdxbjghS5o3+SaFXLkKiM+sDoX6DmdIRBIXBrNSk7hAg9bkCu8THK2l+FWayx/9yAogNmxW+LKGTvm6fbzPX85TrmZcwvq5UYWDgnVaaJoWbHHibl0XEToGttfDkJP8mJtqrjP+JuHf8NAun23OqXGKyFDskyExNIAzCpIbkHK1UVkm5aZ2+1YUlvP9wwTOibT+/y/9clYXnQ3zndGIDO35XRNeWZusNLj4kKBU59U7ZJHFtw+0HZZpsJXrCD18JbC3oL5OAWzdIlFK4fr2FjKHPNhwIZpvsJNWnydrj
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

