apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgASfNBsywaSLAIcjuYyBwXMMtVePZysHYBHkntIrWJfjDYwE7MA08yQWuPOulwiokmjszOAU4nOj8wpSuTdzWLPhV6faPM6SPBcEJAhTVHnpcoMU3VBCGXRoTirTxxqyECByyUpRPLm0ibM2RwtzNeIEfLj80BmMhlQir12hRTIiOWMcUamM1vfd9178Kh/C4+Ng0aWaMQV4DQQ2vcS5kkD6aInUPyPN48jM6qdsqTLWMe9nTMGwIp64/WJe6l69KrwaJbdAU2upQKvsK9ub/Z4ksQtBV362dTE6H/IruHztR3mX7WJ3+59ghrZkH4Xqm92HSdwMhelXRpIjo1Xlpce3m7T8G3h2zU7aSosDAcjBq02h4WAAt157EruYrtck3zUs0s80IwN2R2cvlRrtD6lQ3EsjcjNBEahVWv1Dur3v0UNDAFgnyPLvfF2caU55im7ovQGC90KbuaV3qZIENdxPo7zkDtJ3D1UEo84TFPFHzbT8VDcjXDqnspjM5AgeABfksQAb+jYncm5PeYKW+nsQv3dlwsjPgxo0j5Iqu7rUq4GEKMUxhQwtMILGrA0mPV8SH6CfLzV2JG6WxhRy03/xKN++rkU/j/F4XF1ewre5VLLEvzBeZCrJ+Z+Oy+qXyS7PE2rE0WA/SN+UrmIyXW39eZBS3W95oCqfiW/DFFJ3E4ebD/WiXg5jyJGXQ7okUK7fhf+mMX+R0PnRasTQNp6LbBXDA==
    ALPACA__SECRET_KEY: AgCOqgrIkbM0obS7n8EaSKSHiQXiaV+MIA2zLIIlgFHFC5KM9091GwpHCpIyCTCT2650HzDukZeC7J9T4Q3nQjdE4ZltYuDV2zh2nCPvs1wpOuewnogVKnuA28BNzcStO+FWEkvPk5yMvNC8r2Jipcv0T5ydyaR86SNH8QwfmVMdJzoTXVAYuexV1O4EJe815Ppww4Ijg9WrMZ34wHxLho7/0leWjEDf7OZQW2LhNPCJohuuXAp6zenOrjlskPQjhsm+4Te0eVZaPf3RGfqisR7YmVBJL/NUB8k77H2dfVwEE6RFMK+MI+i41J7D3dRr+RcdqaLi6TAZFQ50gmb2J6P4PClRK1ON2mAL080aD4THR0kanhtSEpqj4gR4LzcwMK3eT/EnYtEMpyWOgToJPcsCfMSc+0JXURyx+zZNjitoaVqz09OgEks/k5thujwebnHyhMAjOboBl5Signn31BDcrJe957TKxST33qfywyByzdcCI/f9LMO1HxhWonw3fIwuBp5B7nHyWkpA4wFOuux/NBXsRbyovELWwBAIu+Y+HJtBMfv6AZUFwFKdQVY5Wb3aOlw+e9+L3FkN0m9vssdh0UWdCBhP/C8xbZlZnw7j2HLVSHQFSOdXURVJWvTkTSNhv/mXnrA8uNs4zo122cbjEThBNO7B7jQY4Hh4PIpcIh5UzQZfQ6NbWZv1yZhOuhooUrdyaVMTI8VEnSCFhqrCpY+PFFz1UkyJiO7bxH2fTUtM54eDDET+
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

