apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgATPkqbOG06rg5FwOvC0mxZWVUwlxAZpHCK0sJxF+rnIlEcCaFMVjmUKgGw2zCIaQb9geZDKO6pXL1zIWZo6XQa1WchYkoWqgnM6fCXsuW91HWzVW85S7M8M59JZCaYEwAZL0yNI7QrIEpMLiMGw0CIqqHUPjP+n//khjy9NUM/mMdF+c30zpuaHXpen614LSkEH+Xo/f3fQix1mITtr+V1pA2m3lVi7urP2nuaCzRCxd/nz3stee6o038I0VGMQn/6JWHR49ZsN1qMeDdHFSvjNWlQHaoHZuYu3EMun2Oy8mk6IBL13DsOfb0u4IpdJ3mSQwA0l5YyLE8aqo97pZce9wQS9HglIzx9Pcr+HAHbLKO5LyETOzvFZr8QDLB/twoQGop4u3KUNf25DM7IpdGc6L3Rx7G5QHKYYhe4TMLciXNtqcXcFRq3Ck/Roz94APjpkmB1IePb5rK+V/ipEkHyqUb1/MMO6CFcPWSNe6dJcGB0pLRnZ48YsLPvqDUZKs0Bmj3WMk4NdklJl/c4gfhmhNSLJOUD5hsmW+F1tNCy1oFCAMf6cYXfFGiH5sOj9/Jll+m2VBLz9qC4D2ZnyphnSlD9NJuAPXx4eLNUYly/6r/2yzWUYVNIqGtwnnyWdSYEkboJR2MHgGxD99bSu9eUtvrvTGNPb/berXRDHiSPFfQCEP1Yhw6ikSOV1zCMQ2SFMd60Yciop2U392OT2i14WM63Lg==
    ALPACA__SECRET_KEY: AgANfhwbM+Txa88KG9WxqHU2x/K68vD6ocFtZLaxtdzM0hNxiNIWow14zS9EjXHofCxGCEBk0gVw8VSZph1mivpVWrqvR+MW/GnBv5unBkFATYQSIffMKNn6m0TPme1PYcLDVHcC7etqwGjL/UEL8mHuDL7ZV0WeeL5NzIS/8s5j/D/H+Jxa2sDCmodzQO5HPytiAli86T5nivXxPYkFSdgBKQLggwXIO6QyAhydalm0NTvl5yj6BNmDGQZi/joRPCu2x8vmCn7Tm+H9CuSiStDcwJG7rqnFocYR6vK/5t+IgO/7sFdYX5KGb50TDWxxZ1TY8Qcx4wnclKUDel8xOOL8jsKP9jyFGsQGFYeGwc4EiuM/QZbpqlHQl0Z71IK/MI5fLZmhHTlDvg9Aw+SpQSJC5WnTD5GMZ1sS8dlYLdXcaNssZdHD4/RpE0tW44PUn1sQW0PYsrBxTs5vZBcWnkZX3GOcaIAxRm0yNNsgO/WXnqEi6H1H1GElDhvRcqimAqRKMQw4i2pSnJLIXjEoeWzWH59LkIwY4HbdWrQ2XFn14z0Ow3MplkItWlgwxez8gz20liSKwrC9O3JzxlEoxLZUeZD/OS4vEE/STz+418aFuJtf9Q0AC/5s/nxgapfStyGllt8CLofnZBmPi9zJ84rgYQvShAIxGXM4E0xU8O41Lo7eM25vLbwjdRjL0ltPX14U8SF637ITmQM9hNJ9R2R8dzhhv4ssyhtbI/yo9f5su2G7Cjdfuhea
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

