apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgByaUiTFo6iRTX6aE9yW4/OeDvVzDYeVvi0S6/TazqdqDsEGEjh6kmuMxfsnsrvY9uOj6Ge3ACUvTvFa1mjHKn+RiKXc/8OV07K4jv1wA58znSVL2xoX6LZw2YTH6Pm1Y4Dc/AR1S6uqiHtdurPkciMmfCcHXhZJ5IaYQC0muqGinc9mRnhNFSwWf1hw7UYegjwfXDGpxA5KPI8C05HvvzE1RYi5y0Z3loOf01wS89HWwvPzxS+i666vctCvdPS02lZt2ngTeqcJGiII5e0bVayv+5hvbPcb+lMz+8hJFdkCw94c1BcPAY/WTWu/CpsOOmSrducrceOy5EhKZoajJZFSD/HMJE1BUK668cgclDQiaQMxwPZNo0hwnLa3lMSoD9Iaq0ZAMN/+0ZjOLUDQVcqntHF+n+dTfXtSRNfNk0vjHl399bUQ+mVoq6/YO1C89zaEoclpqvcLDUSaQE921bFE0f6OsK+hjdYwU7AEbNEWeVbkbUIsXgMNq3i0U5t5H4MX6NVemHQiTH+lU2rUxDq/CUDbRdBxfRkECCRoflCZ4Gb6gJ7xakJEsWPgIFqoSnZO14SmYg48DxnTUYh16ibl8lGQfkopy9nCWU/e01286jgBlMOKAoCRr2BM10DMlOjeBJonYOLADDwe7RA1Q81FF5VKnB6eHkTq/swCCxkHIPVvlyeRU0ydT6z7mNINpkHYo8LHpwIV92QKdB+vytcSqC8PA==
    ALPACA__SECRET_KEY: AgAn4MBvdi8n7XFMmE8vu2LqFqEWyOOIijbquU+cOhnSsgXH2tvvxsOaDo5yizSi4ccDl3ICbPWADCdLuVkuucmc/pf114vEAlocDsmskO33LvnruZfMUAXxyeujm3LcKnCORMnNFFKjzp7q1/Hb7F8YxDvHiHQpolPj/Qo3P/BS88TDmUtaREkYvYsYIok3kIj4kzlsZGBXaS/qIc/AcJmu3TyS6aGaWeGon7oD6FUDCe3pJiHn/VUtPnebHzy5o4UvhkaIqmGMXtubdOjUuNlyytaq31dzHYqkJbrNGA7MXBV7b8gc75CHYyJJOGfPHTPCIOYEkbeyv0hlUJDyTXtPymSnQ0f3buMnhw6kZHJM0gheWPdnczdVYOlL4d13H4GDo5qEen2P7muFRtepIb1CihIvg5KxITIzeUn4RVcCy61nsNQzKgYWX31pJV+M/u7eP7MQNCX7gf1gAtRAJ7AqOizfrhLH1U3ma6NNell03s3vMnNtmUALgSdCZ9ovw/qDCvlkiu3I9Xoqi3mgmdPRBn/2gkXQcVe6Ig7ZxOVEZhxNmY/zRBtr2mlhTkmApbJB7WkcADHOAzkB7p8zXjwVcoWj2OHtC4IMpdjlfKAuRDm/Aqu8CKHPfktOXPy425hhciQlLFLceYlEJCMVq7meUMuzTU0vQIIea9I2TleQEgbdXpm8kc+v0U05AwUd8O9poFy+Fi2XUu6ywlfS/AltwZigUcol6nQZrDW26FEe6ykKpi7/zM8f
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

