apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgADgi0xhFC5UtYffW8BJ+Ntwlwupldotfl+9SpuZ9MRftshpnSTWG4g1GRlHkDFng3HyKQWjqMDLMutr1xAJDage6sHpbaAvArzue+SIBe3BOZ1wpk9NKgdQN1yhCAYoaecgb6Alb6M7Xgzc2HxGFIeKuVKvqg13luTItyi4v/z9wxOJsrvCL4NuUhPrzroNmhP8G9cFp7hQ3YzKUuRlkPsFYuiHxll0qKRNmjOrFzHqTS0O1jNAGU4KyzG+Wx1Qiq18nE1d0TaNDk2F4jkMNydBv5tcJDy0ghNG+EeKM5t9UTpplSdO96QNSmCHOpHEWFsu5gcAw/wW94tsnY58Mvj7N4FhS2mPp6Wwy3Y0cTBOXkDo30js2a4O+FawmD3sk8IkSqB6Syxw3Mfo6yBqGcDAkiTeTI7xGKPIqS7yFUw9lDh7325zbNAevZrv4+EqEYnpPfVLe6EeXTa9jRkyIImc12ghIz4YzT6xdjmOxwnveghH+glTLgJAc3Cb0NfqdQ5xAsV9V5A+Wo8GwTWzSay02XB1tVq1xYylRBXc0NByda21d9DVqZTOKI+4bYJmPrhZrkmoWqCg8SlMMBoNIkZ0puAcj9/t378ZAJUsfc8l8BuFyIVonU8jb4UjXTsSqjqzbe3PlBQpHytLJt6xlgiMoWoMwFMLjxkw2fcTcdQx6GKoLKIlfvteMb4hHKlvnuacLlcR7JUZTS0jtKDQFRVZu8boQ==
    AWS_SECRET_ACCESS_KEY: AgAemYXNKYESc+dlJ3flOPIc5ilNIqDMiOU9V2gQ6vG5kxWKmBs/ZoIMHdAPpbhu/CrhvkFrGuiVL/xSC78/psfaXlWqR5yTEhQZYKid5AB1cpXCEkdwlLGWGK6BNnCV3Lzmvf4FMDaeRLPglcwe8hwzfhzHR4C+zkuxrUwSRD1t16Yjmd+DK1gizp166j2JbSirTTXLivhJb+vJsihk6wFhCNUiLFZpCXAQ96P1UVJwOlZaG2Y11cFofMCKubEnRTLd+MJIzVFN8HITIxQHa0wo58kdZXUaFhdTyNzUO3aIuoqmLxjtxc7SHRGxPz860utbkDK4D8MvIuxWG+tw+RD7vW5Hio2zkSn8B6FVC7J+6IKG4zK7czSbT2l6Nsjc7MkXbT7/DToiV2b0xo4K5X89/CuBYWZyo7vXwaIODF8avdF0hgKTVwRpNd9hiS3ldWbMCoJvbMH9hRsHIfNOGVQ/PCRgNYSrCcBHyyw34fL0XbfFuOosfLi1ySh/vrZQRk1CM2R/GTZNfZ6V31aFRUg8ZYkuqde2kyOMFS0Oazt4f13SbTbFm0h5TO9Y7VH87sc9FJGIHbkYJQJLLVaq4/nGtpJGHmukFUea0YiAGcDGCDfBww73ofQtAFlT4QOSS/IFInBpt4CBmW4VwlF/rYyiTy/DqrijnPiOwQTjIwGZUUauaPm0vJV7g/l0wZba6fv7FNxqID2zbOSvcORGApuDhFgtRJ6gYQweMWeKLbTFpSjC1ExTp0GL
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

