apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBca01Xsm5y+VtP7/breZ2hAQUW5zd2XKu+NlncPcFpeactjGmdcK9c2bqp55fUtfFZhZRfshCZZyGdD5RahFDIVq399R2VxILXq4kURPjLFYa0c+maemDONo94TAfLEnyPVPEZ+rkLgr8Rr424gLMDUDozVdqvqhOWa/r1C4IJnNqqmHsbJdwcjis1BoWRri3kXtk6v7/j8V7pveAakwfJWcOzQbzWvtzRkBWa1lqZSB6p3EGdcLbdYCCuti24m/8cP1WsdSlwF0t18C/XyNCmmm2PDBdHV/8wgx83R+9PwreCakFEgf2kCFdDyaPZzYFbg9nq/aQP8aVnH69g3hMRKeulievfNyQAP96rLSTGErWW1ktk4T24p1+AWr1wQ67byQzRSXwJnR3Qrm3wd0Y1H6Hlgm94EuKFXr1k6WtMAQyP+MlitT4nCXrFbyQ14OQvvMQVl1/xWA4merjY2341l0WuxzvETBglB90sBpplF72FQjgbzPcUnGYSDmvN8b049KeahhYuOxX6XKt3bRce5/1MG+yZkayUM+D2AWmrozWR4ZvWSMOPw9KbuxjgXQgPiEXwdyJxJRO0oYyeI+vP5CoEp0075S7GRvn9yajg+D4n6yQQDy3bDjlFUp8nDZRlqKWPUvvchb7NiEaK4xKxRt9hF1RGhdplKcFF0DGFoWtVh2QVyitoFVTu9vcxJR5Fze7wg9D6lCcI8JeAkwaiZfe95w==
    AWS_SECRET_ACCESS_KEY: AgBrruMKGqeCqignAuW1SMKWsO/qdVpWuzZwuaYx1hRgN4UNkMRrvcKULchCyFIZprf8OJLTlikIHUFDS6Pcwycm+9j5/kdl9Q1CM+fhDgXe3Ygi61tCBQ9s3lTtq6vVSsWIDSnQr8qXWjf0tuUCHLL3L4CxWHvJNSIViI+hCCMYp49SiGRTJI7OjEmF3y4n6tIrmzcODRkgLF+MKLHhxwtcW/sifyo9ZGPqHyg4nlXGuvwu6pAknPsLohZEjlK7NFG7+BsjZThR23QQEoPyWpxfC8PFbl9OM0vaCHl5ALNm36LIRWcTJG4hRXxRAy8Z1c1B7P2xrFB4hwyWyACGZFT64ufHiJvtcwVISasV6Kzin6bgsQGK4LqmbG0eOdDYRNzTpTMO+BCYqmvB4C2k5rYSCNqxGiyFTy4zxea8bu8D1Vb69MyGve+P19xwWP+Qg3QuR56tXu6RQ6y7gOya9RNEz57fcBnc2XSw5oYBfVPk1VeVkVU+m5oGjQV7Fw1KQQG7Lwk+up9WhUvqMThSgIU+Gtqw4zUDz+yzsJnSQD1dwilYgNmLhQQ/NYL85EezlPFnRGXeX9FvP4H2Ie2knREizFYmxKHohOA2zA8fo31krTWq30CM9gL8j1GOr4JWuIo5Wpe+vhDZYt5zGwrE0YKrBt6lcE+fdW2A/yzd713XfwlSH9FldAJiGro5YivHAqczMFwd4MEQMHRmJXj1PFEUQoU3MV0lCRbsnmSDKejmeC6NM7lrgHuS
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

