apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAt1kporh21zE6QRMxOgM5S62AVvFvnT3iQAfOMbAGDGS0LwqGvVyqGFwXkSaXz+JgWaeAapUWyhVIcECzk3oQzScEMFbTUEDlWCU+tLj1m7IA6e4JCTeCrpqM4UjoA2GqjjU8AiWNOoPAc2N0uTvHWvjSnbDB0TCRr4eQtmgElPONIb9CfaWl9U2qCP9jnQhBMrMmbD6Txnj2nlxv0Wq5T91kEVHPSIeRqcvL+wbJLG7G8YEur7vDA3oLFVlReP37B76FjskBPh4cZHijMGRbdrfP8/YLSY2LURsJU6JSKMfhQcjCrdabQ3Jq+1iRqBwESUkmIOtKpfOpoziM70N3hUipwz8DYghQIQyxkOIUg4UboorZqq1KPjS7CcB2iHfL4vLD4I03yI9uf6VqdTCTqbVdb8p8SaCjDDW9uDUWxgV3N0zSTgSMwA8hNV+NWjV3NaKQbmkdWI0gVK6Bd41eIlaZsFItT/5hopGrhKDzoP4fhbm/CXOIcFDlsqLHq2Ymq7K07VHtpwWe7eSeVF2365th7eyjQjnrC52eHSp3DENFW1JY9+0P2LHcFa9uUvM41Fjshj5K+ns860H0smtxxXgyL2r1f1Key2FCfmjLUCYUlK+FwdXZtTooVTNqcU3w2dnh0P0oI7+tjj0Sq6QEY5FBERfcuELqC4+mD+6MFzvghcDQko08qafeqMzTLXUoFrflITxZK0wWmd7O//i5yjqRXwQ==
    AWS_SECRET_ACCESS_KEY: AgBZQZ3e+Iw/77Q7cwNFvoawhhgPA4c4Ua2cQ7rsVj+u3HBA8AKfAxaL4U16iLrJdSOuUuPc5uTx/zx4nFI8S4qKvvEtZJipbeE2MFFXjNuf1pbdKJs0gdUAWSFbUDMxut47ovBNhZJbg3mOg1iVnHsKMdYRXaVZeswEa3ryxIcMkHtx7JvQI3jBms1voFgxiBblsASKOWSegnX2CNJmTD7J/8inF67JtcmtGfLZsiLqQiU0jQwTU1gTzrcJFh+STxg+SXHZcUyl+31Nz7Oxb5xxpmb3froQlCH8IA3dQPeeFrkG7KMaug6UI1UQ2SP99OukOx6eMtxXZ/j0ATAdu9pfF2zbpwzArNIgoShpSNiJPPymh3vs96hZWfQEHc4luHJBJg8vE0ngJ6MNB9i7FaQdi/Q4KqVyIWgLdyCCJcdEVPj2kZfpKb8oy2WWs4AUfSLuD3+75WFKnm4F9awA+jPnel5SXao8PXXXfETt3Ig0+2DfeUztvC6ChhDhCVuL+Ytf34mfIgK692PIFujkrlpJiTjbmp42K1HW5hlxgzkdq+NilrM1orZuNq2parkDLQ5dlztHZkCoq50oah5lH65vDa3NXCV6lihvpG89mN8qT0GANvhOKd9pH4dJLPSbCwu3n6W1/81/kPlgk9PABq3wrNITb21osSq5DGP5Vh3YeWohGlwBcAkbxnhOIHN6bZz3TcAtX/Fr9r0GstG6LzchefL1gCG7/ESgdBnFjWuk8w3USb81B/EY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

