apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB7VHM09y2TaahsywZAuzrri94YEzgJKEqjolFdkevHdp19CbXN5IEfVUPRGXNsz/wWFDQ36K7xl7vhNkujOtmFswUo3/Coxmm75JIAjMYyx/cQgcf7b7/kOFDgG4AyYqdZ+cBC73bzXeXFUz/Yrk1llXMvJEodo3muh7qeCdxbx93Jnpl/iYYpG8f0oTzrK5suUTjlZUuPJ5aoqmX/idAhVvCfpcKCiCkKxQnr1je9umrHOY/16QBEg2ZfgT6HkyKc3DegJhwS35wQmyfnC/gRc62DBSYBKDdsIzcsg2pYbGX/zWWsADG0K8/ZCG5E3/RTw79CwVtJ+LuguK7H82SmuPtC5I68Boho9dqrPskkLTJJQISCcju3MLO5vkXeeIdQbN5hz6XjY27b297QsKJJX2B0Pt7+pMBKu3jmfG3gzBNDm3E2hGA3OCU3ySAGjgrdGUH3FLJZf/QUfVpOI5F78nlmP695aIBxdAVv9lhAsYyDhMTYi++g6syeNtPS2iNT7pHun6nKLrqOT8kr8ncrV5iur0rFFcL03fsr2FLcK1o3W4Ef2d3QffTH8zRBzUf/o2EvACPD+bv46rJ19hIVAn2Jr3Qk31UzKQ4LUpkLvvfQDpI69wOE+6ZXc5wFBsXhi1DUYfmuQXwnjaYNvMcumlxxA0X/bM2pHSYmeMgWqw1+RG0VtFgtzW2kqNpLbUhCt+PbetvZJjGBFNkv7pafET9TEQ==
    AWS_SECRET_ACCESS_KEY: AgAshfngVsnPrSd6SUii7Rcs4B8Nmhzhpkna0GzWhe5UdVT3igc0JtZ94tyFM0wdfLFRRcd1Y+xFccFyDEh3f8vGqGpk3E/y8BskdymyulMFoKqZj3WPiwqhn6YmCZjO5DFcxS6YByK4H6TxjZqFwzDaseRzCDwHWCX4ZGaSDaUwhcFDEUdzS/Fbt1RACrrrWSwS1h81dssRR4nOttxY2sNcK1aVlvJim32Vv2XQoDi7Q9rybJWqr96aL13XdSMZlxW+yFTmYBELiGkUQuA1OfXaU1CDQVb7latRx/j3pY3Fwbyb9phfOyLpYgUX+173NFNInROSOW4hlrAjAdjpTMc/8o6x6bU+LXZ2ixP2EM6zXkotItovgPWBX6a6RBBufkpQzoPsj/FHP+FaVmIXLcpCh1GTrbXwNli91erT4ZPcObW07teNVlItxUF7wAeRgSUF3J8ZQEqsgkSXEIxFVK/Hu+M7JFJdVWb5AcRXSDkYMkphUC47YmN8aEv3qbUtJd4P3EvwQIu6SrkqEqt3KxIeCZsRoVVVxp8fWzisvD5WVAjH+LYvnGMlORhNobBnDbOLdcFA1LFNaXwGoNPb76AU0wHtuxIVXLustyeXGy4VT5Fux5jY8BYpFj0vvAAwsvhKgor3O3IqZhGUrRRzRaUJccSC/q1MVt7oSo06147xgm3ilKVIFyf2ygdz+9TFnuNhFQaBh5gXI7KGUvE0aB4DlkRjMiwsJqhRQjqCiZdgXDXLNgVVUaL7
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

