apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAEXv7iKB8so9KwMLgo/WiPZDYMjOtNTh0sHZGPxU0Lgsh2KlZx9JlPc16zajGK1iTg74DrAv52dbsF4WBUnP4RIWI/SmxuVChxYednCZraHNBJzZIcETEGxQYtsQwxOk3K6Ou8KO7d/E4mcNZfgBkcM1dxa/uhj0QcLk4e06RdW4sAlZsY+rnBY9UtRw1uqSrPqYuWBV8X2aFp3LJpCQlu4411MP5W0FdbYrbqvUJaP/KQvNl9OAJwzLI/eIEbS4EIVpfErnHsAd98fuXn5dIdxlx7f1oZaMJMozT++RGSg5zaCI2Cg1Tdkl/VnbFzOdE71jNrwuI/YPiX97p3ByHdndeutW9AKFRSkdr5N/D9lI5zT5EJVGJ2FoEQvxlTtxSfUddlTpONvdHF4ou4qe28q4cxjtmdsrvo9trZ2N5/4ukuBGcB4iX43gtYrmlJRbaOIGrvRQzTmVDoT7nGYYzZHpfQsXsi+mx1J8FQvfNdfVIWPjN3gPoPAX0J9fuYjmyT2ZrymdjoF+V4nUXIZIG/Zwa+yf9zP2YlCDPrv+dTXBeA0WtV5FJRDKw5P+xeSKkmY8FkvjpAac6njwemq4gg8zU+LVzXVvInJyzp84z3taQ3zuXBTv/w4WmS9UtNtucm+KfZyEP88Ju9w2VzQ4rdvdYPBdZ1rIqR9G8LpPvdHBmZfv1KH2HfKPmtAqxrB3bVtH4VMDwetAM1W6SOLwB/N3zYyg==
    AWS_SECRET_ACCESS_KEY: AgAzFk6090CXw7zV1dsKkmtMXN9qr8zkK5yfVoI2fu7Ea3rTLJMqdILsZZTTrvFEip48+4whEzjmlWt+XABvhEgfV6HvajyG84vFzII5ysKVRvHPVTeOD2+o9eB4+Y3Serb0COIpsbgkMSgE49w9KTtAYcO56Rlm3RCU2ezZZ++E3ugwbVk8vixJ485ADW3WaanftjARP4wdk/5BoW9Ey96i8IN4GiNfTQkflIzde7RanLx4ztTf4hNGZkqC3ym93MrcL29sl0HwsmZXeT5PTR4Fpq3PJo6YAa9XAy4sB+QR3pmMTYsscX1AhKeoiWRsQMiMFvrX1cFYM2FjX987cVDarQC7z0578FS/9gAjCNXhBFHjYxEblTnnwQiKxje+V+r4vn4kRhr8hhyK8itlzNGiIRN8Gx8LoHnb9kOxhjHYD9BwwEL2MKV05X3p16OmOtvRDC/58bBhCXm3hDz1c18vEpnPM34/QBcEaz5JTBNpSX6uPfqdfh2KEwWJiwoT95jZxVoK5XbCN0+gncnBKeYKHOPdmxryaF7I1jEEbV4UlYTh0u676g0rR9Gmr4L0Fh/2LIJbP9nkCb9WyhM2UA3GMXNX+uRnFH5/d//KizkCp4JMGEF/rO08J7TxHQGALpo61dTZWdNaVMXBIhcIuAOTjU5uhFpeS2q4c5ikfuYy3IWdl1Bhott5B+bt8pAE/pZLS8rSFWiTo8QMdb9n424N7rGc2gkkeALdJQFkunil8XDqtQ0MPnNW
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

