apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB7olM0GR108wFExuZW17BcYvqb6KPLEKJVE6KQzqa6syfeiwOuIfHLa25HRYLLcWCyneDNoQjxtpzDwmwU4vWaxta7dtuUN7G/FEKDuHGVm7aIe7+iKGvFxWQDs4OcmkxvwuebMmu3+vHha5YeuMETpGlRF+yWNxfph1VxLN9T/X/Rxp01V48FNG9wWEcYMLO5Qsd2ejexds5vyHHCobLYcrp7D1ZdD1hhN7w+ofx1OkdGgRmlOGW7FLT0QhuWv0Y1iGA5JCdYvIuorr/HwtkSK2r6MMAeACgW7la2LAFbp+wV+gplMBlzVPMOfJIaDboOL76vSze0dUutSPql04M9goe1Gd5ISqhO24S1JbRqXWqzlMXD4yILqQhQxQ+rRqMzU8kXrmtkhAkRft/Dh4swSXlBoXPUt7qkB01yhGuxwpnCB6M0qfYUOfsX41YP5CO6m00o3Oq0NeTs+ke9D5jtgQaPoflS5Hx8nZ+GkSCyEV6ulAKcA3HBFA0LeuCLDTGMykmwseqBoqkLrPs4cQdOV3UL743L5o6xm0yV+lFoCwxIGZZdWvFtb/2+0pYzLDG9yG+D7ilyTOBH/nq6i3CvgSjulCO45Y95YdyEZivMAHhFdqfeiUrJkUu2U3bl94chRC1Yr9KsHen2G/ysZaTrjd3NP6mRBabfhXJR7yrNKV6fY0wwG/+zpwhPiHfRAw7aNsqVN1jkG0lRFY9e88Id8YiVuQ==
    AWS_SECRET_ACCESS_KEY: AgBfH8V8CyxTWXw3Vgdu8UTUl5Z22Rs+3G2DLYfQO+DunNya9wCSBGoaG8HPeIhXJNU22C6eC8qbMPQEy2Yn/d3oc1kfwcSXl8CELtyXPIikDsn2KVz1iSyyfd9qOrixJbTlsUf4Rg2VrPaolPk6qRDo3Lzwez4g5t099lLGr//dAqouXORwGyDBFJB4vsekY+ZWZw+w/cCWg8mOac2hb7lF8OsTMbhtCFw+RDadzRC4cPnnQK0tSK09yFZu08XjYKewSwJtLTaCioWXW86qJUl3fJndfQqg8gXrJWWGArozM9l2shIuUG4ALxyFbf/9wprtrI6G6PJTJIoNOiKLnoQ/UtCc+PGeiY9cT7lMRDpacUyxijQkq/RdrfnoxYSLtVmjexmePsTQorCudlLn16E0aiWuopmqMysaB7ZJTt2FH4RSICJ5IfR7Bd8BspaaVxgpheAv2kQLTJRSWwNGKNYyBMHcXz1OsBj3m54CdDs/S/HG2DuvqMdRnS6ZaEZqPzE/68oaLuzsjtRAL+lMGBqsHtPXCXuIMMQ/eW3WOsqdJ/okImnnAvIYQ5N2PxE/wN1KS2f0Wtgx8GVulsBjKqCxYr+mSF+FmYwwiqqIQo/Xu1e9rlC2yaPweBpYPsjXPBCZ6ytmhyS25xAUoDVBV+XW+LcVg+ydnhb0sCX+pYOlvmpByTjYcC58mgUj1Bc0oiOIpZjPmHr+nPx/NEQNWIO5yRb1JhXtLXolbpF9PNjmlaz/uQTH/xWu
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

