apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCEPOjM9tjBV30RDK3LHtyVnera91+dKGbyvbAc80pTFlwdmTQHQxMumg1iJKSLwdUfwa+O4hU/ZTdwgYy0I5G9YEEGIdJxzjNCVsPvhzvsfCtZOlgFwJPekCCSnxY4q8RQe0Nzq5RKSMGEMS5qJqN3u9EwreJtMTLZk3NHGjpLUG+jZ+CuTenaZNTvz6OnL779Wbt8EbmR9CcdHrJY3wOihe/lHzvk0pX1G5cuwF5hzom3q9EpjJzcbXq4d6LN8QIz4H/nptvDYCXK88qH7BJ95bKh190bRqDIS8P7PixvGfUXylBsTn/VAYrnVrsB/lhwq2O6oXiFL0l2spyZijAb3nvdewvt/l3KT6odpGAlmueWVjmoTXcy+ipnM0XDvsS++nqrX/nN91LPY9hHmhHCQV7kbfE8lk+vX7HX6osQ81+vxBJwW5VTgUNlo/qo2eDVSmvBdxDQnFGGEo/TJXTWclaeIr9WAeH9Yp4f98PmMpiwxIZZhnr2ruI+WkoJVxjAyUS5l6aGbj+i/5lbSnIJs2dsVDbFgaOYMM8NzYaNIL+MQe6Xl4EZCYHB5XozrOmgDdrx8jDNUIOKNUHAnADHvm/iy8W3Z1/GPcwj9ALt8oN/u3nlAuE6iZrP+WXThzDp9yuvR3fM+MHYnXA6a6pAeILDJ8mEjfAPGBaFq7CWYejvsHHs0UI9TWQP+HnmssLfKW0nenfepG/KGiqmtriAxEWIag==
    AWS_SECRET_ACCESS_KEY: AgAvI8Uwnhxnn8B0yZ9mNJ0ojuAk6oP/XeYMsPPUIv0GnK46KjrA2iS8p5pKn6/N5/Fh6ZZIpmaLBc1KeyOmLje5sdFZuVZUSbYQ0iB9G1nUXgAwHI2jGkPwiJrw4F51/f6gzXlZnpgQ6Mrm7CiNVE5+ZefcXPSZOIcD1PiU7lMZJ5C1LmRkvlMw0VUKaUIuKrc8aMJqdtR0E26GNkaRVZC+Nl0ll1k+FwU/AJvr/u5+1Q37nMzNGQRY8zEJ1kCfEgEpfBjl5vrNUOZL6YhqzHkxu/jd5rOKtQ0ZPLpa2EXty6He73udQsrPufvxPFiPRBZMu0Polt8SrcdYfVx3SsF4vhIoC7dGWLjCvFYStOIseqPqB2AhZOFH7suPJ6WXxt6W01odSsxzgNQyA1BPDDGkEmTBryoRzZobVVsmx6YtfJsXPrIPoWY8dFDj6IWq+qdUN9+txNX/bjmjq9KvNhw+99IDwGJi4zZEZ/ZJuw9GFGg1amxFTHZ/XC8xwVhQKOQob9MstOjUhyVZdHnT4QZj/MLak6ZPtfzUhA2Hx8kVIP+QNvAg2P+iBVB7MOjiYtB38RLxFbsf7WE/wqWxS2JIJUmExsZtegFKiq5MoS5ZB6zVw9y+CoOMdwgNbviaLWt0qw/3V9FfcJjCHHuQ40YqWk8vQ0ZY8iSmQE7ltbSD8b5N5JearzBW+XjhA3mJYqh3hMZMjYto3JFrlT576S8lpCLC0EU8TOCfSaYwDH55j8dgY9mRIs2w
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

