apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBOyGlULztQTyrjLugCDSeGj9U0FLZpAS+YPICYkylg5Vzw8pS9yxDfRTZQcPY8MQTnvNsQVj0M37cxAtdaX2JsGWVKBjpwjqda8AB9mwuNjaAOC+Lv/ISXZlWXWQCCMKZ1lUMX2veb0wv2v8I5OFppNeq1fysik1AlV9ox4Dh5u06wL2Gkbm9DftfB2j9CJU9qF8MBTtJTxW+kHNFFhyaacuCnKxhZR8kmX+6XjmaKFQVjK1mHmj+XfRHiVf6+/AGKxPX2hF6fYeV0KxMEMQeDqY0Q8zYv1ASmCet7kc/548+l+zrPrz4QR0qW5ROpZfjFMFmFza5hPItxJQ/puYKN9F2Q35HWQ5Vnqh5INc+xxG64U1n+iNCLLM/V6Wh1uSz8hgzKI6+IFl9KIelO6lBYuLfiDWDbrrMSTzuEvhoXZ2rcGpTXchx9vTc889VzJxW2ZtN4V/6V+lWRAadvjnAeVGWL0XqDz1Odi4E6DSGlclADdAH8pWz9WWuugODCZQQmJaq/mO1/Y1HgSjDmY2iedjy1YPpbDIiBO/03lUTy/wP3RR34sZNqknn/g5jcpRZ77qPeM2hLr5nBi69CtA8CXrXbxKkQVXprE14u50ukbYUZkd5vxX3O/usJ6IwY700nAR1GAIA1h9wOR/aofy33XLEfzuWe72LodFcxCpWxS/8yfMOvZ0fidOUSNJ0gwHIIK6RXtJSfPK1fN2Mv1lTXPowJ2g==
    AWS_SECRET_ACCESS_KEY: AgCFwdl/FYUg7gLFMZllirj8AbOTlYAHpy4bijBU8hcqJXpUldwNp73O0LU8/dm4PUllKMgSNpBBlJEKRJ7rOCPilgTvf+VtK28bVoasGFpiNVZrRdG+LwqSacq2SLjDxGN4a30D7wbQWZDYIDxoCzldpCy7ce4K1Dx0mwCgW15Nj9ybs42vu/qmIraD6I7A+o6iWTuxdtFEVDkyrCUjOhEBlbtnjzD9eBHd6/ihqSIQXjkG/S52X05JSgeTAsO6nOM/xcCsG9/3kOJRdjNsfhhcJ0bzkH+lw7XOxuP9RRprcYoZqtBo0/bWSH6rt1Ng0wZuXUpD9/k8m4W4otHMyjFdxC15LmlIdTWEtZhCHsqij1faH+bmWoXI7GQmhVGxyMOthMPKOYmW5gznn0KRuHGTE+5WyAUXjkTMIVL0GYb/id9ygalmp373ciwvjk7yKiZ34R7bXhMIuaL/SykHn2zBIhL9ugWyPBHKsHlKQ3thZefiOMprlOywmpZXP2D6WnJww79eVfwmMPSi7D334vRi5SRpSD3BkHsQsBurdrZhgcMAjwkYgX+YUdusW/cOlAF5hHeC4NsXMn8KAQzAk6urO/vZ/trFRLDujP2Ur4Gov3P/b7F9p0XCH7d3/6fkW1LGiJvuFCAaCZn9A2FQw6gBiCMg/JjnvaqFQ4Uxx9SN1OR9XxsVUl3pY6KJ2eRRnHB12qVHJV4npkbbMvybxvJt/A0wNX1lnFfy5sqFQ5z/73ybyLYVAxxW
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

