apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAuqcGW9Q9nq+9hWNPO1ONoFh9khoquKhNqh3KJayzfur+8uyRYRZ1dKpaoPOyGnE0ubJfc2ofWZER1mtvUqLs090Mi9jLEIBZoBQLJXOb8DEL0Fc8gDBqY5O2GR6MMMhf3dYhtLSoTXBnW3RjPTAK1RDky2oB5Dfo81Lv0k2+QthLzZespYTRFnVzJmcBEWWUpol/AFabc1NAolNGgbMWizU07pePRXyngqWDs8cgbBn7nK0Wgnu06s49VEUTBLQLzMv6vYSocGctup9BzCBjveCG6UcUMVKJBvezkRWwIkCM99CzjV49aLqc9QeITecAEQ1ZeanwJuyDcyH3OZPokEqvwSY8s2A202NZetNgd7OM31o9EXTGBkCMDqcWRr/txyHkgVrDnODDJ3I/Mhdg88+r3gtKNnLsAC/nrNYtCttRcrEcG7JJoOsIyKpkw2DYHkhImC5HPWzuNBn+SNQFZ9Tunx2jCFfy8U0MHEdfjkRzu+bC/0MoM0o35XBDgWn2fXXibq/8OfaFtCywUfMlN+rdPS+loFScA6BmRxJvfJSxxFjP8WHm7oF8lll2Edb+Qrf0mpqAO3N11hjsuVr0xPOBX07GO+vvcIWPsP+VUqwhdbRYllYswX7/m2riYQbiFG0qo0zwsZvqWEVbwaDtxsfDQz3nZCasUupfd/tbBtPlZtn0O5BnnvMDDUyaeRWV0/vsWt4ZVKYBI4t87nyLs2qA6Hg==
    AWS_SECRET_ACCESS_KEY: AgBwMgn1dBcxpnMUkO2gvpVV3jGa7Yhl5Jzjw+eIYoJK2x/n6oaMACFkhB57bd2XKqIVNh0QOi20fiGE4B+RFZysxgzVSZeZ4rlntrZKs4TED1J5qFvJuJ1dL7ABki0rasX1anBQyy4VHEYa2kKW283AuGy6cI2WL4s2kVD3flCGV50ibB0FEoLu41d0KbKcyUoqwL+CQQDw5g6pwmQJI4yW6aWHf9HpQWt6v2ITjMIJvkPLB4s6YPbwndj2e4ZAfSGfoF5J+gt6WxacnM/73cHU/fS44FEBWHSK0A7fOxlCl7dgTCj4L+NVfGdWhz/6EjiuFIuyBNdvwNws1FWlRTwFLfZyIrbOsue1U535wXN4j7Eozdo0G/vazKMJhNTz5luDPhLTGWTiFwCorfJtwN6SA4Xebgy7X0Rb8r+AvuMDIp3mIWAW/Q8MJWg+RzD50RT3Lbr3Lgkc+OE5+tI3+e12A+QRlRoWernpVUgSyMGArikQ4T4IqIpS9ANjLRkaBCJ7aPfTkQyfsg2bHIdYcDADRloYhdRg2Uacp2/m2RqNOEDXPWXZFZ9QUt5yMtefHzhrmtOt3q2IGzvjwmmxCzN7bQ6xXidfNUM0PLCDFsBkX3ggZ+RBwvIquOQzNP3W1U37fPFI9uULPYoUSP8OehStemx7Mw5Z47uo+KJN85Sr9tv7J2PlFQX3uvY8QbEI5xSOiRwmzY3YbJVS/c2a2MEkmfzxBB6Xj56P3xMz6LD3uEyjmVrZboyX
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

