apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCXkSdP5e/IzzOOnRXjrfJlu38dlFIORZbolJApnB8S+MMzL66oY7NkDpncSksmNl5/hqd4rJR+KSOqKS2uHVslaK4dh7kNAAw9PMBUojljgcJmEWUk2C6IXaGmKZbs2M2/87LN8otZccIS5FW8gyRvVLsTMjfCsdKeFr89n6YguqyR9X++YzYn7T6brPf9pdPIAf1K0vab+ZnBt9qmUXXGSyMGzxQQOd0Y3Wa9FBVWvBGPNaCPcb8p6iwhDgt4ufTt+NgCaAq7DLIwEIx0e05vcE1Rwm7cg3Jjal/kjkASc6ARk5ftIJyW+4dE5O9eftGIduPhj1Woj/qFvwJKRWmkMybPdJxf5+Xrc/fPX22u6HMRE2aTyfuuQ3yKYl0h7fgLXxWkBlB/qw9MplYuF06LZb8pYBPcGUWjSVPnSchS5DuSwjAU6xMpnPdn1kxIKD6JwQPTJvq1qs81QaFd2tax+xyb0zyQQ7u5B9bXzCZ6XgKzYZjmoyE3bgeqCxG37qzfmkKGI9c6JsGhlWmadwAVWfu/1zwBxaA/mM4lUDj6GMvub14GU4zSp2vDE/r05AlQWo0du4yBrYVKpmoa9C97/8Wq2QM6wlPXpuS3WyNVCXTO1enjg7/0AI9vnCO6awL37tEFWGijFaiKgGfvIELyTB1uGlCFwChwk3mLa8o7AcA/8TT+OePRLNYV6jIyK5xMW3BZ6eeM/hGO6eEe1tvTEDXP2g==
    AWS_SECRET_ACCESS_KEY: AgCSvNflI1Nwd/Gq1p7q1lb8aK19DkEcaki+Gua2c8LBsiF5xUSpWM5gRHofCiZb/sdb5bTZjHywqaNoZ/1d/z8gVwf7FzFhep/utsMpdtR23ihOSK22THbcCHxN8e20K7u2rmBAfeUJJWUKgRilXGe6lgpl1WShcFzZOtHRNPiniR44lKlFxIVa6on96uaYczfQPxD2Um++T+oioyKaS4ruokjLYPofIlVf1lIfMXrGmj1cZMF5B/fArzUx+pcfacct0eAA8/zB+8Mp97ojYzhG3uPaKPmBkeupAO3XQfDjyZkHEf1CTmiX80D5YjoDrbQswUVkY0++b8pxHBtDNaFrpTqxVM+BBhS+9n1DcTOqY/aFOyUJp5ata9uwYmiRFrtVjrW/L3U/KNBckWzDqVO53bJoTyypJnUZ8wiwfELcP+qY77vV8abjyJdJ3K602CGIImvgX61vRJ539BwQ9paHZOVaXjUqlVO3cDqCdvdBZEKTXlLaGQiHPwCc4cB7w6Tky8SjXgGsJCNrg8Fe7NoiKNVVOC7Lyfg0+wubtbr2R7zVThmxBtFHMwaiykw8oKCfgoZSR/cYWnBK7XCAWkhizZxIiJ1KL8M1N//ZmN8qi73SmGJuUdzOc+CDZnfln3nNMUq79PNFBth9ZkXOljQUPAER7o0IbiPQsTqsTw31FPmomJ7JjFGBewwjCrS7CQq1GhWwSzATwD9auv2ze1hiVqlbBwYA8SFcExXhzFoW/eGaP+H/7MvY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

