apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgByea3+2QVyvLspCuaDgpCvDXBg4EQef+pgJ7R1r1Dqw/j/8Cr0+CdTXT336wcMLXDKaOICpnliVyVhjOTmboiRg3Hlu77K8T+wYPN0cyQLtM0+2JFPc55OHhYF8wD42JuDeIY+SRKmNEP1oWOz8cX7YJ2lRj1XynG2Inx7u93AR/zX7yz05yrB0uAWD8L2mskMVIYPN3z4rN3+SDMTanMNwl54HdtS1EE/56ocWF7WAFXPeLCPecoIqTNCi8RTR5Srcm8YvZ5TTlo6lFfY2drp0g7VWObcZonjonXJe8r0PEZsxa1XBZiAbPZCD8djgFhG/4IJm7O16VVtET1NsvmPJP1sMtQsMElcHuM0R9cCrBFe2Z2VlYH3ILJ1Vg5KDx0QnidELjl9T1yfrPrhM2LkrVlednTrty/8NK004QB9D7E/wqBQvNZYUcwPv/LqzkJqL/PVmjUweRJ/HjffZ4wmYuTa0AZfABguxw6PLuKSfcATt5tO+4nLYy7sxoQYVLItxUcqntaHzBR2n2Nh4tgUseft2wkjDwnMqS0i1Pl9xXdnt8w/c0rQgcIQOQIXNryrP4L+6pc8gCRejWXpFJpUO5V7tQZf6eo2ipwAvqSZbeamZLtQiRdETovXKnw3gcW5+gJeDM9j4oET0hR1MEF2gtcmVq//GUjRTRugmtOEC17ZgG60MJ7kaXEknC6l8+ivWFLebGEJIKqXXfmCuM8MUY/xRw==
    AWS_SECRET_ACCESS_KEY: AgB2cn6+/B2hyvmCRoIgQzY/L0aZ3pA4Q8KkCFPpvtG72JGhIIPE5gmx2H/fHkeitvwL2H3Wqzui/JylaY7uLvHlyuxGZoic6DPQRGgJsRHTQrMUBblP3tOuUbNN970zcAT0/s2oHEbYZbG9EXTZ1h4b83SJCOcTYTdBoNDmL7Vh11Woru/Qtj7Wm63XTGHmJsUwvDrdYsJP+Mfk7TTLveBk6jcmsb4Oy27rTroNFeduf6EsL39+qxYxp6iHFnVYPx9v7YRf4wJKuJejaz3bBd+PXGPEWQ/Ul53KM9hInD2jKNPfaB3L0YMJnqRv/vXPJac7jZCMTncjjAw0PCksT0VO+73WvdwfXEEDWXX92JQ9ud06rFQkr0QcqRPIP1rZzlHOSgnkAv3Oq9Uo78vrYKJdAV7Gw1FeFFV8rNxmVWDupTqoFUgcHWKiQtyAFPgJSDrEw0WLviRf6HWeXPPHfIsaJUooqQEyEGsP4OnLlYyv0/qUVVPftQ2v5vnwG/VZOfi6hEmMHsPmdgc1ayTBVu4Z0bA0m8EB4mMTqWs2tbVbht3qS3TtYAYKoYUP0D5TNlWSTXbIi+yHNMFaFJBaY5HaTVDJL1WJo66HESfQaq8T3Z9wtWEZtwj6RN05f6XQxtgSzpJxk7+Wf9gE7jCK4s0Po2sYgIDlzXLOzBb1pDI3r/3kaSiQOvVPuzk0UQ+iMb+3Q2h6m88UxJyN5sOwY7mf4NzsYy9Igg1V9F26q/74tkNOrGH1GsgG
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

