apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAiyDi7vo/XBVAPU+5JhkVjA059d4mppRwolOyFvN7CJ1TUkIToFXSvvYdyX7KNC5at+9hEj1cuv5yBcrgO/uLnIXP+a/MLmbdqjulITOyMVFEm69H5EsDey6Iz8HespQS0D78OlTRBvJVtW070dowL3VvuqywqT92j0f50G4iT/Gxq8+7YqpG3yWv12a7xTUYKzQo8FlLD1olYWfrQrvKPKCwkZWPVwfCZHaV5M5B6NK7Gb/M92FuhwqOhdxNBXbZgluanJa412FGv9OzSLLGZuLu1Qo8zfJj4NXfyZy0JFJa//okOjlX6La/Qm9V1PgR51ADi7zco8xrpCM8PGtlUkF4ULjUEIA4XyUdTnhcCIuLjG/8i8O6UD/QQ8mA3lT+oT5mY5JfAxyelHxKm763fQsKfOqRYM68ZEdq9lcBBXHi3rNRNhsJHad7mktmX3nKRYWjw9GOlO3no8LN9QYt46HlKaN0ux5LXbWBdXgc8yLbcqxCxfdRquTo1qIXw/80uzhzaCsiYKkCnoRGVIVukfeTSQDy1KpDh5YgD3/M2FtRP0MnPaNMhv1LiH6kFNc2MvgjjgPi/S1RbcHe8lxsHyhUonFVeaLeWA00XjZ2/8NlZJRPjUAJWJEeoiTfaqQzRuxkm9Z+/lozQJet0RdyVo/BtCgzx0Csp9xTEl0v79zrholmnZ885ewKBLKmZBZtUFfOUzaxM1rrQjOC7PPxy1qYevA==
    AWS_SECRET_ACCESS_KEY: AgB9pkBsyju+cWG0+WfxWGrBfAVnDnHxA1AItHIS5lMp3HVYl9BH/x2Xfpk1gHK3SoiLwRmYTawHkoAE7ANSV9UkNwoGrBmYhmOlua7B56mf3UkcPQHzeeTi12ZkjNDzTEuCx/9IcDI4Z1iF03Hcp98p1rDIKWyHtICWzp7qjxArHr1iyAtvxPcWcQIBzeO0IL5zPNj5wG8+WGVHLm2FLCxnqRgz4hf91jiXULnnLrrX5veMJNY8fRSO6IpGoGU9rtJjcJRG6l5bxdGoT65dT1DxD1Tgv0jwwj9mFjFxGmhOWERgolotVuHYnWaZtaJCc+6Z+XfaXE818drXnAjdZFeBOADwtdumv7vXF7R7AMGPIAisInqwlGfDr9TI0vydPwiMizvBQVixX041PvlpTUS8ASEv3MAVquHX2ShwjRoWzWpqrNN6d0kb0xBp07G5g5wu96nB0S94hYjZ5P76PRaaFMqQq5mi9ESBPqrT37IQf8lqasuBdt3j7lJlHsC0xLOEMTBzyYgL8iYmSQyKsC8N23Qd4glEgQrlj9DXrwKZDjVIpDSKmKEj3/wZSi0psJLUkjitb57fLMLCuiu0awqdmQP0MDCy9tOJFX+wxGd7DO4vwvAhL2rPyn8r3sWzcL7szprXzfxycPIwOyRvABKPqCgmKRrZRqQpla+d8HI53605R8I3QERiz6sTqPAN6zAdS0prC2I1CqjyeDw81KXd+ZLC6T1wbd354d2L3XIXB0wmmDfFDpTE
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

