apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBVcAvJxaPXluPEBsDv8mSMbA9r/3YvW2hccjiLoJh9IjX+TaWHNmfPqVPnNPxQXaDDmKduLCU4ipO1yF+2NOg7oCp6gDY7nJ5HP9+O63QSy0pV150WsqbgD8afAyPFm7PwmFGUX1OoGJMj3/PFU1piT+UyL+owkW4rrShSl5Zh/Ep7Qh3BMFjUoL7MEqIpvRyvi6X4yOE+tV12A6XDQigFAVQtW0LhNz1+mwvh+zQe58wNpyC6KYJQQjakPJMyL+mT3FLL9O4ktZvQ2eBC4toN5EpKE8f5QYD5cm8pDzCLV1JMFY4VITGQ4Gt6ElBQXxN/iwdwOtQa3xklOD41ZM8pDVqKsAFUpArEF1el6jQ/vh8GGXSoYryypk7OjxAZhmBUXK7h4LyHhUeDFTa4dERCVCltu1c4Mpl2oqAiF+ppfEYWGTXyxyKQhWSqyGnKJUzr0ECeXBLEZUFijfhZZN8p0qFmJMk2v4fTpV0XHaaymha/lnI6yv7rmfjHZ/WWw2aBOd+ecDAbHMxT8nEMaoz7ME7N5rLiUo4nINBLt9HqU3X9Mg5lY0wrIOejisYAYouDvJIof9VrTKZ1G8V4T41mllcjHZSrxolkn8N3QAcrf9k57nW7yEftdNKqAKcd2bONvat3WlP9TI7FsKwY3Q9eSFwwnEVBm4+XVATEwLwZXZd9cBRVdcyfQX+Bpm0NzfY21u9kzIOPP0eTT6/bAxicntVc5w==
    AWS_SECRET_ACCESS_KEY: AgA7YtRCr7eNXmXaxiBulTrH8ZgckI9jV3TTNwZGcCokAMKRbZ8vBSlcEe+imwL6E5Gu6ACSfQMtwTWFj9WggJusm2dvBhwPyWQzkXYjVqrTjt1tLaekMsE4pKBZ29peF97c17xeUoaL1ISvWUvBXofaIEIcCJ9rgotQd/JG3h6Lx+uPMNOvmIUSxmgv79zbzNM30y/MOJz84B9FgsCwF4cyAQoSkgwPJo5ib/CoTiKluSYchk3qEmrax+HvU/0WdaSM+aL3JOVlwjuF36OdyP02X/uJbkDhCG7kSaT+x+CSMlRa09S44hzErF9YCEZKaDtnRjzQhUsYoHg8+Q3b2Iml8falE2w08thfoNCBLzhquS8T2R/+++7UaONr9vuhDGOeS9f30Dw2YqPYRxcTldx2CTFarh5Y09V1CCPSwXhykm+osRukh4xqkdhMiHXxm06HNRV57x9TG4mLSWJfii9wqafCqWlLXhNa8EwZgdPcEDSb7d5F0DGvnV2R1ruRTMl6jTJZ3DvNBaqI5frtzVX/PBXkCzEXIhSmprb0s1YoSolljofi1POvxJ07E3azXThxXEZNGo4Zp4DeVW+enGFMyRmvYEpou4yoU9JxB6ZIeVKLl9KNb+7iKhOcEoghdx2QFJ52896pstQR4r8qd1kkDQu3r9s2POINi9TqmUn20m41b8UIvs/UGnDL7mSWafJLyesmgObHsFoLNCdhCu+Q/XMynkbL0cY7GqQoGXHCU+EzoJZ4HzGl
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

