apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCIeP6ZTq3JvBzP18nUar6+/TTTMPu/kFQ845xJLuQiEFK2LYBc49xvLeJr43mFdJNsvwaMJK8Zh2/4Q/iyTOsf0TeA5GFNWjFOjg96xjk6eKMABNVQF/wA2KGqS3VIOCtUKod/Cs1DcDQeXaEkBVTZ8w5cdq5lemamghMuaWUaQQZ4cYpg6WIKulzZhEmWqlaG+Ye9FRdmi6rOuNZ6k3wNq5m8l219LASO4Qrwge6XI4LtLaK/fM/keLKyN62I37Y6y5ttZtajoertOs0JEipoAsySAhWruyJ5a+JxV6IP73YiVCa2EltgLpCRdeJC7UOSiW8q3rxWzJVddlo7ID+rJtbfs91AIHPDWFpRQOObGAVqTmGTQ9p3dllqGR/wdD3l0JCQsgReYq6s4DR+K4KSzXOh3JajangwLbcq/Dx8KmEKILzS5mN206nZlZvhSpF5lcD7/ES20TdH8J+UMipfF9a026sCFMZ92NUvT70LGEDbFztIxEoKJ2kx8hTm+4R0irfE6vb9Vmlcy3MBMTofS/lP+ts0NB3Sra3vwl7XilHsbkjg0CJ4LfRy0ujt0gGqjSmd55SdBUv3Nz2jWHrxfCYlnXbRNTNlZBPpRwsdLP+0oiXcTKHxfNBjrFJuc3VJkIiXNTgcCtnUM6Ar5tS/spSVh4HgbE3+xUIgqp+j49e+Ol3iEWvaY/QjfJtemPPM/oDFv8/OYvA4js+LMhpC4m0wYQ==
    AWS_SECRET_ACCESS_KEY: AgAzPL4oSKFWzkCAzhul/KyV1QWuHQnD426ChqrF3JX8Vmy2v1HTLt7b3bEjCsg5K2xwbxjPiEc3/LWVaoDJr+7cJUv70aNVDWXH7S+V5vytpzWDCCe1HhtYqWTP+wSjaUeskDzGRnJABs+2O1W18vzFooOLP6KWyFp6+26hb7RHiEIn77s52sYwASPrSDencAP4ZF3mqfOCAF+ettiB7Hshn8yRroBDh+P0uMk+H+3m3DZE/XNVHatSmp7HS1XfPsYlCSr03PiEW06JiVO/sjSV8u9lJcvYUaAM4QIW2k1Yp0o6qFNNqnjQxrRl7R/TnEzq+r7hn3LBBzgTtNqhnlIaLzjqt4ngXN13i/ySq4IinLEBgw8tlvM2Z1WVBbchULQTAbSpcIU+dq/bV92oEkSaxSL2yrTjNCxyfnnxqnDPSRIbJr3w20C4v8w6V5RllbAoPzGoUdGUUrvgT3R9Pk3OAqxdce7JiPSDVm0r6prt8qSl28XpaUob/LbEzu2IiXZawA42fVqmUap7L6Q62bPvlOMa3jqj2nbl91WK2RHX4hTNzX7XxkO6uTJzDRRHGUND8oDeGfApyUyKqleSxPKTpjOTyx3R6faWtY0kxYrUZmatUriik04T6AVk7cHglPaCvPUTkH0YXohVRDUZ6lfyIFtZ5AcvcDl7ds8Hyx+MCz7Pu/afxLi8mxFRfjib0AN3b/NLXGK37NwQ/PWsna+9dkuCyPcwHv3QBMxvvepEdK21qg6ZJd4u
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

