apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAqCpq2KQb5rBI3fzg+z/ZFo8mwjFvyVzJ7HrmiKu7NY2RuiJQgTUn2d0vhwZmBLYdgHZjooPWFhDtTGKdtNUmMakEqDXeHQgvwfMdjpPySPVsnK1+ozN2IoVqoIJbBeCJXRe82jD4OzLlI2BfKLrYdeDE92M//qhK1MpkKOcqhJvFA7aQjMXiLQ8MCPWmNxyF85z6vOS4nuXyn9BOX38oNqk6Z9F+q2+ZFQ27cS0NgeU9P11AoDzMbC4K/H2ZePLIuwIOCJyTwnqrnm8x+0AS8D8YvUO/6vwAmwRIiRSsJWQI790UG4Dbf8Z0dZeOHV5K92GQ5fyzrMcoPBTZJJmAV6ei3xWiecrQXYZ0OUYN6NuUn4ogJ0waTH5OdQpgyOOhBpQhRonKExhDzDCa8hB6WXtEcWFxgR+gmClLP0T/k8zlGFu9tLX6VTCmhohO8WCrJnBTYvLGb1Mh0lgu57k9Q31b/VtIrXGvqvqpolkHPvegjQ2GUIFuZnkp4a1V60gZguh+4JS6Jhg7VcJnmYQ59qSldtWvIAx1xmbB9GrIwiL2c8tWE0FqGux87+eSfhUtwwvW2ZFS56rcG6fK3Jq5ptpf5fgDXFz9cxQ1JmOcTfe6TH454Tz7RaIkruDPT2FUUCXF7HRBRJMMh+2FnRrtvkXUbDZRpQSr0ztFUzOteGSqO3DvtgzAcog7CquN6akvIn3B0HjNMVWruNTYV4JmbLBtlxZd98evdcH94FDeoOWW53V6BlryKsEb8BiuMwjG0A6K8ELcdNaOomJ1NlQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

