apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: database-init
  namespace: default
spec:
  encryptedData:
    datastore.sql: AgDXH0aP9Obiak36h+1rMwPl5AeK0jcwYs2SUxTi1+K3DXvWP/LH+KjMk13Jt4/7BMqHiw81oSD7BQhGiiQMgrIfdhVUpLVxodEnW9QCZ9mPCUSRhilJt/9EUOMpYUdzgZzgw62nbV7h7oNkquLO3G+fxSCNSj0mEBumGY7IGfJBON1HuBhjvb0lvym0H2Uk29emv/fSNDoCJZsKH/BfGRN+FW93vrDKRBVk014e4rhUcaKtICqY+nTchxupQEOARtqYNc4umCUvoKjPB4EQ2JhTP+fTbGhp+c9UnHDfDUvC0mM0vyJRmo2+Uk3k/oKGKv5uTUJ3pgsis5Gg2zFS2dqRx6NqOva/Pl3SmIVd+RUBGPprAq1qUdbW75l2qb3e4yT3qVqBgYYyYTC+gejPTM4474ujw/3GSkdAcc6omvJ0V2oQ64bSmZPymP3rEr6wROlUGQcMmWLDfTLRKgniVLILhDyX9b4KoJm5gjlp5rBQqvpiGvOIMr5RP0DZrJLjAnZTjXCGkKV81g8pMFFBDmodDzoQh3zZ4Nq2ANd67zErTgu6wvZiFKYRDDONtuFjN3qTAfQNRR6VsbrCh7qoXwFmOD8STqbMgKgErkD/ptkjrOdsoDKl/ndUVIwAlgHqMTPtCtNohkHAd1jjt2qrYO5rZlGe4hCAatMzt1CxXUwJNlodeXZtT3oncrTzT1xP8EJa1C1Z62m4Rbr6BYGpf9E+X0sPrqPxNy+AkTMJ1mMLra7gjkiIGEOuYNPdAUiqip8kM7kXWGG9J1aAj5Ga3S9zkyJQdngRn5i3S6G7nCAQCorSX8IeH8MbzxnZgkPdsSDmKebXDcQzvYMOhOwQ6l+kz93WEvCq7qAi43PVho0kky33DtMCOwO9KYSWFA==
    order_manager.sql: AgB9RI2D1WM1AVJ15HhgBJ6/24B0pbDH/74OmZ3xEQBQ+r5ffNFX3JQg/SsuT36Wg6J2YejD0NHEe+xSDDllAlWf/S3RxNX3F8lvVBuBbgEG/8uP8TTc7iJRoeK55gRu7gDjBDlhHwynouPCLIUwgmfXVpWXt0qxAYv1i/x2D12cxEGDhxzkiXP3WSWNG4DdfO6jIX10DB/7K9dg3RgysRWBCl2y3BSXtFp3ZZ0pRwgap/eGenGIQzy5m/NS9fk5bBmawwgMdoA9E5tYXkHJd5isbipekwvS4zMFhOKRY4K7I8m/D25enAZrzdpws6zN1oVckuLvUBiAdhRP6bPlZQhxZNm2laxWJgvuO7KUatz7cXCvKo0RwXSfaig90T0T1XIr6CSUgsxNIPJswF4WXDb0zVcBRLxdOtq85ZyeMHzIDxgs08TFJxYNJeUVNwf2D70y7L9g0LKpzldp82efTfoJp8ufhLGbVJtv0j7Xp3O1bCwAphwa2gV6VDThzn2xgOsStxl+WA5q+AmTP5wAuxLOopsEZIEx1hF6tQdd/s0YbhAwcv2fN2u1TBX/RHY56OCLmliO6+x80UkbhZLomZ6t9sSZFxFz7LrnUQF0GFo0Z6a63ZbE5hGqW74vpBKUqq8VZQuJZS3k4iNMVBtxRKhDpEI6Tlxwo//77PdmZ7L1ZEOi+H9Lh7uNwnAArNfPYbttERmKRgs9j/4HN6NWzf85XtP++TT0YFzv/3986DmPd8Mo2NVaSyCqOQ5/utnidiHgLvBGXwR1+2pGKjz6I/er+aySd8R9pbbhKVnKTI0nU5wWKPgicUSRs08IY2X6bgRMGXuUaHTJsKzappaPzKDkzTFeHfgEkwZZuqDQhr1jGBYNh5swlhARNu1Bpu8mycgQZ8azpQWLzw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: database-init
      namespace: default
    type: Opaque

