apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBtji8AHFobYduq8Xtf9hIwE0t7t0UO7e5fEs+WFs5Fu2lVJlOYX5xpYAogtlrNt1Vui9AfkOk6n32pMTcsGE6tXfnTL2rGC0FRUNjn5+6EJyVTUeHFGTD5kDns99d8M9+Yb5v5VKOGxUYZ0xLfvSS0JUSu5Z164jKKKTj9kAECAoprj+BbhsbqFMqsk5VE4u8e/c+UqsjIq/GefhrCBOOBWYRLJDJm4tV9jiOR6uVRV7uNXkAvmNdGKVthceE7iPj3LNdQveBr+fz6GCrnfapTj7jgJeVcb5GY13HcezcWzpKKi4VN79H0jBPCwl4fKOxPL24WcSEbnp7O3ct/ilXjsSq7TFQh/YVxqrOAJ/KRBYd9Lo2kT6u6zMppgubOXgzpAGTbvt9qgoXw4zlbt1bAyALYvKRIAOWK1vqYaUJKkkzoKX8pnMyCfrM35PQ4y6VvIod+LO5LhOUYP0QIl4TI5NtUWumZh8/dYxBOSgRvrd6PFG882BBTSRRKGtPECgWXu8Xb2tYjrFNdas7eOtlNTpRzsrRrL7Jw2w53KOoeFjoXJYd9juP9NwhE0h6naHXYL3K6V6SnfFIq/CoupPWzT/cfEpr3D2jL0IIKUjmJC/2UD+D4ECWirQOkz30WJ859juBKkX2VqXdFfv2eB2C+eDQQFRo7lgQv0DgmT1SJ59dEfbhg+wGy5jTR3fc9u8lcSs2aH/jnfHUij5jGWfPjFE93fcsevoSK9uAqzmOxxpxbJ5aK2nKP091jdjGOTbfhk8TY3UePPVnHydNF5g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

