apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAFHI3iPZ85/GYoxRctjH09w0CCeP7efyAMqHpWJoOs2ZRO6WhUDMDRU+24DcWAJ1WoMWSfeU9rMdJOp1wQmBdpRrVWLDj11nZY+4zMqmPTBK6bNx7IB40bbxa1HEOvzwruddpcwjZh0FN/me8nmZ4G/aK55ViEu9e+4RcYk8ssf6jN5krv4rfHW5xNnthedw9/gZO22wrETBzRHK5rdVG8I4lEXvRVJhq5nNc7Wo9949UQHCevzXCInoiFC7KVHD5U0eYaEtNsXWsP5v9ilbZ1+boqlQ59k6CCosaMCyKipHQUC7f5ZK+7U3j1Z7CFpolENOXmW2e2a7lxQh9WSWhDhwwkUA1LyAqv5tRll4kRF68wdUtTmElQxqQetJmxDosDHUQk16zvc1Ivf+8oAsTGdN8Q/DutBDigYYn1+CHI+ylrG8TLMZK0Jx5HGhWYUAfK7LUk1kKcOMczEY4CKOIodrvuKlMTe8B6O+044Qdpj9yJjRecz6cBVIV5WMHeG0/qdPDL5hfTMOmKWn96niHyTtGc2YQEFa/rHmzvCKOmZrqZGqFQgXYdTGGQPTDzmepgsKqwekKDzsLQRhucvB7XDB9Vx0lorp5997L17+qo9nlh0+4cMFrB6Pbk4wW+MKdnQcKuErq2Gx74ghfL9tp2k+2C5RKxvlXXh43SRETZL5kavA1QNHoyo+JbBxvc2TRQqHv1oIARj2UKZ/4LKJjjdyYI+t97dpNWphQQ5wYvZIE73cEDhW3G9z5rDWh6+0FiP6e5ptM5G2iySfr7Zw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

