apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgB0wazZ5vDMaNE8IyXB97CskoaHHkTSRKVCXUxCJBKinbYOJ8bLgPkR7W5pBvO+FjPICPKXI+elHXZu0wfW5AqiLWwDo174d+isrv3Frqg2+aDXDzrG4m4UkucwILFnxKn81X8012QyjW//2pRnY1gNSOm+VAiAUKc/yWJz1TygTznL9XHeZRZfAy+XhoVksTN2weL7oC00ksY426j4a0hcgI3yuNjGG9dQRovVb3ScMDqfyA8RN5Pc7CU46mojExpA2+9IbAchI/mdb/ixPCIYGHtOSsvMD2fJvhoUqBI9x2Mdbzl3WsjAU0WLbWEo1FBDWZhA0Wf/S4pt8sSGJL6IICSV4BXMI6EAhLfjTI169QB+1GM0r4+N45JmmR8Ap8cjbFeWl+Mq7sYx/vXBdoDpf/OmBrCrVzqNMtNydsDu5l2zMHwIWrU2rWEN7RgzVL+Z4MnddvwPo48Hr7s7oWJ7TfuYwRLNB/7FDWQEI3gUSSAf0Fr+IrJFK379EQlBx/El2dBUDWhBB4K3+CmAus4v8az4/+kQNMgaWR1tz3QSQePyj4s53V8CfnRdol7abMNIX5jQILETBwjoLHKuBstppLq0kF9Ew8I2X7bML4gaAbF+j/CC63kWyoGDjVB/IjXPaF1zg18ni3yM0nQlXQFNlcusjz85AdUc2JafOkT4zixrCHEDszrWULkr5HiVdHjARr66xumcvenF9/WZtkxuW3uBDFH7HdccGuPMg1E5tfgVj5WhEqKRtyqCHK9uCLoV0Igtxv3Z1eWsH+2z2A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

