apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgA3dUfsFcTdu/QQUAHf78/4CktnS0A9YCvS/Jrrc7iVP7JTwNbNV6a+tBhT3B3nw21uYGQ5q6Sp/dhvBVE3BNjfkLK/0zP38BUxWfgM/RJmzVn69A5Fe5Ucq8ccpipL5cCjmny7jOgIZDo+TNyBs93H8wP9Z1HNGelw0u8T7ZBvZfk43UKilgRnIhi0KMb2CrmEqOxbp+Ub7cIbVwpbUJFUMpkNB4E/AUiUfRPEbdGNUD4F36cLHRBQaLqVpSp5jwsoBZB35sW1sg/atpAMJNU1TQ65xBTqcapTvZCTpHtvn9xAfnDzD2PM5SyP7gV91QJcHgdcEnl1k9P402Q1lz5NKmlIf8gGtsLceeaJA3JYOkVuuH5yOQ1cKcLVKNzpn1degWI8HVmTOIier6Ij14Btiue9VasxM0kMbwCkFm75JADbUFAdt2cn0lU1C6SkrhHqtGA3UlbUBz/KDU143/OKJAkmlULsguE5KMGJMXKGufxV7cqqBF9sLwxkxeXUgkko8tWt9OsWlS7TyxajUlKBpb8d8DqL/SqE/ia3l8OSNbDN519zSiYZcDCZj/gHKp3Ule0RkeOkDTJk7qRHjxEsJwtPoWGS0VIqFZ6GQGdhMdIqGFV04do/B0t8OFV4q/WY5cZaxXzvtDkS/OylDNf8dBAjv7xIH61EccaQrYVPsdFenxbHV4hiDyRVTSBt9boRIer+NzkUAZpLpSYYLrCB3xrhgRDQli9UIojiyAbp/k29KyNiJ+T9nt8Podo4p4bkqMt0XC87dgopzn0DKg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

