apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAMhNmZjcC2Bwhw/It59zJiMWNzW5xAAUy0DY6LErbKPL7POTXce5WGmX5zO2r/BS6ILMeayBj1mAak9WXT3hoLndO5OBcmvpnrNU78YZPyOfk6VLib9cvEJjwNQp4iO8VeRdJ34ZPBJXJwoKSSljBWGKQUtUZsGdpyHp95q2Bnlt8FWJ+slyL5LXbixADsIXCpA7YDhf8YLu4k+c0JklsDalOFxeopqWzjKu9Y5M1PTUKMcX9gqsDhU3SLb7hUd0PqJrB1rytUIqfFLQflr0HVCfynCYwYo6qF9bh5NnTsb14gHvEjH+cFlMzXLYkjAszOaD2iRGrWtla+koKqCMouMEt4U29h4JeZhZDc90VwwsPwQ16AlIPjcOlKzH4WSjrB6C797lBBelrHbtwzOta8JrgUDmbEf+2t3sfK4fZ479RsJeVJrzjbU6PtaHARSRNfCVojCVjGaMlu0G5ycovxpjP9WMPYTBappXGVJZL6LEgbyjEl9eOOy4CQE+coc32N4LrY9ExLTshSB7AsqnJ8Xi1hc3jGyTtLekI9ZPnsYxIJpcCoj/a1dbczR5X0mP4orNipUht2WpoXPLfyHWdUgfgGbeTRZeZJa0wGgl0w73ON9A/RIOYoCYl0l7y1ewxFQu78iJqg0svP++t4d/cCMv/6BZwpqfb6mBLvnNsJP6R9zo7KTNw0+HfLR+FKBBcGsmTl6AYOAkROWWet9hAYWS6m5ukNUAFUNMbOxj3/MR+1oLHL6rMBh6Scb9hly8ViHyBAcGLoOCXl4Ixczg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

