apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgB0k/Feua8JKP5IchMnLiATh3ZySgAQci87rpxZ9gQO59A44ttmbCk++ATQN2UmwnlUgDL19p0bedtcWt1iJFaK/ZpdVi4ihPKh2sk1GSHp3HE3xwl8l7NS/rc+o81e66+U7NgTDfbgX21H1aSFlxjWZrLKdPUkLKkiWyl41HWgY1iKNvguaxal+4a9ez+kX7GQ0y96TrX6iJ2EiY25l9gAogDOUCePmXY7NxzUuDyg3jn/E5NUySSvmhh0ex2wxC/pCNucAcasyY2WbhgGjsMCagyHhw7PWiYHKFM2Gw6EiNtlLxqncY3EKIbpPfSxPt8i2JpJxEJVifbqcciG3ra6JYxQwFdhUUBg2iZ/58Y1E60RD3mFnbZeigeA4jVNfr1SAkzOeuZiXV6I2TjHxxLiLruD9RzfZH0khJLVV+faU0hbTpKY/L6zUOYDuywOMxs7gvX2q6y2QFKWfaox+UKmw4eEzhmZK61OMG0aJuj2HmzMd8RM2NVR8OGJpM9z+le5NJ+kfdDwDKtLiH9q6bBdKGPesrMtLSKLa+rIRt/GNoRo82UIU58sveeijAimmJON+DNlGYt3a+tFkXrQWy0k6pvGZTd1LdR6U8vXz+uX3ZB4PW9r41fkGkp2GCLLzTfT/898nOO0W8Zfg2l20evyX5tRCcdP3CA9hRldnMDxtnayrK6HKa8/8w72LnKO/k55gzBV5JA0B7Zm/01GghDjtaTpxouUdmzEPagJntXB3qwRoIuuRnsmu438RHMv5DrqMyiPUC59nHw4HbqlpQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

