apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgCExRqTcDf9aRnOE8/le7+Oe/2fHslOwPPwBR8xQuLBXEYMEeKnLtoy2j07PngpzBBIdYWv2cxmKLsGLj3MviftOF9cTqZbGGoWBMqv+nhlkXXGJQG22DK6r9FWU776E2X8yqISZs+K6Pdf1XwHP8FuVNrqYRubAyHW+oBsLazPgiLnbiIKeyugESVpmnG6X93X0MUIPLbL/8iQqbhT8WlPH2Hfd23gbuUoVcQUphE8Us70fH56v4G5UzcUAQ4YjK176Y7x2Hn3mdixFceAz8kkbUTecoBvb1xojBuD2a0QRpRr3rgRuWmYTG1SoirkAssOjr8waeD+rjpHv9AYmZ05PuZRaSZDMOpoR2/biou8PRYPbqEBFC3SB4NypIIfGdXSjqTGge84OihqeIhyvJdtdWowFp11OrlUmG+viqt/iuiBWT7ltx2n2XSgqdcyLJvITPqx86g1tf8Ul7XYRHE27QtaKCRc51BNVglZ7cZ2FPzRvLaHinYp021gComNR+bCH+HZHuwoAOTvgkf35UL966VmgEcyZp418tEgmjXg7NUNmRQUd//78PO9ODb/DsAXFiB5v5v70YRpGXNHf9W2jB1neNY1kYObO8aI6IrGNQLQJzztWMsUZN0WierHZdOMa1cy2t2BAfzp+HXVidUH4T3H5IGvKPx9ifqFsDro/sL9Le9HOTJNUyzzqWiTmGcltHyHxbiikqB6NpE8vUaKpDrPsDm+vcDksA+HUZdeFU7L8g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

