apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgBbCz2V1AXN5mqmRDMxSN/Fu1bzqxosiSSgSTxAXFaTT1XKQuQEC1FISK0cW0VvjcxN10VtYdkhAen2bAL3pV41Y5KYfBUwsHu51xOYIrfyJqsLcRvfyq6RHDZlJ+sk8yqHAXVOHVL8CknPo0Y51gmhW+/Br6CUitgqQ3xkDiJMy4CeVJ5Fxsg2VOwXIJltiM+T3dmxW5YE/YFzLZWQHrznycOhJ3jXBH+A1uc6Yy2BftK1/B8s5R8HtOJXyGTYb1oyQ3HnBI9wF12NfTAsnzWZwMUcqW+/+l39r+zu24ZSn66GS6KqGIzmfMII87aZHTJlsdOO6IICCkaQO2FAT6bmDbHybkUibVm0+xxh0wGp9JZcWVlKXyRBZT4/uufeHm3nSfpCPpD4HxqwkVfjihSXHuy3V7EZWyyNHlUrr4tR0VYEguUWxH3lCZqEayjOj9Zci+W1AOsPpTAaNVWZf3c5wNjF3j/OMUSaJhV2iQ2rqYMvG1eQsevLrwCYzydH5VMho14pltpEsAYKmEaMcupEbpYnE1hGwzXwHenfGxVPWhF4fh47eYI9Mi7ZmTddSz817Oqxd9VlchUBPr67NDil6sZYj3dTCPvhObDfBc2HzTUc8WQoY2yve7v31mdmL4oWlpe0qgOuPwJ0hJpDtHDWGqujUYIzNFmpwjGTR9+lqF8g5TMsiH76WBaK/solTSkjoK3hnLF57ek1GHD1q6FXq9BsPyKS83nbsmmPtawbx8XMYw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

