apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAzAfsBoSbruGIQDohV8v1i65XATiexaHfeLgGLjv0VI0YHAu46icU3T0jaOvz7Hp6zhihOaSbVhg0iiKJekNEFjmeuR9UjEwca1+JlDgEk3cfGeeCMzD1GoqrWZ2FiUwX3oabbshpW0esST0+Md8378jzhL/sfDZZuDvvIAvOCzKGPDEubYS9ILYMb4KPxk7B9Ii1lquRliSQH7sg6PVYLz+LppTunNvP8Jek3PF7IPFAbd9JK+ToVd/tFZ2z0DeW0WyVs81OW/fgRvy2p6ZCrtL8QgEYE561ukyzJjuMEUKyibIflA96vEMp2oUiz9nhI5gL2TxQNtBVyGeCzOem7CCiLz+LnBhgMYz/KMJNajd1SKDtITp+cVawX7DQELsDckYSHqAmrJooi0I1B5cAvI8lEkR5h4L87qOop04LA/LYyV4p4bXthN/8LE+LQdRElSp16H/jYB12M6OjLn1bV6fCDZBw6Yb/LYYM99Q+bzycGHMgWpo4iTax/bfxEUmTvZfsBUQIrFbK5/fznLpX6sguA9ZME4VEWQ+Mq2WPtBf4sFVbk1O4czr9F3F9EqT3gUWtdsh1cf32U0IybKxSqRBRE5TYJ3MxFRPJ/oRTH6JxQeiufn0wHv0+pdf5KPD7uUmRbu6j82KjwDQbouVZlDi18PbJvbu3eN41TZ3C3mt4vdt1o18/U0BLbdBTE1keCqB4Gm+F79O/FMflkPIxsBbOA1TpNSKP44oRUFZtpAfLztw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

