apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAu0HrdCLuPjFjJeLgVkQKVOOuYy1J02qv1WtAozKvcqffF0Wy8jvwHoQT6h3osJOs+nxPEIqBjWe8SqoJsQbhNQ6nqX6AwVv94+I0m8xmxFI5FJtu0k1zI2QuO3oAcrIj5R14C6oxxW1kqJhxJKCNgSx6dJ6mvT60hPl5RGUILwUKrAE6JVU3WnjUyXHBRs3+yn6ZbxF3cnfpoRwSXNYKJq/dK5FR3ijOj1SlsVk87VNNcgxUOoXegBhnoiVsQOgBt4zYSuqZze0xqGtiJMXnbyQhXKhqnDReo1cJVTI2Dy4A8OHWCOkH8SeNyGMe4DHLbGbLgo+C9esktacqjasz3klcrxkqwQkPaHBP84USSHFPDIpMjMF3Lbv0hxRG/ldT8MATXbIg9YVv/Ua2hQs3tq/iissVUsSwPNSFokaRnNgXo5HcuMKIwDVnscRta1URd/mrtyAkicOPHK7NH8oifa9vHoNblrqAb2wrCkcjEkI+AdW9ctB598N06hLIziSqRfY1/P4kIhSGQNUfhLsejywhe0B6Azu/wIcddcKwdCd5stngBs5sfOCuAIce+FOwOUgVjKUt9hikijl2bCJ14js5ucfkAf/2rxyCk+k5HSZAIWQ0ZkonwA0mjHzgGS7UK5fQ94LnkjHZcoTzeTbN+O+Tq+0SMB0xS0zY4ql2UziCufdnAd/jl3VD3p69afos0jnmAbqLpQ7eDO8D3oqToenAYhUGj8JHwT9onGRLydti2/Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

