apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgA/MQ/F1xeUn+4WbAlfsfop68tSw332FaW72oxYBqf5aopuv8hlD0wY73enHPe/eK6SeD4cMK5xA7vWIh4xEvrGqc7E3peFNJFOs+O4wLauHL6Zqjv244pJ8KWk0EW1Ru6bZxuqHROU/okxyTS6D0+qpeNVLgUY2tZ12lctN7YFwgZAjOvDT7s8JCtkXgvtkgc1Exsv9CWJVxWr8G4KB7BkxUhw7lU2i9nVHW8x9WO5QknK7Lw1j4zjQlSvUQgIxWXrpeKE8emmKLBm4JYETjYvIi7ek6mSXgC6I9I+SVjqftIpDSgw8qJUQKLoRLE2YHdkw3EBWawjCjQS1yxWH4qVGSvf+RLw17Erd6l3VAaqQVAxgOhN+FJZ1dbrbt9D0TsI160poy10IEbYSRmr0RWBJyvINWD946e6QW6hBz/MZ/Fq8afucaFZS04g/CzXatTpsx5kbcoH7KXdxqyiaENlU8tjouu+InN2fvKWSat5bD1eoc7oZPFsw/e0+40gtPCjIvLViiihMO+FyAGV764TMYx1W5QpiCMcLfIWNNbhSO/ZUiw7w9B6pX3hkbCLJj3jkVVDUPtW45woCXFEaEjk+aHnA5SQoaZMLbmHpypWKbDiK/ez2Py3U3eux4MAsi6vg/ZQFufG6/7uyUp6DkuJzgHPLU0avABzvo1Z+9BqF46pHaZUB0XHyQIFjUVC0rLBd2mWEVHeLpBLIPqQWztYMIzfI05hBMzlcia4d/pfw2N9fg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

