apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgBHcZHdnH6kPm7t68nC5lUpIIXl3LxWsRfytVP5f9aERwSk7XDQ8+63cAX6kiBQdRDApemz0lhfmu49LRGnkkqU2YsDIp+FwtcZr4q8vxTqNgZ9LXB7tGCsp/masmpsyHUnh7DVpQGX0oTHjSqD5fnZFrCAWDshyJUXnUPrnCxjuL7uG180No5F24S0cgQLV7uweOUeMlfL8Qgtxc9bRjnHcJPskM90iwDeIXXRcx31Hwauq5UQRhM/SVMreOzDr9MuurQAJZNmM/lZpO4+q/T96ACaCEk2QzRgw4g2HE286d6Ptrmz0Tw2mJAemjeXcj5xy+3qiEEBGYW/WV70xDg2ZxPAci3Xg2oLa2s40UAfM1RYL9bsI4/aqCQPOBeHs3ORj7eAHfQOvPXbH0NarLwlC+juEOfT3txAqsuOTXCslMVHBzg2gR8uYagX9RnTtHSOhWctKe/D0w8394xlpN5dEpLm4xogsM1iRABNvpWPnIH3gKA2cycENS/iXlCXbjFfyP7ha0xTrzsHXaumFjbtGsMkxvSEEey87ZvxKZYsULh410LBaHvqNXEQ7b7ueGMmwbpaXnMq2IdNz1oYADFyYV7yIuoPuUIFCAySmQI1zPG7xf/BcfTyEqxuGw4cSW1KRepjOcWkFW5Rd58UhPgQyZizhGQAp9tASOMfvrkNC4njgjIlkNOReiuI0TqxMxr+RQVcta+H8j3PxfctscS1TYEoAXMIoLbvb59JK58CERI5dA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

