apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgBjNCvdHaIJ8DnUYw/ut00A33GcLiPmOz6phfqFKCYh2cC4YJziUidA2BNeuicSTC39GezRGqh9sCbxdOE2c3wyq8yzPNzCdon9Fb/kf1Vxa5ld8zc/NPU+yfSmGEdXKGsE6ymNhEZqxnSVnioe8+vRnE6PHlnrwJ3tHblMSwGdsQ+QubWCBomy50XPvcmdT6VsYpFSOe+4sbvmSDkmYw0a7u/3XF9QZN1xFPb7GMBOfdvtML/yagr2/NU7f/Hnw4NpeEGd7Cpe8KxuZAT85KsEeqDjdh8p50k/UjycVsXJ1Kedb68k4/CVvAMwfYXAdgOPom0WL2pZxUszOYzFZNOhjWdtAbUz/1BRP1fqPSBwaZDFf/ZX+vSrdej+a+d0OcPFO9WJlyA4qGfFpyCtF/0Sg/4rrWFGBRYY3XqR6q+/Ve4wBs8pFROIKb0aSXre0O9nZgpYvc6e/3fKhDqWHgIgixjgaPMNncKU3lpU3Sr+IXPUaZLh+aSPxa/38NwoC5Fzt/p76En0EwIkfZL89w+dwR9GqB5o0NeHAfHivtPQiHVBONbbnpQrSAdFSZtKImHN3OHW5dHa/vloAhual750lTw1Ps+Fj6DUWHTb181JbKzkW0B8jYUj+YN9XNEAjrQZVCkDAWU5mQxyQiiu15CqQdHqAvIROhdpTpVDkDr0pqWJeSIfqP+bKJaoZB/SH//oF5thqmSQUpFiS4ObvSN4fYKcw9Fmf8B36EZ97lh+M4QaQQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

