apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAfd5QvhdqpgkegnHoBdCXKnKT/vXZULXHpuxOxBz2mHWCIfsAZnNThTlILAVhNWgyjKYHtifhZExINgelvT+KvTTGNJnPr/X3uFiK+1vMERBqOksCYCqWCAGuC1uT+4JF/A9IRrJf78ICVB4bIz95L8THU3HfvnKQqIlaLsQ6YXTciHDc2/Yi9vrzExZq4poVRLK7xmluxBUsdsLRA8dOV3xoYyGn1g9KU54BCGTh8OawKrI0WPLxtAHUFrStkafTF5NFkNcJ+95BgNr1Ag0/U5LiXdvaHPEL2dPKnC5YKc3tnrMhcBHyEmqn2U2bhx3ecw7RBLu+1XRi7PU+t8x8ZwuDP2RAQyIIYUP/1rkWBfTWrm1JjCaVAiLy5k/vlZtnloia7GUYgK2kwL5t5FnGaO1sneXdCPqzPARc6n+0385PPV5nHRPXibcvZJQOyGEM3jRL2U6Ug5/4PQkmEH5FlXYFaQukATEXNDLh37l8cS5QNa/0Av73eVe6KPbi9WxYQ1Ki59B+8EUkLz/y74h5xea0u1cISXHZe7lI/JBRnQxnF7plZ+LFz3tfz1Z6xXQyNiO7aFz+tsicjycO4gQsQyC8Vzh3BAcepEY67Epr2pd73SJapcqq7kc36sNdGBQkv1yfYPOmT0vpzKK6+8W5EpZhtMaUXcaT9kw955gRjwJlLaXe37VPXwCX4F++E5CDGF7EijdnNwO//M9OpjJtoyiUN/PADdUAs8AU6IZ93wGHQ9g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

