apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBvG7QgqUex5kKuPRbqIJ4tAMUmcD/6ApyFFtjderRZo6DCdFs3O/lBO3eIinK0PORByI+GxRruMVfwAzmWO+p4M+3b+AVoeiF4arJ1idepS2VzWU7cXegsrzQiwiq7yuw8WYVtZcveFCbG3OTrcoMECG/PNxWGcJnRLZnNs0mPHpdzZ0b9EQ+VPnEiKVacZDBe34Ax4BYc2S6IicvSTu7tSJJja1S6d08Eto9yxWjBb/7hoDhua05vPUWH4o3/2caPKwS5mYpJ1skYwht/RqWYqyp5xln/yRuMq5h4LIlTflVhQI2b02ThIqdqQ0gdauoZvyAqJkl4AR3pf1LW5yCwDiuRkHfPcbSWgZtX9z8qcVk6DtzJurdHCSYV8109R7ykKzXk6t9PgIIocg3fsitQBqod8WoH1ynspT5yivnA/PN3ibYUsWcbtB7/zbgos9tZmU+wYu+wzXCaErSol4LBqg3BoG+20fwzNmnBc8E5845V9sSsn54PNY+KAJ+lvNOSYe2VSiohSFVn92w//gLNBaMIPETrHNvajZxAXntqx06g7++/9efcbPaSt1oY1ewZo80GOsp0yRQKOn+sNNVbInsbYMLriniE/rbOR4vqL+38HZhURgfOYdBsuBIoIvu5lWv7YPHuiLMw6V+ZAzjnpbfaMWLscVJoR6Tgnw6Ucd1EgvXJFuCjsYSKDFoQ3M+qM9Vn9x3VUfrdSFhA4mHUemdhJbd9+IFQhpRMTdKrMMRAwQ+gMPSld0pqyhAHU5gHMZGVv4pg/gkjY6vYBrXd
    KAFKA__SASL_USERNAME: AgBFy6xKDGvnCDwo8BTAlQDp5j+xHf3Z0rAHF4JRKDD+XWwjXkrS8HEvzSwBl8nfXEiUI7v4gwG9z2v490zUndSGdTYJMimoETs3r0k3Xtt9sQHQqv/NLtZlDaWHzhernA54jhABmd/h5qMpTE6aUnG9LhPzZKFQqTY8G8nI2QZfjSTIcwKFJLITGqNtjsYlx4wivfiz9s9udKvAxmPl6k6TcX4PojfOzt0jtub8rJ8N67/qdlpqdQP6g0IFy1QHGLDmpaB8s36HzQSReElism3veAhSW+2X3nKjXwjALfURzvZXgnjHzTTBfcN+YZ3T/Vv3DqDf1nsLE2ymNzpl+g3uDUJl2SjNGehZiH1YqXTqezl7Tg/5GkSvUDytC6GqyHE40mxyTcuA5BI0fvjw/NYhMAGtzm3l1j84I2QSHADdmMbg1cgjVFgwPEdjkWH/bge8uABkOY0oNvJk0F1lT/3jtWAGLKKtqrnyXWeFkge3s3deb47vWXoxScrTcpMWOus9hDIDqoAEm0Bk4h/DEQEYZ/Ng9xLiJGeicFpcQG6m27SKMrJftzvwCzBs6SRcmeKOW5PYP6iZa5IIEN4/lDnAui3nBbh4IeWk2XTsOtmMN574muuUdRiyvM1gE8S/bLuUf1DP6HBGbicDtJFxhzHdmTqJJ1YyyXdX+vtt6qYjFOj57lVqkDjNZe1LzXAbNcbir0CbWZQiYBuNvgr7a+yl
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

