apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgA0c8MeAMvFUleU4MI5p3XEypQ12Ne6ET6PoPH5WA7aJCKP52QaDFG/wFcnHnKuVNwO9uhI2E0wUxTn+bSMhW0hzPf1OyX9fB+LY7EMhd8dD5hcaYWunEG2rdAtp/M7FfeW/wdncNnliT3v9P4xAgHFkfILZC5bo/W59vm/FXm18d8gg9zoaG/eYXJVtyutzDlQiXc5HxMDODokNlkNCG2LV3bPMbqkpp+aIibmEm2q3T7NM4YtuvX3Al2dsIKY47yoWS2LcuFKsK2SslgMPD1n8C2fPQtu0iujszPIIXx/xAD1ttJ/0tKVJpyGFp41NE83JPAI+WO0dGgyTkLRtn7Kel6WZVGLxmfp2NhNvx340Y1Ge/q05y5e9brr7SaqowwnntkW9OFVHrZ2zI2Qz/1vTtihudTnXJVno7eyVDLbzfueBoecNT3I8X+tt8l5nWgLdvQ2hczv0X3ZiJcSeQEBO04qWubLQa9W6n/OLpds7AV4KeMu5ysEq91xrDIZfMmgDDu32UgIZhulHLEk104ZIVoHn68NBCWSGquOX/0pg6ZSv7KTNaaqoTAVFApPF2pT3yrTuXnqV16N7pOVvCt+KxsRPVKBgd6Z3JgbjFvsc2IWAMUE5AGdmSqqaL5hVM40E6ASZB16BJaHEZ2tvWb+B1KZvQhJAo9DQ6QCod1GDca6urDGY1Au1toUL/xEF1xVDCYqQtQ0UDyD22NjXAOCCjTub6TmOfjB6xOBEyxv34D0da2of1LYSDN4Ti4Oa3aq8dkNECSNlldE5x8xisxb
    KAFKA__SASL_USERNAME: AgAwe5GscYHVBuLixDB+cbS3iGDHmwDEdBZSYAeuhPd49JGCrsSiH6jrDMsjquRUYm/VmQPiJPEcPAPSAgCt9blsSr4mbj6w4JlOCmtMYCIMzV4bElz5Fh1P3js+etdeNOosfYAIx6u479t1p0nxbOJVRkWGbOvGcyjwvgCQ3dWpqoBpU12t7VInyw5Qmq9d+CpkErSpiqdup5Jr74IHYI1vpwAorQp4sHUnYb70EXQDH30oaEf6H3yy0uqf2leRGQswGZS4hoyXxyhvv+9WQju8YazEQRY5zZz8r3gJDfOYaE+Ax/gAbKqJ5O0VT6mNOjRGzpT0hTKtws0/Gj1OfT9ruQ35j4iW+J+5BvWTmktWU9HtPFOasnUbsfl2N/nCl8arcH0saVwDozCK5LwSVtJAGPwqu9IPkAEmIFzuHqUG0QzIZNkD2oFRYCJYBzswvgg1FNb40A/ZILTtTHFTpVXIo1wj0cNlnQyLr2VnE1u3EpRNquGwiJsfTGLx/TJtAtwDjd2IAU/gO2SS1WMroq4mqkn2DyWxq2BbHXMh/OAenu4KaCWq1u3D2ciRuRzqghuDsewoaz8EIzwyR4hd+FlPjElyxYlotOmKNaHSDmjbNFFR2zS5uoL/DKtvDdKWgFXF25dRhOnIwwcAMkIjwnTCsuekDuaD46K/GnA9IKAEPvE9Y72L/PgTDyYr7/SD074TpU2As73sb/sg+RRI8YwX
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

