apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAZXms1/br4T4SeEoshYicLr4Ey1///xyhqPuF2LkJe+Ess++wDtjl8lQjJbq3L+csQfEpLSK0/Udho1js9PQRGv+c/8YTE6CLVphA4H9v+GWUhqdj/JsNyKiS/fxOHFGxOTKgBCQ0T3v3V91aOAFEeNtht0AFtsQvXeeYYNx8I7cxw4xGgELOBZjbyBb4EqA9IEL6YxkaGeo20PWS2FYWEIaQsAgEza/g/STs9yRG0anecvoLdvxl/mzwUeMTuHs+Z8jd8GyiNbHIbpfphrJ/kpQtoPKpKSeKmBLOJ+bVyckiK0R77NQzNA9J7UjahC2nIZmeczuNIxS3DxeONwYLJ9UilPsyTDfsPuIBofGao24b35sI5TSSvjP3D3XX97ONGS4gG4+1CCZ2CAExvbLk51wF+5MqftFilvuM+gKj8DBT0GYMgI1QiqsCC14V+rzF5mfk4W78v5gDVofaPxG0ZRMEH5RibFmH2h/a836klYBx82EWtf0NMEUsUEimFTAXECunAfvdvGHdjYbFfxDTv7imI0ouOzFvOn+hVO94HOoB4pUpmGn5Tk/WeeuLaO3aidHQPM/yYix7aQnFmqi6/zgG2z3qfYhNTNSElCiNB2fIYWU3O658szsiRlp+SSnuPWd92FqzXlrx4OsV/x7RmL4SgHyiAsSPqgyetNJ7LdLmNe3d4BVZN3Y8SQMwCtlY/nNs4HOJAXajhhNsJKN7ARkt90CvUshwaW2tNz3MZ7DZSnQm5W8Z1BNOhxTj9/vHaYoihkpqWl+YOZHRntYj1
    KAFKA__SASL_USERNAME: AgAnYlPUrYwk9fh9g/GleFKl/EuIL3nHqhsvR3lyDk9DzlsJhwiyDN1a5B2/sFsg8zw86lgu9vMLCV7ixIULOVX1v/kXUwxLq0EA3HSYN3hlA/x4FrglVKLCJr3HXS/CCYf29yckUSWTTvHlCQbAwU0YY4hqE6IXOkF/N/9PrG/5Lp0TrjXsyIEv4sIo6/7Dh1omB/K7WrbSRvQZLAJBgLDGDMHluaMsS2MvCNEkBO9LGK49WXdVu1rOgxTLJ0nYaov8DKqQ+FFEqU8Ra+OvZIoTXE6Kvu6nUD240yXuA0VeJtOI4+dGMCc2w1EmpE41n8HBhLvZPFbYmCT9SKZ731BsUohKiFMq+GuawJg9UBkxxL/gLv8VAOo2m2BPz1M2hxwRXGMiKvDKX0F3KQUgW70W+ZP3Maps5N/WFrMUOXN+DHmyvWfH7ERd42sOh1KGKNUbNgoO7oAXj8SPjxU3vGBeIDV+0yml/5qD+ZXN1AFWOofIOXenPVjBkM1czwJThoEexoLPBPdW+//EVKskD6HaWMqJefGaoiUCfeRK00DcmLStzizM0ubXDrLu2raAnhqxksLoYO5iJTPwyz2llwoXJFqLn7GJzU7apvXjmLb2ArY1ZEJIEAe/7a7GETYVgNxOIxAeo7Nmm8+Y52013P1OyHqad54LvQYPqAjWSKHc+1yyVO3K3gfOjSu748hzFAFvo6YN+Gm5nV+HHdNIEHjk
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

