apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgDDoId1FiUS7o5OrOI/5RVtZsHMm18MGYYkSEP2WID45893lCnMNI303f+ye0Mr9G8MVmQNm+SZ9T2AqeY8tyV/a8H/cpTXsrY6RdyB/s9aR+iMhSTa6y+9UqMAarRuo6e0gPSo/OKkWTLK6NOSDN0Jjcsx0APSuSEEU11pCfiFCQPjtaci/7BgVg+tOPW40rg9+XtpdNFY7fTFMiZrnIRlXCmn83Zss2AgffqkhPWZlTnrbfcFA8kZ1Ewie1Ei2G8MhncudAcUWhiT6fdIT+idn50jf1GmB633hRx/jwh+88aK9fFvzmcCfKVJjt0DQvOkLOQ5WD4ikAEqn+FCwYT6xp9XDpP63nroA4wpDjYxirg5lh+Jx/EJktVitFJAWraUF138EkcAwP9y3WKOOqwAIhgue3UdKZHxQKpdufYZt7Rr32FVQSDZkiYPEm+c1n27GbonORNdpHaLS72gJ+H9/QhuUSy8WaQJTBlrD6nBpM+uN0A41qfl+oBcb/43B+LC9nljwdak/dqo+ukplKZZZ+w1Y7xMpBe83jbkrxrFh/pd0kGNmJKZfrpIixmUEUfLvTql5ep7nWddMXbbJULy7CnnQduwGzVolyq+vUkRlohLBBI1/kGrHgtOIXdo3BuPFRGpBKbOEdj5gbyKwvLe5ek0apevcCDXkATpLqAhCwQ58YLMaJjI6nX5oVemABF/qu5I+AHdtb4Xgq72LSZse6kMqkeo5Tjrptt5xDg++ZPhqd4PwYH8DdA6v5IQmxBk3rFXuNjv/jPIbT2Zwvj9
    KAFKA__SASL_USERNAME: AgCqAxDXzwMujNqhRbR87MxfJKTfmYb+Ufn0WZ+yLxqqaP2cX9coAoCCutkGI+Ekj7tei7LcHnC8CTODq6CtS/ZuUOYPcX15GZZ7W7YuNA/uuxTrPrx0mVEpzFZef8rjVOvllMS57zYXJVu7kBU9vhDDcVvQArzaOu7mwS+AppDzvl3NiaCyXYBY7+jgwKb51oUxZ7Psgv6EynOxbn0EnR8e4560I/xPKldW5i7AJJZ6RmePTV3fg+G7REilLEyVDUvGvXOnBF3tZXpppVeqMljPsrJlGJaDFUpyrKJW4sdBXWnW5PsiS/TgCxxIua3B3ir0h6VhWmxFioxqJX2nR0UjmKAahVVcVB3bm+zXPt65h90fSMcXbFkSgvB4mUnCwVVsIPI4lSr+M37vF/QV/LbhdSe03F+FdiKZiK0JE9EBX91l9PJcufSbQe4XjfljwwfL4+1UiFvC+piCil4FEmmw6nrD3BSTU4hK9czuYUHNb0OBQny8p/iTXwxu1LaYobUaBw5l8OGH36mENPZmsRxTILfzHkO48amrEWO3EAawOpJbeDOIgfNQynHLzS6vrKddyqfHCCiCI+47kKYCv2P0Mw0du8Kuqv6UaQ5HzcCtSSU2d3dylQwvyE46egyn0slDdNemITGaDGozuqXradS0Bdorxes/j8hXh2VZzx5sqJAoTD78thZt0nJDVl3BHEDBNmmJ01r473Y1pmHWAut+
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

