apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAXiC6TDcvkNlpnhnjR4wEyc/q0GoJOX4JoltaEhE0fiWa+PTxdiyQMEjzMP0WKKOTpuF0jMoJDv4wk+ETzOeEfaPxTglCVcF2rFNpjvHydaOggv0SVMqvwsLp+qmhMiD8FZUYiu65HlGgHTnrcGUYvyMaoMAYAzIIN4Xpo4ZtN7yKeVO5Ri6eZfKOQ1upwKcdHMK+hB+EsYpOVG/o3H8zFIQkkBQ0QUaL5SGIT5qSxPeljIZ/kJzk1tCZixHixWebvDlF5TAoO4AsM5qSvrcr2jqWPakDEU+SpS1v2H0KJAJEZSlRLEZa3H6mwdesB+jdIsnJPRLQs9UtYgwO2xAq6UjEsO6rUbuLL3BHlnFgO0BWM2nbNSuQ+f1FtUne3AenIk0wEOlUmLBbGO7XdcHrEKp9DWaUb6FU/OwLMqFlDSmAj4639+YJ4HO3UzxvcuUiOysxp5D1XTh+YaPa7Ec16FesI8+JDoNSNEeCgP2LOyvmmCDYtZ0fKq6ijoUzbOsFW96cwJotmtj9sOCbAeTMJXTB4RfNrzvJzJaaZm+oYd3f83cz9CqZKsHvVH7V21LVdgUBVxmJW9iS5XwA7WfH8Oq79ouSPbZ4kOPnJLLyLQxedjVbKKB04C2+zmEqQR6jXOgjPUiPtnhnYCYYjZbLVLtL3qwX1J7Dj6VMWqEpAYE/8bM/pwM8EUBWeIbNPB06GRrGKOB1bgeHSjdydGzhwRxOChLPn0MRrXbkji1VSuuNYo4seSBibFNLwn6pDpjzcACadd6AdJCIFHGF79/DW
    KAFKA__SASL_USERNAME: AgBeHAsBPlSLIa15Zepk/LHl13NBaT/qhJ38Uvzo5BcjBKeMGKcFoW6Z99uv8ONz4SnyY+BekA1YyghMGDOBa/fKxgCB5zYuBnnT+eCKRTRHLhUyuZQi7dxi02vtLbQjJAV/BO1rHQ+FGLs6XQ/kRHKGKfi2dDvXxCSx6MicC4EXbft69w+hNfYegXbfGzWQ33jbvUjeYvUxOerS0LEohVjflAIJbajoEuQIS5e0oKpSxcUfQt4CKzySQD40VPFHFeh2+Yw3FMVlnHoVu3+1ve1gnleEI4ef6u3VB/iCmpRUYk/8sHgD2Ha/klcOc5Lz+YY4dFJYV0SJW+85S/RKxCzYeSEgHl+bAXiVUPtM+T+VC2FeFa3gVghQ2UrqtGLdVY2b/Iv9tzm9/iN7YZaX6Hly2Ty34IMZg1Og6ZeDpXFiBe+yEJFGb9gKioqr9O7nw8RQJZ349HEk/PUgdE0+1HhnpIn0vk6tYt2ZHrR0FJHmC22XgY5K5xn+4q1QfFVt7/9+Rw7m4ONYQSKnxITf8JNKj2AnCDRmFrLmbQmrlfTQYZrA0AC3oR1RZGbqpeJdxxmCEM7tKqmkIOwdaMjys8Ovfi2LfGC47ZVwctVW7wqVEZ3Q5EWmJPzmcscbHBGru8H19Pc2HObOtKov/KpANeTZFpX0iovQVgbdJwqxlM1d5z+VnPGpHY1tFcRJtFdTfUmnQ8HfIxsIiaq3tRfC8pWg
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

