apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBHmUFAikIyx0WLxYhB9+DmcQB7NOgQ85iH0qUi5KYolqFSine4tyMmU6mQg2jg8hNhyb0w/jLCpi0CVVPeVTULHk6pjX9YZQRlRtQTCh0DNOLZ1qik14RFZqW/EpcxSWjqF5WuCEQhpfe6Raw4vWhb3mjj50Eni6CVCbTMYQXYdDWEzR+lC2UTWRH3vMvYgxK0ckVG/UK7F6xI2hf5ziwaD7HGgWErkR0/y0VByASc2n4Lug4L8sBqHiqzxS0Q9zw1rsxWz3+t8la080ZwRl86fIS47IkJdTElVzpi6NsR83+yy2C+JcqCgENqvTeVDThHWuQ/zU4f7zY7j7+IU8lc1x5fmf0kISSJQd1mkxMq6Bhl4UrqUi89DWp/Mjm4vdhEXOe21pDSUIpa1WNQ8mMSzEMOvQb+W7h3Z58ChmNMKXtGjr92Rofqb89mzsSp6Ti2rZh22rxf8mStroszLk7+tHa+QMGgxhRnGu3S7x7iGKHM9ZeW+Cs3mTYOj9cUFRhm+Dko6eYfuoY2qyrOyV3Wum+g5F0Qa2iSWU3VectJkORgX9sWRaIEAO1XrfDchJOqtP/djPy/T74CGFQOWoRoR3QRHX0iIvY2E3ji9m1Q+ZYQurB3yJxajcfbOwaAYV9uD37IfhljfUJ62bJi/s6fjlGiVLx0B4SG7QM4Wg4JEmO+g0vIwmrpDb9LMKtZqczDC9BnlgiCs20aPOV/q2hRaNhYzsoTotHUcjvhdVsrksJznPi3FSGxqz6pSStrRX2LEYs7hGIotNqlS+DYyyUR
    KAFKA__SASL_USERNAME: AgAz9VTGrby9H6yQdoeoUUAlaQ4/sTK6EMygf05Pk9l2fNGkdeLDgcxrtdXLl0II1qZbE5joOKnJUHC582hqpuisauvMX/9Ln/4FAzbttoS4tNS+SFf3hXAC1aLxwrgChuIRUeVbYAQymQiE8b3wOR0vC/QP7n0jUG0UDtNa1FQVospEr7NQOvDgzwK0fFbBvq2BDwQMe7c4zOggSn5yqe4XrruK/vcwdq9MWR4HcppF0QeCPPupjQfQv1RoI2zqh2sjGRQbCK/7Shi4o0Hqh05oRCE0yNcPtARgKadNvtFzGzD68GkW2uswLXsyoutiMDWy2SX3wldz/mFXMZyMFBkYfSVpf+fAACXiX85LzFbNIwS28cRDdZ8zmzRjWWbtg/RCbICv4H8M6yHJUuPwm7MLRe+GXeMgIAiUGH38iqGZe+6xlRr0zYgbJOrYhCx39OTYdv4CqA7+8crjvZsAbFRairBC52qy+ZfLsesM+0mPg6FmgUhus68BozAkY3I5tsa6VBanxl6UZgfe5jXqhWEi6Oo5jiY24KRIsL3b2cyH3Ex6e0a1T7ZkRWE+TRplyc7cVAQnpMg6dR07v457LUKbXlELA2cTlLqTGtQi9ChN9+iIDzPp1DFmatEEc9w0Bxz72oVVTobHidgPesB9Von1Ng2b4y6LAftRgOK3i9R464L+Lfhoz0BNILvreUPTZ1XQsj7EUMl2S6amCKn6qisZ
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

