apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBVKA1fBxm/rJFU2xF+VuyTceuMQeaO9qSxebKlihgnR1ntBjTxEJhm+TlH75p4ahQUqfyTbg4AaYgbTfZtPll08G7FFvKBWtUXGlCzyBnAMqyqA9Jh0wrVOJaiHkkn7nxnocSJuuMqwMuDVxHP7tdZapjW3pxFfCtu+io8IC7BhBp9ipdl/fbZR20Yyt5csq1xa3C2aELhegGQmq0a+Ar3AE3ZWonK2qhfwF1VIS5sOO/MIpVxWKMu2VyzhHCDjv5xbZp0eqVrnlP4H6qIdisv5S3YC9BKxShQ6fM5JH/u4QMu1pxzTO18U1VnGBAv1nXgxg90pDoE9d7RDHQFGj5BrY5xlYS89ZTBH1eqt+iMFiCBEFeNt4NI4K7TUDHK/9I/sARshnNrU80qV7b/FxGZwsPH3q0jmfXKM8DHUJSfvg29rZKMnECTq90RyI2Q7vlEDbMJUzasXDSBQJT2/5mhzihrPf/bFYGudRC2JcBJkHE3hWtHoN78JQ7B0JH25qZXD9PPaeSbJDPRbI6fdaZkYyLkJeNo/QJgZG8QTRpg9Kw2kOvQr6krr4JhgJDHdzXIVOnJUTZymDeaYEjGxu5cVpuLagcXZKat27L0IylBr9AqO9QgTsKeTRSksmWxlujcKWs0nAuwSMvn3mkzjvJv6LrPHRa/JRmRwQmvXxEllo+NfnjJrfVryXl2Exd8E0Qqi5Q7QW8KK7LtVE0myPdB/lb6MHekhTv8rpYtvLPVdvVP0NBHXWMFpSGe9LRpQilJ58FRcVVyevSZlD6WOIzS
    KAFKA__SASL_USERNAME: AgCNPYkS7W33usjw48sC05Xn0vOWan77BZUNOPQDljiQ7/Uu4GEHgGkRPeip8jmvT2sS/GEJn0Bbxu6P38bwa88OV3cInmphLIZ3QPR5h8HW/NHA2rwinUtKX8MzxFqTWwq3G3y/lJ2fYSlh+OMClY/dRs9KneQbqZWlmXryzaPZdkKFLeUrx0oF2pCN5p1+94HUV06UtMZIGuVqNpAzvK6X9jS0+8x0qxWEMzsGjViPI1P5K7p6P4WqfWqO7Y+nHtbMdfuJRIVEnwMzcc9M96uI7TZ/OyyH+ERd92hqZtQB5grWc6f33HjgrTEQdnJZPrbxvd1zGINJB9MMXwer9iSxrL9aaWkNsF+wWht9dP7ZaHqS/EDkN6KVnDKtkksLO5GsS/G23ElYDoaUpyHTaQzmO1JTXfBr5+ZBuGqYP00vdkjnHHc773oylNuUpFkYXRx8Z1PuJnct49AOEWJw3INaaqB0kqU/C8Q4QMZdy5uYuRcFSeFfz8okxU/j0/QFjIimQn54qbZkq0+14n+LwKPxs50vaVHuIcTdKRh+NCvmLjOrCSRBpMMGLp8wypFmZZI4GsK4ifH2iHeEHDElHTtrojM5/azvmzye5nh/z8lBHYemch7D89tk68lBPtdTjQ8lcGMCrme3LVh+DU9wkuFReJdAuxFCZHukk08s0VldSLfaNX9Ob+pSA2UizVtCagxU0aloFvZtA8q+E7/NzfUU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

