apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAh0N0P9yRkSIRus4WgYRF45MCuJyEonEVCTybCo0vzGPPh6rIbpqfd5XU+9hXJzz6TXlzyWKnGu7MTOm/xXf/fCvw1rkLOaQOdzGFhYQu7mezH8HQtGKq32kFPUIgR+d8wvpw2Waxw52+EzhgchEzYnfkYgbmejHkVQDlRsmBm6MmtE7dZB7ZZaypt3yWB+xOtDYrWVV0wCdUWzITtIMZ91hcjN4X4lQjG/lB8Aqxw5xfS1rERDITe/411+Jv0r+1G3+sFXV/vIQdX7ctrxQI1aQNFPwqYMjJ2S+BfwtePs41+BsoC5YZ7MtT29kyowPBr3GkQdLX3+XXJeDBSrxPi1V7xEZ7ZEYBLUvZ9JNWV9ahI0mVAIko/IgFXoO0CajLeidvOCFTjBsyefEyRg4Tl7J2O6Fd+tgRjSAt9JmcQevlu6hN/6tDCRiKLPcuhXHkDtuox3pCLxyvt7sUme8+dlKoCEYcej7d4XYy6wIEGHy6yzmk34/T9Wzo/gr25GpKGTHK4RE9BtkdAG8FyPLG3cgJUMofkEDrpGmHUVI+dvVqOvhw9wYUvs5kfuLd37nfPEMIMtE0pf6SR/f0Yyp9neVk9qEWxyisy7Tw2zlL1PDsC5dTmPRNJ+M+78s9XJ5beAwYYik9m5AH2mDhVDLE6Qk2PVWifUKZSll7HcpH3mvFi3uEZjwBKF4lzvdYOayPzMaZpOq3jCwx4AYISfppgK2OJtHYhVjHrtIGQ/z7GuhVh9p1EDFWMHfKT3mLRSDtlmFKkhQT3XNXpu9wKLBOP
    KAFKA__SASL_USERNAME: AgB4lZ9KprqcQeJWYp8fglTiLLJWOxXD/0apBjZlOWeQcCykjYwtPeASRHXD1dQ5ziMczUFWAk07+G7p8N6fBZZvv4/sGHhl2lQmXH9TfCs76TyVQsgFABgaz5GGygk7Qb8fIMpxICCvhewNYAbQrMKN+H2aItwi4G3s+JUOiUidMAitcVQtrOAsGBshzIIWq0NFrSx982MZw2HEm5Mgxivr+CCfoNnR4HDtezuzfd1vFlyJ303UeDYx1wcIJf1Zdwo4Fa9T0RouVfj6X04J9xbRJQ6SvpKg3JeAbsJlQJA5QS7ZAORhRYpKE1TEYmbM2pAVquwHBl3TlCQqRX5Jc90WiEPtA6UQb5v0RDLvM/WV331TJfvRVMoE4k9Br3A7AT9YC379NbLXxRJ/MiUurGJxz83muaOJmGOgI3tLSryqx5cVjjFu+VpgO74L06pj0i59+VWz9liEYE8JsjwVwWmeUGLdWyAJASmRl6rEo9ogSV+o1NOpkEYpWzU6R1C3oT3tWFWHketcWWXupQaT1c4LBlgPitvZTgE/FkUm6yYGsq+WmgQxJFtKw9d33atGr3jqs4woalcJ9NOToIQV/DJcDpjFVySo4ZAyWnlLqL6hj7XJwTTad1lBRkvR0ks6IrPtgY0F3XbDhriJJqfHcWeJPMedh/ZpG6cELNS0ZXenwZu9eLAXsLb6fPYjCTpVi8gihTtDg/Y3oyVpL4ubX6Fh
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

