apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgCYQJvkZfb3eu93NONpZPf6+f1h/N070YQaphMsCGASKKUg6uMqnzJmqqTz0cDympqLXC0q7lu6IPkW0ngy3Djb/x8N4w4+Ey/qGBE1GS11se6GGWcmZ5Y3lX5KPN/H2tq3dCoTVKXQAX3ugHtLX7bP7Y7E/oLT4VL7MUxKPADhZ5V5kWlRNyDQonmm5tAiCbVoiZX5bRK3Da8ZwEb14FbwtxfUbWbHPNdzbbwfYZogvbqrQKLM6/lihnmkef9sjZw6emEC2CqpGf2jK2+54pwXVH7S+ars6qPTz98snLLAWqaivQT+Gbg+jk60RJaQ/Qmhd6xfFUzJTNC/yShb+5nriaE8mrX75YC7G77NIm7nar0WRnzIbK3l4QT6Z2E/0nMisVvp+C0NzuaHlbqwY8qDqLXGYZAOv9/1sMlN3VT+6ipijq3VxirWSBq1xJSNGMbERtAnk5ao8OT+edBdty25yjnfiN+h6R0QGv8exijszLOgbC4wMixxz/0n6D/HPkyhncTvPGEkVP2EmhpL6PEi/aUyJrU/x3w3UHYsG4zzAYL1g7a+rbYTnZq2eHACoBh/GyYvCshD59FErA1jraw6zMO1i3VbBoXds6+d1MWVCkMsrHVfqeLS6sUbKP1bl79k9Km/f0cYLKY9wqxdxoYH3pDFCrUgOPUiJrK4M1pfoLJ5aPUxvUCoBocjtq16BsBEf6kQPxR9hRJon5ZgVMZd37v0D1q1gkhvtsV/8bOLv0ERJfmVgp8sEYzQxbvWmHA27rmgfhx06IxwwZvRHuA4
    KAFKA__SASL_USERNAME: AgCWsMeaKIV78CkeNvKiFc7H6I3YhwZMnRgxV3JLBagxAvSiC4c6o6EA4puPvs8gNEiYFtAzOOppB4s7houbtXATh1cfBzRGhMonAZk3/59+OnIafMZWkaG6NZPAbOkvnJ3WtDmpqashzJZQZP8Pyy3O0PVGQs831JEyvyUBH2g39BzvTkZLYHIJZhTocYaBJ6TbAUvGIQVUeyzjZnVVOa7HhGtKxKVz/LniEwol+mHjT50t+MFkja2pNoPg9YAgPJEdjOJtkVycAWRIKvFdVkmurPNkLOnPBOCloKxKsstQhnnxCS1ATxamOe0qpcbOmjv3B/wDaQrYttcYbTTI3op2EOyrmJewDUJCWHnAc5poOhqbZ/EI70wEQx590fNCvar1n/nuQqXvEcnOpir1lgXwu70i9HEWrHc3ExBNRR69n4gN64Mvc1a3ifJL21uOKGx1nwRkO/G2y6gwjbfQ/WfGfP+6RBhvJ+QkA+xThBF6iDanykAFjWCDpthvo8/EEGuCaEHfCeYCKnSrlPc7C2On3kE7ZAKTobPl9M21mlXm3uQ74ta27ofKRcF1bal5rZnfMxTWfRjoyR+RxIYEpoT7yZ2UA28qiDZuxrDzrp6qh+WMtllMhSGgb00X48A41dlbfO3LV+/NpZ+zAdLrYvmCosLb7TZ1qvLaDWvMnA67lql76YH1tAKWOGgg5S+szwvpVF0tgqmQuREhjk0dDb7b
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

