apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBoWf/8KhpcoWhxA2WYK0otPNZsV+kuv661CIkBeagQkVou6CIC6wIhrM9F8PiOvZ4KJ/1/gqEkorNkYH2+uV5LXGrwh/4LLb0kYr64XYl01zNwWDVloKmlcecnQyrToy0q/3DZgXeaAYUjgyliQ487iCbvaEKIurWOE1w3fB3KWcmx2v+DBnIIt7Kx3rDs5sypwOFZYfI0KkbUMJAM+fgroVqr6Qizf6QDNlTEyim47JXb+PS/OsFqZV8yRIIStbdV9mLKQ/chaBqHGmI/SAkepuerabtahzbNep1nGI2yB247ARshq9WlzfkzB4qAXyLIcfaW3il0kqcQ/i6m501b5Hwt2bzmfWHpaE3jRCdxFo3cDj1iaq3L1ZVCo+xBnGDvRfY5lu7waeLRSM/UF8SJArLnV4uhcTAMe67E2nvLVSmBhgdddwGb/qWbNeJf8myCIT8wPVrm/JzSI+OmM/ZVcHCg83Kc8N2BTka4HEAHww45oClsSI5+d0e9XXF9L+9bYqPQtyc1H05ZS3BiZtfLiN5jd0jluaE6s2Z6a8pFYDr1Y8HtM2GUV2hJZv2PXfWwVTxypJGqPbbJ7uzzFLHAEppIPILTjPKm47XiYDchWCAzuejpO2/UpmB/shlJbpt1Yv3bI54nBtq9erWM2JC6fRv6LQhkS4fjuefqXKcuIQea9cTNXoj8LEJ078E24zCQBx11BZA72VYQNfm31H1q4TYEVDNDqLtPwlLNkzt5pSvR9s7zdiWj/wcHixD69h0nOp0dXLG2Q3UE1UeER9uT
    KAFKA__SASL_USERNAME: AgCBeQ9uP/wiZUji2hYQrWogJuqdTABabzZqaDwTrkVQrFaOyqhOiMzj+tmZoJx+b04juaqSKOkARzuUf4GtfQcSAWd1nfVOC3H9BJW4J0BRlghHkd67oMjvgv+7OIByI39y1h7Gx0SIGYoRCKDE78SO0sNfhVCpFcjRpssEvOOj4Jypi9PuRX6Y/jQ84eRCLpNVEoO+RbOaptmZ4nj+FtnnwdxRyO40p02EGQNRrQ6H90VNNXI9UkzyG7oY8WffKAnbnlMSPczXiwcKeAEcrwh4I792KnQZaTVePY4VBZVvqv+5xIsvzsOJsc8zBNSHvNaZiyUkDBZ35uGt9fLWHk5+gNHxB37LUvEuxRZa6IpnjBi7OTkNAHWsXsqdo4KjonwvUx0Y2gIdRk2TcnTWBwprA8fHQrQB2q9lEtQW+yb4FDzS5Couvx33igire+XSL2y9V+yhm8jCweQREotak0uK1bfZjCNConQCxEEaDi9qCsqKSfAhmbPXCoXGjqeRsYJ21qUwiUGXvfr7Q06WSV+gbd2d63cq/QzlM14pvU0dFfmwiITzkOzXTOLB7LwSq+xAeAuZiFmJSlrOZdfWCxLOPJ7m7mnSSyxwb0ympAcFG2/0JMyqT8l01qGlF4ZnaOtynt1alWeFv7DwSKXCxYTSDrSgM58NBSOjMJB2RYkObXssM420S/sUb9jtBKkTihsl7yfQcq/Vdvuum7/vsT7b
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

