apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBGeJ/3vzqk6RRcnFHKx3N3MjIzPFUYuyduJZNy1koHZuQNoUDr31pEwDSJFevkxnc3Pp4RKqD2EyDt+cwVDEtNAZKUG0hLapqMbi65Wx7zSV4it9//e4VMhq14lZPb4W3XKphFex1mq23UHMoGjUiGuqwAg6d2riPUdP7qeLb87tjX1D9Blvkb7ilqlNJ+oRguYCaUuzs30mbZHMRnnqn1cfur1Kwq4qUrGm4xsamAfRvD84g7FdbrUrhavHd4SThCcUsNNixTtP3VsO09Z016cK2OCa3aCLusm6OBw3RpMIRGHH0PyrHAwiAubq49BvV4G9aS3qTN8pudYrARMH6enebTWfEFm0r4RDBkGBLSWPMRpra7VThzMqoB2+AXGKUXu4qlZlFsvMaaZoUHw2WgVWGKKFA03m1yGGz+iplEInwYVRvoQZfrnBtlQ/V9L3qoDn4yt3wJFifA0nOv5Te2w0R56NVWBiAUdObnYBsjqFkdsYLgeAvjZWPCTRkoUaMpVn/ctV5IYoaISoJYTLAn7jpGladrObPW1lC/W7G9NX4zvH1YL9Fkvt/2vn6rmKyQz76QWL/ZWLH1RoZ3llQ7Qi1Je2ihsn88VNHAWkYEE0BOxCpJVQPTxzA/yxIrCG+DASDRrZp60pu7n2F4U5/EQJZ64Hqklp+i36ZLy4l7p5oEgORBMXW4g79Zt+H48rGQTXrXCzySfe1n1GTBYyy2I0QtUFZodvPeosHSvTF5bbTlMtVqzxFWQBKeTeh1j66bUHJultVytm1wzYv6bxoj
    KAFKA__SASL_USERNAME: AgBXWtv6Fs4rCR4iY05yPQ1ojfLpnKEWRcfLEa8YLx1qFlFGeYaTKUIoSbRRHsSKzfZlnjZPeb58h89DW6ruT+hg0/9gAblYZcuXGWsFlyxv0DE/LApZYBt/3xDhOOhPVlZLCvVRnH1PfE2oLLpA8Oko6Joq03XItgQOSpiRj17rjif76lUkz/kl8+UpxOspBEkjhQsKh71TanHBHcETbbNA1IF62pxANKR745ilbNl6OVY//bDd3NYepJbuVB/P7HqO+6htyHieRkS7RI6xDl5ThCHvZuBdiLE20zTW5JOQQdS+C4OiE2t7YoUEXbQbJX5E8zskLTBopnHFjVCneY4Y+yl+TfkA4QWV4OM87bDmVbU9QHggQRzbBSuN+gBVkBfXFdbrNhbiGLiDcPEDZaIdtQSWRmBH3KuQWBfzQIRjn6pBTElQCN3ZZ1fGKIjm5yHQG0907RL/MrnQBEJ6OTDUDw+KyO0j+2yMYF555wEWYEjeaQVMTM8TzFqLxi1BJ7IsgiNZHoj7TLMdDW5v8kowAxJ5yu3Wrf1ED4L/K9RptSWn0fHxO3Oixqy1aoLHTbpL2SNEWK1jIAqnLMtlvDDW+cSRSB8y2FAC+PRmhnCrMekwdUimVsxg1UGhyvC8paBUlb7Wb+NxNeuC5LTed+bx7rYnT5AAdCRThfCqkS+NEecrGaP9yv8aRzXu7dz0Mut+waWSFiTSDFVeLlxSVeF5
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

