apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAg3Ox0HBdHt8YrasQikg7vdb8MGQLa4a+ifgAVe6xx52b9EEolyyGJrtc4CX+4kv69WtgoSJTNA0JF59NBdKmjtcXqUqZ7aMA+xW4csfLbsiyA70cGzm4Y4Vsug+A8jjU28EUvjd3grrf4D4mtHwS0+sGWsdCsFWqGdlXKKzWls4PABD69VO1SoZltAlZdvHJ+ty/HbBezQnogIGn0zIiPQ8w8Gl0Q+xUTamWGi+9tVf0oWNgRvUTCNxp3kC58eRRfiC1y6iC53Z3zlmPfbbwFSxF0Z12e1rMCJSNYT7g8Sm1mYh7Vx5Cd78rfyIPYUriAiohvwt1sm9zllQbVSDRxw1OGux7DUPOozQuF2CD+qLCPAPZhnbr6q6n5rrkdA43L+7O4PdrdyHsvYLIstmOCE88y0TWKM26v88qkwsLxNHpx/h29RyStyRZ+SajiIYXlyJkTIfQ2q3T3fbiDJpYQJ11QEmauNe2QHtCTSr63pDpipp7Rxm3Y+bEBQVcpxE9D/S76CYK3gSb3SU4vGiU3Kmxsl44JsMhJ0DbCJeFd0tvOVAXwNgeTWDfKlCknHIh6PRMt64Oez8nn+kCCJc9TYOONZLlmvrr6I9o6cGhRsNRLStZQWWFXaT30NsTlsWAzN6XKKml4RzSRMOnHg4agKFeVc+QrUNNalU+ttOZBfJvi8JhBi3Gna9+xLnpNZOZDeI3Tdl3oNLmhYcGO/EUoRoYmTg9cRbycqZuGnpvy/mydevVZX/vyIIAtQpE7PTnX0QDtMuUz8WhJN8HSGeW4
    KAFKA__SASL_USERNAME: AgAcTSAlbKkV3A704UET/VhKUj8lXqjtzGnp0JQdSr45e5ENzideMNTNEXDVTgfy1RN9zvB3Pr3Zk0bPn/8HIsvfChgnmo2ukFgc7h8YvKRivlOKVLS0K3Yqps/7Ie/Ss/XBi0xJTS/ObWtLOOEtzAmKFCCSthVgRnqyeXkdIgPNudY1Y3ge0l70vFcbs3B/vOgtQ29OGSbPz2UOvqpPa3c9SAMLt1WGkMOf7ef8AbKwq+/Rzc4PIMjYmQIHt1coACjuF1BWV2CkrhBEqMy/lWkLOtPfZZ/7PTbdbLM6t4x3u4rqzgvqpCbUjMWgsF6keltbRqgPNi32QV4K31iTCdmVD5LnnsS+7Tcp83uWsqFZGCYq5TbQ15Rowwm3tc1tc1qxH47r0HcTcJQKuctyE1p8fbHoVZVQ/2LFoqCIiRXLtPycAdQPXQs5uZw5FzQ/+dRevLPUi6rUF3SaS0GC2ONiRFVIgnCebVWoxUUsxqqDqNE/pFRI9w0Y4knWEQV+jMpK2CPr6yUeyYMA4rj6J4MLymZo+kRAv8CDhEKqKAz3vXrMGNysmzwEdFFdKgojfPpTvlQy6ty4BjQ3lJRWCFjDjU2J1xc9NZF+kbPz4pM4PvVSEsnuxortKLxaWGSAHyJTs1FLUu4Xd00oIWb1kn4NXCnaJ83QyTdJkichU7jxMZEHyyxpbTmSXN8h/2UJcLsKHSK5FOn6WRdV7HrwASHB
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

