apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAUHsWXhFyhue7PMj3LlSWjlyTBvfrgbMzkWpEWd0jN7+c/1X+STBdWsZCLrR/yAqBg/Cn579VTzDkOIPMUwAaJRdalttfPUOutR440qqjd0MgWURznNDjVj6inO50StJvnoYGD2zBeVsFnLmyPGCTL3K/obMwUVWkNiXa/gnyMKgCZ/+ewEn2QVCWQEckk0mEndxuSZ0uOKgFD/u569dF1eRliiRdXOO1Snx4g31zvHRQb0gMdLKpGSa8q0RW4OsHUwBo5bhNRxdJDxYyshVOK5WnDWlj/b1mZxyEA4bkSGMQq3WEgJxAacpV/E0CBDaRJLPAQVKqizFVjnabd8YzaIQkKg7FJFcE0ihCyNAxa0i3LXwhrfUBCOXS2svPO6gBIzPlhNRSbiKkbQ6ADqpl0T8e513++mFOuYynJhJrjjfbz2IQEEmpVTIrdtqNEjmtCm7KPR35ERcIohXDOjUSmT9EM+Jh7NRsKTw1k1jEwR5WRWIIJu16X1kXnJI9Y2044ahbiX8V48bCBITlKsit028NrR9qliTBT7H+6rneBmY6s10h14TspBQoqzysHWBe0zQDHhse+BOF++8qsNwm80R8jT6PA5uSLnjc7HRums7f12uda3leo627X6MJ1XGqpIQC7LIELfKiylafOMqzyPSUkb10xaJAKdchLLdY1MdUBNvQ7yxg3Nvkwzqq43r8Sx+em2iBnzH0pwcKqMOtTJ01mmIsp0aKDcTsWZtdqTk96IAdEfXFDg3PkPsb/H6bETqXvpcVReCJdmMAP91HH
    KAFKA__SASL_USERNAME: AgAlNE+RLNRMh2f8C/pqgHkirIKmT+zRwwTjvhDfrkCvTIT19uthSRccLM+IiSlglojhJtlUWYWykID3LqPIjZdmFD/+m+cAQz8enVq+syV73hfh3HgG/9CfF9+vlzW/EKQpJck2Vy0oTZ0XAfmwdFYUGAMjBA8v1axN3+lHcTephkNGXSvkjLmn5fFikRUcPIaqfMRqx0XSgFH9k1yVtlr2DT1Z0fzOfqMywz2PgL4uWv6dhfEkv7djGrPmG62WS8xFPRpKPiHi9dvZ+JU3aoDUDzwFOFDs0htyKU5snYXzabP3eOw8gXfyF97I1lsTzcmPmVpBuPPolKfKSpeibx+tsEKXQ/6sLrGJpABhVNRhWausqOHbw2+jZs1JhxXcJzBf0kL8OXX6/t/J9EpwhvOa+BPFYAHMvBKIrZOoAM+IwrNTIrtSr4JkmJ/c56a4/kQnZhdHCroOzQO691UBlQppShJez8jz5ZzjP6C1YToBZl/xVnCL4qEZQNwfO+mpOxLvrHfz0CUriiYf4c/n3FNzhws/vdn+YoPDVaffjlBCYHWS1v0qrMo9QPnqjdy+3gwhXxqufXa6FTEdwF89Fcgum1CKiC8Cg3NhQQOgItIFwnkxfC1D2YG7hT1MxB/fhreL/1F1r2C+GdaGKIdpJaCotNe67wtm1p02pKPHzN4TBI9L385/W77h1SRHN8uYlYxNYmzv6tBj6YO9FVx7nSbg
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

