apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgC0HBS2vo8V5WOnpydqdJvWPHY03GMhsnsqyaMjG0VFhscJPHdDvAqkQhW8J00XociHdx5MDhlA1aZuijNpWFtQ9B6In5Be4qccSb20NHiJIPyZwi147xxgusUK4n+qmwtDCIAku+V/Yi8wcjxxnPjZ20as0/Zcku2x2Gz3L6AqrQlKHsprMdvtlWWj6gyAFBhumQYSdN8Zw04CvKYae/rb1FH0CWgF1DwnrM53Pb1KBoI0b47lWFyQDkbEzrubt7odlFpDVenMOvrsLlFkk+dvYzCQmTNJByNHPlnP8VQYWs2VAGIHDvn3zrwkqv8cdsM8j4YXCFwF/Y0nNrdSbH+vSBBAFidMaX053YY2zdeM8Tk8iJq3V7WYDYRUECrg6Lezhv36J4zhV1AzoNpwZXiOCl0p65aEPXiw7rjXlbudvi5RPijOIO8WptogHcBdvptXF5IgIrrSImgI1e0lZZVJvpMrsyFfBts52aEVbi2PK665ewFjeT4KH04Goc4P7f9inUl4flQLRfDrFCAykRk2vYPVwDiTAwvPsnYSI/eaylzkew/euNjDAGAGboaT7eZSSPLpDuBCXcpGr+6mbbyoiEI+BGtVO9OKSTaF+v9MW8L925nLxvsYUevRHZ51LiGXbgrbsrx04bfxWfLi5ZBFPN7dYwUrrYa2dCjK0Jt+m1HkdAKAmmmNWNzr7yZV0J8+o6g/XFm4iNVDNfWJ/oAwp9xLOLXfgMnYErcs4X03k6zVyzPLG42FKqGpWX6U26Sf55XkgBgV4TUEALQoD/ncJw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

