apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAtjRFgawtvTTEnQgg5gccNsQw0zAjeDlYvNPbksUAdjtvmffdobzK59rjMSNLB/Rd0bbNu6+Dwz7nT/naUV9cNiZaCFun6ztbopIePRA5EQX20Bz8Z0OUaD9ETYzwleFTHF0Ebk3pWf+reLCOlDGvceqZjPloOR0ZiAtLShLkv30GAPte3hzjUjnsYOfQZ1z2i6Re9l3VODcmlgsaImLh8WeTZF0/QDaglGnZ1mqXgVf8gu43bX4KMxRX23DN5t27JnCctTMVywr5QkZs5LRGQh7A+ZyjmDIxQGUOsVtraPItKZPbH2D2dUSIWL4aoh/RueyjBuUjKvzEchYjy1MZ6gDa6bUa6UgcpBLpxZn/LS46AQKEpLazzTv25cOrb38O/86aDK9Oqrye/iGEU/AGx5v+LjQexsx5Jrwrltf4HOSyRX8UXkjSt6kdZGEq3zgXN46H9qBDgWklhRUXM9wi5ZuOV7fX4E1TuBKHGeRvHB6IKK+gFTX6r3O3nm+bhQYs0pUY2k3VtdPifmjco1JiXR7SO/ET7FWppp5Go413c7z9aJ0eO/+pp39CFS+N9QZyL4HHpMc69xmrPAiZki7Ur1KKyyEyFcQCpOEKiGjkkvhOg7MJUOY9oVybYdfKMBZL/20bYnJD44wzJw629HHCYwgKBNC9+tB2yipO2c/mN8+xpFvWxIYKdlu8x0JzjV4Ltt1yAOcFmHQ5g1HpIDTkMzOkAlzNDUXL4AcfgzRMZGuAgdEuxn75jJ82mJG8WkgMLVfVPo5wM71Ai4l4K3rAAjw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

