apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAtwKKLx3KNpSvfuyvvxuO0uxHEPzXywNP1odYra7xpH5WNUBUOnGkWnWTfbTUJ3AZrOjs07/PSZRimGvVOnBugr4L2kQt1rnQ7KH5+RxuuOXCgiuQpgaCv06eihDjKh1ZBtEeUl4rj81CNuKyuTsfR98K6LExcuz7XTwfzS813jY8sLrtCbVYOJdRmPKmr7honrTUCPI++TQ2dt68IdvlHMHqkhygf51pcVemQPsezMm0W672fS7sYd0ZhOfsTN+IukiQW6Wfa6WwmCIrleznAGw8n609IcPyYrmEs3lvWkZnkd13iStCMMRO/PeWTim3OxW4qUoxgbk9c7uOPyTjF3jsekDojVR14z+ng2R9XzZXe+q44sFfkYB0C8PNWefQbX38scPmlqX3s10wbnRCo8Rl3YLbJJZuU2Ahm9GaA5ZutOWVZQjnklAY4pTS20eurlFqTPstbY9EZutMySIVsherguSvoGqXfBW4RfgXTmRkKzYRPXYLQX5iBJu4yVTjI/itrmNpgEngpSsJDOTbAGdxWmlWk6a3Q2+F+4oR3DQcqVeW3hBOewDpuoS+01jsWlC6a7IKM7B5H8kHGaz3pNlpyGWJ3tc+Xu5taNGiAHnWdUqyMyjFewPAOs4iNSprJT44sSN6AzEoinBMDC+bRmhu8rNrX60Qim6NdIK0LPfcX6itCbiBUleBUKld+bMiWMeAZaOf/naVepFbDpNT6dz5xhWPNLIQZE1QFBvGujQ4x/nFnU/laYWXX4NWSVwKmmjYY3R+aICB3w2by4LiBtA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

