apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAeigPMqZ3eMTowDZ48+fVfEtos9od5bJlnQ6uY9tXvkX1OlNkqUtm/Z9qCue9XF0MAJgRjZKdx4XFap8Ygh2wZdxtUUr6ZWlf83EObZ7ywtfKxVYyKUXi7lMHwrXXMTbgXCOGlOGj4lHV9mZ9zl9TZemR5LnVL7Nwutu90ml2f+z/zy1x0B6XvvfTC8kjBMMK8kOCa4x/QQD8yyLuERtjMfShkGbouDpHP80hDO612TSzFYVMq83w0EWGrdzzO4v3yigOPR1AHJV29aYf3uZWehDargyGp8GpoOvoqTHyOgC/z8cByRj1Tz08VdgZtuLEwGSQiPh/5nLAvcsj0dQ+f3uT9UZJt+KDicyhu5fqcxoTueI5TvSsNJy4lr4GAFotMl6H2Yc+RcEz1UgjKoVm09HBEvri/toNuAPTQm2og2Q5410MNPN3B6dcB1vi8LjabiEN7q/i/AEyDGHcW5jC3Zi9v9eTS8aCbx941j/LgxIfe1wT5sPXKVNQpjY8krhlQ56DRaMQYZCtwVuO6niHrpHQB3aggrw4+cVXqsBYCVyYYscygy2fhzM6DitmnJGGrVh1OJshYXVW3JBPej7UaM9F8Kc4pr7sWXoIJCPOgZldTm08u24JrCxQEJlkK5OJEl5bfV1obQ0Mv+OwFjNHKG8hJ/iYqX73GDAv9iwidQ+Td85LbngSdQEbrQeKAx25VmtAsaDn1e3n0laBssPTT2a3+JbOpK16bEet99nk6PZy+oTopY1Im8pk/jhpxryhMYrbX8Utw47xtbPV0SC2/hQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

