apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAeMCOR3LoShjhQD76qpRBYPxPeGWQAwFkCfByPjObQ5yx2xKFUq8lhKLFRqMaU0m0H8EgL6gMO3TJmKI0DPcDLIi6PyGM4ywqrepL9T80jr1ssqVGIM+uqC5yzorh+Fq3+c+qW8om4+SnRE6IWULBTo3a0h008y4va7djUAH2uiE9NTF0cEyw4HMTGppQILFONU8xnlcVvUnbO5CPmRE/g4MlUg3NZSEVs/aQ0ar8wH0oL9VsEUQcVBtWVDEx3dCqNP7MGwEYKz1A4oAb+WMX4k+HnI0OOM+IkNAa9ikWgO+5QtlWbZqfwXVH5YjSTYhjTrh16c0XmpN7EjP5oQuu9IIgP00YT0S+q8mjq2scUQw77/DZE5k+7POHB3l8aG1/jC/B1UqXBFHSmTDIuOnR0IAoFlH9RndpZH4uKod/s9RVNODnPlqCYvYiCjlE/R9haU++zaJ3E4BSewd4MZ7hyOqkTUS6UyvrDllHU/qVJQm1A5qPr6TinQ+rO6JLL826dr/24kqBZQdab6lU5TlL28mVyclk9vbkh5qwjcCW285869EwnOw3W24HlNVUP9xl5pQhT2XpM5ssGNSyylrN5YZBLP+efuEol2glRnTQfCxZ+ZEPvPEcTPIey/G7mYgWtHbc0P/xbAiUScIfYBx6yEujPa2S4onpIxxdA9KiFXMRoLMxvC5IQlSQyIMPQ7Wu0+HSJZfpzbs/XXR4n97Gs1CS0pRobkpUATAfejdR+1ArknNUV5S6E98UD27Bnh6nDKNCCPErXyoHir7vVDMjVAA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

