apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgASNozMutHSIwRUnOwAhTOYUTe+RbMUu5FlWGOxahz1NNhbRY/H0DbSviGuvwfU+5FquFL8/7s72fSDlHrW4UYaN5fAg2unkk/m3/Zs7J4/RMEKnB6p53CseNQB/6ERCvQcMxOUGQy4iQxbY6PgRDX8w5k/iFevY47kUeopJdzfCp1CnCBNTWcwWrNRYauyqT0qZz0FgEpCo7i0fky1pW2OPj0UriUQj6pXTd1J8HehOj2Vm8fu41jKb2d/Hebw0WeWR3HEoyUbbOEVN8Wl5cc8JMMdGcSn6Jf6UAyUejI08TsTIK431d/8udd+iTodiCu284olTOTBOpgnLNQZNNPtbWGT2M9h3MOaqw85MtemWnfCRhKvyQEgQOCy4y51ayID0lJRzR7x5CzSVd7UltnovEMP4usfNyTfGHdSODW/BYCiaHiCu7v0sZSeWllR226XPvbEWSKb/I+MGz0j8az1OutoiO+U0C4Ft8VGqghgeMP0Gj/uDx68r8KTkCacvaa8AqjGERNtWBbpG3srOHC93XjB+eYhREZbmgPYQ9ECiMgTAh5ffXtiJEgsceGrV1lHZcjf4NnorJQDkru5INIcNWduxzltXU0XHEI9kBVRWsekvzk0WoZ7aYR9u1S3agzb4bFUwGzPt7qnGcT8/imomEHOoRO1JXz0rMRT0w3ItnYpAG2v87RtVSWFW2FsScOYqdIoEp2/DL1wqOCBLgKFrMh15pXKBc3xZzqLz1snLQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

