apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCIMYq+FAYARonJ6/Fk7wYVAvkgwR8htRNbTZP+uZuVVhQEAFhBOUvEun4d8OkTzC54Eay1zHiFMFgNnuqYNj2PvrsQgi8jIdBSr7QMwO7amAY8LOR48zS6nyd8wZ0yvgkbFl4YNHh/u3XfZLmfc/TIO+7OMx9AgxDuBu8YkNMqq2ksyb6LVuKY5bnknYZ7XSJ+8wmcnisGJKHPuR74CRo0d5JyAw8TYbkeoQ/kjys4Xt75jEBRWASMJfKaeN8aXQHI6c0V7sHlXyLI5SOpiCLfCt/V7+3AeOCc8jyJ24cwGM6VQ25NMdNt1uyfdimQhQ8fpN6ZP7CaGCzB9K5tXOLHdBOdWsGs6uJXYst35+2ojJcjybCI8aVmk0JLOyWVIKLu2CCLntC+wpsvXC7yjDXV4nCqh5B6UlbjYnflhryaBCRdoBjAjfhN0Q6KHL/qrltaOCAZ84tDnIDTf2MkJ1tOoUKyX7S1KciexHlDEUpUHsiEFLXiWLMwGmVlYaVO+BnqCPCy6+FLCFGc4h3PHt5L+GyXHaGXsUcMDkjCuWIkRw3CqAlyAlWo4OqMD/ecf4a5trBNnBli9zmJ1sOTwzlY0KxxDZ9UhqAqNj/yDP3eY7XqaOrU2yQlWwahmEVXdZ0LEFVNeJcBeRUvU2uU2qienQSVFijXjT/WoTYh9IUJgtdYkIEahXAd4+viG7djYiHOlhGra4DN05tN/C4IkHR7aHoYsgFipH61WcDM+7wNcaD0mHVmaNvzgg25g7A3ZWBHMeINgXVMHPF8KLUe7Y9mYVbDVNxcN6S6KGnjmJV16n4=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

