apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBoraagYN9MKjTZPWfx4DgNBaH54+arPUJ18RV13ARzxR8zbHVfA58a6w5foXjyj5iofXP1/9p4RtdHvVy3tQvsr6H0GVyxrhWQaC5QxzzTv+MMg/X0tJCZmJUt1JiV3cu639PGbzawLPsfdRy27EHLUflYyA8E/k51al3tgQyVHO+0OcyKJuaF+bFAHb8SGeMprTwyrLESBa/1ie37m8ZQGEwviprd7WzMskFjYyrgGoFCa1QzWlr+8o+dQbF+X0XnccW0CmaTOAfFiVj0ERqUwmwEwjsTw8V9X1KCev3l1yf5o5CtegGUYVN54TfKOcWuJPzEPW7RvC/fCEd4bOhiAsp162Yuo9hNWWDQJYsPCVJj2DY7C/XvEmudB/qYDcyBT1LBR4b0maKKlrpIAa1pZbePGKcMY8naOj3fhQRfYNIJZEfs4/z1meAo5+nPD0UtaXAHLcBJjmIsxTJaRERwV3RfKSMUQr8wjzwcSxo00LwPKtgYkcCLNCsXNBX0xfkaAooGFuOhrLZaXwAUFc+hXPJ5uHqCVWautTuYQpjkgGlDg4mh9lb9uXqAtOqta7xPWFSt3mhXkySnIqLZwl9VK/E2/lNecg7mwVCou1FA7P1GfoHF6MvJn/yqihMaav0w+BDpmXaiXldN3cGDvZKfaVT4MsJQRxNwCWLXhk+9fJ0cxIbpjN6IvbL37rj4r7qDUXjxj73PI3H2RSFFkXNolwDJKdPylN48uSIEaoI7JVYQV/Sy2ayEYQrj/DBvrl8NEcho5ujoHU5nyZHaN7ILDQn151/uj1XX3lsJVn0h6fA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

