apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAzPBv35LDEmEMDqdgmozKv5SS/A2dBcRLbA/ZF1db+02Ll3nNSvybh+fNHrHCUIZv1iMzHcRLPHHI/GSTdTrrjmQ/XC3h4whAMioCs8Tsqy2zg3PV4kr2DBR9ks1nGGTqy16j4YVU7YhxvwaKZb+xyBemSP5dr51kE2cOk3+XDv8uZFtCdXjX/+0+odYhqbsM2n+FVs+47fWBB9EqOrz1t13Q9aQjZkG7mtqUTOtY9POgmOTXwgxhnsX2ZjQ2K3D5mm4DE173J5qGAwVtdlic5dzoZbebWfDQN5yKV0T9G6WFNIhr71yUrme6Ndj85lU5bc5rnDRJ3fOdgUloeadtiwSJb7p9lyH8SALvUL+KRTbRF1g70JSkoc3ReNUS8MFfpOY8xPWlh8ng5gWa8us0r2XnH//Hxv5Ln65g4jCUJQgg8ghWCvRde7Gpp73rk1t6cBUTKwwRYvro7hw7gQ/E1N7hz4jIoVskUL/T+1Ae6y8cXkryHEdXAKiZCj67Vx0izDebZzGnXwyQVRFxRytPFGts6A08VcUzSk4fJY4UxnNsS00J+BxDJe7piR/+dXcnjXdgbml73HvdP/6hYvfMNvd009lZC5ZBkTcfTtz+dVfYAoI3k/s1hj3e61u3fEdSHvZ2C3iyie+LyEZuNkdjH9/YIpJ0neZLkJKVXSKxJJNgW34ljoZ4ERnaC5qiDx+oRSCB6R2dXkAfSmuHICltwPAlLVbT49uPOjeALjyk1dgvS6g+zXCjvRfUPu7jLbQL8B7eTdZTPhrCWqnKnH3nzWdbCiqSi1KvpJUI6ngRcDuE=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

