apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBDhJP9CKe29om7VZgcDbMcnHt2A7sRh4Di1E25FcvTqZcFQiM1X6CjG45YVxtorOWknh8Coh/t/eCOCDT+w6a1qlXIlv9SpTEEGgH7JTa6eLd0JnvjJVFRoKcQ7B+AZnuAGMvYiA6WjpHNEaDaHfVnWlVbVPdgKX2ev2EZHjf/X1tCS6k1evE4RiEaTCb5K3b0VYDwH2AVRtoXzB1l6NIIpWTgmH/BN6tgSvsFe4OhvAeGZjQnSGYo7eLnC4axgTV5Wj6a2k3jPIz5JIBCC5YVCRxR+PgmybXvUeC5XTLqDNnNm0nkMqitlvygJNm1/OZneHY139ONcZ6kAcpGT9YJGlpftop8dNbnlshY8qJ7VmACqO1zGE7regS2b4DbavW6APRFKzA9lOaplwP+PKky4y+FzO+ST1UCJRdA/lDD9lVRt0KO02ip6ISZKdvqfeja1Fw/UQeGQx3PcHuBe82BPmW4rgAssr+XeEpq+VzseKf+ILFiCaQ+yykiBvJDhAMnBtn8OtKFJnoI2gCyjSD8sjKzFgZoYJpozutXaJSTOdabRioKkBTOinhxwBRxiXP51yf2ZNsJLT2bUbhQH5RUOjIyqvH11K1YuUOS/O33gyDqOpSfzfZotbYFc6lqNvXkERRfkVvEIZCZoYUlpH2AziUZ3EdMQ6TUlb12wbVDF+Sa6VStJu64E/bN59vOyyKRaLV3ixXnVWAcCXvzRdAxqKz3NUE+JllS4//RYTkygiwaa3MdCv6Zlro8gBXWPy+XzUfNNREryNrIUiYB3zABKBboWavn85qJQSxLFcy449k=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

