apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAbiGVRdaYaMo/8DCi6CopQB48wugIYqgwYfpVKd5snXa3MJkeiHmTLzkGuzfgRK81YKCaFOLSEvAGzz00j7nVuCWXG4xciN1CX63GFCqrLzLbszD0ecBNJIGU+Xj4GBwvIWXX4Vmt8FEWquDnH/TKCdjtFhN136fGXoByPY8f9Yuut9xd8QLL2dm58w3iUaPT/TPoPSqU1GpA3VoJHrz8C9qoN/J61QDMG42cedd3z/xcZTB+y7Q1OzsbtfvKsz/VNt5Joae2KaB8s08ZTDMObZs/tuFbsE/bfR5piiAWH9yTS+9ssNTS7PUvxOkYp2gSf+yCfyDUp/DVp7R8j/kpAICouqJWGQPMrxTs+/Cvnc4kcBDMqFX5RuIkA4tojAhg8K5Rb2G1at1IYxKGYQkOR3wYTziACvBnvBQR/HhlHkI08nOgUOSL13HVsBd76Hd4veubL52vbGCy4FtTlsFHsj6mjuQQQROvUUBQMqTyjNgJ5Dgco16Q7B5sodjd8Dz0fO816F4cYalPZnSWIOiT26HOdfk1+T0D0m+P3pgqxHE420DfJsIjVmcEJP1Tw5eCXfILOTgQw4HbgmqqOpHnsDW0nMX1dwmP+PFdTnMHYcQzQw58MPLhJj9hSvGuSzsbx7o/Xe+UJTgkJCz0BQXAcs+EG60h82FLW0ufgL9iD3xwz6lofu2oNpn16gH+lB9WHdO+mNwbawu9b48/Ur3KIS9DZbzbjuJFmwhfG/P0yO6XbIQEIKZGJOyp3/4DNcZ9OGCA9c/Td+p62dyZytHkg2CyRyeEsHQIguWQj93vHoJg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

