apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBpBYBF3eyDbbw3+1is6AK+bD5EJLsjYtb5RwOftrWmbICzpuFU+gPOfJhCfMxKwB97F2KHvoXnbctV5netU4AUYkeYsXm2Iy9o4F1ZLONpOouLBvl6AgOPo0lm+ecFb2VsU3AXL/MH0x5qMhOqkhIJRk4Ve+RP+OCZff4nxC3oBvf/HLxlXwR65Pwj5YBu8w8JRsJnQAwfDybo/3St5iC/fn/sgg0oUvO/fFbPvizkhQzxrQxVTCaC7GmOW+cf05c7Xn0sO0veenM+XtT6ruH8urx0/Lw0dt6ahYPt6H2Ljp+6p8zBT3VaXrw4GrgTpQjHhvBgMzxqMrokHiAZgA2AMjZ96SAH7t77ZkdmgDYt10M8gJ3YySJjjTPlFsETXpANdHXZiCpFEX6Bj8Oqy4Q95I7S7cN0ZfXyy+q5x5y8Puj7scrOm5ZBtWA9kLRupGh7n/wCC74Wr/LnisnU9a5q8puD3nDMDtBdrhR45RoUz2WriPxUKf/8bBDhu43Ekc3iTJ3NnDAI8lJAZr3HtT+jrAPo9SS5zZZqqxD+AxDPlkMPoIcoiwed2fLcq5i89pLazR+V2c19bEblgiqpOX6p946aMqcF8pUYq/f0fo++1VxaCKQnsIol6/vzaTiEuVRFyH1YsMdcrkRnhO2hoaONFSrn7/jL46JBrpnSkHcBm48QVMGg+qNv/0vCXqvmin7vWx7NE/g4ahfxCf9vM4hpttA9wqlBWRL7qgQhK8AoZcTdGpF2/6oFKs1z4/tFUblqR5MGKlnGIr71+dGTG94Y6VKAANnQFEYmm77pbnC8APw=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

