apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCR9iV6A4pHv+z5xIMISDjlKfD8ZhehB0qanQnJBM6jBAgp9jcYdDgOr5KSF+nv2THbXxcBd3Gkq4jEOEJnXTe72pPrK8199RNFK1fQmARw1LRmRngfySYuMkxFoTwLxP1pkrP/y/MsrUldT6UYBvD7XUgQsSqP9cUY2e7a3P6Uz4NKdsP5dzS/e9HGOmkuaZPKHGUycjCU5LaPpprLrIBJaJOroNTMLTrSwyaPAPS7VGCOK9TgbhETuKVcYi4tN/Fg2tlMQ6qTIUXoBnlMEE1MtOSslbKuNV1WLtSPg+m/OzIfOutnsZO45kmE4QMBtPnNuVugMViQBbEdlap3Nyo7xXPot+Ir4mNF3fusXEV8yiCK/vnFt4dsgBBE/0/hZ/WSqXuYcVu8V6+W7I36Ci55FjhulAiNWocI8dPugECceWaQ9fTZe7EybbBXQ0oKSt/zZZrRTYvGogMnHOEGuIfVqzJ0Z8yKIDFn/lFuZfz+SFCbhz4FdzTXxIfh/4MRPm8OuA0NLHM38/OFAn3XZIS+d6s8g4YzXqJp7m95U7Z1lOdNRfut/jh6OF6GTsui3JH9+S22vOxdVdBp0nqZLqs45zY6Ora8KhPHsKruHcVhZAP5fcC2EDWbeDhsW9h1rfXLks2F8iMVplVbOdRclaAVU+/3VcIWQ8PWB2hf9BLTB95yV5tQP/8QR0X9QMb6YjQVlvC8Cyhc0OxO+oYpLQYV3eScR1Pg+TvW/ST624qUaoIAJiK9X8Lypw1bIkRJRFvvGIa/R3t0asX5O1frAAC/M9b8kP11agsfegmWGPcSRLw=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

