apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBb+Le6I+J2tqn9lruI4x5JkWxUw7PJAcqnvQdIqEvnoirXPHXK5rukOY6sWGbECqFhWt6+5xJb/ggF6uZYmKahzxhWROLY/yzb56Y6gYSiAAcWw1cP3xWqlKcopjgYmUivlH10X5vdMdxTxoCDacT05E/dDZqvJp4Xzlbo9knrcvoleATwqU4/l1zc8CK/1NzQnfsJ4sxUYK5k11p8L2ylqmiwMuJQ2Cwo0VnIdKolsIf4tpZIpcd6oKmZFhRoUS499o0pdQoy+Kb5bD6sM/QPUlH6GGJnsDWWgpqL/c8F3oOie+8AmkIb0JAZPYTQ7sIjufS2jujRACHyLu3KzHBx1swQ3UuR+nF/GhVtWrG0zYSFKWQze/LYvcnJECNfDny7VPkKKvT0yzro1iLDsnYRoFQLRmTPKqjEzE0/WIDtcmoRb0MNpOeut/cgmHorjUaM/d8hJs6Klz5J76ngadLJyVjRys1hsTcwSTx2EbO6WBFW1B9wXf3K/pIg0ftdnwCKeTNV7SBdK0IyxgKe6NRDYWGMrdJj9UoFeYMxIHhbs0ALNqlAbzu2guLNOxO/H93JL7Q64AKY5CoLIjirw0/VGn9b88eWZ3IXRiTcLOwKZ42LM+kQinB2M+YsNr0bk55uk1UEXoqIGyit6e6VvqEzi0xmU0XhDgGUv8dPyR2KmodzvV8Wf1dlGtTEgz7F1XBLQ2hndfb0mvDqtdXdgrr/h5j8eEKfFP3fcJCpioS6SVow079AqL8/rG5CispRrRWk1if1RWXCatkuC0rkBCHYsVOJQWppFD7kZXcdzQ+EF/A=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

