nameReference:
- kind: Secret
  fieldSpecs:
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/containers/envFrom/secretRef/name
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/containers/env/valueFrom/secretKeyRef/name
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/initContainers/envFrom/secretRef/name
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/initContainers/env/valueFrom/secretKeyRef/name
- kind: ConfigMap
  fieldSpecs:
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/containers/envFrom/configMapRef/name
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/initContainers/envFrom/configMapRef/name
  - kind: TZCronJob
    path: spec/jobTemplate/spec/template/spec/initContainers/env/valueFrom/configMapKeyRef/name
