apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - podmonitor.yaml
  - order-manager-podmonitor.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - ../grafana/dashboards/control-plane.json
      - ../grafana/dashboards/cluster.json
      - ../grafana/dashboards/double-trouble.json
    options:
      labels:
        grafana_dashboard: flux-system
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - order-manager-podmonitor.yaml
