---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: order-manager
  namespace: default
  labels:
    app.kubernetes.io/part-of: flux
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - order-manager
  podMetricsEndpoints:
    - port: web 
