apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-manager
  namespace: default
  labels:
    app.kubernetes.io/part-of: flux
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: order-manager
  endpoints:
    - port: web 
