apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reporting
  namespace: default
  labels:
    app.kubernetes.io/part-of: flux
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: reporting
  endpoints:
    - port: web 
