---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: jump-diffusion
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jump-diffusion
  policy:
    semver:
      range: 0.6.0

