apiVersion: v1
kind: ConfigMap
metadata:
  name: trait-finance
data:
  APP_DATABASE__DATABASE_NAME: trait-finance
  APP_APPLICATION__PORT: "8011"
  APP_REDIS_URI: redis://trait-finance-redis:6379
  RUST_LOG: trait_finance=debug
  APP_APPLICATION__BASE_URL: "http://overmu.se"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trait-finance
spec:
  selector:
    matchLabels:
      app: trait-finance
  replicas: 1
  template:
    metadata:
      labels:
        app: trait-finance
    spec:
      containers:
        - name: trait-finance
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/trait-finance
          ports:
            - containerPort: 8011
          env:
          envFrom:
            - configMapRef:
                name: trait-finance
            - secretRef:
                name: trait-finance-db-url
          livenessProbe:
            httpGet:
              path: /health_check
              port: 8011
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: trait-finance
  labels:
    app: trait-finance
spec:
  type: NodePort
  ports:
    - port: 8011
  selector:
    app: trait-finance
