---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trait-finance-redis
spec:
  selector:
    matchLabels:
      app: trait-finance-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: trait-finance-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: trait-finance-redis
  labels:
    app: trait-finance-redis
spec:
  type: NodePort
  ports:
  - port: 6379
  selector:
    app: trait-finance-redis
