apiVersion: v1
kind: ConfigMap
metadata:
  name: tca
data:
  KAFKA__GROUP_ID: tca
  KAFKA__INPUT_TOPICS: overmuse-trades,quotes
  SENTRY__ADDRESS: https://846d8482efb34ca9a04fc5fe52fe1b8f@o515476.ingest.sentry.io/5826935
  RUST_LOG: tca=debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tca
spec:
  selector:
    matchLabels:
      app: tca
  replicas: 1
  template:
    metadata:
      labels:
        app: tca
    spec:
      containers:
      - name: tca
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/tca:v1.0.2 # {"$imagepolicy": "flux-system:tca"}
        envFrom:
        - secretRef:
            name: kafka
        - configMapRef:
            name: tca
        - configMapRef:
            name: kafka
