apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: order-manager
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/order-manager:v11.3.1 # {"$imagepolicy": "flux-system:order-manager"}
          env:
          envFrom:
            - secretRef:
                name: kafka
            - configMapRef:
                name: order-manager
            - configMapRef:
                name: kafka
            - secretRef:
                name: rds
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-manager
data:
  DATABASE__NAME: order-manager
