apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: order-manager
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/order-manager:v12.0.2 # {"$imagepolicy": "flux-system:order-manager"}
          env:
          envFrom:
            - secretRef:
                name: kafka
            - secretRef:
                name: ordermanager-db-url
            - configMapRef:
                name: order-manager
            - configMapRef:
                name: kafka
