apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: order-manager
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/order-manager:v11.3.1 # {"$imagepolicy": "flux-system:order-manager"}
          env:
          envFrom:
            - secretRef:
                name: kafka
            - configMapRef:
                name: order-manager
            - configMapRef:
                name: kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-manager
data:
  DATABASE__URL: postgres://postgres:0Fq0C*F6DtAb^Ks^HsxdhZln@live.czn6pu2ebanr.us-east-1.rds.amazonaws.com:5432
  DATABASE__NAME: order-manager
