---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-script
data:
  custom-metrics.sh: |
    #!/bin/sh
    apk add netcat-openbsd
    while true
    do
      echo -n "james.custom_metric.dogstatsd_unix:1|c" | nc -U -u -w1 /var/run/datadog/dsd.socket
      echo -n "james.custom_metric.dogstatsd_udp:1|c" | nc -u -w1 $DD_AGENT_HOST 8125
      sleep 10
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogstatsd-demo
  labels:
    app: dogstatsd-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogstatsd-demo
  template:
    metadata:
      labels:
        app: dogstatsd-demo
    spec:
      serviceAccountName: default
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: dsdsocket
        - name: custom-metrics-script
          configMap:
            name: custom-metrics-script
            defaultMode: 0755
      containers:
        - name: dogstatsd-demo
          image: alpine:3.13
          imagePullPolicy: Always
          volumeMounts:
            - name: dsdsocket
              mountPath: /var/run/datadog
              readOnly: true
            - name: custom-metrics-script
              mountPath: /script/custom-metrics.sh
              subPath: custom-metrics.sh
          args:
            - "sh"
            - "-c"
            - "/script/custom-metrics.sh"
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
