apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: '10.12.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
        # values:
        #   initdbScriptsSecret: database-init
