apiVersion: v1
kind: ConfigMap
metadata:
  name: double-trouble
data:
  APP__CASH: "25000"
---
apiVersion: cronjobber.hidde.co/v1alpha1
kind: TZCronJob
metadata:
  name: double-trouble
spec:
  schedule: "08 12 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: download-data
              image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/double-trouble:v0.4.7 # {"$imagepolicy": "flux-system:double-trouble"}
              env:
                - name: APP__RUN_MODE
                  value: "download"
                - name: APP__OUT_FILE
                  value: "/config/data.json"
                - name: POLYGON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: polygon
                      key: POLYGON__KEY_ID
              envFrom:
                - configMapRef:
                    name: double-trouble
                - configMapRef:
                    name: kafka
                - secretRef:
                    name: kafka
                - secretRef:
                    name: iex
              volumeMounts:
                - name: config
                  mountPath: /config
              command:
                - /bin/sh
                - -c
                - /usr/local/bin/double-trouble
            - name: process-data
              image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/double-trouble-jl:v0.1.2 # {"$imagepolicy": "flux-system:double-trouble-jl"}
              env:
                - name: IN_FILE
                  value: "/config/data.json"
                - name: OUT_FILE
                  value: "/config/pairs.csv"
              volumeMounts:
                - name: config
                  mountPath: /config
              command:
                - /bin/sh
                - -c
                - julia --project -e 'using DoubleTrouble; main()'
          containers:
            - name: double-trouble
              image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/double-trouble:v0.4.7 # {"$imagepolicy": "flux-system:double-trouble"}
              env:
                - name: APP__RUN_MODE
                  value: "run"
                - name: APP__DATA_FILE
                  value: "/config/pairs.csv"
                - name: POLYGON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: polygon
                      key: POLYGON__KEY_ID
              envFrom:
                - configMapRef:
                    name: double-trouble
                - configMapRef:
                    name: kafka
                - secretRef:
                    name: kafka
              volumeMounts:
                - name: config
                  mountPath: /config
              command:
                - /bin/sh
                - -c
                - /usr/local/bin/double-trouble
