apiVersion: cronjobber.hidde.co/v1alpha1
kind: TZCronJob
metadata:
  name: jump-diffusion
spec:
  schedule: "30 09 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: jump-diffusion
              image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/jump-diffusion:v0.9.0 # {"$imagepolicy": "flux-system:jump-diffusion"}
              imagePullPolicy: IfNotPresent
              env:
                - name: POLYGON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: polygon
                      key: POLYGON__KEY_ID
              envFrom:
                - secretRef:
                    name: kafka
                - configMapRef:
                    name: jump-diffusion
                - configMapRef:
                    name: kafka
              command:
                - /bin/sh
                - -c
                - /usr/local/bin/jump-diffusion
