apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  template:
    metadata:
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

