apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datastore-db-password
  namespace: default
spec:
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: datastore-db-password
      namespace: default
    type: Opaque

