apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  template:
    metadata:
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

