apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rds
  namespace: default
spec:
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rds
      namespace: default
    type: Opaque

