apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting
data:
  KAFKA__GROUP_ID: reporting
  KAFKA__INPUT_TOPICS: overmuse-trades
  WEBSERVER__PORT: "8000"
  RUST_LOG: reporting=debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
spec:
  selector:
    matchLabels:
      app: reporting
  replicas: 1
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/reporting:v0.3.0 # {"$imagepolicy": "flux-system:reporting"}
          env:
            - name: APP__TARGET_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: kafka
            - configMapRef:
                name: reporting
            - configMapRef:
                name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: reporting
  labels:
    app: reporting
spec:
  ports:
    - name: web
      port: 8000
  selector:
    app: reporting
