apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  capacity:
    storage: 1Gi
  storageClassName: emptyDir
  accessModes:
    - ReadWriteMany
