apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
