---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-db
  labels:
    app: datastore-db
data:
  POSTGRES_DB: datastore # TODO: These values have to be updated
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: datastore-pv-volume
  labels:
    type: local
    app: datastore-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datastore-pv-claim
  labels:
    app: datastore-db
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-db
spec:
  selector:
    matchLabels:
      app: datastore-db
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore-db
		type: postgres
    spec:
	  affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                type: postgres
      containers:
      - name: postgres
        image: postgres:10.4
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: datastore-db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: datastore-db
      volumes:
      - name: datastore-db
        persistentVolumeClaim:
          claimName: datastore-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-db
  labels:
    app: datastore-db
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: datastore-db
