apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - providers.yaml
  - datasources.yaml
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json

