apiVersion: cronjobber.hidde.co/v1alpha1
kind: TZCronJob
metadata:
  name: risk-manager
spec:
  schedule: "15 09 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: risk-manager
              image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/risk-manager:v0.4.0 # {"$imagepolicy": "flux-system:risk-manager"}
              env:
              envFrom:
                - configMapRef:
                    name: alpaca-7425hgkm69
                - secretRef:
                    name: alpaca-46f8b28mk5
                - configMapRef:
                    name: kafka-mg2mk6f7db
                - secretRef:
                    name: kafka-46f8b28mk5
                - configMapRef:
                    name: risk-manager
          restartPolicy: OnFailure
