apiVersion: apps/v1
kind: Deployment
metadata:
  name: microprice
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: microprice
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/microprice:v1.0.0 # {"$imagepolicy": "flux-system:microprice"}
