---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBsgqdbeDSvyd7DqF2WX9n9pyUHbl048fstWBdCau7Y9jFpwYb9PXThJ03G2DnE2e+9nSRlpwTqMS2SDiNwt8O5pwI+sERHF5PIKsY6U0ZfWmv/aFT6+Z0lPxXvO5cf2PA8/ODEZNMGk/0w8+e/+f4xUoTIjY3z3m/dkuEAAAZoU0g2oDupbmDmKlg91SnT1M67TaLVLvjVMkuXWYLvfhyT3r5iRJiwWDvaqOXkHTbtww2sPlUUUu2HUis/KOOTjtm8cDjtBnuvY7/N4o2a3WgVi5P9afYbhutxzIGUpBOMmYnaMQG4TbVj/Uc8zzOCGlCpEzBg5LzgPUANdhio9nMNfZ6aWa+OnAanTNDr5vPHYZxZv05JHIqQmnVMsbM/Qye9Hi1pwrh1hKWAQxKtXTCdng+VGjqXowOw9eifZhfQRCA+02Jk0parYyY5Aj7hNMdGA14SDzqAEdIr8JmJ82ttc+kozX6g1dUGZDaNvDIucaIBX2zHnYyjsngfqVw7vKT0n8y0XAbklwD4/SH2Ij6ma78dBGjvGCoRRLuZjKRv/l29WtipxlC43xKlCrMroyfhxJJcQb5JDE6sIbhXGH80kyxj/AtRrYNHr2WK/N9MEKPGwarevyzB6lVUcArUcDVvjaHUpCEE0Rd2yf6cfixdGdKSdYHGKcAAkX+EzlJwUTTV8Yz1mAk4HI/1BlD6oZpqcfbX/Nqoaz3vmwPwi+cih34tcd9VC/aWbLyqum/wtlMY7yNkK8L27S6EEWd6rDiQwCzH1QwBZmHQeFlWBA==

