---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAq8dgkLPkDNxjowy4yzOHEwwT8Ij0qkghTcL0wBLOrlnJjj4ChaskDJKSxI2UTpf1vcsdSS2EIxqJd4/XL9hnsvozuUNMbKmUnDQMZJKHzgSevKetPFga/Iq3ixhGqMz4JqSUOY4Ft+9knZhiWUz6d6lSnrHxNG/OE/xuc92hBZJAtYJtQMXF3SUi3Q13Y0/0JZVLhMH7SHVnmcd2HVYxFnJ3MAgz0kWxv62S8nC4jrXeiNfcF5QslJVNgDZPKT3uC6eI8lW62JLBaTY43+XrsvWqqxGcFYfxoKVfyYuqBxoUKLQp0icMh+Zxq0Va3bzbl4FNyK9YqNsY7fX1vD97SPgnAw5WN0PwFeTqqGfacLFEy9KRNP+0Km3c6AhZfxaE7UCm5YB6QwGcL45zPBp5iwPT4dpS2HJU/JQ5XrNDPlYUV3nnMXoIAJ2ooofP44vmAEn0caVtwVZK7R8hvuqvPm12QTYuN5uO2vLHdcoA5OJPWd8Cq5VLmyNHHtA9cpejtzLpuMWdEYk7TGSAsePxgxed6IjSTfQ6euByBODIQAQElIggRk5iW/2JDrtASGc8sV/Cgq3jr2fj5MTlvwcfwdYur1TA10BO7pN81BahXjeKaVM6eQXE0rUoxB5Vcc2eQCk0c6JeCTTbb9kkBqbx7CKM0Gh5r5FZRPKlPm7Wvl3R130cqDOYdjXIdg3+HKJWVEfXTcHB+C183kFkI88m9kHWS2Hy4ZpOl9ZIXzmaYpa9pMg==
