apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/config
configMapGenerator:
- name: alpaca
  literals:
  - ALPACA__BASE_URL=https://api.alpaca.markets/v2
  - ALPACA__STREAMING_URL=wss://api.alpaca.markets/stream 
- name: kafka
  literals:
  - KAFKA__SECURITY_PROTOCOL=SASL
  - KAFKA__BOOTSTRAP_SERVERS=pkc-4nym6.us-east-1.aws.confluent.cloud:9092
patchesStrategicMerge:
  #- alpaca-config-map.yaml
  - alpaca-secret.yaml
  - aws-flux-credentials-secret.yaml
  - aws-flux-credentials-secret-flux-system.yaml
  - database-init-secret.yaml
  - datastore-db-url-secret.yaml
  - iex-secret.yaml
  - kafka-secret.yaml
  - ordermanager-db-url-secret.yaml
  - polygon-secret.yaml
  - slack-secret.yaml
