---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgB4RxQANN0i5YMixIIHttyCJ6lee5rSVEroZxBwzV70EI0/CuLSS1t4L7KtJc506IrDD27OOk0R3GX7I9hYd6oATckTxoHF4XzAR4lByInch+VrRgtPOx15mL25tCCargtkvbD6W7DvXXwVGc3oUGPRH3/xREh/LWjnvuGGb9/f5PIOukILArUlfQFpFlWu4ITgNIL/B7w/BKrGPiWbWgMwe0iyLXor88V+kE48XDmyXnk2LvJKQvUuMWjYU2MvGayGB+L2hqgLB1uWHT7n2DBgY4Xnu6slQnRHtTmZ4VBzi4nAuHv5vxx+Pf5vb3noIEIugCLmo5Xm8rNvt0vQhCfNekw01YMx38PI5xuIzoT9Ev24iIrkQD94MjZo4Vhh6A4F4pfrrHs9iNIJvZ+FGBs7SmGvWQVJqwxMOOpVKVVK0PGDlwlsDSJbW8HV4KVoQ/YiWIigxrSt5ToBj62Ip0LjYBIsghNgT/GV/37oWEtHzwLj0jQrI3vC8DQvp654fkqiSv0eIO/N7IjsPMcaRA350r+CYLvO600XRbCPKiJJRR3a+8SGRgARK3DtMr+xSOUQrIUTOgYl+saAF6M5s5ONrWsLa86vCyDCubbr/7VjfsyfvrxBIC+s6Ztx+HaDBNZd0hFwmm7UV+bMgb94r4740GSgCXg47qzx6VHyprnRhviuAjLEIK9dfO39IgC0Tb29a+jhl2uFUM4GEGHOdn3c7cDHmiwKvlfPhBHB4ryiUU4LkJuNbJd9JX8mngvzbVylobHh1D6GmtA32fPGQ+zrgQ==

