---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgAeRIxwVfVKU2J2sAK6t1ounJM9JzK58/n3m8e7sM6Me+eaEHzi3Czg3SRjuDvtBXR7Xme2+jmHhWw3oeO5IwybDfA1nlXotj4NOAOaPn8nlr82dFvwvTTscIQS2FJcD3RlcphI2LPoapmOpbUojdIB9Yf95b6co704vYU1Up59BYlDQTXo9Nm9hOeCVBpIIrTmxBqwSsGuF0kpG/gC4VFIyAQe7kTuWOJNR09t36I9PHWMG3kVOsOx3Inv82RBwEf6mGqR4ePb0XOHEo3fsphak5pGe7JTaasv8pmQm5xxSl50JghFSkLK5yiz7Urk3ELV+v6tV5vOp1CosIc+lqe34CJA743uSBlOKmWZpsB9tgJxQM80RVEc59WArmPH72xF8WHQPQH0b6OAww2BkHgFKO/91uqPvDKota4v6SKk1D/S3o8+kNTwSPGPYbAayjviraqH9dfqnOnxLs8R2HwUGjoRSx9Et47N4ZrHZdYL7xoKKq61zQ3qIQIVx3vZzrrIsb0Mb3m9JbyACmU3PWT9Qb03uPHvYJu70eAkfsR6Brvkj7RRzzSpudduGwuPcszFvfu0sv2qFsbwWJPfTLVeQQpXwl7pLMM8kKvg+jDZoZe+YQ0SECH/Ictdr+D523pVNWeugJablo20/bYnxU0VfN5fkad8InJET407aXxsaWpTfzS4vWVnC6r4LctVlCWVvzBAqhREiOxWcM8donaUj1ruqjiwoXrZKYx0LaPV9g==

