apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgAW/oIp84Zzs7TdSLcxNCX7LrtDPfvOsyRrIgMR6FyYHZRIwRzVDiJX7Bu2z0Eij1Nghp6BnpxDeHSsC4NokIlCDUiDvEXX4dU10PM8XC58H431ETKeYR78fc95QYvRpYkNRGeiEhq4b+cccB/421g/mIgr6o/L7CZOOSGHJMZAtK2Cp6sQsITDIXO5RaVEoOt6MJMIgEvRbf+MwLqg/a1VyuKgFsc+dD2rMriRZPt9BaFDuv42PDy6h+Z+0OuSq2bJsgc5thvctqlO+dnONlI9YstBLjit7HybM1KqkMMJm2aUorjW3HatsQkSWkxMa1IUsW89jeSioG/MzhVlqNwMuWPnLt5wXJqf+MQKG+H6U1aTy6T0Bsw30WA7bI7WfGbg16LInKmrtSyFSJ70SzPaDYTV6KRW5pGdhhZWWgRKFlA7TlI9cMN3a3l9ehjlGT8+PDa5MRux/yDuTxADyWAh+lOz/mzDw9Jst+amLm6yZQNprH3FDY+wvooi9z3Cms27dzOb867bLEum+HS366ab4dmjxHAT5WuPYNk90Vdr6j+VQnbUTfMP+OPT+3OnC/rWqEAdMx3NfN9aneGUZzMC0cZMziScCcEpT21vWQuWvSRSVmYJKkgekZ4FlMvq3qOnBH/iqLNabgmGrcLjhKokDuJSYODheGgSvgLuEySqAwEMxIV/yxmJIArqPt6IQB7/dHHSSmKFRhvHWazd6lIYyJkjDpNK98mXdPj1XgQh7g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

