apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCSdG1PKxndR3udYp4VmQ6Z3mAWLTx1KRVxAEx6xYizhe40jLXYDBXXcpf2JbSOLTwxMLp31D5MeXJv28A/weEpIOJEkUZFaljDQdBXpseFEjI2TE4gx5hwEyGMXSV+qYU5vSewSkhag9+BlSF86MZi0W4cqswbcJ2P4/e4Ub+UoV+lfO0fVaUbP1qIiPtCNtgoX0EoXVx4031VaX8VzkH2zWs5jRHg948mdPGLlm6e25DzF82C70OvzmdePeDWYMOCx0KAlm5kzzC3SQApi6nbpxwUFvZ7j7ybCHe1mnEENvxeUX5s4I9OdaLiKLtyLtKZsvdKhndq6GKoMF9tA9YsVxaIja9t4wbKbi9+qQaEOKAmH6SlOenNDEEId7nMvmsLdMv7e8M5tHJCDBCZYU7dqcqSD0yrwsoqIV6HiAkdRhSp2vjZ0hj+3i/7WmW+nECDO6JqE2QpGxDVycxQhK5Q8TViESYbW+j0zHk4kGs9P24JW7Mhevc+qE5MIU9QcDtaNUsczgPXqto4yQAyu76FLgLUMMP6s8EW4hg5NXEri+ArS2Ahc71cY9P+8uZXUvqkEtK0DGFH3Inl0J5ACtEk3mpmyPrKaw8SesJS7tF9brqOZBBIQyAX5z9VEdyhkr0zl8JTtvz2cOGoTbNmwVfrWB87Lv3GZ3vN0dxpzPnVdIsCO5m9uXPnBRfvu3E7vmBcJS2UeBytF6GWonosuCF6fGFQPGaGtN8NmBKKMCVMwrT48oQcq3sEGqTp2aEoGNFLZDI7EwjBjv5pxWlU5/FsgM/Txvx2gCNvOFXw0OrTuLA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

