---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCCAmQOWrCv5IwEXH26oGCNrfaO2dmWMV2/jsyuGf+oHZT3wszl64duip8DgbPfOAs08lXrdUdhSlswWhAVGwCVtKeJIPa2hqKn/8GTDeeMxYfHAvV4fexmlunTGD/xnzkmiXXF3U1HLPN/Skcl4CxAIe0lf4KIznYxQZa64CJ/qPAXvnQqWw6bAUh+66MR7xwJgbpRY8JHObIvUdhygsa3zj/KCJuWSUStdAM9KljRUKDmYOsYm/IRyzPQ4laMrCmTA7KeR0X7PV9D+HqJdMIjlnA3jJNPiY1DNkjm21SGqXhHP8QhcApggV38LFQ5QGdiG2pv0fDW9pFyuIuvbWflwb/qtfVxqo/mveWKA+26RBEuYFSbYwbUUN0Mbc55meG/ZMHObtX+OVq3w0I/JuJJfTSzvrvfck7d8zJMh40+el5yvnGFBEIZgl6rv43kVzwNf622e9EUBGVsWOLNuIKi1SRFWYdUFxzZGo0MnxZBbDNYKfHFfa6IZSsLMNU3ACop1fKNpqmf7W3x9uH4+Z31s2Z6hUTNlnmhiTVR4maT+ZaX4M9CRpXBKAdB/ykIlFzDW9gDtzASDTf7brEQgpdnaxTMrrrboO1IfZIkfaVt2QgvQuq9zbB7kYvcaWC4nXuP9Pmk5wRES7WmQtgpxZjHPY0qU7uoqg5E0l3V7pLBJ7p5RnWtxAfTuepcS7X4RhdkwFPDAueRJ5dkXBgzK2vnWO5Q4r411xYoSktBZxTt+2bvopMXUVmLHRkfkqwT/eGTdQsrkr+C+ry9FFGwvB6fUhDFSbkO4/1hRnj+l3m6+WM=

