apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: trader
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/trader:v3.0.1 # {"$imagepolicy": "flux-system:trader"}
