apiVersion: v1
kind: ConfigMap
metadata:
  name: order-manager
data:
  APP__UNREPORTED_TRADE_EXPIRY_SECONDS: "300"
  KAFKA__GROUP_ID: order-manager
  KAFKA__INPUT_TOPICS: overmuse-trades,position-intents,risk-check-response,time
  KAFKA__ACKS: "1"
  KAFKA__RETRIES: "3"
  REDIS__URL: redis://datastore-redis:6379
  DATABASE__URL: postgres://postgresadmin:admin123@order-manager-db:5432
  DATABASE__NAME: postgresdb
  WEBSERVER__PORT: "8000"
  RUST_LOG: order_manager=trace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  selector:
    matchLabels:
      app: order-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
        - name: order-manager
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/order-manager:v11.0.3 # {"$imagepolicy": "flux-system:order-manager"}
          env:
          envFrom:
            - secretRef:
                name: kafka
            - configMapRef:
                name: order-manager
            - configMapRef:
                name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: order-manager
  labels:
    app: order-manager
spec:
  ports:
    - name: web
      port: 8000
  selector:
    app: order-manager
