apiVersion: v1
kind: ConfigMap
metadata:
  name: order-manager
data:
  KAFKA__GROUP_ID: order-manager
  KAFKA__INPUT_TOPICS: overmuse-trades,position-intents
  KAFKA__ACKS: "1"
  KAFKA__RETRIES: "3"
  DATABASE__NAME: ordermanagerdb
  RUST_LOG: order_manager=debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-manager
spec:
  selector:
    matchLabels:
      app: order-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: order-manager
    spec:
      containers:
      - name: order-manager
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/order-manager:v4.0.0 # {"$imagepolicy": "flux-system:order-manager"}
        env:
        - name: DATABASE__URL
          valueFrom:
            secretKeyRef:
              name: mongo
              key: MONGO__URL
        envFrom:
        - secretRef:
            name: kafka
        - configMapRef:
            name: order-manager
        - configMapRef:
            name: kafka
