apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgCOYEYRzvaa/MoqziIRnwr+Nu4pOnNCIjb+GvXW66XB+K44PVKdgQOll3iaqRQVU3tBnEMRPGGvcn8/A2sKpeD4Sd6mtfla3iCRnJKdGwdn7elMPypqW5TK+GYd/6TxtcFE0JUBNt4asyOBr059DXHcQ4ET+axOWUx+a3LNmvW7m7WczUemqRgx3fiPg1sncRj3oNhSp96ySkT2kliwI0Dy/lIuz82veP504iO9W3n8JWfmEKhccB+dv/fIi/lWXIexJ/utiefigHYT+ZAOzS9cGjOFxRN4qs7wyzhCgxbnHsbsKewsdVdglqSZfhT3Q36pR98x9b6HiM9zEa/OMDQA6nnRqqTQTfIfp3C/Gan2inGphDcWVMe1xA8qev6KrsutZkdyPmcj69k0RAJn19qfmd12DHBjVIWcFnluxGtYMHqz7q4MAo7RGDL8U2SveUsSsWOsD/B3CT3ur3Uf79NXImQqToGPOV7mBgOrAYeFzyhdOfor4cyD7puVEZ0jdwv7fcznbilUR1qdhOlTVy8CzVCYC6SK8wtBwFpYWGUPhbx7aK1r23eqsFic4uy4PAOqzzN9cuUxIu2auHaq+wRxGk2M/RHT9O/m1fUrcI37OgVLTlxLMxxqSAIkTD/cl0DopTa66ckb+KDTKh/kYeaS/FyWs+pkbXXOZU31993UQB6TmoH4jwUpQo92teThMWE00WxzrPEnbN1r5TrINKxTE0Tbpw==
    ALPACA__SECRET_KEY: AgAROafhOw/QNGcf+yXDxuHV4rddPpFVF8xYDgGqzyZhTKiAtKIFSuejZPrV+PWUvit6atgotIGm2O51R5ZuJ6IiCkXVPIo235BwQokedWgHBDS6yhSdfOUHsSjqwUrUg/MHiUegvaAxeaJvL3r2MB+S9H1llhlgGnsZ/7BCVzzcaHHf9k72K50PZmb5CfiHvs6dnWRvk4GhrZN7qI6H1RksS/JOZeictsruxpg4a2OsvZcDqcUaPdITecWjpkfzcnY82XJxihRyOJJpmhNuL9q4BudFexMYJtlb7h3z8ZIyRhWLBjjpHgIqzxp8XAChjNzwXaqD7a9nQMRbL616m7a1ebTuRWPA9n0XAAcZo0U9cfN+BurIHwQsI7kdJyCk+zbGofktJIcYaarRc2USxQMQtTSMY6v5J/7EpmATne5r0Br32LaXoosH64tQD9eHf47YiCUvuPvo/5t46kM2idXpa41ipJr7dudiYSaaaIK1fGpHdRxYz4mOhsT4Xp7bP3SehZncASrIsU6famraoYQK3/c50UMZ16ERJd6d9zszfYtknDEJSCDJ9yt2EUNhJ3RuMljamPJUbJD24Vw3jj2By99yUD7H1doN1WJdwLXnytejdt4yn8eohXb/+ftBFI3HDsCRvkwTRsX1ZRojDyg+Vq9bzQeffedMNDiVhJzglA0Zttab+lCn39hMYw1oD2kulkA1dsRLA3QBmLc+elQX78w3pwRaR6CEI8rkUswiyNrVLSl0XZmx
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

