apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgCWDl7dxVPXHEvkRsCdACou5lhFheyzEOtN9+QR3lZRn5DoE6wKvxncbVNisfphpDShOJXa62D7z8mH4UtcR6f/zXtth2tFY10sT2Vdc53E/pAmW5LfCls744I2zpHV0vdDV8L0yMc97DzKpHjjPxjHmOI8pyu8FvhTXV33Hh380UZG63ndpI002GcbKSddu9lUKR6DYeY1yzZ1Prac5fHxgXpZCyBEv+3/6PhVDcj6aXwP55BTU3rlPMMR797Z863CjN7L98iFYeZq7BTfzKeUN45mObnjgKHE3c22U2A9zwx0VfFodzX6t54BNjqpGLzaPeMudek9OJnt0jLUGDqLdR+fqcY7R9hO1eggpVHV2Fd1R7gFeKG4RtECusgpWztR1z5PSFDTWAMx9fR8V+17HzRrw4PUKptcd2QQBHzrlHE8cIYWGpuffB97A8HFckKU+l7BjNsek6H5RCrKgwOTLqgjfKukkCJi2+R4BelDNSHzEm5VaO7TwRZf8SpagxdxAISIabLnH8Gcj9X5+t15BxyShXwt3vLmkP/PgStEXSHo2PjXcNhcmE4KZbEw38zelyQPa5BNJHo48KEEwEEJ5A9UEHN5woYmtm2SRzY4056H4lKnprRcyxsWjOhOGIPVRmFz40Z18GsD6jkpIC3ae+Ww1bRnWYIgYGojZSbXCmGIRO21Nxd1pKqkXw2yw8pbx9OrgIABnWOofZt3p6HDH0H7ow==
    ALPACA__SECRET_KEY: AgAiEs91AZk/y3ByWB3bqL0smL4zd/BPLbz8qppS/PgJOsFD7CsGf/pfIjQba0P/DVlUPJzgqXdfQRRmzfur4HYqR7Z9WsDWGQdpu1tBAsC/aszSqUtpyTmX2hdVj1nU2RtCbwscF20a1AbeAnsaiTltIZrP0iuf2SuM05idCWlvMfPdqXUE9nPW9VzxzLbdHuBugzWfEoYwOyf6Q0Tm3R0F/+GkvyFs15H4eQiuK8tExMXGXEJMHvx/6E+X5OibM3khUHvNRUlL7Yc0Xw2mwAurfs8BdsDbH9tg8Gc6FhR0/hHbTRF/GQ1/+WYjcA/oOvmJRkeYutlmQKoz/XTi50QZmZG2Zf3nUZhj3BrQ8q4pAb1DV7VlCG3EpV3I+/JtiOn3f1dCOBEFGaC9OR9lfR2J6NcYn8ee3Bx0NsA0f0uvKlgHk8rOq5oaxY3asKBxmPrkgN31OLFlvSIforZKQbRvc3HEB/oc73BhCabY0jRoNsj3n/PZzXa0vLYrnMmglpXr/WXMmw1ZQvTiKbGLcz2FwgOFSfwEQWplUrR80HBh+rhONDk2xXj47HmS93IYfwh9FT8XDI8F/vPQ8XXRTI4umO+FbvyMG15Q9A+BJZi2W/Cl2Oh7OsDKoL2x/rEL+RIir6Wh/JodmhfbVGlhsfaTb+2wZu6lTy33RnIM//7G+eYfON5kJwKzT7qPPZj8D7Q6iMNsvVHcY93plSMRfvzrYfGI+RIfsj5Y93eUJluLS4EVoJP+vF1/
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

