apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgDQ3vpmPwxa8w5Kqj1YRiK3VYI8vwmJYNNW2Yli494IfHePJNdA5mSPxROsUsULBKzpe9MFVM8tgq7KQd8MluQhZCBIa5TEFDWuktH0MLKqlkTzqAn9gqujXTZz9yxZ5sOwJ1D7L4kp+A87ROrj+Z7zLiJYt/Vbpj15vb1SiBNEgpk++8wH9e6XX9FeMYKTEuwJsXwWvicX08mMDV1D/N3Dt3m3AIUcX5M2Nn/UmtZSOzqyHXYtAEkMQKlCGXTo/Sy3JDGHV7mGLrfF01JNOKljN0liyLnO6nDGMu3gsMUIb5wvkOAJkVsRP0EYga10w5lzNJ8j0qsIFrXsoH9zqBbCVot+eU3hF8wZyj3FhYcd4rYj9ROH+AK1ti/pI6QWLeVUONeZpM9coCSShpBa141RW1sHqKKS1gbt2GX8JQBqPSdBV9xFvqt/4qwnBXxELMKzkuIHs9w6/YTV1GxL6RTrmVHExyaVmz2Znz1Npbc5PWnNT2rCXG2UFub3XC3s9WYPfIFWjLKJy9FnEweESy1Yxc5K++w8Y/9DoGQc9bnCD6futu3R2QT3Ti2vnfeKp9bjsEPcLPhi+GFJNwfj+KApixsqP4wqnwZZnKBUjeN6L4HFzxIj1csq8rllz0qd9pLQoyX0wBIwYLy4uKAkvrl+azcBI+jZObWEAiy8DMzjBmTeOsfCUcZeVCD3QsxxQ+YvdXvKk+hIn6cl/q8JHg46bMRTFQ==
    ALPACA__SECRET_KEY: AgAu3VZHL0xZR4O5sIi/guyLArjWy9qrNjfg12SLmHegVmitjHlRDRD/HDeuSrllEqcbSsK3qE6QZATLr9ungd0LGZw+lpxeZym6lWzMefHL2irtps5tfTs6bPcoiTdHGfayQLHXEzlggbAs84sAqOV/2NEvKyIKxSMC6Byb6qsliXMOs0WGrrx+34nFFkXPvsQm8gfuviXYUNyaUEEU1/OxWKDKL+wHjYiBR6a5aVPvAkXo5wK6kVpLbCL/n+X/7aCc5QYBjzGUb+tcGocOe5srbHmEI5IcHcMCOTABKDQDK41G0NPfiR291Q3+nb0/OtUsse2i4yoMbhZzg82IuqXTXE0VjkLbL/zHpxEtwgpfSrXHgkxkz8tReU2Ji6sx4b4Wr7Xw/HINpy84W1ogx6pMQtdPluxVTPwV4fI5U9UBw+5HGq37Q0e4WqNBejSFlJNqwn8msGC9YoILvh90d/FZIi+Nzru6saMpyVeLwUna+7mZ8wpfA0vTYbbLcumRPY80KFebefNMG0waDmLtZQv8YXGuaxQVKZGjkv8nS09RH07kHT+ihUM2YRB/t1wFTuA5+FHi07Wta+iBHCK329gnz3YSAo3ubCF/FYFXRBIHGNPWrV+NE5RCEbmToj/mzSPI45o7U3O1OzdFbYG8obFcoWsL7YUlfliM+7x/rfttQt5oq/WZVGY9gAbzWAv2WDftMjVVReBmNQo+Bo7ODrO5HgPYLJBvGFF8KkwADlBTGi8jxkTTNf46
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

