apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgB+BO+QzdzHT//zhAlwS/fVBYCGJGCPJkV6NZL9JKE0cVbJZwBIfJhMu/0xHJuDQfQ0oXnJShgHP8oHWOmImB7a9mQGlxJdQcUgqu5SMisj94z2JidGSFLxCbyBMlCYC4Qt9QXRSLBO66Z6QfawrdXgf7kBTtcKy4uwYjjj0vfFPlkUqjgpdUoNfPpmfyCHXEosaRdNJHrL29E0PyoPhoYNbol/xBYkeNUq2J1k8Jn2gsKHbzmaZj9V0Iyk4oq09A48gl904KzZLKQkJvz13EZ7DdVpW8ljL4LBHTu2ZaCXxLmFUBIMAr45ebjULSJC7S62iQW2UIgHRFLLQ8gxV6PYo2GgLj7ASoQQu2jhW70aB2DRZfQlQc/pG+4Qun9/9wVPnbNFPIGyg7HMP6ZD6Ys36uCpko1ynZhVmFl7hIPjm4SHI5wlUBOKSkuOmMCm000uIcp4GiuZb20fvplNUhOadeRS8Y020AF3SO2/EsSR81fY8d9IURMeP8W9QnEG7iBTOnTLvgJS4xhLH6RdLpoF9VZA/fHa6brdzydz3jooGAcFBHcMeQ4bS36/Dl4xj1qq2zAXODDPmP+PvXVPAXf8nByN8bWeJIaO9u/3DmvWx9RxYynW300fWxg4CCM5whLgFjHB81AYAWqwnX7rYdbZ12PVY2sU4sqC3n1x7V0YAbbssH0u9WUBByjuuv97eslJVYNbxDw/wnRhxdjU1Lmxo7myGg==
    ALPACA__SECRET_KEY: AgAK4ZYZi3nmDNDffpG6fwu/7Lq1/K0fxWiWYFM1Qo0UTiewRi/Ra/teAsBHvUQTTKishaKO8ueMALxSCCcpjzzonaEjj/OMnf8i8WiKjy+kGo+saujqU8KTnqwIXD84sWoDxCfphiATvskxNOXpW8p+9OYbslUWSz1oppkTsfMTlAUieV+CP5doJv00OAFn32PZSqk+UkGVM3crb99NZkbeNQQMZ3wW9WkOaasMQrX7E0M665KF7T8z6eM2RHkSoOQgD/8MFHMllYEhhoIIO+r3Qnc9BFoHjRFMwhg6BPgo0E17x4z9sxYX7fJBWo713b6U2bCwDGJUgx91lESuxa6TcOMgCgzniXa7CNBo5xWIKDVa2R5fW0zvdoyycAEYZmFETKmc+PnhtzCfT0MIHJbsvjmJxg9Xg5/CEBFilOQ13S432dsYQh8bp/KcxNGk9UXXPmuMFh49f1a8B7GFmy7HExmJXNPDJVXmgrxtn2iNDMiIDXYMa2a6kzq0aKHYwtw4JDCHu2L/McKGSXRfMmyoqhTE+WXoe4vYkvGm9I5Vo8iqtIoPSjlsOnZWaQyXSgIeTOROy6g3xCfzZ3OP65rPm10dzsy1pyNCpehRvXTwTXS38Njrs3pzIBmpPb/HfURdwRQhuur73PifAcm54ojx8gIDMhFzwdaedw0YsjN168mwKJ941gk+vTPewjKYmSP6h5RvbiAGv6h5HgG+glF7+V830by81aY28ddlo5Nyj1AYsznUTCMO
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

