apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgCongDQVw7zKR0XGjoP/7M+Vajb2Zf0eihB9VXj2YxAHHxkuEJUrxX1GPTL4zyONEeo/FqGthPMMwJK4ZOQ5ck4XzUkfAaAi6jJw+FJdvE1+UOJN9XDvWQCm2lu/pRgj62HOORd96n9/s4/N4AyfOuQ9S7qPEiFNxw/o2U81+D4NB3dDEPKqAuy7uwG5P2/mL8+sQzJC/XiftLGYx52DBP1CnagSzucsNDsPSXYFyXoXRaNtwVQvo0fx6i/UN2LEzTWENZpiq/qjqUeRABSvYhFJRtYLVJB6zqMSYByo5pFrBv9V5SQv/6nOmvb5cWtgQsE6Oc+OjusbaA9A2KHZi0+GGu1KJehl8TO7mJ8F0YHsSDQFYIUxIhh5PqvCfNN3tslU8M7B68azTBo+YfNAcAfMdlekfNUHpQ0Ue0Fb5KFeqqc6/NM+UdfQpGwZOxuJnIv2aIEPw/EzGQbsMWZ/wugiBHnOJCp1POjNihuxgWoAGQYjVcCVKELv1XGDgdB5zwdRoAD8fyCcbHk9DyQPuu+7M74TnZWLpxKwshNWJv8cVem6xmpYukjAjz6BBg6iGjUGWmkakwBVKeiQjx2lTb0i9Zpvyae3589nG1achLFIT07w4A92ktT8WzLYuSOWbp/QaenONiSTxhMs0FNeznFeBcFSfpxbD0SXZlEAfbfT2JJTIiVm9eloseTYjOfnxnhlLQQa0K9lnzafUuGcRTOTt/ZPA==
    ALPACA__SECRET_KEY: AgDS64VrwPd7JgOVg1FxbQxFGcUcqJbx5gLfRYuGrdXYCshkYfVgbgo11FFm3kane4SEqT/LpXVQoUOY2BWq5fUgKTvKzLDGYzrTFBhXhl/umzjgMNmQmVIYQji2KsQPOs1OBKtmEXFO6iOnO5R+FHgsVG90VwTBx2fM6VdSDAcMaFbxEL9OXjQAmtF2ExUHZwsffF+2JSOVjm4R9T7dPI8im+tmR24Dj1nQ/i7zWJSABnjW6AIQJG6sWtqFboszuS2sXVPQ6DEzI8W6TcxK/7jJl21SXTuBHTx4uGH+hfZ3uRJQO+3M4ZB4wEyoLQFi6BlDeCo0QM/BADEFze+lYQ2L+H7tzL+jlpKBeZU9SjPB4dKb2WsYarsOnfRRmYuVBkwYPIEI4NE8WEGUYmIqJkNQ6xPoK5Cw71FNjaErLIrJfAFqT4talvIGL0heJNEF3Qpt/n9CbiDjVQ5WMZ3yAC5PqjJ2/fV9NHbNKUwZGoDtI01rcWnMiPbaHfQuCqQNy+z5wRy2PnvX0WLHQaeneZ/t2UzbwPQfiNMTegJFiR6yXLYPPMjgg14zUzJrkYjxYGXxdved0f3u/7m4rWJY+jsA5b3nLhvlkLKOhfaThP7xkVXtCUpm6n7+CxBdgqXWA0lcPvtN+sXCogza+/hSWeMAXhvFa5ysuBU3r5C9LV6QUy2CrLVTg4Ykpr5JjsBA8FBMXzbFX+hVVuZZvPCMHXR1GchNKK567dUPsePi7jfHwD86vFICw+ob
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

