apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgA7yamOPIVE+b76ydIgvu00LO8X1onV7w14Y4h3jEnsxDOMEJJsNU0X3Sb+w19X8S+WA4k1tV+67bRs+nhq/yFlUZBVMtp53+c17HsEqHEwL0Y0V8uUHNwZx6vfHHBj08CtL8iSCGCBas83iLKPik7DJZOHFhAKZE16VL+u9mOQBVfAuwDEpeKfwPLC+FpDvdXuylF4spyccxvZPIhfDpMpIC0R2EfZI7/PEhe+6X15KsF3puogeUcjenOfu3oiTN8rHaKEGoFw9yS2OJX4eDo+NWP3/bzXvzKce/TwnDXa0WwVD2gGo0z1SeoxEah7m7gW+T4YHKGrTN+N6BOOh31eA2AP7BtBkr0/3dFbEAjgGCtmfKEHUfqOaQYoKzVXu+ZIeqdlElYZH1fCIwIep2cKtzFVi/PQ3W6RRDBiCig6bp8c1tpfHeXg6RIpG1/ZP9azQL2PqVmDgFzrzIFR3iLNiL1q1cfkpWUNSiq/iA+k+cQc0+Z/MKvcziTQNtO+/DETD2G1Kj7cK4ZF4MA41Go7ibOMU+wxBIk1UHMYL68YhavtKm7g6q9beBR/jlzMs3ibbMDEOTJdOr0nMT0iUQE4kr1r+8dNw8vfPtiNwKkgoBXLwx+dIaoirDMHX9MCdtqGxAS7Lcl2cSH+NyN1T0tRMzIZu1pCBFphMmhH/kmF61Nm4hyxvN8cC9T37/2FBBs2UuiEDi9A/imeOmtYGvTh4KeD+Q==
    ALPACA__SECRET_KEY: AgCo2eJKOuPjrCN0UFH0Cn0AkAHIJgJoYTKrqwshuuCIR67WL4POwIjMFQ5AoOFIp/r7eF+bCVHyI+JNYyBYO0hszThxSuDPnPnOuHpkijtAoISFelw2USdtlqQ2SsqbUib5L9gwWqsJOluIX7BRaNPWnKvq/bc3ivRBJb7vTbLiNXoyVAXgqtPr3zRKsqvIB0U4fgHd8krpBmyF6Rb3tNLRXGA/zMLSSlY4jyO+92xUvbxyLsk1MSk0gQL3j4xcqGagGRMenr9s/QfcfqwxF+N4NmA1hXsMxeer+qQPxQPUg9zJV1EVCNoA6gRf1CKxCWPY1ncTjpOXbbxU+TrLzA9o2mKqSbhyeShwIvH1ibs5QFp+ZFUBElJ9M9WgLwF1roemjZF0/IZUcT89dR/cBQNzyJzmPgZNeLiNd3KbKEfpJWC2TNsIzmPhfRYjxlHrj0LJCkqBQhPZMBYvs1Rwr38vLMkyBJWm5sShGozM4HgUHo3LvBytpfTdjMVRhqENm49rhOaJENgc8k9voRINu3IEjlSq4JcB+KwbIZVuhoWqG3rywCbeawSZjg4Gd8lfXcP4s+tnY8e+Ub1BqmG7y423jn3fMx7gQDiyVn+jDM7NSB3+L7+0DYcw3jRpnFfGEFsYNEvdxSVq/gfZlW3m7mpKVrQ6gphRmt+BUQ4Z7+r91+4NaEMZDeNIyuozHvdlWUwRNCoxj6soyvJ50+OxgAwj4RM35kSf0WxrPKI/ssWMqfnD2he3t7HN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

