apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgBflnAXyIQE81IcSihrGcZqWDNZfU/Enih2G3SUpFB/SQWN4T4rm3CMjZoEuWNXgicDUw7LYF/ADHq5meeLct7ZCfzPeyXOGmhLd3uN16cpveYE17o2eMt5SxjIeUlrKDgmULT3rRfPUe0x1cJW2DRls/ZMH3qdRxkBJrWXiZtmnRq/2kPbXAiVZ3i8ObHvlGfKx0JYjOggJmKgvvpcDUGipPW492kd+mLfgYSpoRlBISI4TxdQ11iFdCPP1qqqMOTUp2D1RqQfUeYyev/KYHQH9OZtWUQSmPft3XGmPAdXFcsd5P9aMtSj6AXBrr7sdBnGEK3s4hAkR4epBF7kF9asCEZFil9+Iw/o/CVqQAZQ1RG9LlwuN5Cmbj3ehuLIGAZSR6zO4mMLYY3C9yMVeHLDfP9bWtj1NdZKS0uDqT+EazPat/cgiFMpVjarDliQzhJMTIdZRKd08xqkT77Qc/RIfVLPAOoH50l+31Ium0ob0W1BHgrryJ+l0yjB4sxZ6xWl5+2N2XMxDVwdWbCCnotUESidKAggYNz3tapAFBw0KW/m3d6nGcEjVaAZkfKV3D3EZmfXMnFYBsU/qz7iSXR8m2MULZL0/cJylyIQKJSGT1UCwCm6sTjUqmoGFQOSi1sIIBW6K9iRRIsXamKXuY6LQr0JXylmz6FgfhIRLit/TGEgiyI3sjvVl4ykq/qB5uMJkRQnf+zO+CMJUksfrCY7d2bUoA==
    ALPACA__SECRET_KEY: AgBlGTyY0CSayW55Lx7wVM9UYq3QQr+26HIeyh1FuBXGFwmueSpFpIvHY1YoxT+bBv5jwuBgifVjRv2tf7g9Hj83DuPGF4Gw9AhoFfYBVIG8iKpMW2p7OIRRQoXSJEwDX2Z9wwFKXv4JjtN9zGz1pvmoV8hGRS4bCDNtJNu4rrzeADabvHk0Vdg/ZxVDK5AYAD2kC2hRajO4Z3DRHywFnFj6Utcno01R/wWs8Rflw+NKjpEYWFUsEp/BqdbTMQ2+/12ZrTipCxQRANRPQKi8zYBpHNK2TP/JXHpa5vfF6COzhI2M6QVb8KUej2OJlujGwHI3uhkkwBrfOA2zNXrM5X3LPxskynzIT9WuFtR93nvLzFIDhCWk+X5cD/9HbCH3IZL5w/uMzkvVDuBuroKKhCuMtJtIDoE7n4fw37CSqZYnas2PZeW/GMPBjGoS+aDXdZEdfmr2b7L7vp7dEgmrVC8BsWlXayG/TVMAkVmdgPrCmzp7tpyey7MCM2boO+TTYBct2BA1EdKUmxfCxmi2exSt+mxqwuUi3fhza1jRD3N42iKy8uR5Bb4A1kbd72e6D2ZGC5BpDWc8+pt2gMNK+xTiVvi88kiUts2dGPjs+J3xBrSFSrKW4fRmA59y/rAuxk+NlGWneyPAHf84GWZoAFh8KBC9HesYWzhNPTnIJwqF3DclnQoafg5BPjsO6oTU2iHhTmuiVfIsPy1rrQ2hJHVZZzi39DE17l1/Rvp2AjpDJvWnQgo3oZe3
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

