apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgBFVQCVlGY7jjZ8V8rf+p6EJvJE0Vr+hsb5Znc8VPjJszQgBca/9hH6zK67eUmhSrzoZP394OBrX6blR1+NvcJyskBC/qoQ/VuBcFcrao0otejrJNP8QWDOLb5i74TwEntjaI2SPCM3SSPJpQOEHjOVihZX3UbpXdHaCtgYLGg9C0KjtDSYOrl4d25auQc42gZowj4VAofmBs3At2pbp67ovoaSiGJ88n1oJ+FEA8Qm90agHvx/Z9/bNKJQ4JLx9LwYPLOWsximCTbSq3oqFFXwzjxfgiJOATUXVhbDgd2puwXP+4/4gRJ/nOSPIq78VHPcEuyUx2pYYqtC6kWGnbf6rg2IbcMT7i8XHrYhyNoHuq7f8CK8218JhgjMclZ8OBmQSGppm3ks6WOM83WkYuIO0nDHVF4Lxms5JIKx73ReyN0gUsfMTW97Qn2rHP4qf3XhqjNYSgjkZ6sGakLHiv1TQ7tJoQndvCEaLjq1MAnd3C4lj0571EyndIJjUefNS85dT1hr/ilpC60xAc6MXhqW5nn8nRDTMhfPoF3XhuWHcYnDSsgBVHJpjvmoq8HgKuvJjGwr3MPwoQfpoT88fwI8TOiP+SRxkzJZryzopY+uTubpzr01m85kZyfd6Ms/xNJj8n+J2SaiQy/8UvucN4s+ajRsKv0KkCCbwOjH3dLVym45pho2GxdEoHJbShUg6InwHr9dsiFuCsb8TDZE41AbBGlYNQ==
    ALPACA__SECRET_KEY: AgDKgTORGTx+KjHwB9Abe0hZL+5QnU2B3eGwDUd07wUdHrqT6bimyFP7zVEFIVmDli3wPGHgz38OcHv9oIZWQ0aK+RaC8D/SVhwaKwT5ECAsV/wIkt//SL/mhW4n1qaN2pEDegJJMHK1GLzaMFhAgp6hke1GojUUO6DxU4nZfxOO3QqZEwI0m6nPOPgJ4Tn+z6dGIWxJ0IeoMxhI2CL8OtrM/WpJfW2k61JMskkm0JDrJ4GzlNEvEF/AkpzHJ9yu7tEwq9juOJafEc5RiGAcMJ4i3Isl09agrQuoTF0hQO0BB+z+T5DiPgGnr0+CuO6Hvl8jNVBNnUIrodSynoSMKe1lmYyUDWchx16BcJ9DIeYMzLp6s1zVQevumrnFHTDWwgDBkrYt3HZ8qW5/zkeUAPXaW/K2KPHYTG468K0FasXIZ6uLCyuMr5J43UeaGkFtPsvTNX92cEeeZ+OkcXTQqORAV254bjkzNcTFPYHcXWV8d5z9xpAVz3bZbhy9lkppl5vuG5jna4laoYkmaMPar9wPu39dGxiO1oU8dCwYa8IQ5AZWOxV4d+Ql4C4Yg4q1OUVvGYBTd+4c1ixWrVdlzYefptzj0bs4ApH0Qlg8TwZ1TlQiUpXWhMywOjmnNYMaBWatfir7EqKRTMyWXh7AQaGTFOQJaSDZ0SbbbYsrdroobnP08d8kqtNUbxY8YOwDIu/StIFxiV7czzWuVAZwrdTojfoOcZOWNlFu27XBgimJF6tVRjhas9rr
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

