apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgCxcoR8DEzZHXPb4rNUr8LBEgWURjYI+ELbh2fCQYYjon7xGI8++uXmr1YFhFMpQAKAdzlKb03MzXLIFomHIQXt2PYDrBffn/T0qC/083hKjKFOjfZ6w6y0VBu1rPe8Pqat8dvQ1Z6akVRGYU/xuOG8A/spdlujYp2gaj79CCPxR0J2don1BfXYAGh+SwKVPZAxTh81thk+Hss4D9mwyFnGc70m6ttSGgG3RGS14SH1jrLWWW/ifAfpCHpHHRKpNXfFxcF244kXN5NdZlv2FeYVAXYFLzFDoV2hP75jl6kjHQdT6XkDuqD3SCTC7QsGCVaL9uvsZwD864p6ERr9WmToGQaaarToburZMrOLSXrAgN3sEkMzVzBZ+Cc384DYudcuu1Xn9kOqGhMNprUaufS2CwoPDuDOFWKfd8SN/e0ExxO+lEn3s9wekgArq7sR0EEhVRjy7z346kUFJ1bx7wkjwsH6UGedF81h4R+uHSQCB8KLLPhA/U8AGU+5Rxa64ER508GzriUF4qGxHsdQmskB44AJfE0n8KeqPGctohDRFiZ6LJyqso4IH6RtnJFlPMYlZ2Zx2i5mv0W4ErGhowVUZKo1szsvOQzkEygw4g2FdZjcA81MlpdDe85MqayrP1odlK10ZonJ5LOXAJzVK5/i0oxtDAT7zaXOVNQJ+uAYN1SZK/5QGeY/K1WtKFnCgNs+yjzhjn4v8thypTub1Kt7B4XG8E4=
    ALPACA__SECRET_KEY: AgDeWpnatlTI2CJzPPNZzWnh3hXCIToJ1UHjcmvZr7nX9xFHwd5JKGP4d/ar6Rc0x2/Dt1uf+bikZaXVerX5QGS2tIg7saC03g8dnV1VFby+qR/LRnmLpTtiG1PHlYKjoDrbMbtT9NzRBihXNVqEVwhD7LaLy7bfMLAm9UtF2V9BqCGxMXlKXwSRA2sG78I+b1HHupSlU1hk9iGge7P7AuBCstCgPIHW0GXBkXzYjvwugRf+1EzL4HRVc+GYGy8uMtqyvme9wKEgNMYWNyteNHWxDkrE+c493St819UgcsSoxaai31l0au4ory+VSNFEUuuUe8sfBlgxRk4lJb8+OAjutob8bUgKtj3l+7JK4EpWgE2MSVui3aDblziwj5FW+lHVsxmioLRNJs4jmQv7zUju1ayrpMZoIi12zZP4Qi66pW27k+A6GC4vhkKziR2FBXcPK5JhYERLdWLWc7w5NT6jfVC1TeleSHMn1h/Yz/W2NDMgY9kW0qHrJELHg9GEH/8Q3Wf/2AJSGtoTtAv/db8y4Z0Q0Z4baxdS2ZTDl8hDnX+EOksyl4bIGwQYNXyO0NE3akQaYlm2eU59CvnFBTM+IiQ4QQKam0Hrk8P9PY0KDkLSxdojjkp6I8A/SSgSewwZTMRfWKLbsoxK8fyRtWf/OdkL5m7+EHwyyDcwwxovw2Ol6fAY6BfmcPcT9DDnuKhfgdCE+VpKr9NnJgx8kYp04KzVMWpCIVhSx/wpZy25hlMXpT7cIIIU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

