apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgAVlgDvYe4GtCDnE4QHQAQpO5Zd17vvDmF1xnf7rAsj3dlINouZWnh0hKc3GuDRAnQj45x1f7RL0Gwxo3nIKEm2MgRx8kGm22kxeGvhOwiDJI+oShgxPzs32Z9g/A7LJT+M++AE2t+3pZ+UkfE9SnwCl+O9zLkPBEJ/s32DbHCH1/XbmpSBTyOWKLmfp4E/91Kb4ZOwuveiNaiPpKnMo2XLMVFkiFygqtI3S/z5bsZEBl3uamPs5ZXWPu1QVxMqfhf3gELcIuxWidA+HVDWyKWv2IBaPp4+R09GnuYjqXE0kBsfEXPYdnGDhUFZ9samaQPZzyH9K4541sdZIepIRGXn2NZLjpB5x933OQEMANe0OgvHPFi93e/Hlk+vdYCfJsZaqxwx6qiSCqBFsVGE44GJcL91P6xA7CVK5eMcn2QHHte3aPrVHWvJhdkCbjhy9knItnKvKNco0oGLUQyYAQ8A1+DycUlQMQ/a73zgYOEKdAhB5/SMixGdmez2mX8oqp7vmAUK3nw3G2zUqXPZ/tccLPPQfMApmHw9WuHuB4zSUmUFti/65SqEMW0Da/U6akwL2Tr8FAGgpYAl1Wvs/WgLItSSgCLT7rx6nzZvg+cotxaCRYOsS5N+JLZha7J3TVQymSifRoadgu1BxSoEhtH6EeK0W9ifvULyFDvTk1xaY3HZBMNfXS+puLK5EWpwP/ZLSRRZLiL180EenRZopi5YWMSUlQ==
    ALPACA__SECRET_KEY: AgB1wxyUyjbNyh4yrkvWBuR/PvRq7a6Cf6+Be9HOVBGR81jCucLk9jWTGGRn7PxZ7sZd5AxTaEa6145oj8wPqe4tXz1SJ2X4bBHPyIifSCIxrqsAR6zH8n8UIDiNUaHT8JqXRaSBMgMRwAcnxp86AyvbUi8BhWCH/CAsTUws7BiXa87LxWdyonv/aq4yDTatk9KkYZSX4KzU+DLdfQ3Ssyqif7zornqdY/zihxzbDEpgj4qytcx5abMe1pqXATb8d7/Asb0B0MGuP2G9V5HES/TUw2Alv1pz46y3wnNRsr9o2kt9H5jKSf1P3BTGdjXQFOBiNythn/UEnfNk0SlA41qsGbrKVwrQDE4Vs+Z7oIA+sqHSDT+IhEqxBm2Ijm5QpvtrKSmkitW41LBLCXZU4YyWRrPg4FfWUE4u98gZdc8Uqb0O5x+CiD3TwI8rlxRFI2Pqy3VZOlVZUdgsFEO2d0h5OLkLUEsO911/hvsDth2tG2gLg85Pj6U6pVdxtC/VZDj53Q07ITUkJ+xkEBrWeyKKNPLFaLOtT4GpY1KXoWRH8OTJ1I0iaQmijOoLUkpWN8+/cGtSg8YxFifFn25brDx7I40IBMt6C9UlVskyZt75ufdoFBGb5bfp9nAyVJADjcNeWRwTgSeuuADmbU7UXsi4/OQwu6u77E0n+5X+gPbKpwXQhD6hqZqu8+y2Ad1ixGZjuAKq3H7PLUBvSbnlgsmfIk39J4XW7SlxF98x51ete8OBtkZgXGVp
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

