apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgAl5dJoEm1nx7zVwHg54Mrr6WunzUU3/AoTIWwg/ecM0qMTRM7K/R75KemUX/eiNY1bj/mObs0Alb5ISyEpM/fl0aNSGvwhaha2arg1P4lgCDIpodGJEItNiBL5H+LL6zo7FthmtE9sFm7nL5XKkvq8GnOPvsgG+heYPYrmpWCthHT8nL6U/dfvoZKsM2Q0LWb+mTYmvp3HEBeeelfgJw5ks7FLy+9HSzraty3JMSAPY5gtoy3ldpUL2j6E1mtgoqwQjesjOdJCnVyk8+QvWV2CN+I+algqESdCF8uIzOKMltcQK4xC18VOLJDv5GdJRMDloXlIWjje2QfrwYSu7IEWbU6QpszkOM2CKnP9L5AJcSx0AGRp7DhUCRhe4IMOGHY+KLbjF/1WcFF/PMcBPO9AExZu4yj04aVQ0GWirX8Qr8z3DWgb2AoBWJF/L8DXDdRRlchYPxJbRhf0DQuGAh5BEBRp6/2l/sSUVqSc8Nq6GjmPHxsmGM107T4nwuw3sj6IXieQz/detfG69rrIYteWJsUPD+pTaHYv7TvsPYgnDqtaYJvEmz6XU+whpNKK8cFNMyBHIZMiMZMGbCrlMRcnVOi26Yz9H0jnQZdHQLNZJ0nYpPaj+oWQpQeeERfLWEgCXJ7CrOZEFvLT/4CK/lO3oguswsbrYVMuaX/7X44izhWfl6TlDZoXjADG3oqv07Sd3iDuwuiLbSaK+J2by8mKfMjyXw==
    ALPACA__SECRET_KEY: AgCOAFKNjzdvrrbOrhTETOAlgp0yqLNY9WDpXtV2kcsnu4342nNqZVQQnZ4pntPCdEE0sES2tRrpqvcqSxQku7K/nSvsDwiUAqo68OlLHtI7eQQnS6/dAtZ9Fsot+ARZ7CQaiJxRr0zcMcmFySYJQKyFM/nFG2g9/tntWUygB9FsshWH7QfTPEDaqDKWeQu+VpM9hhe+m02RrUW0kI503sWfPKKMAavFzBo3G1uychTymnX/p4QMKmPZki5Du8Q5YC7rVtqsc8bhfbPslwjCiUqPnIhnHLtpL32UGCUPoXzQnOh/MHt3irHhCXuHFT92mepbzlmDK2qUGxVMtqktOSH6kGa8hzMAicJ1aLd/KW3lhgBU11MknBWc+js3x/1R+yFvRC5lNytnYO9Ngx37wdbrUHNsQdy8U5Nvke721WiAkhVOSQECBYEOba3TzOhe4hmkbO4cgDnTlRc7dLGs5HaGs4g1j9ITTLq6lWUAYiDB5KLONsIUhhTl2BiNP8zaU5XhJmytxaL4610Xi86xusHmT7LmauhXMLK8wLoKolwYVOGMBrxM8uQAChuR7hEUj2Gai6ufbZX7ufCrtCAMsBLCp0KxGEDjx+XY6Vb7/UGjRYwvDZ+A1eqfXTRjOcA13YE1BGpd0RYRwYx8Nv427vcVmSgVJ0eNVQEYa5yzqf3m9TXu9I+QhsMlYU9pa4qmzPr84KOxgUfJ93lvAIajLQ6aMGCbmut9HXp/EKriw4fwgwUMX1ARZtDN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

