apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgCw3R2VQn4OY3dTZPr4Ka/sLzb81IURo9zbveUFYint/JonwfD323xN1HLB3E69I2Ckc3Ty4johCyv5vwwdUvQqj8aNMECp4R0Mrlb9SHg9yrkr37s1x5O1NucThH2CSyRG0q4LGmkBEf0kICQKlQSdKRdhKrG6+8MvPYejNuOA+/bdTEJvU/mDnaCYp/gAd2o/+8ZKbDqvxoIf4quwk9TVdT6wnkQRh9OcnObC9noCJweiPmAj1YBhjcJhgz7VuQUM0ekP99mqCvvM7NxPNiBrBpJYXtiU8k98/dYhSU088qhEaaMQI1sD3+KJMGE5vFUlgYlUEsnsuibAEZHuZP8NsfziALhsw043BE7JIPwkbz9ylY2hBj4FbrAe/0U74wjL4k5hPrm59ba1t1SXqkZ92ZCuHhnmBj0iF0XmVstOecmGpC0Bbfx9eHa9ZX7Da2Y+fj1Mn4G6LWEkTWattAHzwSYp4osIiv5AtEydFKWfjBCV3E5LO6AV0MQs1Ow63LwzbyxIvl64U2WXRCRPm1xPtsFNzL/uJm+8CBua9Ip4cUwZHuLV3XfSILU+kZJWa1Y+r4ApdK0Rlx9+0L8Lz6yUvawj2LWnRQ3TMzVqApZT4xhc7AKpaUlrLIhLmBMXIwk/KcB8lMzIcnY11UV5GugzB3ynKNyMixOTQSslCrWNcRcJqke5M3YoDVUwMtv1QrAY2TXRpz41b1Emnfe0G6VoXYI17g==
    ALPACA__SECRET_KEY: AgBTVTR5X8SWOwCLyfsAXtPMA0FhTOMAjKWIKqLYxNcr8msdADQV9q5/wRZB/SsjeaY65hi4PO1KU1dipAterUst/1OyYMrTQqLhR9kFYupX3B6Vs9VVqGgO5TqZcWqYpbpQjevuvcduXh6FRoZhCN97vVdvTwj3TRfxRtOMGhMtdx3qSKk61NQIGgyRLzCJrnV+WCRsqBTE6Rk2crZEqyz7liByZPDIQV1/NZF0yAIqbKvitQ10ib5j2T1egR9qNnEUlAVAgEepEx0fmvEu4tQS6WGDVNj67p2iWeSmHdxMRxj232P67dISzPLTHzJVL6dAyq5+Ty2L32UweA1z3BUHbJ1rJHE0Ke/hWF1VgHjQ3gE3b3CY7YK3Wqr2hP2Yj5Y2PuudF8fo9nKBMC1JebBKMKpGWSpShP1I8BGxMPI7e6lJUmAmZatmKIFbXJrePo9NaUBQlscNAzupZ7YW1HQeitTrOytRA5hCCGYd+1aMVRXlqaooBRcCv2S7aCH+ln1Ewo4PxHv1ww119+gvngIAMlkYAzvSjCXRJ90SNIHQA6Vn5HF4kXnNl6H0SlS1AfoGAffZQ6w1WN7291UNTdJSrA/XWSGFPmIoiiAzSULLe7N9WVdTJ621mirv/+6SN9hlpV3BiehSwMe8QYTipt2beIsmfPyEDZLJGzXYobzigR1onJl6LdwmZrGJXgpHFPApSQ3CXRAhwwfjAdPW3GwcXyKmG+yaAngAazClgAbV0cKksmsU5EBO
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

