apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA4RokPVAov8wJwVmOcqgPEpkEfWRxIMhwAqXT5K9S6Roh6mch19Ipe/4MceDjUj+EfnH1MukrdtPeLctmigvcaabg7rs15wCbJDIT88mt1r9RRRe/jHtqYnp8a+LS3WyS//1fnnX6TVh/Ow1zoB2MqgH2tV2EOdhPnlWfqDK2MC/gv7VUYyT2sj5sD8SD0a8JoeCSNIQR+PfrgFtToRdIrdTMX5SrXsGmUzKYAJgz10pEy7YQ4eF2lq+kzIjhQAuwtB2GqflHBrOjvvSixJJYnPXQhJF+Imb4M3yOSP5SRh5tNY7w9blvrOPSYmYiqTArFSP76RamEtQRYCCtDYbc1Eei9wcvhvAoz3uxlA4nEqtF8Yyre5InLxMpk/eAUTD8Ot8/gpMCodFvIc2sNZMz+AvACnUOn1enXFVgew2jOdlXwmG944kwWhhHtHJBV1foK3OO8X8p5eqMrXKn2Ql5PAKyrV59CmY6H0LWqDGZhH5sW3RcxiKjm2H52o69ooNM4qIsJaE/l0t8xiv6c6XsrFnx0VC9uK/Ambn7ujX2qWg/bXwob5BHHamoIQPcbA179X6E4L8+8NfMKP+2GGQk4BjOlZEIAIzccOU5dCBrOd/jm3SsMmlc4UN5gaN5rH+qkDPiAkYQPtGD4rXpOvN4/9piPzajhcGF1Qepc5EQp7aju2BGt7bwALKAOCbLusFzSVmQ7I89Kkor+rknFDQh4EB3OfQ==
    AWS_SECRET_ACCESS_KEY: AgBRRjqmZkIWFtvo9WjdPmPeSp0+Ld4Zt+WyVafREzyYPkcJyCxbsUXW1T9wja/9/AroxwqNh5raq3uOup/ZMBA08EX1tboA4ViqHpJoGXdAwWK1Cz58pMP33Fm1SWEFW0zUr5wGVnSt3m9ML3U941Rsi8nuFX/rTpl5nLngy8KoAKXfMReWMHrjsT1ay2VWeGy2g3q6NYrK6I+ofi0N8A1Yn1KKb3PJBAg1rLLnmTtjc0ugGPF/qUbWgkgRd0bnQGMaFkzUh+BmEfjVNPb//XqPvxTl6VTrmQTkzk1RYi17cuy7OHPnxghJBcya6fy4H6gJFwgA7zUkrO4TQRyLCZSKyu7kzzphOZh7YYf8rMmIDyNJbE2iT3xNd0s2Oumz9spLZu3Z7xUpDM7SgAaje4sUzmBVaAF1XpECWZZkTCtVHaZCj0GhDy8c5M3nGpsHmsYXGU/PvH5PfqcdhehPCJWk6QYgM7N5uQD7Oz+xuoCEEoVopSVsPP7g5H/q4SjX1PuGyLVMYwJT/9SiIyzxSHtC6cLNX78DV4XwR23KBGKUgNyDTPrdXwzqIRTR+ncFSrkNHqUjOBsEdAP/URUVcSCz9ZHofKtTpmZursNfJOO75Wa89xyobZZaE/OLqvo1vrVv6FKW+85Afjr3s+f67sIqZxgtXVUlSs4SBitNb1SCHtF6o/45O/v2uFkPrUjN3apevsQYVclzTfuK+yzkoefY/mLcqRa3pZJDJP2FKc2rwPBv1k9r5cZc
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

