apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBkAwwflnqbffeWJYYmIUQL5HafdPisbHHEH0T7DIvoAY3CHEO1gakj3ixe91tlKwIaU6XQf0RR4ms3Zjwzl7ktde8m4e2dTNCMTw2w7MDnABBXKZmElCfUghEZxwhvKzRYzODlobxmHfOmky+D6QQy2QzdpX8JwrDOf295AQOssdbnknmAHzD0J8dz8SaNknOvtfcYHy6E0R6gzjapTMPpQCMpbmxyAz9lrLpduGWNx2HULRVQucHsZ7x7kyfZmbsQ5451px3kGUPohwyiao68MbKRMgtoIZastKJHTYbliqk8p1vN7R2YDvIiPtlsTe+Y9DQ+2wfFfvltnOFSlIMHoFhX+cPswmUNqdVbLS0jWJhohT/oovakB6fCzJZW3ymD/D2RVN6iTrydvPNGf58prOgKcEmJlN2xAumH3EuVECeAUCyMVVxZ6vHOVR7Hz3bF8yvW0ofmXMQyTt15Q1aUas2A2v1ePz9mtzqsr6PCwRwu0jzUD+wwmiJsBqGBd11gxyEJMdyDLi86E6X3fRCG1jRKF/K6HB3BvJqKKPTaMRk+ogiWpTtlpfht+SgMav/IMdfhYqE2NuaIGJ0MzsErzfo4eJHDHJdknafxzZ9kJiHirUDG+dEwMwANsESTcnVWDhYiaZ1j9+LfTgajPpTa/DoOOHncaDd2A6NN90j8WzelG7V3rdbs5Bp9I/Ta6ruvHeQPYx7LRG00h640Ruysq1ADwA==
    AWS_SECRET_ACCESS_KEY: AgBRvzC+PblzDErU+/HJHZ3EYweUu4faLQpX8xcqt1hCRNnhes0Joy4VEBykCCP6iO6Zp8CNyME00J8/rv0+CzFIM97MATvuodnrLA2XF6kX+FGywBaBRjEQnneVhGGo9XVOpoubCLObinSEaN/h5WdIxMnqbtGkw6DbzB6C8mJxPinqa5B9a5AAyaWy5zeoBBCNGWMunUYhVLbQRwd+d1uNX+ebENwSCq2RJXyR2/aVYk/OfOKkeyzUJe8kWowRJFJ6ezINALoyYZp6x9s1UT4TsFrXSbc9JqG5qIsuGoPzW9s03sqUZN0mEYDDngc2tR48zzfQSC8RWCBOvUdNqbZqotzD+c0vxOl4mqejXrzysTqupCbtTeKyoxAIZ6hAt8HLZo5BuDdgx0d0I+3BsZWgiONqQE8SFCUsyBCwF62gka6fFpq003sUeHnMxjvXW9i2GjvRrm/O3+KbfuvLrDI88GhdInPTj21+kBmwLknslB9q+I8mq8J31GTuglxl/p6XQmm2vnqsfXUCr8T4uaya9xQ09tHRuc1WzVNxnpiWb1ZpuKSFQA2K+mlhu6Hfy0PLN43OVmtj08KVz/aaZDZcJKfxRbsqpy40LgJaNuqy5ev+HDBT2YiKPxF/sacE8wBrf7A20TO6v2qaL4C4eltCsdAwGSp7gM8PYH0ycHDx4L58ghyKYgBqmokJiMh9xrg5XNWjTrjsbt3lAMbHNVT8qtYzGS7D6Cz5/2Dch4VQrS/v9BnrB+JY
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

