apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDNxWs9LyJ+9i50PENFySbg1aqOc2YX/WJVllZvMke7mIJV2lj5DIKlA5JTsFFAkJR18Wu+8awTddcOmIExlJhSlI/xtUd/s1o9ua7e6y0LW4vdbfZ5yBQOeXZqiyIeATYT5OkoCdKNnbgturGZq41GzgEs5XhTEUxpLd6JGXCFwBs2ViCJSOCO8FgjAovUhUR4NDPqYm9dAWi1Tz6f3LhUSCri5ckmx0uJhKyRlHVYG0PmuuvYoUoSfYSBHTYrdmATU/eRCy2qoV/itGQskS4rQNBlvbegjTjH+Z2RAzvSRX2Mw4lQJ2+easmbCfoyOPhxeMAzOx1f7foY2QV1O/QfoCqTw87S0t6bQKQeynBNU8CRwgZthTB/cZjutuzMeRF+acPimS9Y1y9FfX6An50EaoOxJOMnAcd80u8TlP7nc50FkNgg7KVXVb5FfhlZiUJ7Ih1EI3eH2w9jF4o+r0jZCxuLKnduympfhzuOir7ejN44jyVTt9EdfkrSfXQO6DoHc5wPgJnb96tUe6LXQKeQtAeEweyfxn35c60iQvGWJQ/aUxmqZrCZsYFkMAt3l+lWsjqw0fDx99G5ltE4faLdM3dYlcVSwyAhmx+eKhJZMac30VkDh9gjtu8iLsTXtRmUWFwdEzR9Aqj/1eKuRaT38PpMMyVPcVppBKQ15OdjdD5ZwRap4lMRZY8gNB3yGVaDipq43tMg8t++0WoSEdJQhGUfIA==
    AWS_SECRET_ACCESS_KEY: AgAXDlS9AMfScYEsianUvNgy4JEwE8dfYLf4usr3+zFiJuaHGnnBIuGID9WmMzjutIw/ryVE+JyZVhlCRenENocrUlurqt472OSeYSKDsvqaQaX34jok3T3XIymL2hUSV+I75JZDxrvAh6DGoFurS3lKN6nmaWyVWZyjYC8PKhkPthh7wbwM9EngnjEVEkGbm8PCPgjIQzM3+CVHbdJt/GRPynvrb/jFm1u9fgLrhyhh/AmxiUWcwcTuENkYsj2AK12eEW0/VB2UE8OD+adT7y+lhftpeIZHdl6hGQ4GvY/KNGx7NveZT6dYNlZNPlZl+Y3qF4ISW6Obnkn/FSJrHjlu0NIZ1Oy1jPc9SiZfI5oQw7AWhjWYgM0cqUyqt8OZ/JkYzGPjg3JaIuxOXidIkN6TaCCGgfNvXSVCwLMGisggYiwGqP2xHFqLnbzGYR6rUTIABJNUPqQvD+HPw58usMLwmWGp45/c9bRjjiBXg0VR26oEyrbYuoqq1vFv5ob5mFCWKBHKM0cpuV68U4Y9RZPY/BtUzGjcI/RFejIKIxy9Ompd6Xa0PsG0VJfJjLEHNY7QRAi2zScnmPLrfhgaU435uV95TLeB1SuamGWHuqXvaMoa11Caj7hDZd913SiPWn0fafeOINIm+e7h4sOHK7t8BTnYYYPClDsyD5AJfs3H9vo8xFwzTIqXjBMD5sdWZXZclAsGMgaa9qW83gjzzG3aFHOc0pLWEPBzifk9UDp62b/i0XxgdQC4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

