apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAk3K15Bxv2fjHGYobF1bs0G0aRR8H1RG0ga29L8qOYJpBGdIqtQNCBPimVlqfIiT9scyr3jJVBGmZSKlkU+ffRbLhnICYRUg10u1Ur4lFDdg/M1SdTzjbu0Zvm37d+hhv1N9ZS8AkUfV42IaPNiR5zqW+GZOwpeHyvDCin2t+Tz+daRPFfEgVx7xsFh5FyN40vNUpAuh6ckOPUQA0cNcD9/BABCzDfGTJ7dUY/fs24QTaIiDuNj712f4GClj6sCghGy1mLz56MOrx7RfS+ybGM55F65wUGNjSa1M/M0PbxSW16doWKdY4Dq5CSvR/vgaJEHanzUQJmynMXETP68sZzqLg2Cs5nGwvMaeNSQwk1EpmQMYKEC4a70N3jsPXLnzmQxJB+BqcMRMe1vI+6BU/kS5M1OlYKSsXMpcuuk3heU6okfbRbxxDef9LA8dHXC1Tg8G4F0FjVNz4U4Nl+PUzrFdT/CUZEPht0gkK4OzdGtgkL7IQtR7+qpjOPE4F0WNNK5RTCuXzwMF0DG1n3j5AP3yP5xB/SiyR7HGvwiT8f7GCaKFLFjRjDr+JwCEfyYJVKeY1oY43aXKVfmp9eLYcrs18Az83yy++RyIHG19s6EBbb+DoWFoh4+QRgMLIFrlrp+iW9s8xTNQvdLOoi0fWDUj4f6tznmvzYsjahb2bJ6aX+rxgMJGmoo7rLrZF6cIavl8qF//VrD05ooklVzOxwwwmmZA==
    AWS_SECRET_ACCESS_KEY: AgBVenHNR9Ik0ze7Hs/b5H8rH127wbQpIGzGqN02L83r2+toRYT6fsLVeWO865n68EvKIkfV2qsZxi0TqksoC3LMut1G7xux23fAmuoa353Ca00dUbViNF+cT897gZ8Qim7TiCqvdmfdqTlB/o5MQUY8Dx2oeXBJ+1K1KYatdn7TykDmdnEiuCcFhjJUJcHVAxAusEv0nHV5LYP3p5/i3OQI8kjAnV3KIJpNBdWpbteraFJoTWYv4p3x7JZDFcwTWuEIgnCsJvtvnZmIXumVNucDYNqUiQXeaxMQ9mRkIUinpV7xRVde6tzedaPqsqk5nxJg0GiLY/9V+9dLVsWnhcWO7IwU98ncCMDuvDhlnDGWeRuXcdmxNK4dpoyeIz2A6/nDBRFUuvR42C48nIdjJehkmeGBG2Bo31q8zIpbvQYJ6WGZiVtTzdkFLbll+/SFfsCO6Zmh+oEbyfTlQ+K+MDsiqnDuboopBf8eAbFRgbA5q6OQyAshsF428/nqWJQl++0hI/7SaFUG+OqvNJFvbArnhgpbW2Gl35coUeG0P6oLzMuUOziGp2924uweoMNDPpPFPoUI1IU6IrnCHRWcfQjx7/Edxk25XMqBmMYWHOOUQ1pU+XY5zj8xOcMR/DwAJlzy9RhUFXIDvvzZGhnKJHinRdqdZDkr/D4FLZqgPpwpDvwMUyJX0RP6UfADvzk18Xly/h+mWN678pira4JJELyS7OHJJIXqMZ3hPuKbAZ8kpzRbWgYZq9fM
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

