apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAYQMtVs7ioW2kTb9qkQrzRM/HZ7+wCtiU91mn82D8nhwC2xLW+Yjv09ucefIJhhvZikS1+ZfnBbuaZuPdtU62WN1Ihulf11R6VZrThfmLYIQquWUwpSEX2b9Y8BYnKLy73+/T3PP4Jo3MzdTfsOFgAdZmub37zJwf4UjnvkMuDQCcV7/qU0bapop+jUH0EAyFvRleN07/2PqL9+axHg3OssIoRnrqsSk+wJbwgLZGWHz5lnNm0nRLhYaYPxg98UgnWdUAYrP89XpPnkTilwlYu7OxxU2PMegRwUDtZ5dPtlfjyV4WG6+m56KGEAK1hkaKRt5GpIpWBD0UQmcJ3AZdbwFXEjKGG+lCUQqjYCPtUY3zLp3r9Z1H7Z+Tk4HfHqRulCSJkqLOLAvw3M2M3qO/OMyPxuQoR6qWnRcJFnDDQ47itu7dJoGITBkX9sj9xARUfmNjZWrqdyh7B5RD+VEdQwRVCt8P/EyN4KSuX9/v8E9O1PzTGEuKxfgOjOOyolCSLyhRtCtwqTMrxUMr2VwrFTb79NTZ9uDK27gFhgXQjLzffLRAfSBF0OpE6uNykVKf2FtjA0YvA0GuOTp3vHDCt5NbMbIDO2+oEoLzkMMmErawkWzpJQ36IPY9zULEoeBWKE2izT+i+ZAMJ6HwR0KcxdLKUKzBG+zIi5cuR301WNbgTTzi2jIL1vgz+OHhoa2bayKB+qb2BdUO6smV8jZP23EXt2g==
    AWS_SECRET_ACCESS_KEY: AgApEfmuGhDkC1TO4Cv5Dcp/o8F8fuDtzkTyVOkFLqAOunfryAaRJiyfS123DpOpmyqgUjgkwCgA1hgIddVzcu41OtO8pzPy2T8Ntxo+M9uKJa0KsC6HlmCJ/oAtjolHiv2HyIsx+WAx0WfQyAKxtGNAvhS1N+YG5UO4OciTe5S+D+h3BntmYBa8s7WrfnwuMFjrY8SgV2xgBiovxA7ttygVfsy6Cc+sU1s6RJCh2MqBSM3pRdEsprIIzf7cQT7cc1rH8xU4yTpo19Wwa/SME9sW9CVQY4VUGCtbvrBAdhzZGAdMiTOA+PKOGbfMDLaxop5rCWC5JeD2xIYMscpZPBKx9XtMmpVphWb2BEb6Tad+YFpRO6YuCRL+0Xl25I9YIfsXrBfwrsfdRMQSGafugT0OqKhEnwyRWvpH3xXW6arri7crh5Aq03C6jb60osrIyWnHfBXMU86JEWeqh9L6Kd6hviqiQT0RCpUPh4oAzPXC9pYnD3HMPJUlmyIWCu3lBhGYTpu/I47aNEm/iLBIo1UXCEadf0Bol1ISLChDoh/g86vUUshoqJ31fViuCR/vm2yEpAowQmLW9VrafHy/a+50wvoNMZWGeIkhNALAeH8fgNvzGL2sfhb2Ae8ChzB2tz3VdD9KwDEKT9BS7qDMzUvFvpurGYG4ZWvtE8DaNcnC5RtWJ0u7uoBuu7In2YXT3OCcXPK2ebaLdEVaeLlZR4/I9Rdad/3SpBWg5YVl5qAxya5aJ+IKLQi9
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

