apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCBFzP2ghnMMDC8oZV2EMjTWSuSHzsYqoR+e6YuXd/riHfiQgamYgLohLNUhgEqywDJ9wIl3XyuhX0hrcIlxLZ81B10WNbT5OUm3K5CYEko0+KGcxXkvMYUuAIA6TmAIZpu5S7qv64DsreGVwrVL1Am9IrD/HxOdMKLPaYMOwhVTjLsPAYvQedShqMs7FgWMycEdFc9uTo1fGY1y72N9VScRSQ4M9Jq2sX28x/r7xFl+uPZwE4g+0Y5kywFyzMAIu0UTIwNvQCF6ePoD5MhDjSxM5O53i61oY7LOSiU85w7lWx9gwdgR03Cq5G3kmVvv7IzSFuZbJpi31QGl5U0yJR/adOhS6M3JO13xIQ46Uw3G/59b1gLKei1fgXfNJy1111xDpSAUAdbOZJ8b/13vy3Csq1gsUYckuQWqyrXzuGpw2JkiC3M89FbI0YwuHBRqUuATjX6xK8go72BYKockJ8r/4mLj1wgdroxO7XAWQEflD9j6ctYsZppDvN9jPekylv5sCfvQZqU8NXOkaCXt5yBbfWGMXj3w4bVNsaN9pVTZ+zFFpipIHcLrD2oWSq6J5IIhsFVln3NXWO7KTYuyn++oQSHqPgQYP2ZhKTB39iM6k/cpZ9LOjqpbP+PFw+fEwp/pR4j/Z2Nbs/ZSAkJMGBK+KAWz6MotACi6YJ+5l2ta9wYXAs57IBzCgIBeHDom6n6I67tCJjIbyMmm6voPQHkXgPLmw==
    AWS_SECRET_ACCESS_KEY: AgAIi+80kauPGYl5HTAk34ED6nsQma+m5z2lQkJ+7YfsU6uTGBBOnWO+rKkxvP6Vr989wca3Hm6cJ0A+Qh4C7p1c73dNJdtsqUGisRVxMU6YlnaJObC8gqm4B12EGxhrncJkOFkBATT+IJuD++vNoM/xntQZ6conOQtUVi3vTIeLJcDkhTNqp6wpN3tqsIYRFfd3cD7xqQU+kYrmWI8/YoK6lGL0w4VqcLEXwsD/kmdYYKsxyJLgvfUakISfAMwoUI+HrneE8ng7ji1IpCG953TM4ihU1w9J7G/Ivy7wsGe/iIllAt9kcnWc+P5qtiLy+bK/EtILAc7yzKVNCW1DmsOCSY3LtoIo7Tm8n/hGKJveGUYkYeNsxGcC7/9boyzVNsZjlokZLednaTSskC+bt4U7xbvdDJq8TuZwB1Y5wySFhYbwOXC8J42ih7F22EQHLhm19mW0UT9cpNdxFW3yimg6HDEaBGFF0cb4jWIRMUkwoIRRfAJ/wLe5i8marKeKy0V+g8sEqXoMT3A0KioFDXS/QT6OqTzBYnU0v42+l5RoRyJuW/77fKDk0+GZ2sNuJzXKV7e4oFFdjdJKlT9PZUyvnzbHxzHb85I70imtU6v8anqrBiFopcYdQ+bWxtQ36TxC92Fx+Ske7vupmTRyvU2Ek/Y1sbNpuTwu5HlJ/bTgiexPP1nRv4RB7lB4594pFb3Uns+KQeKfJH6z02qn4vmJNzAsNvg2MaOlXVqAmDH8uwZgrFo1VQn0
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

