apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDI9c5C52LO+9msB3OQ/um4ZjTIxJfZhgp2E39es1WCe17i4JW+QyJvSPGRCf901bbmLyM0FqgSERgI7VL7+gthmyS0dwLhdrSHn8deiQDVmrxe5lP8U97PzZZmUR5VhS0eywhPYKE5erIBiQX7sbBOlqz3q9ygD8Yw/xgDli5ZVmsDUE5Ym1jlid9EJvQu16WNfZEfsSveM8GhRvIJ6pI0WvaxvMy6TugyPdwpAKbyydzh6PqP+bsX3fg/P+h1fQVCwummmZCMl8MenOSSC6tXKZlWFrWXuzOc/mhd29/ClzXyuXdLX3q06sHUkXZl+Jz3RF/LOTt1/NNKzEokWsZqlHhgb/AvDvhT2ApylO+sZh0ERSeVS6gNTFSzhmwYxZcIOkaGuXTvyIR3w1d781mXfQ1t/iMjKzR24miMrG7YYuxhHrGKdUz5E9m9RbB6OWfXvM0SqncJ8rGl+jN6XmrCg1zP7kpsKl52IPLqoRhCR08xK78rpvR9WsCj3aGTCHqSlWImh++Nb6ap7rhN8hqSSRWoskNZjpXyNGkpduGIJ17VeAM7++97jEVTzIw4fw5bBKH96YdGHdaH1rJDRSet25htu1NHO1onumrvx0chZhtYKQBPHXt9UHqNmXbkJ5lcN0XUSo10/69raQdDVq0NRguhVNV5Od/B5VRyYZIVV5k5F+IiNAnMxjt6aJl4c/PYm8F7GEA69WEbuaHSPiQQkizvMA==
    AWS_SECRET_ACCESS_KEY: AgBSGOAzkrse5gDiDn2bSRKmdTSrcJS09OkRaubsxTez7eTUtpNOzhROlc/LaVZpb1YAOh1yUhjYMDq3YqtiwQFCE9ujUTZR+4q4e9dm91bsIMO3kBfo3O3x8EzX4LzpGy45/tWiqvpu/sQcB2u9TFBpGT3FV9D2gadWMw1Xr18R4WpLABicbgc/DggUg6BBW6Kdr60gOTI+g/MYS+LjBma0cCBdKhkGWLmbRqLPuOEctl4+5LHE3Ym4uH4WnFuZHPOjxAttCHHDyy0VjRrZXOUTjHXjgPFVhs2P/hmqiZZC+kRDoHYh8uVCwtXRrM+QwvLj7ns5G/nTzDGaVkND7gAqfq9dkCtO3HGC4BYbrkAUr159EvHlbTmMh4sE/tb072UrI5vXLbg6wnkJocR6BnKUg3sQS6cXArkPUFcm82MD1PBfeTSVXQGXhmxLkPQ0oI70lXlnb6URFuHjvqXB5OU5k0n7+Sl6rse1F7uj7jCEFFYX8tu6EALX0WaHO4qCG+36d6bUFH2UAI6rNUH5GDC153XNL7dd5JJqJVbAs5zUZhM12Bvmk1ascd9CUdygfXZSpKTMx+WhB4n70phMCa1TL0zL4nUlYswVwbp6bJc9fJ5e+jr4i1adr2ukbBjvtdPBphOrMHw9o3Xubq9a4IhWQlEg8OYQkBlL+dBHrnHm90fgLE788aBA7gNh+WxOxKOrJPM0KPpbLQ+6yX1RN8xMlcQ5vYQco/eQuAEsHjiin5pm5lpvsHs2
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

