apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBD3oUegbpd5nU1IJ5dhuCbS7auNnjOMbznu3DbxV2EHTtx1byz6I4kGusKe4CU/3hTUypCkqAImhNN8RF+Sev52jX+TEAQqsrUzGYANMIzw9BSxkOzAW0Lr1HisDOcMtw++x3vjDRMiEaSD5AEJG+nKK1VTj8QO/0TJg+8PsDPdb8OM2zsYuHUpv7+WY5GqFME7gXfvL92cVR7FW2rWFpoX4W+Ol0M5u7Mp990f9UcqwdNFK/0MvLz/3qLzRe1tSAT8tcA4aXP8frPWLelVDOmUgExlGAVN02dKV6/Qpb5o22h+uUlYKlRKn9FJ+Th9/iDPvm5bZGYjONSr1/DsEJ2WPdVmVLJQ4U01aIzZu9iY/5auBBfDNKwLSD9i8oUQDZwTZ5VG0vGF8VXa0vhnAzAxoERKefnfiV1tQbCzFnT4g7qlFGYY6BCg5jYrm/iuYceOFC4KNeeJA5n+q5I1+Ikujc6GzBuQID/498cHtHFT7vnTQLHC4FoBBrAfGswhuBMUR8l/Q7LNjqVr9Uun6OSQD4zega5uF4PU4P9AsqiAqDX/5qPgs7/LzdNKYx1OkUe+3+QCueLhGYudw7eTTJpSDvwzkzAbcjoiNBJVq7ZROsaZJVRyCv1WD5BpESjX5usyCsN2iJ3/4/xkgb9aJByp971KtL5cHafJbMr2YfaqSCcRPO1Peae3KMQmu6WkRPqAGw1Y68jMgr8GMH1ADGyF5UVXQ==
    AWS_SECRET_ACCESS_KEY: AgCD1kl70j35wi74CMewjGZiL9P3B4XY0x6m6poZ5koPtmAv9si3dG9uLqVhVo8k/Hv7cpZ7KAlgtVm4xpP0f0AJ+8OAgXmeuxKSS+ODHhK73yy59KM8BlfxAENYTz10f/6qAFph9WqdZpqn78slWZ/kzZZ8N6E+nu8H7l2LBm+md5aRLdditCjY+4pQUZWIfcxJkaDrUMdSeQWEh5fPvZUGqXaAgsOCgCcDyO2AKvfUyYVObUIT5KmVGsbeH1G0SYQmpEV5WNpAuKN5TQwvqKe+D0i4sIvzsC3urOi57G9UeR78TuKTd7wxC1iy+AGwwmJNJsctZxw5LHCuumSdeZWatBuWF3Tz5f1zrkilnLVjnaLKcPhfnhOpPkOqtrC+4OcLZN8q2wDXkybOoq34/w5cz/6feVGFOo7FdL9kE8wSQyik3yI6KAuxLS67TH03zSsha+IV77sYJAmexmrCLdxl55SfpytT5FKpAPpv6RirTqVIpU/9JrKJy3UvXSd0cIuDBGljQ5o0LuQhtdWQWOLP4TSAaAkwqJJL941L33Oee+kFg4qvCVreKqrnns/YlfqvzU5LtyS4GZ1SqxnxdVoR8ACmWAn289e1p0Z6Ym36m7aZKkJh52TT6syUIG91/LQTjNpD+zn1cKACKtq5JPgnGkKEgeHpBG8FEC30ROUt3RmheozBUCKHlLe47au2vXigy/Xsr2VUGNkOSMehLOb+Y4qRL54QAHp/rSJ3OgvE6uU8PUF7tq/o
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

