apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgArnwQ7CVILNdTiJlKN0/5DZUbYW846H40XoKV6iNkuw7716cT/x7cPm/BPkRWXxSs5Z1WlbVnZduGMczi+3ha5ySHiJdXd5PPZCQ9ygrE48tXQ2A43B2iMjTwwS/drxVBdqa3fCgC5b0ntTMawmIJk94gp3R0uH4PDKGhCT4+M1BKMFv3RavNJuSpZ0swu7g7TVNVXTsMVRR5yxM5c391lx1fvGZPnEiWjdgA3BCdT7EnRbpWlkpxLJjDtyNlQxWT6ymlHSK3Ug23rC06eJkj/7GGQwmjzaHxrgd4gmNTGV6NtvIt+M8sEFjpli9oyX3Ozs4dtosNEKNH62xTbh77LNcvjt4IaP2ALs/rW2biGenTNV5vqTef3zoB9m1gJwoBf9xczRCjTEgd1uUV+hLwyAgjwhE1cTcZRdMk/UzxGYW8aVE/GktnEbd41UYQjlqRjQTjKKXdHpj7mj8NXPB0sYB3V3VHQLzi0/9iiwu1mMmfLAjmemro3ZnPnt+x4XqK8Pee/H2J0i8NUW2QmjJltNMTdaCgiHR6Fm5FCk/WG8CC9d3rkRACxZWSPtZTzxj4uCA75dk45QRZk8eOFDCCC6fNjpYuDML/P3TtbpNleEADTSdP7lhKicmfczfboUp22k5f0iAwICHVOGO81ejPrviTTPy1YJwkLuDfbw46VE4d2M/0hmBmd1QtnEpPUX4l5+mxyshltTBAaHDimI1LSPM8hUQ==
    AWS_SECRET_ACCESS_KEY: AgAnH1p9MClXwjI8BILy3cK+rcRG19wSY38oVKcWP5hfUDP7SOht0oMGUSawxWMfJnLibsuMZt4Imy9bQrT8jxn55KsutKma89YJYsnEsHihbgKGGZPNRCR3JGr9IRTGMyKN57JhWea0fu9qzRnE1uWVpXlfKYnYredmsna5dAcYSHC4j12HsjuqLSgIRf2LHLYadshXp+AW13PLUs29Mryp82JxXaNdhmcAX2Csz59JVk6FnoevZZrjtcVfgqCMv5p+us10OFWS9xvsqCQzRnwEBHGIfgZtZ2xigW9/5+blE0KtDvqZeX+R0iHyLC0ANz4Aj1CnLLUq4PdlVQ2yLKxmqylpHJ/5rVy9R8GvNAFjOZYfXZttP4LBME3VJKUr6V3ad5pXnua3cMXyuwndc4iETqV0d47q5ijSg7Ynv37seRrAp0PN2wmcVvqcMPwSNjfqJx+D+M3syq0ErzHaG/AUjy41WaZPKIKDY2xzMbiG2I99/gNhVqt1ch91Kl0stwFaV1/YzrjqDRLhtC2XSgAo22zRuEK4m8SbfghoESliC4KOOS2o97Zal9d7l6K6tZrkWzZrsD8Nwlq4iaV2B1H3HOodqUeCA0RKjfv0tBGnjYgSXPwhmEyHJMGo9eBBZt1DNaAYycIF+EWvTeg5LHY4xocI8TWTs1yPH+JdAO3zwuI0R9sGOuGbW53dY5UaVu9kNp80DknL0Zlv1MJ1wmtn6FnCfK88dL9R3IWNshvwKqFhFzW2IsWW
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

