apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAVbtj5OnwxMevZX864syudmwuaxkYIJDy7vQ1dVkXAkB3UjtqNu/5Yw2BxUYVB59/NFmHNg4DF0unATyBEh5+Ydq7196+6NbPvd4O2rL2zk1r9lqei61nlYppOIT+8ytpBRKqJRCZGSpD+ZXIjd25F1GOoKRXnMkQdbBX8FhH9z4LDcvmWIF87FQHCaA5tV//2VH7wq4hJeLAb/anl5hBNjxbtnah9rddYpZhglaLW1qRliuPxOILz0ffp6wZEh3WO7hReVs0X7oMGwXaZw2cgOlng4nnszIt+YZAkr5ZQ1IX8Zgo0ZlHIii2UCNvNM3XEhGkVtmeqxtLMVEmZU+2wvR45niyJI1bcy7e3qVhWctTqiHytjia3ZgcKR04ijR+QEHsSv4FRkcr4nsBtdGTnSw3Hkfm3RIdSId5BAPv+SSRu3c0ss+gpGLqiS3QXw6LqxBb9JlGHy19bpfmL3U5NMHT11CQO+A1Iq+ncWomTZJ7QscFoS5e/3EPWsWanbiULaH5JzyABxvDmstHBF4NvS4XbMNu+2LJs5QeA2j+pZWATreze5aIc022SECsdTolXeckudU8t3Xa4i/jMIIjtwYFytj0TgHGImizaAVaaxrGIhakQEp3nWe64P7BkboSLviS7GujIqPnVOXOs7xzfPLUsBiufFmVOyx3EOZ+kxzZ1zapEZp7W2gsRCWUxVRFKJu8zs6VgL41/fhtJ6QWdT36tMw==
    AWS_SECRET_ACCESS_KEY: AgCqeThz4G3tBmOlywdklZqurmAN7HxvoPIpOCE8JhYaN9O8K+mV1XXcvbdlQMfAZL7moGg7/fL+ZKbc5J8MbWtWxpp1j2cKUdEotJgB1Y5owG2Nvs0Hjq2JQF4ZjNJczzXuUqZJFyfctTCZ0UQTR/+DSDmCFDoIOLojPC296941IW6Xy7P/Or0BTov6ejSpmUR8Vbc52OpQgzveorcay/IIsedA1LLoM1ySSjG5+Kfs5uxqUVmsLJhkV1clpMQrBYuab+e1G0xRysKS3FmLkgq0y8mQKL27rfRjd2cFxcQeqV9O1ZGlywJPb4fvU96D4wFJ4mLpRgB9+0uAEzYqZ03tG34qNbK8MavlJfm5zVp6lDwDGm9imI0EG93cHuX2k4ARNphm3OhWd74eIS0/cI8BY1s6Dhmm02lgsqizcIPmuHm/1uN2DwSEnDTHM1dan0fGGu9Z50Snzno1gnCnUN7pFhRwQA9XtJuJmZebtYeRXQy1mfM5N5UtBmR9Y1qNmFqWcUTOIDlaYh9tIrIxHV2qIXUhB+XHqFDyDOaYocvqExYEVCjWUaXeouPxjGJzWq7sQUSxl00js+tSjoHq0agqociRgJAJLlfuJkFnzFlzy9zaeD9IpQV7URuk4RikicAp5Nh/2blsMc+qZwnKUf9AyQ0iWX6GjkRxpsbkrKKyTrWjn09Re/KuARkg17kpLFIYX4/MMp1G82Irbb5Alt0cVRFBPlU1FQIH/eO0AbAhyVqHEYQCjktu
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

