apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDCnvpkH+kLlTIRVZIcMzBLhmHP36CQ/4qTn7se9c4/0CYzG9k1jFC3LLfMZ4Zu6HslKTPr3bj2sW5TwfcWgmJsuaX8RC+r539sqeQfRHw3N9Xw82UzT5T8SxK1FgcHFhNpnDhekpWdNoSYkYZdPzpcFmJKXvRF4glrmg1WPFIUymIKAwOVjklZfP1x+PuzoYGBpydv/t97fe0oZ4VZ6XHiMKqI9srcMs/I5KsjL/TssGvIAng8qLeXL18qGJj/GVjO3Mkt1oMMfnkXuQNRFFKuC1dyr0ueoUgXzH0JuhAhy3XPPlPKb8OdhbrmFRzEi1AMw1FQkHU5ojuitET+bHxczmqOg6YhUVRYL4lujbVnyUHvnMFRny+c54hjmg7cOp8FTMhNfWUIyyMNlC48pBcb2OMS4LnxUl9fjcwDyiLIzqZvwpYn4Kx0YiPg99GwqBZv+h5e9Pp1HvTBo5EPCw2EaZaawyYemfnOsWmMRx0BTl/fggDbeU7w2In2MAzwBLhdWZGVIzG4FiRL2R41YgxRCQvXxbNimcyEFPSpEprM/N6dcd+FdBMMXslF+7xBxu9CfIUWFtds3fnxXK+LNd9KuvIqNsXK2meysoZcmCZGS7zgXOE/gq3G+2xugHU+UVjw30NAYDq/OlyggtjVr1HISywQrm7aUMtb8bgn6VHO+Cw2s8KE3OiCR8ew6f3mU6u5J0WTUHYaJeFwLSb+D2yXHnMDnQ==
    AWS_SECRET_ACCESS_KEY: AgCm9SLqDY75OxMrT1bHdt1S0Y9s89QSgXv1H5YyiWEBBTT6i6QBJNAl9Y4pJ4/fo12M4WxqwIsQRPVl07ahAQfj21/U+suQUnnjUJl6f7HyTgHRlpOLT9yJ51lcFnvpGfFtXZ5dnsLa95rruANApngTrsxRezrBajRJSe+erdY/zBzp49av363wf5r2I71pbbp5dPxNkEEGIR2Ph7nWU5TWc9ETd4EquJ6GruJ+tD79B7aVpKxfmblAzrCFiEOulu66hJUrka1+LUdmA3ByRsNP0mUNWdN3zq++zWNvBGdNUlRE58uqqEDuzETJijUAQQoAQLB0VrxWJr/galJ9gpybaXplfUQ4zFDaEfntvZvU2SvVUCcQ1KpwGF+o7xmesU78idQVC0c7vLSz03HZHogiEQRXRSfYhH1JG+9HsUdAuvVa2EnTP70BXac6+TMCFbdZMWGVcB6Y4Drar25iCqvV4rY2oE/XOFTwQdZSya54erpCzLynE4Ieh1R5giuWz1MkvuCDea2t66h9Ucn57VvfcgD12PDVg7C+CAc8vn2+ZVOiyAlnZGtl8aZGRoQak+wBtPy5g9KDRgOWsIE8TSqf8345eJNteMfrgiLMLavl8WgRjZhqaiZO4o3SmYjk70hdJFkog+5z0JwUjP6TjO6T+vNIL4ZvzrvKDuKtYf37ZkI/RIu5FjBp2WZAOzp2thw7/WsM/wVUl7Smjbr4fH6grorggJXQy5rE4E0VX1M21W6LYc8yGxiV
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

