apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBipziCGsrsuvtF+RHbSA4u/KDsazYn9PHKvPV9yOOXoCRZJirsB168zc8JqrNm81wn3en0n20QEfqjcf17aIkDQcVYeGizH1A0pUJSNQxSshkC5opIESKDGpiJvisALPHVQ/yaL94RpxWeIEw0GkhKp3RevviEKMPjlMjoC62ihDp8XqTb/AIzrK/cxSMJhT4yx4GBsDSeJ//YMut0kytQomPrzbdFRNd/aTiFLAX/4rCATs7pgqYh6ihUaZjk8rkwiRiWyWaYZtElovKoKBiGv0p2EbfgoYuFj2X9bBPEoPvh5ViMZOTgBAi6nSSqlf+/IUHIN4abTLg/iiblnjdMRLjvoHbrWDfx+OBH44vrw66tP7iqttMv9ZVMsWAFj1ou5LNIww5PzokGHc9kQlPOLBmVat1WZWNoCOE9zsVLsEFhkODDWgmP20c1vJzkpb65dyfkYksBC6CEOPeBvBRq38cBzJXkydUwF5xjqzHFApa1p0ROV4sZMDF3xcVODxPQ3VujoHjduifvHiY5hcCVej8v7SklslpxO7k0PhKosCHdL4HJde4IDPcNj3BlvDIbi98sDo0vm7cS+q9uoMqmzbKmrb524W2TOLCpFLfboCOfJ+UnBq8Fy+j4hPKWE8Vsmqe657DeD+6qorZo8/jkdq420+k7BVqiYu27l8cqyUvz0Jne7kCpvm9CBF2rEGX0vVmbKv0nPt4mVTpSzSAYcSzmWg==
    AWS_SECRET_ACCESS_KEY: AgBR2qm919gFk39b+6AM8BEPkivzf2GoonqQQliDLR6XMdqWPeW+EoBgJZaHjAzFxJBPP/IM6lhlxwaXp1zlXbeWKC1R1mZVtE9wQzEVtGvzS/5wzY/LverTrcXBemBdnYNLvYHE2oe2ckAefDTTU7nyDsJRpaQ1phTsrTFRG6x4ZLoN03ntIWXHTHl2DrHEsZ+ljzf4eT7u7zOdjAQYB/14s9fUcXZnV0bQn2Hd0VYTLPJPXTgGahnBCqLatUt7gzgcBBAtTM1ARQJS6j7kdofFI+f1cuW7JnXYHZDCMew3VTOpEC5ValT7pJLRUIjIzllCxzDhXFuZrXXwYT+AMOlyiH7sAujBuPIYkH+1LEsXQYdtE1JBJMgUf15UmN+1DudKN7stuwf02X9+YUKmmJ0IAUMfjrSCSD8z1kDXyIFy6aoYjDJmC/YDVoew1pTms2dhfUx3dxiYxYX1imezbYaQPVwGcfQF41r03D7RX+RD0fQwzQPAO8U7pXq5rpdV70/ImzkcTw2V+wVMVpf5fNS/On5JGFYFxbNMGesAgbsl6KXPmNe+x1gprIBAeeAX0QHzYWFwWF3PPfcX7YjSzKmgmc+KqiODF3H1FLMkhD2CJ0Bag32I01MF/2xbvl922tEBnHvgMXQ5F+HU6LxHUIYEBH+NI6k4+zdPApcokarp4RAY48gvGk3B9m+3/vztpjZ5RhP6fNURqs9m4NdBYqzr6Sz5QIsdTmrbyaAOAlvRsNYPKS20slOU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

