apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCD5Aqg43OFdaUyG1IZ1S7tGVuLWaHW5F8r7CJX/4NIbX4JT1SdRO0/c+anfJM7pGj02cTwLquE4iHWqw37EElm8bYWfSG2F90XILGw1/W5xXjAUY6RXtMXkslaSEYbpXOgfx6X66vNRIHgDUQnuci53Z2y73/v87ppon9v94P+dcgrOGdObJCP7Cu3E2hBR8e8+LJV83ApfZYv2LW1+wlU15hFjKXQv+UwbHTo08OJIl2CoyIb3uwwQ1XpCbeaN67/00IWTP7g+DoK0uBmp45l5now9Mf8p5LxFCXa4cWJU7xmBCuOhocpo1/ZxVPtvuOpRH3eDQegO9brWYq/nIO/vHlx2lYRdPBtAlYlolUeKUl0xvTrjcyjJ0IdzhOE63ATQl/7TE+kyvkPpWtAIqaOjTSMyN49VHfhuCeZJY3Nrl1gy3ITNLKBhrfU+gmAN5zjiQbLd1454JVE9I+/QJsW3L0GLjZfwKtD2nC/nqizOwMlOmYy5hCJ52sjIeSAmNnkGhFEieYPsSKQd1G6PSw9IUSyz1cpdXHWeoqZetJJRpiWpa6BiVzS+iRybEOPoRsuxeZivLNeHzV1gMHszHxJfJ3Tldc/if7gGiWirRWmrQq4obNbf25pJyciHip/XCby8NsckB6Zz/tkQtOYqWK8mG7Geh8E8h+XRDvnLMrD7Pd2Ws5EFnaYr5mlAjfGAhESXQNaqlGI0ITeUnW/6S57Lfkm0g==
    AWS_SECRET_ACCESS_KEY: AgDGuqfLjb5LvlhnNOEQQi2AmA1p7tnwqxQmyXXEhzaPlgpxfEfTYktwFfTxInOmAypkbNbxqmDw4l0Kp1WvJ+YhRMbITisnJP5U63kf19qqHHNYAgyqv3rp0jXHl6Mhh4pEYDL3thGZ3Nr7uXXqYUrZadJzC2Q6XHmGrl0P0bqdJJ29ubmnrvUQT5Is406eBHaZZdpnYO8SRsow10ddOTESafKtQyXPCoxXLoRD3gs4l614OI8Q54aRlxCBwRVKEwQaal9+vtgIUrn+PN3Z37+VLjK8Qmg05yuunlN+XKsDYPLlLq823YuZk1q1QnAJWHBSMtrJWCEuAqMOpD5EjixdMDZk1Bqz1vz1xbNsKbabZ/ds9alU+LY4hWVlz8i9REuppgtGDztHgk1KFyb6KDN52IzduTOFOmYhbdKGXup40J5jLXvhilEPrCcKMHBnHTznYW07JwDTHqbiia/9FPq/KaEqDbEcnJjdg9Kt+6fa7OR6HWOjUIOHeQ2jOLUwpCPFwnWquJVMIi7K8uBmZaeTHLs9LXTu4nxonZwSLG5PzwTcEFWJI5bbESwUoRhT8MVA01uumgj7nTgwkR9NHxMXq29FPafuxCHQPuJqb+rx09ReDVlQkfFd3PVxykk5RuRu2/brlVOMk7pKHDoW5WqhObrbsnVCDZfrjmtG9Fp9/kCr0YGJbhv8myiOehfjKixn5PtEUuiiW7YAkDuyBhlSkkC1PN/c025UqzNn1gIi34x9a/4VyG5v
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

