apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAW1NV+gYdRbMdZYyn6se13wGKCGOSmg1KvdpbhRbHDBjCNB3+QYT4cNw9sAbuJg3h3+MUSFkGm04/jqhjEZ7pDkITVkITz73WkFyEbjz9xma7sB0z0Jhm5DIEkq8L2JfO0dgMn6CZvGQKlWiw/ItKV+AiwnC3sCpkpHN+ZvgB9IBPFHuTPAnZzt/iI731yF1kxmgCCWFzkHGE0aQKOBMJk4v5ufdsE5C7s8Tgmbe/Xg9l1+a+wwIdi72vBY/qUa5sENb9frQqFIZd+nkGlxvwNhKMEI7FpZNSU1aTTFL7vXhI7o+4H5uF2aurCKI0ipM96R92wIA2y4pzdkSkI5Cj1P+07fuCGm+q9lktM/McjJP9iZxcMGUeCXcv3xUc7YkfobLe7kYAB0gKv4wIwbv4G3h7ufjHyONEjAmPgrcsod4dw1Xxa4zAE/cTEnyvQBsoRjEdrs/B7wTSQEH/jz+T6sVZfeJlCIhGNyhujKMSO5/TZegYQ3UPOKGrsDEvogcsaJsjZ9yiMMxsxexLyzn7zuYf/usSNAdLlfp+8z9Paa4ukRQKsN1MziIE6REWy1MxOlh8PO3gsAfta8UIX6MK5pLIIeZKRvq6bnDWpoy0DYY/8DxUXCUqGgiGwtkKJEAeNyCOWv8lf9obt8Sish1ei0Gzd6z8MgNLODBMtmz8HSMgC6ZVf5CEmOOvQIyYQrKEM/KrfV4Sv07YmY76JHxJNMT65Bg==
    AWS_SECRET_ACCESS_KEY: AgAurufNv5PL7MD9eXX0mQuADFGAo6Mq1DMBiASRmZ2KTK9Mhm1QDEMJN3x7MRmadZwuTAX69frf82PFUmiU8CbvaYnVAGgxJ1/Al3X1bNsaO8wInnHp87QKbI8jL+kNTTc59fWks0/Ia09Udh8CG9fodXL4ojHJzUBzz7zUIVNSrz7L05Y39LeKSv18QQeoC0GKUU6Ewl7MTVwu6o//fmncarK9vHzYneEOdsZOWnUBimhuHiF7yh/EqBL0zZPLk/XgmripwQW6KS4qi2/2JKP87lebUZZL/CuLEGoARaj30sCiS6uPen8uBd701AtvEbCR/wKYWyOv2iS2/ilBqP9wFoZDc9WFu2n7+ttQ42qD41mhogb8bKShMRpQTsNUA8WZMeDoSyf8JR5E+ensZKKIgcKSOZLzJYZJWzX4hidq+mgORmrGdVMVHudBmiGs43bMoWI6Gok1HmpC1nn2gqxTZp3XdCo577c+BJYnkPlpiYaCjk+XRxot4uzFlbZNixcCxHN9Ir1dHy5fWYOIF2zQOHsNmC+Wd7a5zDQMRe744TxDKC7SwbqzXwMHvzmr95473hlrKONB+BD4J8K9mwqoFzZpF4bjpH2vVEH60rIohFIHz6BIHRZK2VCrfOoA+xdn9kNEVpNcayiH5vB9Rs2f/t/W4bFZiW2FvowEYPcHzznAN1hHHbG7HdlcpWEtQWVBYbQvIn5V/K5lmmb4E313q1ord/WgahHvPyTYOHmc0bd+GSo6+dIA
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

