apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCycB0ByrfcEUcQMjXd9V32shzEYbIewBwOOk2PenYJebJetfM/sFP0mfufY5HEwoW3Pkt0AxWGXUKYHQ3fkVq1gO17dTH2uji0h5GxtZ+OcvhGuP0IVX/EY54Ckyo78OcNrQ+e3rm36pz2pEsvGGzYV0QsIVgyN5wF5vutrYuhxpzzslmyxOvOlPt7PSbasbCfAtcrn7RPKtdBc+O+dZsDeqk2YneSu6cLIPilA0ysb1HSK1y27vUNaRiPK6M8hp4IDGRv9/wfjrlQGaSTeSmirFVQCkpm1dBEh0Ye+jtzQKD8FM2sbZKxu8vN9Im+miD1XYUFSXkryjhvlduwkY+SeTLmI/GNRRq/3VzeK0TXlD1jcgVUxkn08RUjmjVDeQUmPVrJeW/xzRTDum1yh3u2BaPWgxDxT1iLeZ/DTdcimH5ggrZVWkqRokDJihvvgBlHgeTEjvBJ/tGS5UnPH9uA7ie/m6OUENuoCd/RzjbPnDtZJLoQA4CYbvj0nDK8agNhdG/AiaZKgJlOmoY2gTrWGXjmN28WBFvqn6HubfxoIRT4+I9INFMJOKGqN/hMFFLwhnhs8aU7om9ycLG6yBzrRydwaccoYu38AZX7lvInYaUL8ScQ/SL7mWw0+jXnt6Q1AB6T2Wl4ti0jiatn5z4S0xCwXTMBUSL4zAuYQRLKupDgeMiFouvkv6QhIkzLr4wH5G36NumVfVQcl6allCkWD6N9vg==
    AWS_SECRET_ACCESS_KEY: AgDIAfuH25Esvigcu3Y4VI0y+13ygFvWzky64Mn8OoopQ15ckPkiHQHYcHOqUUpIj2hwXwYGjLtQP29s4/4PiKsWW2YQK6DgURaTPcc4bynl2HgFpXxJxywYvDP2DQ9nz8wwwQDdSHcyYCORI48z4t6Bo3xDaXS39kuNrtgZxMyxmqc+ym4wpTLh8tz40/ua1JVHfgSRQhjEq1M3PkQin2kepzEpgdwV5DCQJREtvZZvJemebjifdQxOhJrfc4VsjS5QjL6/95UADhccwFsGWekHzYpfqos41C+7339P0IHeSNhZ4pLiohptL1J0q7qbCf35PZ8SSmgxSPjhpChJ+TUPjkytEi9aIJrkgpTxKF4rkmEWc2QNOa0XtYSplJUucEsusMLC6h1DjmtqoUskbWN+GO5Nw9sqGFXGUOaJL4vKyBjUdp9bn+WjxNnq9Hg8CJnCzpobLCXLvEUUYiJGu2R7Ec+0eOUo0MLefP2itePRponWY1bq8zCIpSSDPPtfeJNJYaT4vI4Sw7QZwWYRSxlycYT3em4ac7d0NPsOCRrtDGpxrFTTKSzD39+I2BfOgkQL05QURu4+4ld0a1WxlQMYpaPFBNCZ5BDu25o5oeLnimR+UrBhlnablqlKZgFUJOLG26qTaU31Dow1LlwNvKfdvmj+Y2A50LJc/jnCY/O6rmCRoTX1PV/xbL0Wv+COagK5O+d6XR3+giV5zx+SFCBWIZW/MsS49ZXkY2Q4F4YqM5Ok8SBtYj6f
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

