apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC9nwvkn6CF/ssEaAVDDH2j0FuOx+feasAVEs1xGteA/s29Qjomh5db/EzOMZH6DYM7AJ3cBMmecXFjWeVbYXUAfdQX616nWEKbvMongf8l/QawDp0JE2fWSNYoVGO/7Zr3fJTcKm5V0wTVLgFQoj0g8gWf/cbig4/0YD/kGW8VwoNJQx9+I2kYUpMEED2Wo/n8USezfBHFrKY0eRZuGsw9z4hCrV8UifwotluK4QN6j+mj19LDvxVF3aWKdeYu21ph2z8oJXBLlJP30FCEMeo3Kja6nCpEigE5Mv3cyr+AirN5URKScWvLFjpEAp6wn8gRYxGS5invWq29TmAPtPYVsCpE6erm5VlBurITFvRqvVFTQLbPyXOnwvGZSf6Ua98j4Ip3SAFSa12Pg669DE61G6kV3U1uEjOyvifaSvuGFPO9QLPpb1OTxx76kKiL8C8OzJDnTRnDpBLogCU/q+3Ea2h8w+OE9bkApaiYeAxkXCXwT7ILr42PdmHp56VDFfXamVwL3cpYjeJ6w3hT7/pfwzdan5ogxmzd+tfzcyWuo5LZ1AHt9x8k0UpLeJ7SR3jep1BbvU4sYNiFW+tFhUrkOx/M9tmdXOhZufIF4A3RDUOciWzRfF3aMq5V/z4qglyHT6i0GptgbRok90Ytxn659S/8Ps8LSvpa2HwsorOLG2v3Rl+/uWN8Ma2Id/PuWWsr1zLHK4AnDEzcwsaQYs/eGy8ZGw==
    AWS_SECRET_ACCESS_KEY: AgBazS4ERr3plqROWem9FNJqXGmk+SIs06UGSg6mWWv7iAQioP7guao/Uf0dlA42Yj2SQ6v92LeRZGC268o380T0YubyeL1A2diL7wSXhGvTDu8Bv1nASvoxAYrR3f9QUvZuNdgslyRzvgkdiS2mecOBdgtfv9AHiK/jIV1tnlZu2icrCs2aBZQk0rR+knnNLcj/ICtP7HgOrYeaw+kfRdRNUMsbn5PI3MfWT3J8ofdxwyM9x+piFVUKnV+OZXZfnw4mj+tDsilRy0UI3N69omjf5Ygcmc4QCFTQzjiHjYQC9MuifKOSZeb9pzIRpk2t5O8FVIIpvJ5uo15y7aVmHrTYSUwmSEAnqgbte8M1TlYVc70xQ0rIWxdXathvz4wd4aS2EuekHodIcvgp489qR0TJk78JBHbO6Ax4X3XSLSK2RIN+ZeAbiaTQCqn1NfRrQFMi0tqJMZIc2wj80wxwTJbVNTUvrao6JAHBnW/YHuPThV81ZW8VP56kUR9H1RGIwgBKRsJ5tmgUmVfzUBTw9bgWk5lmNrYqZIBTqneKfXKEQ2JdZzzDhFavCyh9c4r1T0xt+r6hVYcN74rWPjVTItVcecgor6XnmuPPSXiBpX22Qw/QabcXtf/8r58czyW1Q6keSFPO3hwJgHeahdq8a1Bcqkp1wPUCH/rXL72Nf58QTt/rLaLvZf2dQTomZQJYI4cATva/V8+u46v0zodiYcoQi5824LJDPh9tZcnNliLsMqfoYFsogIN4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

