apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA5zSQIGE7HdvGYCgMjTes3SIPUCIwyPzZI6CXowNxEzLkE6fRiWd+jSn6sv446tsGzm4W1jvTmCyrjmOhDjeNSzt+mamAt0KuEYMGxFbjVLtKQEDzptjedQo8sc/BK/CGXngeBOn7vZTC532GpC+CK17nlwhY89Fc9e1aikY3/T8eyt/viJr6RXoY26XbyWi2Qz3vuQc5DNsQDskn8V0KkwqT8U+75mNHVNsOxA3OKdawmz2ls13BYw9hXTUblrxvG4iyYwKs4T/5qfsBuwIxE6r0Zm8TsC5H2Byb5+Nq09qVFw7D2A9Gu/VELOyyYqkT1D6MuxZbjFVSUOUmRQmzU6+p2aKHQl9DB1IHed+5227n8cIVQzNx+mzwgRO55Qig5f5G46i+LRoIZ6sdmCFp9kIAabnGOq7vs3Bj/nu9+5Az12t9ivjfxq5+LEgTKTN2JKJ1rheLnUmFWXH/iIHlT+cb74mJQuqrAszwnsna8qPhMmRbuZnkfT8ws6XgP/EktOjxtYN+KtZgLwhi5izjbtFK28gYjbiFwdQEr73PkqBnzn0+I9l5bkpI9tc0NvwoyW93TqaQ1/AIW8OupiUe6iEch0I8OqU+22HG56JTQhEbM44vOGfDO7tL8ocqQmU9NsCoJNMZ66ep2/REQt30HFMg90F4Kj65z9NiFCFqRFry+IhCM+r3JJjlkFdt8+5KaTPhvDgO/tFKr1kOkiJrM2p/E9w==
    AWS_SECRET_ACCESS_KEY: AgCISX6Iw+G0KAEeXWlq8koQjfepEX4p8yS9Rsq3lO3dgY63UX9CCZzhcFiVj+bSPSy3allvmqJuBJMbr5R4leghqDtA+4jcl5uoR1UQCu5J8sMCt7Mod7Jx4lIkmlhYKVUnUF7YscDwXyuNNVk+F0dXAMlyWBR/P0fnpEoQE/znDV6yfKzxZwup6LXNFc1icm/tjSr/FtGKiUyJKylJruifx7Ze8Dsrkoe7Z8uuhkBcEbWhScMsUJtCp/JI80cDJa8uvHHPGFeWxL9sH6iYsEEluEQN5smVSlEZHkDWQlK4zwI4qUmb/6u2/agVcKYavJgDB52suDEyFkEzXzthyliWIK5V2i6Dvw7zLuqtkhJvfiHeH6iMsvNYO068vy+O8hH094MAFz8XBTguqmSD3n5k/snW5Yxh34TjnfX6CAhTbnG4yg+GVHaWB0hJx9VPDuZI20pYuwbH7cJzct9IQdflGxdj7B5n+/5zAbZ/n5fpk+hxqs+h7gazYl4PsNs9Le1GT70ZzUHKgCY7i7m8lEldevvVQ2QMGpBzE0X5Zbmwv5fAvpuqWSMyXPMG7pjY4dr+tngDTT0OEylfHe3DryIxBU2XlNlTvSUXDwAM+Yvdrb13NN/aV6h3mdGjVqvhGt/dcyOP3o3jXK80s9VxupUyk5XWECUCdenyAcOTWnIbNu9dfTDocJDwx2Kq/I/FYtlKdbkaScKEvOqmqOTUt/7u7bGZssq6k2XeIsH1xHGqRxX86hPugfPR
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

