apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB0x2uSSF4ZFs9OA9fyZJd3d3R//lQLkmpb9jBJGMgpQzFPbyqqEyyvLKgokCpDkS3Q1Ltr5G0eKLCnQN5Mx1ZQKiFC6QHRaGc90SBASMMGEMkieENHXZm60P2yuqgBSWru4P0nZkf6nLz9f1dLBI4ANWQ9mGP2qDziXD5b0G8XX3EvFdWaa1QL23gDT4F9J28lYgwMktCkCfj+uobig68CwXOis3dBQcwpOXGVEbEVMyiBxIfeGei97nqmr8oMjikgFY326B4FbPYZ/ZGskxg9y3UrlByHY/3Yt5hxu4XybfBx4cmGZgIP4zejosUnuK/nG+hxHKT8X0lpK47cc7QVKMvyXpugtmKbKr7LaiJvOC1zl4JGAgNMCqW6r/eBXFH2Vz16X2xD0KkrDkHKb793v2sCa176kY7hKF/+XCyyWe+OWEuq8ocT88y1AZn/fo52qG3aRz/0PwcOygFpIOkVkE+4mCY0iLTc/sLLOcw+Nb857ijM4U+Lgvuc3kjSqFBrmTrLgjG+x1ghnTcIjaOhwtPBUS8AJp3//MoQJUG0+cPEuH12um+egAn9+K6dEoV6j5oxzbJiRxzf7s6ng+z6cvCiq042/e4rVjGoYpdEym0SCyc7cejChzOlNd826E7wShfLxN60oYAaeRlWgnv4Fo5Cxi3iGE0xnYZc9HweZ1lZvNdR+Akwfq5S2n8Y7a29k24K9SAE1HPl9aqblanMFZ+ENg==
    AWS_SECRET_ACCESS_KEY: AgDQBK/1eAhc95ruv35CHxJSP5lP1MUW34LbWusRDoenlRUxKgKFEaOuh005ah4ADE/mJsQxE6supA1ytj2MT74j3/XbyvQSc0ybbIt2Cez8fxg29QV7qTb5EEqkvev0bjPW8EKe7PzfUSM+UPKoeCpbY52a9kC717IlwsCD3UnBelPiqbMAA6kEcOonzPQY6dlLRfpcBCqtRUnnM5KcNX3gUW9gdODwgmggZdjLtS6OtzJNcEd02rCSoWSXzfXzDjtePvZPnaKcgIcMWEsUbhzcOJ2BV4/ZSFZMvWeTuhXQOQ6R0pVH/+L4EMKHRmy1t6SwsjWU9wrVaRcg0XOBojpabAzbaC3yNsT1qWy9C0bvNJooIz8JqoFC67qCzZ5gzWxZWA91B/9QGe/e5dBU2ebiiUo/u0j+tnEoeUmwmDSUmKuGhZiQb9bDSEVxYVhXs6nGK1ee0OIifTyByXm14KNxFAe0SLTpaZu4PiZLfEOztHMzkzzE8Q/PyufC0VrcVS50CDBYIZ4gh37iynPtaFHCNAPdwdlWhAQM1Vzu/HuYX/gj/11cKTXDpLRHdXRoF1uZRRC55A5kdMdS1eaJJt3LTwzcbh8aZKS7m6HOWQ/MFCWJiS9+8hcY0IcKohV6JDCh0MNDVoxCUVSEx5rN7jVrl3q0MfhWd3UrjgYrYHwUzsPcefXgwox4XJYsf+aBhzItkssCvmgsuBbbuate4v4JhXuC6DY5IXLpUjD7oQltynKOC1foQzcE
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

