apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBc4rrv26pkGMAOlCidrs9Ddqw4+tJl5CagL/0NFBPNVf56yDE8DbZEg0jIylygrLuOQC7PDIbcmIXjds4t7+GKbTvUlD7fJ05lw+nTgj3yiB7TTXTdmXHycmLiFI4m3TmFn5VMiSn0fZcw1YEhsn2vVLk3uvmzrLsMMybYj/BGUqRM1hSIleJ+l4aoatVbcQ9RyZtOYIRYPWU0agJmbkA/N0zbqZJ6gostEluyfN+ioDFftPXzv264+xU9qIuyLT6dzKv+TABzIRo9IFbbOggN4opEkrdx3h2MN7KvzYdVvlWErVKk/ORblR220RvBmPp4vAuQvxYCyrG1QCBfmZC1Kcitl1knQP7KZXr70XK99fOkTR1k1UOFmoSVSGwTXJBMgism0vcVjQ3EjWigEhlMgzzZouLtctG6eVmV89a4Ezm6lv8LjV4lqO78jCvoZyG4b22rWMLtSen/2kN4WVRV6+Rn8m/0Bnw9b4LwVmU98jyqdozr2UEt5CNgu1EVlU6VcUw0K5duCYbZgXMpYAVhwxiEH8OiRR2H/8WWzCgLNbqZRpFq9G/24mBiBYm41VtES20nBR4UvEpk632SNoPw2E1ZX9aGtF06HOanF9+kibucUzxd1Q9wbP7Fvdtv0RkajQmkqVFV/c99yJZ5j4CbbtwfnsTyeaYNfdpqZTDzgEqlppj+oWmx/i1EVvaT9eGeeuyiD8XUtMlnnJ0TD9VrZrVmeg==
    AWS_SECRET_ACCESS_KEY: AgByggcYOANfs9L+yZFZ3/OldLCjPYeVdac+ULSedFbsiPpMSRu0CMna+Lx2eBd95FXBiXhYAgifGAk1gpKqJrFHl2o7CCFnfESwsbG8jCKrMy3BaZIi0cz2GrpIF8dJv/TwgTN85as8gmIbM7Gs+ZwpKsGUQoaz45S1rtEB8Cm3/+NI+Gsnbw2pbx2/aiAKqYFk0Btue3cVOWywRgqFFsCF6dXcwNuUUpH8sZthT1pbskwzn1PZM3Nu5zSBEmSgGtHCOdq1JV5wDj32+4mQNBIbvogbfreVAYDIlv66QHb2OC1IxlBCdka5uTuCWQObydKaRe7hTOq5kUS5d/FgFiAr07J5Tz9MJTi33sa39KKPZ3syKS2xCQHERwVR6DHlLImpvsfFoyx8A+Im40U51/iNASghVaRrECzEroRtECFFoxnVEN7bsSHpiunxMhVuzTMoBz/T0Ag89LZ4T9WhvrNkvknof6wDMdofHcDGWbt/DPfUiIobALdZWm3j9sGfBGPXTUE30EoMGsKHBiC/uMN4IVSjKTUuvcFAbhPq3baRfCfKhJ1ubW5VqFT0K/LbP8nt4i8+eW0mcdn6DSB+JUp3RjSlz7/SSh91596LxY68l+tklHAc7+7dFGmEJs44Zoe7TtRFzyKgFqpcXROmm3/BOH2g8X5KJI+OkNjhN7K0FZ5HQp8Ssg/LQWna5364HIrnsEXrMariuyObNcbbxTtJRWaOmr20X+DRFeQFR9NJ2gIGte7KOkE4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

