apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBVxY/a+FSS/qMcbK+WxtRfxxwdPcyCVc5aoAhv8MitZvRr2coj3HK/ciDxwCMfAbPmAzvE+0jpBgR5LGsa1iH7gbrcKw25382OBMV5CJOph5O5zZCBHPmC8y0GTeECfBdR7jxjUiActXF9/t4x7YtVrrjTokvjWEawmqT13RlsHsvTrJfL3Y5Io3mZdDMD0W75YhVJWtOJYnI6RPFBpihtwXOe8pbpNo8s6vKlxyaf/UHnj/DRPyofvS61fcOX/nrlhdcMoOGYSeaNVmbOBWYj+Ny7qik0Vsfrm3oxDhzjmzbqVTTWLPbZD9liMtjf2+/Rw3zYa439/G656GGt6reolyNDzflloGfLkKKCSU49OapyAoojLp9ENKAQIKiqU9hsSTctGpZHJv+moA/+dHBLGGX2Dm4UYcaB5RAGf0I9K2moVAt4oPFIzjtOi22z8GkWAIgWJc9r6W5DDQ9M9eq1CsYkHQGT7QxX96kH9EluQWe69rv9WYamCetrUifvyaRdx/77i6XeW1uZGUleCNgORiBiT1KBKoEGaALNvhfqxB4lpyUFFAXjBAWJraM2w3te4/FaXRWmbZxhuGAucVQGR+rVWNxlK2VKb17q0lrmBg4JIyg1FU7f7Rlh3L7Wkfur66e7W+0EMXGOkBs3Zp2GIiXoYClAfx+mN06Oc4SqF9AK0ATpTSWsmE2/i8dXbhZ64k5cbYDUIdeKX/qpd3MZ7aFwc8QzfEiyAQPRjvEWdGpyrrGnWIGXDLV5Iis1V4FOYegRyGiFSsANnlgkjQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

