apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgADhy2fZhuMM8X1LrFAf95qK31YuapglaETvi9mqH/9PNtK2KAOqfMu+taIfNvI+9hSs9qTWVUAbjNdAzA4d1nfNg3h45np0sLxd73gj373X5psA11Cw/kd/t17QI99Jic8dZWj1FAOjBfIbf9wEIGJHrp5fZL2O6n2eifdgA9JzpGM+E+BWstslk42WE3Pz4NAyJDpWOczGFeQhuF2h4yVW0L6yLI4jwfKG2HqS4V2rMHs0YTPKSRZ/46NlqjZzA4XSzGH9Udr4WiO8CS9xNuJ960rdUVjakmTMPGxolDunkkC4c++YR4Bh9gdEmvCfW9Mv4lvx607+n3WAtcLxNFPTFS49mL2sn1FzOjtrvMuA0fo9RKuYzy+enQNdJUg4YH1BD/XK0DJhbA1+l7S7GyekwH2oZQBGYzE0FcBV4ehE+hHNyJR4qYX9sAsaV+uCZ/bO/f8t08h8BMRb8gsnNi20ZvVls3rxHNU+h9WSl6k5FmBGq3N1OcGzsRFd4B6u3gA1w1Y/lwgepcNamX8UlkgTWkwxF+inSvfr31uscRr2r4iJ5pWBBgotz/NpOZhKoxZEtfMQ8sVFnJx742Dd8Z07iJMBLi0v2wjlCEXk8wG41r0plcZ1PmboaAX051qQt3U1h7lAJgKwYwe1hJqZjkmmGrrQr7ghPy92H/8r7IvVC8+rBc8C/f6RWEHsTr3XtyA74GVIcPoRQe4JaMVeUFfkurQoPmyFTTC0Gxp2eTaD4pKR6qjytZMf6RR2NOQo7tyuHrH+Wxo8Ghkk81/+Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

