apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgCxJHQEZTsnnnxB9dwlWVCp2vszxAligBE97gBMbvdxGzh3W4is4v1o2XRKr4pPRaV9Cb/oVy+mDr9LG9+mKgyg1NsOWUCeZXQ67xO+WmFUQrqP81DXf2m2lol1wlusLiGxtBqiOfRZoHQKKR7EeMb75c61SnmKT9J7Y+B+m0TgraDwI4RmdVhJaE+pWSOobfhj1+5iw3xM/eTY2pH/kA7I5efwIp/DuouOFN47YYBSza9gm2TFxrmA7IAaYaxn/DRSyOtCgybX7Uz1iPDOPtYk/PqvPvRSLLES0ZC+CwwrkMKjWrXfL/NzY/1E+/+Z25/eAvng9P47hJg78e2SRN9wZ/4i9wvnqWpASUhnN9OXs4jGqpy6kZHlg3PCLK6K2eLvZlSwZ2wOIWxg5PRfOlaqpXuRxwcSF34ToDe/bbfkFMg8go4bH5oyTQP2CeCikLJg/71ZzJ1ErlHa+ATYzPD5kualMdCPB1865xRsC/NIOVEbVgFuIdHfkYLG8Tu0Gcbr6PK2z1hLJ1N00KSMgsfLXxe/Z83uHoaR2XgmIVvAKw/fcSZmEcrUvog8jh7t8HNaqkPJH/P2YViVWdTqlZX3eZzgMThO3qN/1wkxVIHxDUXQwGkGnf3MRhIbVxfOjq0389drhH/M9br0S2Pg98FFTwQlhvc0LaHuMz3QgRs3X+OUSizQSmu5AZXhoeVEbcKmsDsaYfSL6gDErr0rCR6wsMEWLESMObW/3x1LzCZu2ucUcWxjX+ItmkPHljgZHRgjsMj6xdGyYDRRa3Pqaw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

