apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgCgDMwA8nUoAuEW3y/TYuafOw8d1FSxXXSKcflwHbLYmwdlqqTc0OJDnO7kQfKtpYjUOI5wZRVrVZnZYOXpO0yC1uNKyMvvI7Myxm5FbWtD/DicvO895P7NL5ueP19opE08BNc2FFYpcvHWtSVTv9UH7HFTFKnoTJk1KKz29QPaI+Gx+/oCy/kmr8B/lMZytPF7G4uv4BxNXhFMQQbnfdiLZUREfjB+I0ctv++SDG9CHILN2ihrRhV7n8qRQWVEM29IgOyysykQmSObuS3c0eKnQbQgDWGvbRh9NqAm6SAajYr7ku+F/IYVIUR3SdwYEOHyJl2Ylq26LPQ5aQHtIywEEIsuxGNGr5UnrUZLS2old6fAAGI8PTAHA5UNKnmMAU+ogYBJ9dfVMkW+TEPLZIqqZVboHRj8RZofU9YiHBZeVzT5W1HV1JJ6OLHbO64TRkPJouKPlbboaFyALUXyKXLSu8MMbjTHtFv8ATqmPijReQWPXua75+uxCfo9Y4doHY3//6aAOrjz+nR4BW9q5qYoIt8+ul+nWOP6vFXqffR0+Ty65UNX0gWdsOiIivPI6SUBIVdxuwpjSWw1n/5KO+qGN2k5aL9+OdJWaekB7cP1RhWKrv5e48DnkN6fxtB+FWRqOVQCT+Bh/epCkT0Nc6UYJ9PY6C7dSBgshc0k6oZsE7U4XzIJ3Jv2jciVUyd8fMwB9aBlz//GivSgrkUWK7BIrYiZH3piS0/kxuHOl7tsbxCY4e5zUxIo22W3bBX6HsSKpu7j/rhltbgmDh4EKg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

