apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgDckwrynWzb6qBYgs/Ol+7+8/jIZrUkp+ycDUf+Z6CWun2dzV/fOsRoVZ/Fhoi97+1wfdYD9Ta7TJFNvWrZP7AxBBaWu+4wkn1IHMbtVxHlZtKUQXxw0UQrz9HWD3t6coaGuZaM5oX1JeohuERp23vKgLQh8Q8/+2M5T1k1B18Dgqj4CvMOW/MqZff2kZ+6Vf6i77ngNCBS2OElqyAa/Lx4W4wLmcD7iZNloFW4/fHybsVXEwN2h2za5mXKEmfFm2ZDJoivMJ0kWPJlAmM+zMQrtXC4QSi0fViE9awP3IYJZFGlhZap9Rde348KhO5ESLeYO2KUvnB5+h1uFiXhkBe3msnRTlnkiDVJJN6PDQHVhuUrNlsDUV1palFHcWjxeYCptjvPgaOjjA3a3U9SvhiVT6ebTPK0R1WGoJwIcX7tp/yZ7/Poo2ZFU7AWoj8q//icqS9+kBfjpdAZCx/GXde4EWZsMA8N0geVCqMEXFhG2EN/lmtx6D6dUodDyKFjpnWw+paC6CC80TYEPJQRYNgRnjviqn9TN/gJ4ooLZ0Ll4t3QJcjyVZkpKgGkzdOaIrlElWzPexvnRT/PuqfBUgXyUXiOTLdXbDP4LAoOynI23+CWBAnLc/wT0m5nVQCrUB/7lWz5G0jjylY7m+P8L0JRRZtI5dkKPGntEc6YXmqtzwv5dXgwxdjY7lSnZFuQshStEo4kUA51TYXwurh6HcMwE5JEu3S10D9k9TZXY2+PhVkfNtd8zp3pn/JKWWbW2Dfc4qujSi0NwjIL5iwuiQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

