apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBv2CUyEVWUzH1qi+P9M9B+FYXHwp3wda89E6aHXqhMPe0wA01GetYBU6uIJ8kmuyEtH2DSVAlB8zRq7KDklNJ88AcECuET6Ivk2yl5I2huffUDXnSuvT9ht0gyz6mTXRWH5RpNglqWoHjyeLXbGzyiY4UpQLGVcuz8f6pRKj5hcTvEOI6Bk0v4R8YxKGBepqrYc/qFeaD+Gu2D779dZH2c4xhpJhkdP5uA2xyeyMYxZSjhL63VdvmYng0Evywhp3Wl9azel7mSZjtubbXkKam7993GJItvDw+XdtoDcsg3E8yFEjNejVGpiGGGrAcLBl3BgR4Nt2V4TBWWjOovOvb796J5vKIJZu7TIsCuptl6FB3HtRQ3imxgLIa2FrI7mSAKzDKsZf4ceGzRY6aJ1TviJBzdkZucYKrfClgpC0Cx/bK5olPFm/gUKxdse2gBwk3hit2yV+koH/WydPrYLGVudPX3pLFg/2kFgUjPmCqloiGkbHkWgFXopJDuq0xfIyMMwWOMETFRRrlXm19bKZGyGhWW2oJqb5nVBXaGc/NjQPWl/RO78xWSjuDpR1yvS8KR+aAP5LpYVBZVe0NxuTkXq5ZrDAmMv+pPHzJlqMcBlZzu/9b5xzejtiXnIqM5x0Ja1/dF9ibkoULeU62XuGWCZRKmriW8aTxH4rHM+CLVz3MFoKKUk9C2RINE1ViWKD6kB4GWksZIO2jm3ZHfU2nRJa60V1SOLQrCDVnK4zlNbjGI/oJJbtQHEdOHRzLoo/QB/Phh7O5K4IP7CVidAQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

