apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBBh+iQrrV7cJKxCjOpwlMAqXvHEzQEEZfr7DP2Oq3FLQEPQSjalGcrie3EnGJrHZiwgZ9C+QnWTNLYipzJwR2O3kb8OQZXIHK1UICPxwzqWp2hh+pGr7AtL8GVgPtMaTWTXVr0yYEuoybTq9mjDgvnJte5aX7ABpGjQECVhlJ6Eo90k5oKZBgd95T5gUDGZ3zb/ticZt/pdVckoCVuB0JQp9Kev/S965i0hlbLig5OH8nXNo27WMue0B6bPT6ILwZrynSAehzohRPpMEpwejGwOQi/lmBwl5lQDSoXMlxQk7w+L6Eepbf3N3k6jIAAFZ0iJE0xwh0WDRYkMq1dSK2sAnSerYSJLF8HzlJIUdWOcRce5uEOytzTBhPAk7s5i503iMYeHCIkT/wmn0LCI+2CEcyg+KflxwE9INGWPbouNLb3FouhZVMvwKd06fN3XxUDzPyPv/7AGKo7mn44M+D/VcSCU+jm4FsUGdLElV5+QT37yRr9mt5F7YjpJ3Y6CpGZMQqinaNmORCWUmaygHYLBSfJW7SejM2uHwe7EVUbUZ8edq/Fh/mpDj8z8tYxuecVgp7uKFlI2V0O6HXfxWS2NrWrR/+P04UldUaBM17aKV7RIg5HcwxaacvqFU1tfBo/79JCkIpp8y/I1gKKhseNnjFnpP79da9+LAC0mWd56Ofu0jYhxyFuI8GpgJrnf9dgtKtzTqZeJhGRTBnWwhrLAQ2Ro+Dmzujf9LVYbQL90udaLnoWvXol66XSY8EgDr+H+3gqDUjAsnDqVUEK5w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

