apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBdFV8CYPFRbgx+gx+90SeA/OWUBYgzWnT1IiXxb7yXBkWpcL40IeDINonXBDK22oXsoIMssrX4X+emq5wIhlnNOWLGgcEdGjf4gJ2aUFN2ndd8Te33tv3UZm+0TGs6OXbY1pvAXQHG/C6kzwtKgdv6VfKWtlBt8erMHLuguWaCwBz0d+h/RC9AOZuQpj2uWwgXB3TopWTZxvnIcOfOf72zj4KSj6b6Ecqf9XiExDUiRcgwUlhJGWMSXZGaMurgJgoT8og4caUXJ6GrHVzomcfyl4NfP0F8HMUAp12cMN0VTeNfZKSjdxgtiu3s1syh0EKjLwDEcUn3qrFPbypGAIBJLj71q1Pkc35/cik04DGMSitDkGw7n79WveWEdvWmOAJ1Jif6YZQRtqm2KlbDe/J0MX+e2TTyzr7ILFxnRjt6YvsCrYDyjuJCf5+EjXKFXHWBGuen24BbYpNA8wbXavHSaUdrOP63UfXsdHZ8ztg0ARHrBCayil/DWXyrfKC6DQsUb2wDD8KAOj4ovBw+mKP1kkheRZJ4L+vNZ5V8JmOkz1bngrYXUfSzxF9vtsCvB2gD6kPJvkfGykWoxEWSSi9frhjYQEfDzHrUviFCnbA+VMfdVC6YKtWadhnygZJvM+bvkEiN7lxGNtBtAk9zgnzyFsJPwjLKoE9lqFH5Iz2nRCAt90i6QN4LpRXAX+NulCc1lTj4PZeBzb8mx9ert0TDqOcDT3hbrXPptQqwXm7+qeGf0kJHGjTeFlfnBAfQBebg8/tA/bfxvf6LXe1rLQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

