apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAQPEOwkqkixpeGhFKVSwhZix++OzDm/eQPsEK47P3kv/OhRju4wxpx7jssijhtlxigY1CR9Oh1NUn+IjqMpk/kVkDOjT8wEOt4Dk57h6uD/aRz6BS6Gl/sXBhktXNYTZmo2VmtIns+G8aQhLjY36bF8HbtpykZjqUpRMsY10LEohz0c4T05SSjCPK+fKzO2tq2leKoV7UATVvrVZr/Rwy5GK4SN6LtnYXMAgxfLmqJFVVyMW7ILMTlRWivYbIFhSmREPFtwjmSq/Y2OhgYC8m/pg7zRUR8MFGS4cu+vxDnR1CSKueyqa5WVungkpgtLaYFF5XwhfldxElvwXv3SDsbvSt6jzF9TSGFLOsMVfOJnSvefPS2tNNaY0GdsNMdstwbYeIoMtOSFqRNhIupI8cJ3gqele46Tltt/5EzjXJW0kJJmnWJ7M6H0++KSPgasWFQNXFfeP/BCuJ/H86iPoiOhBeWJOEjTGkszHwZud+GyDF7qZKe8MK0gNdMrieyMJNU3A9dN6bAgMAzKrsz0dldoZ+WkJKcDqX6jyoHULYLYTG+Ve9MDwRGPGJNNYWaymeg+AuDFeDPfzoze4I3G6YDge8SG8SUpZ3mma/1ZCEgtVD+9vnVgs29GRorf8PHuPQxCW8jnsYeTd/qslqIk0jA/aWgKG0T7xRPA0kmAkyOrUkT+JCorXP6Mr3Prmxzzn+szPfm5gkbvH6Gq1zcYHuCYdMrwSurphrRHfHhwVFeYfGxUA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

