apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAbuf1panHioDOEqr/572JzYBCvFXoiWra3QwWm2UaY/pok7GPlHm7nGzyZPe5NGO0sWotc3+gbN7TsrdCe7GCzr8hgP0T03y/pOO5QY8JiTcgTAzMOZB64oyzjKOJ25vHoeQr83Zuwxnh+y0UFGTKjb/Ddt1zF55g76tYJrgczFU2wyV55mwO++vLgyTB9Bv4my567wHZ3FvquITeQSVmePjaMcirpHGkPLSOAFkkB4+BIssM3Z0LIazp+jkwRUzBAaWNaNZ1WKpa7yM+CQpnk16F2OBpykipWdA4WexktXHWv4/+pbO4SbgUNITWvrj5ZRhHaW2aECYi2s+IKGnhMa9kjIRtf55+JRPsdh8QvmF74+FYbohTClBasbO4kFLMmlJey7ArVwJCQxEs9JbDM+MiklN83TQJ3onmQqo90SwBVdG7VX7ZTQQpUt6w+5m1pJJtT/Hi46DpS/TnCort/5ubdPJXQ1zp0UkbnctvhgsRDz5Dn6owYHRER5L1UJkvQ2winXH19jdqIXQR/03DbHB4mDhl06QE72x3wz1xCSuLgEwUBu7AYrRUERz+MFiepm7CIKiSLmMpEgMUeqQQaiQIR8cdpWpeENQezyssSR/leUtzrfwIFTo7gCeMEg1BcwSdhaBFu6PwCUqprAdVWg7sIyTsn0vPVuIeYeOgVseOt24nwQ5rD03qOXN/1J7iXHQSeWBSLA6RAZZSAHZx0QUTCaYT0wy0f8vHI1HJL7fQtig==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

