apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAeG43jG29EHPBEUrpYNAIUqd1+9rddzq3j1+MSVziaDOtScw4cgavkidHJKlMU9IzofXSF7BErsDLm8YPKPOxSsuXbC/NFPzfuUTeDleXUUNs8YCBHdsuCq5/t9eRik7v+1M7R7sBhpR3n5S7d4Ui+1Q23/jfhwdMXTdRgrTinrZz8zoebUPL6gaoO5QOzieyfhd9rniMDDfq5JUzNiboBcOZWe29g7gp71vBxajtDXbDa6xbLjZiOFY/C3YJTOUMIcgJSMCSy2se6vF/MkSQN9qMQSHTJQu/tXr2g7dNEeA3qx+QkyOsmY6SNq1ohWB8gtSVrlreNRirQgwOp2Osw+JQmWoLRyWeDbxHfMpIwofhxDj8vrpOHL2iSW496WfUefj6hde0Tn5MBMQX+iIT6oAgIg8rMjRz7YLPEsKZFetiJtbNCyJwxVY8dyChFGhNxLW9kb/eGKWg4SslUOY1fTEx3RYBwXpu4f/dBA+U86qasnEx2qj2ae35BVkD7EJz821YHmUXWCIH+PIajtKwUftpOde7+KP8tI+LKnlH1F+BaPd55GBAxrp5q9SgNRCcF1L/izKi2XC6RMyhiXVZWYuhKSEoi2A0zdlby3BlvRP6K1sVqfGRCc9aZTTejeIzI16m3+okfttWtEhADjunGWc0MmjLPcgS1gOnXNFuuWRHZKUFxi+mV2ZjG6QwkcCpAR+feghDHX8cGyWEDLGhHQdMgAN+Vc0FoISyAkygskeFslA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

