apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgCRntjD3T+j/EnBsh6s+zVO0lV3ALVc3O8m4fujqknEmb9vsG1Wa+T/xBV0KJ6a79x2G4epPuC1Uz/kh5RarSfKlH/2EyTvLoldJPNiweS0WNnFt3q2rJJbvwrCG0ssRv3Lx0tWnw1mXy3BTGCEWD3CVkNa+LBNVv4I8HwmQLoG7yAh6mXU0p64Pix0FBR1nTIeEfdl2QBPRC+iGuRRImowoqfXGmfeT6fyFsn5FY/hwapgvMlKEurritMi2+zSmoKVzVScovQ4yV/cBwReYjbbpkO/9O420djzx5VuXc8LqmqtjJrQvBHtCkC11lhwlETLFQeg/Uv9O9qEDbmWE3vZbyK7UoTXVYtqpcn9PUJSQXU5sl1Eu9nqBPc0kbGhj5azar6g5LBj6GVGKmsHVM9FLq8MdPr5DmVydcp/HptCGvEp+KvKHbsYGat6r//olGt55PUgprRyMd+EQD/nIQ6NLLbrRYFXQCa5p/yAbHUDQBQLlGJxKsa24eR4lPZnDf+9xbzaDzDP1yrq2n5kVqC4+owvVk/RlHeXCG9QR6W7/yTXFA88+WzLMAKDaDCdjk6Fpa39GKQhdqW1iGtS38JPRPdKos/OiHbvbEq5M1QQaLoA7VRQTTgBOOZFHksry/UrEJ1GSqXcDmx9ZVuA0UeiJbuorCWhE6NvDD8W8EAOmM5fyI613bCHDLyFIRRo/lWBLke86Ompp7fkdfuvwRyksS1uAhKxBhmUNdV+tb0JDuUNeA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

