apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgBmhqnBEGUtMAxFQ3eGQGf/sPQkFc4Av5ofVfAN9ePHg+TwdmZ53vs3uTQaBdftFMqMmr8DsRJ0H6f0x7Eqf/mXCSRdAj3l4sqDDIlMPUAutS9UZQly6htFVD/V/IR92I66cwixajdOjPPIh7cGoKHQDVePMMHtgMzzxtP5L1s+SJWgxrcjT9tVXvq4vXGTfqiw/O42QWkIYyJlAzFN5vyjl6oLLwLnEwsy6lDikrHQFyeSQZP9IW7/R3g7x+BDs7gY83RsgMG9SFrTrqyH42TsONW/EffrJxZ11ly5gKBebrxzG4JCecThc1FywKANCIYjhOR80sWWnKP039J05jbme7edbRNzfg8C9hpPQw9aMw+HAtW4Ctg4zy90Vlh0i3wuNx+Bydj2jCLA27fvp/0USHjthmZlrkMrMV/sO9mO8n7BU0QL7t8Iwd4stSyQcUgkMjcI9fmmLBxQpziNscko7XWM3sHl7o1iu7TNWZhMoYZE/lmkXixbhbf5Dc73vzPpCkNm5Gv/aFNOjJl6hLKFqoe9hJCYAeV2ccZjs9JDMgtledhLyrWConOBwbD+76v/CJB3bJRtsWhXG/C21YtFdieuFtlRqfo8x2Fp8y+HX4pRcFLhIA110/DSTM9BfOQAW92C4zCIMp4F7/gzCdDddaltbHDJ2/t6yhWz/f9unKLBiFI5cv+TVk/Yt15FEsDrm1zZTGRKa3w003cYWLcdROtY6A95AxDgc0sHEWfCgAqj8Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

