apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgCa5WuqDzwcSSuiWeLTIIZCtu9NuDHp1S7CTjvSyd1Jj1pbkv7TVGImVY+eNW8w28DoWazOojvU8d7wVaVVOGk8VJZPoanT5MCTBJONLXAwQL3sK9RXaWF0wjd0ka/qb3vHa3Vh28CcNpg6tCnSDxrZHOT4lezFLjJhAIFWyKowbg6dViLrKit5CWeuEABgpJovTCpSK+AY4Oe+MTI6ftNSNKRob2eOkULmE4vE5927drwmknCCLbNis747x4pVL0fTcq2Lfnoq7q9f+ZCjpc6MZ2UQWesq9V/a5/SbmIak7JvbpFlMhW8nSoeJ2sxZLbpufACFHQ8rvaUNDXYlD1M7UMErZR35C1UfEDgtiIRSndf63Lx4kW/SvBCtGFICutggDth5bMHDvyPAgNDZmRLBdd9zbVH1vdiDuuFWbJ9xnakBYu8mDKCeeXs/HAlKkla152JDpqJeOCcHr5qJ6sgzYCiSD2wwvL/dHuWImV3OM7hqkkWZF9EoNIeZaOUviJrKhQTDKwtA7YeHxHUEQyMdRJjgasuKNB5HdJdPfe3EMi9Ci8UUNRHHx2dKTuFm2DV9w6Lh9eKTP6dvxCdkc09l/RF778cOHVwwrM+r/8wuoLRt5eGb/NGkpH0cNc7sOSV5J4xc9fTWoeRlZIWmUrQyomnVq+VAgTjairrTKe9UqRgooL7UTez/STXnnW0N90n5YkYQEQb9cmQSBYy0wGhfXod8I6Ep+Rv/sPj4Ma6djBPkwg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

