apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAKyYHTHBnoIWYm/5XsWobQOvbxDQMJ3w8sViVkRLH5/U4bGblOJAJ5xvWRyaSFydXDy2AcBWyF3sEfB9b1Ob1LADQAr+1sBjjyZBIZ8NQ2gyezQkZXjEU6qL+hg69iwOtMSLCs+Eq0aTWvUOXuo1FmtGqo1hOmtHkLOIcGhZEpsOaklKLwnfCTgP4hapi1tNGO4PgTYVtTmDt2mQY7Dl4dMfbPgKjFoDAdXAcwJ22LVfYR0LBsdEz7hmvbYpSveffy5rjgHPNHXyyC73L0ArMzLgzNyIqAXU+PESdkqaNcQ8cu7gAtk7pN/Rlq8oJICfUdlTiqvIshQUzgWYd5TwgG6FCY58AzGaI8//HH1RhuDfXcbf7PKv6oMVX3e8ptgEt1wb7tzGyNOpA1w0jXfY0cA1/HMKMRhDTpF9HUPAafhcLjGhoFBJgQHvmUMQQJk+n3XU8KMdHM4LNBKatXG5cEz7J1/I3gwVPxSMjh5U1P+YFIAuLUyNJff06UhGFyQJ+mbmDUnGlk04sPbQCmeZbEr0xJt/RqEzgH54gDWYPwp5QPH+XPXhO81eyDJ/kuGktwX52uhmsd1WoEFoFPabMpo8qfZnA3ri611CJc7lZmMFD3+XSmmVRy0CE2YrlcF+a22XDxlhr6iGm/wupGWDUModYhZgZUArF2Aqq9pnNUo3UWgoOi7xXpcxoMlfDOSB08mKLkbWlCPyLZeRUzvcH6kS3+1/dK16s6hiXMYxZqvQdJ5A==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

