apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgBnKNK6EqCEHA/fIXG8WV+OFMxqfvSe4Q/tmCrYDf7V73xeaRxpHGhp1FjG+QCJpo+u3ikU0XitUrmT6NnDxexxcVgW/lB7jWfe0qJHFxDaCUYa1/+Xv1S6bV7h8P3+GLWkrTlbM4WrWexcXGmxKolUA+qHYXj32YH0plOvsIJM5O/6oqJs1JxnAyCuRHYkkrZlc0sQR2TIR1xAC0CA7GnBZ7Yj1DeneKy418dhfvHPw9YGdrD0Ydmb5cNNlOC3cXwOAlCJ9t+JxiyWxu5QPwzZHB7YS8V6w/kHP7EUTQbodIPfMfJggaFN32eLVCz7XC3eVlcfW17BRfgElv5O2npbxC3sd6ityWhuN9mhsXDBh2EWziE9f8AhMPDkyGeHRo8hiVV7Gdl3bDWgh5t0XJ5r4/pqOAC2apBGiGehjqBZRyvxq/5DBlaJVlUk/S+7zkVRqJax7SxM5Q2VrxT2GfzXpedf2o84Ppah6gwDzex/+dQwq/OTzjjvBPDLV48AcjNCH/JAdX9MnGQz5mi+QANNE1HE78RmEpSU/YCGvF8lrs0poTXXZOBSf8jK57KzSxGmD5mG2IkiK+bkX7wiOmp4lcHnC4XlXGumyEBygD5bmDz3LYDGpD51lxh8We5iJ27Rg4sMxrcx/YaybGnYewTQIc2cjfSrZjd4Vs/OCYh1lHRz7/Me4ZHenOkkEX5kWE1/HedzYSeARHuMAaPHzkT0daN+kLUMCfI1j6sIsc/zo7OVjQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

