apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgBeqrZTwBxlu1EBKYR6X5qagJTBR+Iy0rr7kLGwG10cFM3ECScvn1AxAtDcHJZmPkKS5zG6dQ48D0ITuijF6ItOvq5Y/8xCJojr9dtz+YVUewlpJfX1t6hO1FzLjjsGriCSsVFYpwmFR7z2B6OlmbLyaBlCbEpBXUXv+zY1jvKUVIs8gLVQd1mufZbGK/nBQTAjndcQV0NHRoOySGKvz5AmTbfnMEZS8Mpy1FPIV74uAo0T3QbAwCpxIUKxsiU93z2Nnbx//ZaxghZZX9oUn+E4KP+gdVgOJzueX72nSSn5Cd86sVYvbkjdpcWrQHDAmEmXpLpNudM/yKkfDYZ+EjrqQrW9Y+OU2N29HKhB24UCGL1Wvl2ciUsbB/Nxwwzqxy0grtOLt8lb/nr3ya/P2Ypr3Vu4IN3ZnlPaGO7gy54MPU8DDu7CH77Xqd1RRmU7JYug3RjLxBwJJdSqd0uut+HYHzM9SCdC8tIDtUdEsKf1Fhn5pC4OB5do5f1YLoIZRB16gzjsO/ANxj/kR2A6z+Zk2bw87Vk+VsrBQca9LoaApok9PkXPWiTkujY2fDACq0athkXPknDXOMC33q+SL3sHxAC36Cdbgo70vQ3jvdoX6Y6zetOECmhA7B4fI9JVR7fM8P0yq3tSV0NiJlgBV3VPBkNDh0+8+tHExSuF6tYq3lP0+T/qXbQdhP+ocADYAc56dKY+HyB5P04OgDasU+wMIZiTU1gca38DFonpsqd+9YinNQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

