apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBE56GtaDy6e4S5uNnrYWojIOlm0YoLciKnRShHUpB8hEUPgzzM4U9KLbeKeVUzFwbgvtl8Z1UoWAy23O0FXIdJFoNw34hvVD5FtEhORJMjp0ZAdMrPEqxfGom24XkyrUED7nj/pfdkywSbSssa5ueihhlNnGg0Mrs2TaoI2S0cw0PU5MlDVyheNOeo+qEeOEN9V8LbeCbcHf1UI6T95tJpJy0Xj3Q2pgpJxa5JyanYNDQ8YSV119rTJZdpp4FbAx2HR1+J15VCjqb4FOmBLgVkU39vFPnNCLHfo2Rj9B+iIBgomQXSJ7+YNMUwHSMjXa5//tj4vENp1ZZ9Rq6To+qKyE8WBKtbt52ByvOvRnoISgCwtMAQ2X1XLEpyedV0rXr+As6sZE90NKPQnbk5ASKmMpBF9TmOo8etPVv9EK4CQPd5bbrXyldgEGJ8PaFCiBcuxs+mm8RN/FD0Z6jFflWtiUAxT+yB3AmBzvqLSgQAp1DSv/pGpFleF9BNCQDAqX0GnE4vGJ9hjKJG1EjnS1xXPmNUemBBnqvToU9Pondu+fqHhKvjefvD4Po1ea6dv6i5+irk2efjFa7MeovjvjWJ5IBnjeE3oC9MgXpIugIpFWtlTCSPU3HUTpDiHKo9cEPEi0aADat6XTeIuaefw8LXZ5yEPiHtGFF34Qjds+flZEFv9CwOzrvu4KQ9SudFXqyAGyoMD+jLSfRyuS4cchVj7e4V7R5AIOSum73IRCxNvroeLk2BG0+/UP3w0m51lx9OsHfvW9N5ICXP8P3jvd5l
    KAFKA__SASL_USERNAME: AgCSuwal6t+jxSklXZmO/wS16mkSlbhWjabjqXX/jf+jfdIgaADic7Pe8Jk5GjykJA6TqGJzT2OC4yyDlGF/kkAJBq7p2IZ7tJCQIN+ijXPNeC2snaT8rwXPLxYRyJU4KxfCTl5XX08LJCNtP92mre6dzexRKU7Guo/eepsD4lnegSQVDRGZBxlWpsAFRRbH3SZzbyOW7qrO66cgDnkn85jwb0jGp1fR9T/9JMedKjF4HghTb2AMV0MfKKOfRjuQdp34vIkD4+DvINcbDrJD15c1rehZpdTML8ntrFZ6/oHY41M/CrkZHO1I2O+/wnvsGSOCs4CGU4IytRddGh+Rk7hFxbXOJdzolRqsY6Q1SkksvVzniY9DjjNzcjHpc6N1g76sbepUb0RI3oW3EeJEqqBBzHDHNJrJHBsvRTCpdiwR6hykwkMtjuXeifsZn4z9Z5XUILJ8Cp36j6dCNhX27qzKaPvFiEgRldGJI5sitosh94tETGsr4MokS6Q154nZReYJ+6I7GNf225Au0wcshnn8+d99gBwYomebqwzVfWhDWVmRbpMDpgy9Acp1H3lAsRUWaRpDkFhDt97nbu7gX81qxfaiGLSVKoN2PnpDsr7disDg81LJKs/0vAAj9PnDDoE5y1Q06bHwEMMuVUtefjICyJwF2PUGRYTuqkhbBkORTHEAHs3ucEIAC+/pwk1eIuRVaHcfuWzktOFFnQ5cXxBq
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

