apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgA5pvpGBhX66Py+EkdZoLAqLocRE0aKMpkD/HM3Q4zBP/B47IbLfT226yD72fJPm1HcVsDiYdp9ny9Q6bMzEsAXguOPY8QjO6jYunEwkpTOurHg7JN3uuBar/gUqtHeT1j05DMzpKLTcVb4V4QMJIvYPd4muKM9NkyGT5wunbthNugRPr11hyxvoAqF8K3Yoq+eqgInNQn02it1ycAccjmiQZQIKNu1n8nk8naAhYFxqy1YzP9xlJfSUKi98YwHurnAcLWgE1oycHtaCVzlrwStPYwktO/N/xKSDCI5l0F1x6+g+RvHBrgxfhKsIXLdu2HQEJEZugv8nrri8lkRetIUuZvtlZcCI6+AuHcCB4+wdtzXl/WyfIl8lp9TQjVOw9zCtdDkSK2gcFW12drN05RlKofbJOH4FVCfuVJY4+b/u+b09ganA7V1L8iCDoyodRDksdPBf/mh6gdVUdaUTI8cgstrmn1gx7BrSt/iNeLgrrUBLrv17/Fnrpl/dxI7ux3/ob+nlOg1DkfqDf5pw+YalUsAD+6ZkWwwdcfKrnBKx5OLqb7qrKyKeTZ12crAoax7xrGDU1rtU6WabmOwWrlzSgTVkqb+Q97bBgLXWbcQPQFTRVQatSBxxWZXZRsCLIIMV2zwe+EaRrAXUYgdkb6Jq9sJEes6iAWR2wMX6yK8LBv9iRmz0ZcZjutVcsr+pIawIyyZeOapqjfsYxBsKMZtlDzqw8nUiux+Ym5KGFwLvkIWGxBl5A2aAg9TJCtTEDUSsw1gBKUjZCMMGclRC/gM
    KAFKA__SASL_USERNAME: AgCxmVTnlOX+S9iq9C10gnpIKHHSJB19kOQSgW5IphT/w0IF+178LuewyPn8zaaa1HBA4IvO/z0xid40Y/1qriezbk1rYcx9GbRlvhU1G9cGw5kga7bhqpkVYJ7gJMfRWNHxEvrd5twxf2fsToMn98abdb7NZ9xBvZGGjE4sjj/p8rUzSPfL5nJrcATc5rENxRQvb2xLr4WfYzfA/xB66N7mWnKrBRhCKMcwu1PfMiAHsWOQsDC+tYcro35HW8s0EUkN37d7cXEDALYU+HrzuTavvlAjDYQkK0kP0NOA/lk7hWQkaQVrvmITl5BiGLpCj0shqOaxckJrL/WR6VPXIwdACyCtt20D7Qmlx4XhcVEZBEopbDDkl7N0/4OYrJWMIOR41yGBMWjM4wJ3cHCxrecY9K1J0Mg1QzHV9u3+bUw+9CGUIZQe9qAy86dLPu0korQ2JKDwplQ8LVWGwguAfWlZSqELSkRZ7eX5KZ26LuZ3AWVAm7kKxoDiDy2GUri2Tco+1xkR6Qr2U9sCLH1O9PEaSnrmA+clC3Hku5dXHSRIsX7OaG7J7xJZGlJsknto+/8Hgyq8R5z2V2i+jjUTKRCZ6M4QS9VTygn+6uggSdnQbMn//C6pgbroRIZMP8hg/9+skNrmu5GCIep7Oc2cECXq/zwDJwhWfhOXDlPs78jJIXtwYdoU63lAK46k6rFpcDGOF9dSvKdOGCBRNBMYM5Ku
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

