apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBEqmSMAb92BX7XT9zEx/GiPPnKM4kf0pvZJYc+Sy1j4l2TjrGlFu8IwyB+5k1OUJbSykb4JSQD+g9JB4X2NFz0cvznSdAu9WoC7SvY/9edoOV7hI6hEODgQO/lgRN2eED6vmlK2ZL1Yg7rHPyYrB8zeiIDK90Sg00xUnfqGITimEMweS5kAItQBJbYNDM5tc3UWP3/D15CE7rJeNnWN3lAdB3SK/kI3fIWnuqIcQ2cRXvRYAp1kb3LAlI6/dbT3zgYWXB1BTtdgTb9SucWfiaCjSQVn1x+UasyFHbYLF97LBVEWSOOGPxp9g72ZnqVlugeP3oQrXABvzgvjwQ/RxJdp7UvKR/+wYFj+BCwZhkRqPk9Ab5A3y8fHtrc+2CTJS/pAZcaObApBSn4w1n6RkEfreWsnXzDneCyclS73g3kmffyq4gKHocYjXF+pLB0+qwxi/JGZxNxbbz5JV2JmYdnBUDf6/Qr/xtF0Rsok341noPfLVHT/HXEQAPu93qO5T7cEJm9pEByHUEgXGLxeWQVOjlZnaeRMATaOWPN6SFhvqDTqDAXjsPLS/SJ3G4AwNCmeRkYrI53CHOzA+W4T/qx6MxWyZnf6a22upDHfopYXqzC5ikHaJ5L9YDZeAl1aTjvV/4H6agviLHlO7FzZfg5E0yW/aV0qmSMsNVyvbleKBY/Ez/hO2ALCaaftcihHKjaM23a3ZAE+hmjIH00RrXXi/kTvwKqAcbip5JVaWR9liEMOHi2bTjhpEdkdD+FEXWZR9zPFYtRKM7T8ItdXQLH
    KAFKA__SASL_USERNAME: AgCFfW6gwrsWvu1gPwARviJhBtl4xwQIPNvtZhfSuxDHL4suwZjWSfABumaLzucqFAY0SIFTLXr3zrE5JnRGcxJrc6DeKbGrmo+uqX2HglJDrGHGpUUWwNIW6OkauCfMh8yIgOfP4LtaIfmHBgu1xs/8PsBRLDAdKVsxX8ZL2/PLF0VQbP0kkXnSKwnQ4V3GWkSoMyiBrtDjRiQPxlbPZhoWvwabuyC5y4ERlT6ttBFqZaHQzxRW3dcxbL2GNL3vSZosDe+SFYpU0c2JiFUdaIw6QuyKV+IslVQFwoughgu/PSYZMTbHxv/Y3XXjWSYckxo86Ne8KCcoMa543f+in76IcW2IJ32yJulxzrBjjV3zY80a/WDjQGAXfcjTRNeT5lBLIv15ShK/fINzW0rQiveDVX8+lk+mO0OemxlZrse+1KKWzXbS5PMTZswhl70Ko0CgTiPJS1MQY+eQ0mY2+8bb8Pg4KFtWep4K6KXBwbpYYtQkJB2JbgoT1Dp/QdAUlakfp364SUEMv5iq6cG9xHK+Pf3gLUnaB2MStwxZn667JPPjoV8wzwJBG3iHV1fjmshMFDrjHhkq7wVH+yUpCHmI3deUft163L25G7z3+Tm0VwxXnVVkGS464uAME38OWUHPDQ2TKEilRY4N6kd3gsv94rz8RBiQZrkUGKNxdtHhvlNL9P7gElaV0N0NJQBPc2HJnxWg0V5h3z2Xn8H5fRki
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

