apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgCMJjU3LfJnypmKcRc1SUg8U7GhaSxZSO0YsEd9Q7x2DDcIZ1sU42gFnqgYXR0Qlb/a21qWXv+qQp8yOA/nXEPniAJUNGxocoEYIDonb1hDCqoqiiPOUuVgfkTDP3KdNd9x8m85ZP24opw49IipRzmRbr1m0JUO7PjYC7LkE/LE1s9ExoKFLsBJO7PlZ8TsvxBBDXDCfy88UozBPtYqzDDGQWOnxpZZwjgEOmqHhxjRHb5rjaCzcDh4JXtnHCw0QfOZe3Uh8RVYje6+xVnmI1PC18NPnRbBP+YXH63I1QY72njHbTJHqXlqyEzV6InL9IgWyd/O63Vr1Eb9wLKeSHPKhgPBMMj+084A6y+qEC63z0fK4t4ymb4iAHQp256bx2npWiFbosc7i9973K9KIg35Fi4reqomXietDXDP2Ot08LcFUtYn1TaUP0UI8vMGNzN0Qo3X3XE+sxHXE6B3ix/zzBujRff+/whbmtnx23SxZr9DhuRrj3eeDz4H6pFY4nbeUqvN+7clrF/NKeQxjSFsu9LB3yMLAq3wh/ltMXzQiY/ao8vrOMQFS3QSYw5iqdDwHvAaIdt5qW5hX8A+BoG00KJQQCeb5pcsvjkpWoMNNQARXg+VztGnY6i1n2lDQM+h8dd8XBp1yCFcAFaSxovGNki8T1SgmHpUUBpvAWL0hRgVBqHV8pANTe0lvyZaJcawhhS2GwVYhSV9kXUm74RAdLE654G0dYc4bziOPXgrX8XJI2ioP2xTqUrpZH6JsGehNOgIZw6OWLzObADSkCKZ
    KAFKA__SASL_USERNAME: AgAW6ZaBtX5tFIgaLjAJzUZ+eQshjaFjgzADZEi0FtD4j70rkmNwnVrak9PLLnwd47M472+O0yKCSqbGuy7ENSY4I5kKEDky2knoh1N+0CWezxHUHytTKRvjx7A5CI+nnIUca79SVWT3ADQxj5ZXZRiGL0Kpj8G4bjz1Fpf6h9VvrUN35FPc+R+QfTVZjgsr29CD8b01fyX/fQeIzvIF2Z9WoEOeK2bP6QGlLJuiQS4m/XYJv9JhtJj+2M0LiQXqRlrGk83acy9gAyQ1ktTmuYmk4Kk1tefQGejjsNiYUR07eRoeScRliXrqjDlAuZZIZndQr98RneOl8oxuZg8gsvmIQmrQpIrI8Z5+vfQOWvsS7C/pChUPjiIa3NepAjmevyU7lGFGRt1boKa84Jk/UFTm70wf2RR7Xtj+4KJbWbNg9OCs9Xj0kJaAoeV6NfOBpyjR+W4ZEbXAHjQKbVEZF1pJ2K/qHjHa8poLrKVYZW1+hHb4ker3u/H6twbbpELkoxZ1k2bLPVO4lbdYi4Na+tKUYKEGdFYzHZBdb3fkbsIRIeILYx60d5ZKG6BbDb4XgtVAdBpBD4pmX0tUeGYt/a+4CM/Jf1KeRL4T1Q/eotqv/SZh0f7QH8QfC8sS3xKf+SRuP5J9uw5ftxinfov8HYwQWS11uSJ0gTpxWH8uIKRq6OtjwPNo+RO152Dy7VXmpkl1IJGvV4DyDWAhA1BsrTY4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

