apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAAancYOArmzONUoRH83g3a2q5KnK2LwCEJMelsqYCiuwSxWVYEXzaUvUlE7p2WiwJCuN+uL8t6LXmadWnzlVSc50x+m9C5Yk/omJuibCzwkT+VUwWffX62neunmQKOyKsh238yEYJiGyxRgKNIWOJ7KjmSMaS2jAuVUdxPIib4LcFl4yyW7Gi+l9hDTH2mf3yspQyPHLuJNMctHuNEzOQnG61R8rqb05zSPzhfHI0uEeuWwApsu5tPAyaN0D5ZbIoEfNsBgih7wRgsRMs2GgJaQF807RKdJMgqJ491rmnxuYyw2LZeqC62NLVt+WK0h9GdydgoOkKoyA3ryZBKE4Y3guHG947njVinTLKeD0zP+AErRdVMt5gN/8ajCITKtTvbiuujZAY8aoT8OIKeexvxEDFmV9NfV4VQa6LP8iTfBSaGDcERSAH+IZ2ExBa/KSCL3yXqQnOzzDuSSBWrlL3lRDZnJ3dupNjVXv1rnrgCvcESzUqm6Q7ZHKZ59jwPQEFT6l7QIjmb0QO358ahn1ogkjdJcAJ9oe/tqDfQWytxRGR0xSWwhM72LM1dPfUYpmySb51BgJcn3Xg+hUM4cy42CrtTKJV3ErKfIpS3pK/yIXZ9S3Zy4jp88fjKOAIv1Sxwy7rLOO0VKkv8ScarwEHz/qyJzafL8yJvRFf8C92FeScJzFNWLI6ISgPPrmeKDJHN18shGpo1N/l7glXgW1k8/scB8M2+2H0C3I6yBi7JOduR/3pqG2lsdtq9LVF28C6JKcbYWM2GMEKiGXmJ60b4
    KAFKA__SASL_USERNAME: AgCP1T3Yh3Rfka45uZHBQN+orvYPJp0ThUtznjEl09c0kzhMajZFVq2/4bG0lJO/3/A1tBFbuSjMSLMKSIjizJoSi6sfab7+fxx546S7MPgPMdC25DRn4Fl1ipZlBVYtvj4fWRlrS/zmPDRo0MT3QrVlgj+Ug/IeMRPibDOUFF+GWcpwlpZ0/u4Xuhbw+Ke+Y6rpp52FFLVwZE28ORHDDINwyioGw3oxMTcjkjchj2jfW/881694VRW0FT3+w83D22p3etR+uD8/CDuiIgTcbEnaqVxOD7KHKdyAD6z2BFZ10J0J56hXXqqAiCtda0yxyNqDpLq30ESQMN0TLh9bgdkp0GS6p53sx8Y11T9bgfJ8Kss5rC/Iija7B7wPrc3Z+jtvbFyivOy9o5VkjCM1+5aWee+6T12NaWdJ+O3nKA6zje93j5uc5Sz7vYJzqBi95W2CLqMUtgF6iGviJ77X45pQDgqZJ+rel8dBVAnWPEuaWt61n4mkaTTxrIhna4Fe8sVBWHRhH0HGQ06d5gv7IRFVN4tw48JKha+2pDgmb0bUnL/jYlTqHIQoIbLw5Rbrq8f44JFtf1E5YYwUklx38SZdZaSTVrDKaCWtl9spsoE96M6HGrSXTd5tsGrXH+W+e9Yo1VNVoqV9ar9EHorXrsmlSvFwSQyMCTHdaHZ1AihEZ60mne8uOTMuli2BXYBI4HYrwASwmAGPN8qdjHGhVmiz
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

