apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgCryPBd9tx4y1W09nGDW01w7nHPuBT7k2AM9XnYUL7WcALtY1iOFfhL7BOCo4K4MDhMpQq3Z3cYV0uCUO9JnGzgEjn+X+nwGmG6zG73mXRX8EG/iECeAmWAU4TDAreHLRcDHJyM72FU06IqcJr4eR3N+VLYuQbyUPXBL5NmwyQMrS0z6KLSDTwoVeH8rGHolCMPKGTvivr33LX7CLftycvhnz6UajIvhFbyyE5DcqiDOzWQZrwrGZBmmiERAbhgiV2KKQyz9A5CGYR6sgZqtmhRos94f7KrgeoimsJKgHN9QUSRpcnrpng8/sxRfJDD2KP5q3UYmxCcUwtXutcD4qUF0vQkHamfRNC4cMgRN4vF/hwhIMvjqH1iW+zAN9RkSxA0izdwg5LbWY5gk/m00vNu/1o40tp5JVFOIByiFM4yAC6X+u4nFdK0pwiFDGwwo4Pdc7hrth5+aOKKmGoDtV/Y9ODZb6yQYpLoHF0wLD35wNDB8wwygzKvmPBTHlOFl07mc7+ltAlC/3LGptodahPjE9MNk1Wng0tazQr3p5O+swTonR2KQaFlL8HfdNMyufzEUEjtD0JoxpKh9/t7UGB2fyGLMha/8y5Xyqm0BU/RYWtZfqk9ZimRWahW7y5MGWnJbiomkcFSj0G4qhm3gzk6QUbS4QdFEvxneQJ51aOjX6VcKcjRiJ2gYEP/wRhnt6gtl+SNwZ6WyRt5OZiG25oCZiMpFY/bc+L7L24SmRO8WjDJAxCq5JKeVQNAKFHm5N9rQEDqebx7qqKQu0l9ijfR
    KAFKA__SASL_USERNAME: AgCIqWbhT/u2dhsDNZDPtxhmx46tt11X//D3p/4czB8I9pr9zCOAwylcSWoGp2fnwPnXO02IyqdtivJe39c7mjGU7jf1eyq1gUfisMNrZof0X2+hgtkX4oiigcYgTllVEvrGgvTbdeiNlQexYG63zbYGEXedFqh+AJaZWKVbeH7EWp65pqklf89+8wc7S0vS8NKtgZLx6cNgulN64ovkPw6+apZor+mtDkkLgrEZI1hdM7O0wPK2Usf59HQ0brnn2lg0i7V3OSoU/2BDaKKjnCCDMXDqG3Wt3DMneIyUHI2tbNr1jaFqbSBs+vRnCzH4zndvHI5pVO+Xuyql6NC5V5zB4XzxknM7aodlVRQ85HqpORMGwY5YukiZsh8HW18mYAj+M13Ar6Ro/KmSsQpxsFxSvrhKeZZz/1wbaSn26YRaISxtk+72WKlaLJcYFWddrkBQ40c5QYsnuxJV2pZd0483t9MEYZRBYXmw2mODT1b/+EF+7ydxbJx8HFoY1XSWnRr0dsdbIQRNcSRiROiVSzou20lOodThmaD4q6bMPataaFM/PvwTc9LjM40YAhW54W+gV7N0Yz25kBCeza/KxnzvjyD2HgRcyWiStz5jJxV7WFAe/wYUDrmJA4lFy/hziGLLHG9W+MQ++ir5RuJJZX0L89D061vYYqG9ArKZJuD321zwv4bKX1oy6Ms7R8prQt3N4l6ptV4i5cGiTgCCizMc
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

