apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgCyGHAlZMFlJaEdVcJHoh4VaRlO23ty2KCu/FdU6PEkO7dZbgfi0LzfnASaugsAzRPS5ys/u81apbnJQumss+HB1G/p5mvVcuYyLR+wNW3MTHbuCoKaVM2i002xY9d/UlzuOavIUhYgPG/qC3dahZZeIb/xIbVdj3jHV/s7Fwr+vEE67rYVzbHio+WeEq90prUII606+knIVr9b/n23tZnWYa8IsBFFvDeS4QdU/rlatvwANVMp75tkIVDLNt6uzH9gZ1qc3pbk0aLmZLBPTraKc4O2UDYgvfU2dZptx2HpHMvyuMwczpeivMMfFrA+I/y6hBsPd0skJoucNhnKTZEvTWb/nf3is65uHk/W8dSPidJUYv+fcHtLeIZJZcdzywx8exwYlDa/Agrvgym9tOcaH8vzSQ7P56pAK2iFzBxdVRvX9UAow2TOps+A13QMyBxP7DWn6beSAFaES+rk4wHLcXZFKJMDORD20QhvN2r5kMyhNJhPQMgbkaEX61BSC09RdSJaNw1RPfNBRjxBNMhHGDBAOAVDSF5IIxo87v6h9jQeSD1Q5NgfZaZQvL7vQvpBIMt92BMA1Cd7yZ30JdxOYrwVIDHlLqkL+U8Jp9Qp/5+6mJczW12kP0Tlh1h425Fc6ZPboJzfBgXpN/TbAn/FKVudKBpQCQqAd4u1dERg20i+uS53RQMypp4//i8K7g6JAHukKh/J6BEoKWGmCdxxuGEXR+mdFNkDO3oMcYjmOPM7m1hfK8I3z9Y8Efch+7aJHzfh4lb25npPZLwDvoa+
    KAFKA__SASL_USERNAME: AgCt+DBeinm0grfzzveXVCspd201/sn/CH5XJcNeKwbOWT/fAn1s1qy9OxdK7E9VCsQpP38xzfq/iThvFSiAawYv/mveUcqYSl3fQXGWnUFcE+4DLlVVWM68Y1p9lIw032ZTDSZwU4CyKFs1t8JNmtG6RagFMeDAkk2b/9WdeFdFPa9zbiWwAMru4/2vlklbn8jwglALyOBe6VBC0v0djLa8zG3Lt/N1fBRSG4p+HrnDCa5uh0PJ8a6if3Inz3YdbqiKeUjPrCHTMivSBZxa5hIipW4k5sjexXR+zX8YHDMx9ewijV7sQrKsCU7hZ0YWD2voFU1nNUdLBWG/9bdqz6dnmN/VoE3JSPAaZDY5KGHJqyIK1egJzCK1viJrmO7xV1K7D807j3l5qMPIWXTdEBorhRcUwgX1mA6GfFAjg1kC3qcyz1irvCICL1ALUpQcSB1LCWv6fPb25k3laiOTFyv07oFpnqhwPovPv4Ji4UmC88siAUVOFqLc1q9Ws/MVw0eaT3TpouMDW0kINkLyV4LdwFDv2cIPJAmsvd1gs8WpcOSpcBB/YU0OslsLc+mQpMJlWIKqRfSIRxfrNKscyia2ZZhyvodbWMy4sYSN6sK8U5oErbDu2Ip9L2Oho2K2jabSSH86SIdrRptOZ5g4VuDQIegSQofKGfPi5hCjWLv1bbF5nVotTq3ZBPPW1/R6i9stSY3dEHjIBqpwNeYdZ7rN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

