apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgDJpwKXVmzKewOBmYTbyTwlAnsGFBLi1ldJ7Szyx5X4KKPUouD/44YUwsSBpMGRD7jP/DkYVuWeLUTm7wJP0alemaMz1Owr25+AbR5zDuRcnxinu1mLoblaNohBcRj/ZtUdszU8W0DcUkC8fZxQbTjrVQdZqaOKn3wAbtiD6LzTkMknybA1eF72tQBByC6xso0UjVbgU7YneENCMEq/Oy21Y7lvkE02soambVnZ6qNVoufUyWrYTVS1a2dnNaLTkC4fiNTQtVcC4tdxWUhUBKmVsfrZKpDpxDjJWZQ7AoR0ka0Ugf7PK4Beosv7IiwTYU+rI7EsI4WSDi5BSuAyO+UMCkwdEniBUYksx7lWOLo+gnjt63t9TB4o06fI1P4/wx1d4zBnHpTTQYS+NHYemkRBexB0ipH2jh1CCgFIpconsTgdxmTPbir4KB/FjHyKN8KCybj0b1VdcFlXW2I9vhGCO7U6vhBg3lxI2ebn0kr0lLlHf1LPc4MfueEjgbaERfvL+6Was4pF9j3doP9Ghl/4kMTiQRAvYBw6vKvMlesTZDAJjMiV/mci0DK1qecdqodtnzQ6phBJNWTV0Tak0wjgIzRgCe13Frav9P6VoYHZF3Afz6dtsfOy5UybffB9mkxjBYVWMePUioVPXfmfpCkhg9lXXYxyx3DzzeaQWCg6b78lswkWq6qGWu/umwGMSPOPPFcsnKJJnDl/I4ftLCauyCJOm6caWZeuvQLDDSW+UnZgU8YS4mLr7Ta3Rpp3vUzKHA8qRO7In8Lzw44YY4wX
    KAFKA__SASL_USERNAME: AgAB491V83YyLUHWeZeRJb6Vkqugy7E/IE09vH5/mmX1MaJTgosp1s1tnboACiuJzLnPZ8f5ZMpNkQCCZOqVR3Hp674NwQOsJ/ZHZFfdUnWHg9VymwZTuu5yKHxI9uAlqqoP7W+zGA9Wo0c43+a8b8qExGBshjEPgbUR8+98y7qhnPHTcwgqPvjFO77pT3dA/zjo2YJXMdTXR+MeSTwmX9bS3bEFi+nRiAtU0Swj8GgkGEYf4zCUKB0h67Y6rZFvOM2AV3ZpQG8jMJFD4H6Ep7ObzXpFG8hvTGsZTK6gqz4YRe+jHeebD3G7TFb7DSd4/HPzi5sYbcYb2XOdeslgNmBj1tEr6LfxXaKPx/XKXvUH0amSFtHkjpnhQKP/9RSfji541dR3j8JK7zdukXUbbIBTJfr8apVp0dqvjGUghEktIz/tRpB/OB+t0TRh7pSyyu4FWj6kevs2jTEIPSIrLhKjLp5Ui7u3VHS+2JjrylRFgUpkwPvEX6RQjleUo1ZT+PO0c6TuM3m5xlvBA5TtD0n/IHAYdUh65jmWL6shcm/OAQtlbUIuPLbLKY0YFarj4cgdpJ/YNauyQ5S3FUK3hQ3HKW8VBpEfyj85scu9Xa2Eiiy23Wf8tY8XjDhwyb/tc5XGgf70ykLZbILlN2nx+Mut2VjfIZjszN0PxWCM1dETvu7PPvXCo8zNTFExmcjWdhxGjj6eyHyPsaR3I+lBF4dI
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

