apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBl6YBM9didpA7zBDT9sVXzkhDbSG/LG0ZZT1/B+EWNfJhvfPyPuGodTtkW3g5F/CC37lsZbPhD0AVh81f4K9yj1AMMOkZ5I2YNPCThivhf6WMCY7kkfBhLPKVOdRSH1HJIV2qYdkZh7pX81Lp+6rCLDT3JgRb20HjS9g+0zD8CmQn4K0XSMZhUhVXLod+Tt/6TazPHmfml8vPXYcVX0H3X8AI3JEOzEDkyEC+IoaAaCI3HtH8ix9/AeS3pLe3hnTSodWOWNxaDVu1ty2zHrEWy5aa2gkYqmJoQBLMlFkJ2hEjYN/mAKKma9aT2QrTfjSSq6md/Yt8nBG0PH5NbwZlJ6Fi5E0GtxHxVG5Yy3OOjRsRhvEJZDPOJt1AkgUnf8+bw8c58MxLdk6yhSkkPF/5Vswk+tfC6kDaSUixsXsR7nSgqF6T6n33nvhex8ToGKDjl0u2PJnGTVNXuXwnfdq/mlLregf0VlxmSKVNUiMQSlQMRMCVJjF5KPvuOgociC1whHosdb6YJBby54Ag4JjzfhHZV69+lrgHuJmyrVKZy8sLioN1bhZn7fB/0p8GoqdhlVzGjOTbcx3eGeMs/28vLIFH8aQRIR0zobBCHtKi7ayIQNaqjpn7e8d7ptlIfStlOOFna7kJu1zpT8p13dRdJfte+Vp+toVFWsL3eIo3xSJ+qbbu4BUzYTd7jZQ7mua2D4WUS6yqr2JrYmo/yR+Qwvz3u8MlvyOGu2xcanloPp5Tq5EwWExyXl37cIYGM0UGLCV5IDd7sHHEUTvOlhTFH
    KAFKA__SASL_USERNAME: AgB/9k02GE0OurZnvPuS+ffqPykNbfQme2korpT8c2EyFTHc5qgQ2Pe7B6fbOoyUeNWgYd098p4bPxGlAR05axzuEZepiwhVNMzcYoe8rOmeMSyVEvE75HczxJJFqtYse1D1NIvathFYm/QWTMG9LiwBG2mfYyRbY7cJ44AdlEC1zea82naMZnNFpcRsxtuwvXGoTRHIQaTBBpq6pMtHyB710KaIVZtR6ujefWXUNL19w4BahAvsp6IEimRCR/uvLXdYNnJWlxkkefNGKXaR+z5nLADse5a5XSK48nkH1KTYqmup+ZUgwauupn7T7En/FYVyLALnIEMXutPZVFifJKXeqe3hjA5G1XTccRKxESmauRBlS4pNw943y0g/X+Pkzwol2hs9WUfycJF8rXd7C0VJQ80c1eBehqIoniNvvnhc5H7zBq/Wn4JVooVrPoDAhojQyvPHXkrixzvDES77dJQBapJc03cxlQvdkGx5ARCrh48F3mUKkYIfFk94kUZEymJOsMAt3ugw2p/6dEnxJGCqpvTahpCj+4jP9iQ3zmgSWpSD9L9QoL7jJCJ0AcQaSxalPD6NeHlyidbjJfdeQsBoRWdYDqyCzAIFt/4A9mvELlHqWgG4NIIj7czSvZ/SSa0jFkzJH8nL9ofNbRK0qh2cIBBCs7v80aJuZd4nGxZBnBnGt1qRwKYn71SSvucLwv/ubcM8LQXs2YzO4NO/lIYt
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

