apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgCFZDRQmtZy63p7WdEcbkzveVqvLujLnahjY7l39j7IZxaIU7CuHV8m17HzL0L1uXWyXgzvdhk1y1B1boEDp4cCNJrcK8jSfRJGSkhptokcHKNg2jG1ab30Tao0COggQZ+BZKJU5V9aqZ1HmDyLoUCIUip+G4iRUNyq3EEcN+OCJ6a1Aw/Iqbs2wNN7nNGsF+Oop0yoMc/rNo4kHZDdg1Cx5+9sw1eIXAw9yME9zhG0IpqWo2l3ZYMZYJhMqKDIcGub1SnfRIrw2afgAxyZXvJFqHwRcXLC9CA8YtILiY3NpxlqrNcwETbQhOMlsbJadso5ZfZnoWdlz+/hn/a0eIEt39xwuXYlZObex5ouuoyyJUB9rnaRJZOllFJH7rFpXkEGRltkb21bmgqMvBkzDEmbWJ+UeXLpLfwlQyXNJf4VYpUbcM8WP6P4dSnmPMjSRE5hNvNaLbe82mf2vxWs2nV4Fxln+4z0W/XOzYKJgrpG0Tf+CHjPwdT+KbCYwoRhWu8oI9o1Ou5kP9D6o8/NRvEkWO5/P2Uu6+2H1WW95d2rSD6LA5s4qgdi+xQnizVohZbZ5jIsaX2gNJfTlWQdx/+K/It+dIsJx6l6q5qJ4/YUJKb5dC5t5grAt6oxNpxR4p5H4z0d7qQMA9z5lz+U2lgRZFw1ytOaXUDe3w6lrjU0cff6COTTEFIUcPAIu81a6dOQduBUQ5V/f+TRny7CNtFoTWUWDGvqTH7UzYGAZTD4tEzD8limDbhdGKh5wY58AZ9WUXb/olMd5aDWpP8Ap+Yp
    KAFKA__SASL_USERNAME: AgAww8h7fFhv4DCzKI1Yc3JYGDzQ5DGnnN/5iBV35xRaaHiUPgjX1/lifh3djMJBVVelQaYaZVCzZpCzA4rv/7qm4eASRP1CtwjtqJkLNAJNFDgeCLRebsOTArP4cv7mj09X/nj5UMSyI5k8bg3PRD9dijDGqlAJLbPj5anZor+uPHpOVAqvEEUAiVEQvZmh2ynbrZBsZjK4sYVEovCNWDnbEKvuxtyLtFdgdMbyXF4300BTF6zDnmhnh++LhfuWmE8j28dcqfjUxA2+daFnGLPF4Iv0XDe/9cEhlEimqhEr+fpBN7hzjbWM7nKedYJnXxMH9kRvU+42qWqb7HITOAMBSwZmcXb7DHgH6Va6KoqGmUL3YMoY3OmvWZIuEOPej5lNP+xQxJF4gtBSU6aI9it1pfYs0XIAd9w5TBeE9IqhGMwua8/hN8xQ99cBVVnvr9lhGqBRbehhJDpJZRxHLImnQKQ0ErVeRoCrsKmnqUY6TcX5Zlc2Y4uXY1zURw2OT2B/baeCmU6NyTsbx07SypJCrt38c5J8YgGs4W0mMBbsWicIdBeNLaMYP8pKioLv1caHqML+AE625ywAAL3Fg7loADsBRSfZux0ANHuFpiLvCxSMbzntXUWn/lDh5u1fUs/yJiQCp5wwaOki5WXmyzg1c+44kozI3xFfzV3Xg3Kdr6msXJwtMiPggDCCI3AsWyaH7b0MvkAp9NEl4T/FXG+v
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

