apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAmbPyJf3AKeUQONvgMaqB+CTUIuB9TgCzjGFzK3k2uuTw0nRB66DDT44nlHuAk5tyYF7tE2b0gVvGfY4yTHxvEbI89OA/a/PRdMWyNOrE9w85K09Fcf4FxJ4249flivFHdmzVf5EbntDveFtx+ukzUsJNJM+YmpZRgznMN+2ivbHj7k614cK9Y2o+QVlWbjKws7xSMSAidggwjMoSokdxUsnYjrcJ4yWDclOom+nJvmYqoSCm/R3n5d1d18VFPSbma8HRUszXA6bd0u8AFVLy2QgpLtGXGMr0vuK5ENlF731X0GoNqF6Doq5bEB3ROleM1LXRpx+egw0zO+b87PAie+fG1b8a0y3+jl23hd/xWeqihAFvaxD5NwlJqPkow89i1wtGPH9VCy4GM6fCuZwXjIx/DGq2xOrsUf/TBZdgKXjGSm9DgIxAt0cvjpytu48aO3xPWlwOgTssf6iErlpidjEKG3lroh0Iy7BmFbIUqD4gLpFxkZL593ol44y65ihduaPgZBu88J6yCrmVyHzA+YXyJtHRNnf1kiMu1Rle4G32nEVZEzSkPnLDRTvst+xC9W4uymU/r/CWd2HgKlit+8szkeUa0BEnAw+l4xOB77sX9HzgPWVXAlJ0l30XtbClt6Zu58Gwu7feqS0lSxED7qME69aSl6UdP6s9W4T+LR8bUl1wd24H9PDO+J+9QAP3UfW9qJVAOyn04h5oTkEnhsjl8bBRRB6CMImkfA/9PsU5Lgia0guke710YngIeugVuIzGTQv+qFAPyebL305WF
    KAFKA__SASL_USERNAME: AgDIKWFgFUJpgZLGKWJw4U+BqbMpmo+6Lc/f3/SnWeb9BHnBlE8DEZKB3nQohppB97Qx+KjlWAgmeXFRUeJNjQdnk0jwxBc77WlQuWB8eF9SwV9UV0F73lIjrhJYEb1KQE2Akm+FzRL2XwiMn6+mHa9MgsD+lFdj4gsqiGIRe707srg2Rp1qDJ2P6OhkmcphuEpDDgrvHVNZAyDLz92xAdrxiHKPvzZu/AdicVHTH+EWlDgauugU4B7DP95sGnEQNSMKThuxNPQSQ0wzAfSjozjZVubu2ONfcRNL81+DS19g79if9pzdz/NjbkPW9bh8fGerCr+XFvd9jTotfz2EyovtnOabG+lqbnYSISI/R4ELp+s6NH5YmV0aIjp9KmnvZN5Vj/BeSoav5psZ+rLq7kVS0PubKTkIE/LUiA9XBlWTx+4euOKxzMXSKm0xNLiSnmhOxBmqttPciUZqi5aXHGImEk1QOgpv7poB2w5RoQShdKu0YFF0BPcrQ/tW4ehPIQvj+0RShx/KlBBu3xCsMCrL8Nwah89uDbaIYmXchtRiaL3bqN3x6StAjy0BaxlQxpmTquai1mAvLhSbf+rVynC6S+qIeQVLl5ICutbbozExqDgp46BIjF8bSofuu2fII8AjN/xjI5C3laqx5IGuQw3CB89uju0olJX+QcnWsKi9LSDXzJBJrT3NIZ5bvNDFnqafvzsTKJEy7YOim5pOmzeB
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

