apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgDLHzGbIxizS8AhJ32YAO6J5yWmER4YBKLypVfhgX8rUQ+aiiNxUlVgZ1LPyLnk0snWABv4lcxr/zsNIjOUof6K8kc3lMEAjLlyvd6Hh3ubT1W/P6e328D7YG6huP+XEsAlDO1QtoyTfnB9/mokABwvcytvvSG1HVILt3gXhsqSR6SRwKiR6uLKNwcxxK4xhM8lBWVtFnUg+RiocZVoSxZq9SHDn72wYFiVg4Q5jIYipfYlKKj7Dq03qhHzO1YwvIV456ii/QmFqkwFxtv/qKfwi2Y4+8pbGNqTV+cu5szo6mj14CsgS3tY99NhycwIFVVlaho6ZdficZuDdLQwh9hWRYXMkc/DTl6FLXssb1sxeBLFdqR15jXDteGd1Ax/edr8jlRDDxpJ1f9TlaNW6MA6Y6sRSess1scf8P9nga79NJhe7ExeTOX3egE7sPmTyK7KFVaJabcT6vdee9OdWkN/+ElbayLGDq5WTYoCBDFYBi4NNrNWeuq8EoyQon0OJJKgYjyS+W5AXKEZeMI1WeEdU3apfjGP2LxlN3PhqG+XYltCFqHwb1X2Y+YlvrEShvT7VSmJOTslZYmmUely25+UzDdt0xZ0d9ugq2jkABVJIKpJEr29crJrK7G5aUGXpul10GG8Pim1QrFNFhhzL6SYF1ADjorJqRnMuEXhq4vH9ZlpDCLskwriwy9eXPHyERtBD42oHLMxH3qg0naE6J/Zt5aEWrTi5H1Knei37Ty66TiL8z2RC88KqRkxqcOrrSyUO+j53F6LQqsBLsdc0+Xf
    KAFKA__SASL_USERNAME: AgAZUhOmWCRyRoh6euc4Dv1UpqA/t2J0pjQwHH2G1DksPIegqK+NdSr/dMhgrfyatCHTq85CLRQuJ3nTYcZbP4ELhvf/tU3ZQKaAEQE0Ob30qU4G96ajEI5RXKgo92EB7mbb5rJPl55dHXnRCQBri0q+CS+VvZ6Ci2hDUxd98tKqL6DjEaoRldhuA+yjwdQcK1i996cochY7ZFPfxmOHJxTsLl/LhUM9RPPcbG1nUJ577whZ7yHoqhkJEghojB5lCreyg6QSHcslHjm/rgFotddWNzL3BUD8SXfdioEd26a3dXPHhNoiwLRnu/vNaq/WmB65M5ValHlTa3MCYIzWbB8I3lHX16lQ4drjoFUqesfDt7XPQAMjw/8LaF2wPhNWgUmUvcQhRhshX6zdHcHKkZfXB5Km7HuQudFvB79DIA2GoStQX9BVZRtn8v/DphPzhvqSQvGEDceYVnCznHD1f+S2PsYj18ZIX+/jtoA5mtfWjir/3wVzlosWQviJwGxlrmsbz7gEghjW/HyUK7B/n4K1XRVzSNso2HYmX4ma3C2+4N1Pl3lLtzJT70FPomFHnojXlDmUMlEIMbDoNHyPJbfiy8NhrJqJwiVdksU13+rdi02DuOK+e+Dul4b0Wfn0e1gqqyJWs1W36S0q348cjqp5hugnSPpdQfZvE5q6JnspK/Zr5fa/PoZbDYmPKfGQTJjZRijwA1CPA8hwlu7JYypa
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

