# This whole module builds heavily on this article: https://faun.pub/sealing-secrets-with-kustomize-51d1b79105d8
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  sealedsecrets.bitnami.com/managed: "true"
  sealedsecrets.bitnami.com/namespace-wide: "true"
resources:
  - alpaca.yaml
  - aws-flux-credentials.yaml
  - aws-flux-credentials-flux-system.yaml
  - database-init.yaml
  - datastore-db-url.yaml
  - iex.yaml
  - kafka.yaml
  - ordermanager-db-url.yaml
  - polygon.yaml
  - slack.yaml
configurations:
  - tzcronjob-config.yaml
  - sealed-secret-config.yaml
secretGenerator:
  # - name: alpaca
  #   type: Opaque
- name: aws-flux-credentials
  type: Opaque
- name: aws-flux-credentials
  namespace: flux-system
  type: Opaque
- name: database-init
  type: Opaque
- name: datastore-db-url
  type: Opaque
- name: iex 
  type: Opaque
- name: kafka
  type: Opaque
- name: ordermanager-db-url
  type: Opaque
- name: polygon
  type: Opaque
- name: slack-url
  namespace: flux-system
  type: Opaque
