apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAKxnJ3rOP/N6el+X7ndSZ5Ogz1A+sRa/SxdsFSIo3rVo6rz8pii0fPHrBFsziXYlA1K/J9LGo0NWA4fdj2BUZ45BH65rq/e4ZeT5nCok5S+uPt4GBjVykQwIDctfyM8R7W4yK376M2KVje2xzei1N+Rki+WRi2JJzJCZszMyGrrksvD+GbxW062WldByg+mBjKatJGs31rm+2MKbi/wkcS/Lt6JdDVixE0yig1X51323JZ12QxSsmjEboHIbkJVhN7yp10IUReMkwJfzl68+eA3CHeEAGvG54xGOeLp2hu2EefBCTU/qLIw5wtvVMO4SEnViWHGJQyOot2QSJJss2Bj96J/ppKAYAYi3pbv9DIC/tebpbZBKKlW1uDae8q+T9LPRKnpIu5SeByrKuwQ2qTz2izHE6AnZ8WNeECI2FkMzFz/b4FK1MmEXJc5p+ZAa4JiJucA3or7mah56y7cA+qJLVElljCEsmZcomZ4XITao3fd8UCtXTjpBDLtguSJBqacLXQG8aRgUmjW+CDHKVz/TccFZAq5KxzUiI8EUSKYrLFxqJycQadBL0O0Ve5Drkvnx470f+EwpApYbkN0U4hGdIFiX9PyzlBlcaCgsEMlLsXh1+Y0v5SjBeuGZkwsWKVn90EDZSbQ5KZyUdwkNlD48OC2m2XRR8JBOzBk2mksTMZohw3n7vHhszIUkZU+5/3jwIZqb+4GvFjbf6pGu4tKE1z2S4bqnALW8W5u7nqFQ9LCdHuCz6aMkeVmrpe/nyVvD87/DJluTB8HyarJFmMLA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

