apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgACwnXSELme8eMB2yFUaIex1d2avg2DlxeNSdBAISZO1ph7qQGRPlnyDDStieVFF2neG+GBbYZPiRkZLvNE37qTApK+ICaEvxx21fTP9bEn4M4zH24USDlL1fSY/d73rqj7fJYNkDGuzPWhHUrwaP3YJDsMBBdRjuY1jJvFTEfvWjgHgRqGEZeA/iiQdf/TaBS27xAmpFWNTUddvFHatlX9WwGzBreJx1fjgTQrfQZVGIXz8PCRzuKXMl4A+H8HwZVbfQRwYmx47i0UkwewT1MbBurgcXCiq8anBbo54RYpiTFFtjf5IR5tV/nGZKcDOZuNY0BgbRU3lR3KiORML3PfD+Kwxdhxga3S1ayeIuzixPIsOpq1HDvjZXD+tX0jqSNkV9fEiUQ9CTwFf6HyWwTZaY52xEc25oIprn7zkCskKxlw9tTVACx2u9upZ3uMXX+TaQ4yaBxpbX6GY8KGxvCw+D99hTa9yZv5WzzpNt336I9lyR2rrUo1hDVCbmmKy6NNmdAPvnevy4m4LPgM01uu4P+vzx3MvOkDgtPjynO47ytyej8KJrh9vUPy5M/nwAHJVfvXSbOxYNFFWKX6m35e5xHOYomCXxFDfRzqc2o4fuVkV1uhEry/etbTqmmybItGUApdOo0hmW0ploDxGbptYshfOXNx4AJq2ktUV3VJLfeXEYnYm1lRA0tXMTdrByUPeAVyKWpQYnP6cnW7VKfVIya5+D2Zd7YOsKRyNjkmeJKn3eB8THHlcIzxqVPjBPSLnzxKXbCxeIbrRzeqIx2sDQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

