apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgDe19gLGO00TPGLYA7jBlfK7BgC3jF6+2FecnY0AebYgkJIf1+aDmUgHdXOa4FXr0eQELoESSyB31ehBSj700+tUC0ep8eqFeOQz52ysYVhHc8JKQK3ITPFVs90k9AJaRHy67ZNkCQ188ge49J5HHHOczJarurA0JBJMfVxZsOPe9TpQw+np2Y8R6xqORm4gen/Yqpvchc+lnO9gjMoK9/QWihg26ejWlkEwXYQtA14qC0p/MQEbSiozgjUsToRY2YD1JfUaxLwMOvdlUGDYdoz4A9deV9m8vHZXChXHezRMM469I2kRLIOiILx40QKGwGWf43uasooHz/sYfAhcTZE5wcEol8Gawo2ve2ovRXNlYVUEHf5/Odktddg6u1D5/5ZXmCp4YKoblvvP00cZnj2ODURnktAJD1oKsIchqPjwU0qsFjdNb9IJfDZR9E4LZfMpyJbEdbZBwl2KXDVdBJ+iY9lJ44+Tf5HwSAMJpcBmqRw10W2yiLxEO+/ak+hSa9/muEYs50u86vrBvrQmDn2+yBbttBTb3QPgUQ5sTKQi3BM/tl5mqo6vmYAeS8TKs/twBwPTxjYmUkSfAPvPCdjs+0uSEbbiTqkw+IXAaKzZAbzBlslTaptl7GdDqqQSYk66h2M93bzaID58xJMwWB4roYmnwzXqT+sH/DPpOliK2xOeJTp4UJ1c75erB58AvCgLC0S4YqMtNCYZcjM3ma+YcHjWFWsQ0oqUMbKmyZBppmZVMoTGkcEucIyphaq+TwzI84ivs1ISB/t0dW0qhlnqA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

