apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAqBNvATxYkiovbMdOqPMJaxgUMWXJWYekJTuIovFsBQoqQSorwKHpkdB3JT+dRnsfy3XFlN2swzWNACxiG0vlfOiNdN2OGLWytJMcUNgevTkNwZa/Z7+mfp4ftfcSufas+Z79QmyOn6zVhMGURqtPI6rY+cPf74qdNe2IKHrIg4yR6kkIbCxWfLevAx0KyP2uG4ex6FagvrYhLVJKa6T+N3KrobfCCoj1lr6yT0CXeJPw9e8l9p7dffH4JKov9lnQcI6ayJLUnuZyinVuvHOGFuclGn8rThqGnRSuOXRD4uLhb+gLNLj5//S/Vz9Gq5bQsqm6pG7EAheI+9oZr8KrnwNIM4KZLgYAkAXde0FcdEZjkCe8Qw/KLw4YQu1+JK3joBaWmM+a5BfQ/M2Msj0qC3FlrXNOhxjmRWMuM63V8qa9Jmm3cmoZdmwDeYTPTl9rGpzzMRkX3f6p3XT4eXK5nn36UunPseZ5nPS/+plzQOoijzwCPgSL/Sk3HQBrL6xlgFDkVPs+uZe5rNlu3/kSM1VmxN9PSYnwMYwNLBqjq0q2BcijbJZGezz8akYf+NsqMEoPsB0FSpTRILc0+3kbbZedHNUmA5wNGt0zD4CnhxlTgzjAiO5qEfbCiGjZ9pXWPNTnzFGH/mG//ZN2ZtZnPrss3cXxgG7G3F2BVyI8YNeHFwduRdIoa0kwr2iRf/g1Q5lcbA3Ktr3rAi5kRfU/s89n8EdbGG4AMEnYlQxH3Zu3HSYLMGqVsXrahEzch6qxeaS9OHCo8rgLAhJZJr2znOA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

