apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAyGT9YJTo5jTaB9NmzGhV90ePyqO1IJQxKa8K18bbJ257NelrIa0CBEyh0Ek7iDsqPhGFITvwat/g245vdthzmtA6K2F6C+l3amufxPlC8nAJOiYwnm50kYT4chObK+a31H2QqR1oaLB4o5Lmjk4/j0sfI5BW6vIvEmzXomBHIpL+C9eJ8ud5oAL/QwDVFUaEMsSbhYmV5H8PQN1tDldbJSN1w16UNfXcdDPPyoWU1LTEz0bxhq5HCZ9160ijkVsTCYn7I+PrLx1sqLzVva4nUqIyaD1XCflHYskq427dnntW7Z8XgsxdQR7UWWSnFbgpNa7v5fmRzP9oOAI0yS2TK6MBVw3NtSizDfIaZq0ZRGOK3TC6Kv1UEPkkc7mg9qxgSdxx5rgSaz33rIcnERK8NxuGoJjq5rts9XzZXDTBi50fbD+tcluEKsUic/DpXGRY84EQ+9AqgIk7+KJEUI7Uy8ygHggku8mKeX9p6SsjHkAPG91A/mOMDfSVSx3qu2DHNsXrz58fUAaMnG4VGpcLpfVWTe/hF5fxQJnNamdHpAGGzV6ln0MWTg8fA66JEoi6R6n4abjq0Xx/36Fi/ryGhZzEUK3AdAQcdmrYvTxW07MHa37WLhxTYtkfq5y3VvNA5QJJtLFXLiXgj6/G0Jgp8KCqY5gBnIAdim9jiLRPOGGAMzXJV2UWZbrezDaqC+nXFdGMIaqd+wtwtEf3WPPNyHVaUfBgm6srG1Jlg/By06zs/Iop6+U4BB4R9kUX5y3Zi3OyPmyzQR2GGBStswh+gZQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

