apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgB8NqYcuL4ZeBNZFstY/0N2uCajrwVyNU34Wz4oIkFqpGQsM9OSSNMimRp5GaIAi04Vwpn+N8OHppII+syrQAbZMZkBPOjOcRDR3/zauKv+X+A9n6OYItC7MbffjvNuj37tVf5tK7eG88aXjocha0Z/ZL4cMsHe/NhGg094kqu4r0GwRNPfj+jI32Whkwvt9NAhbUWUd8fmK+48+2jmjXgqUGPp55GepfL8yJLgeIcTz6GyW9sRsmGZ8zQPYi0HfM4CT7za9fMLVhtiY9EDiXQhNODHQduCGHZI7xgWYA2iWg/0GhkTDJyeR3lcRB1iVYjZYMiOHzGSYFV4ROmNIXx9Rouqxd/+D0+sUCx0iMyFiz5BRMECiGY7rY1lCCkCdZXAKm5JY3uATB8KP4YI53+RrwwKugmHrcmTa68ZcFX/iChgQS+opfj2hdPP4Zwj58oVB9c8SwpWU86O6CUf0zXOJKTC7/HFkF7vn4fUlGWP5HTgoL1wG/Giem1JYZzwST4lMA3t14k39mhAUJgc6A1xN1/wg5QEYwus9xiGaa8Cvqhyl53Pvsx/QutKi+0XGhUpL/1hrjNQtGVahfDIEf0P5OWo0ubFDC9ByRTe6i7hBZi5OkhsZdDWWE1pVTY583tAKySXMHyN6YJx2L4OtsP/xexfP6tjhPnhao7dLKOyLKwWOrvjxjwog2c1GQzIA+gEqY8z/r7JuSS508svC2f+yr0jOkKW4CRurGzuJOkNp/e/zJfdoam8qGaE7HikOWeziweRsHM0q2hJVEqB2E0bkQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

