apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBYhneEUJ2prtvl1evnxYhDu7wyMDEwxF2cmfmelh6udD0pbTfQdB+bgv1wOyGB1OI3lQD7RIFipWl5z9vVn8VV3VcCqKDYSgsrU7mvvoVuBlxDzj/H/XJafTv5ALo97ndYTGD9CXJv05Ps+oZEZ63pNDmnxYqLRWlFPvUHz/cQwkUz3oSEJAIAdQjxy+D5ta0swEHL/78jBQIQqfD2k1WygO1UuAB+LMk1B0l9QhTx7wzHUNCmb8eC4AAAjZNPC+kkPDTF+FGRlAYZHKgYyJDDk1PMe+yryuL5D7n1aiGMMXjkrrv5Dzic+La8RUJ84DaJe66VuCsjXVx578W83iCb5hwePA7VVITVjIx4O0MIwIHzzmUBor1IbIt96jzQUHYCqJKXyReXZBAPmHLrElDTlQHmoHC4orjNKnfxH4MMIbGuIa2uEBwNlDRP0Uhl2Th265oIPI9AZRmHjkh9Nrtgrcr2psQ1BdTu5Y2sNuhXfyWxbAFnkvk14vqxzErf6BTABkEm/UdI8y6gu9m88ZhnTtS0i3x3+1n8+c5h7pxEeR+zhPprCNOK70SOp9SdCQtc6SVJNG2DXuHLl6TcEqxn2dvfGqlo0mJX5xzqUutHkkcsHnHcHFKul0b719OBRWFjFp2Kq5VVbiYh0VWqaqzwGfwG5lqwSNm9j5no3i88CYNluPGSd0FpBF9p5xLDIErxIXjY96LsmIXcBIUrpwgDpBhDSazerYYs/dpeq4JMmgwjGIUfv9O48de5w4Dqyrh5zGAZwPDS64i8jr+MwFPfZg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

