apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgBLvr59IDLfOpnS02EomSGZ4DGF8MUzR0oyzy1+YyuTpkU1UFKSSkB3rS8I9GB/okWnXQ2se2CEs3F9d8FoFlglpuOjSQVsyDGQ5cbg4YiO+EbY5z+KD14jlAYMTmllSGgz+yN7804AkC0VcpX03TYFmrNfCzqsCvkM2ppo6kJDvJ8J/IeudZtNd1bWe9d3piFgQiQgY/fEM2UbhABc1lof3RwPMOMigV+sfDD75Rg+c9eyZkAD179u4EadpFYV/ej4XBcJYhYjnUvX1hiKUUK0YNAhyAwxTSrXawlGAII7QsQZANSe2i7U3BRLe1skhohQuRX3/dGVwJhnvAc5fB/3jxb2vKqSrnm1hpNFRwGPN+DdKhBsptDRd2gogxWt9k519jtzr3HIsWcQC97/077sThaWRfCBu6shatT4vXFxXPThVC+onpsH6fCkW02h2eBVUOIShTAPVCGGSyTVdw1lAhnVDd/pSrTntSfoETzAw6r1OCJ5mpTeQGTywQDM9gXEMoWAeUTH/UNmnMpJRauc+2xXzIMMqXnU0o3njnJw6Ep8llgr4PfnM8MEpeqyXQXTXSqzUfcEPv3TcAoxvpffptkOwzEFGX0z4F3Kkyknr5QqCBW7IZDQqGFvnwr0BbJDL5Wdat4cBJ+JxwOi+HFqI2iPolyc1xfGJrinYYI8ctkBcfTbVuJTHhMz9FZPZw1nWSOVnZYUxChqxOnm5M+H0U8IftFunN/301Vdq25Zo81nVCzz/aD4T3bH3Lx5QJbdCEBA8lGU7DvZz6rWKKzUnA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

