apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgAPk33qys7ZmBCa/2YfXOoVqBKCCLcN09ajDJggQKzgpX+to/efglbYCXRJ257m/1kxTGWJxfVERXKOT/gH0O2dR0ylfACmMUGqE5dy78N7i8HZb0y89kUadRz23+I3FDmCkSxqaJ+f5kpwRczzhWpitHcu0HVr7LCYijJRdEuB8VUVhYF3dPh98lvLIDfV/DQK0cRFYRZSEu34Tz0hiAMbgXPhEG841PsFK0n5BXutPuR8XuN6p3Q4ivFRAFEObTSAnxeUd7AdNMsb0ZfyptCQl7H1Ivicz9OEYPbHvmBXTNXW2x6dyaS6PrNVLMjbcQPvbYoC+iRn2HN/kQ3PH5pBBrX6SZs1M5IHFD1IE9DVv6oxW12r90Ha4LgkBJTWBVpk2fHxkdkDWYeJyPfMzDBl6oF1HPU3tCMHpUjnydBtNISIRuYQfGVyqqSm1gArn92naGhCpzE+HpFBZJfhEp/ZP51SVMOk2GIOvk4lIwAYGpUTPTGN4LBupBY4jioBNWe7vVcVvA4yKwUHdoliGqJx2gdXn0PAmTRk23qmhKXsKEYvpDydQYq5OXT9ULoWEti9QcPpew7ZefX8gO/fS8UNUlGFnCm1pcFmwzufbO9QuYlyGipxIuz4WhpjHv3oKhR14nFIRhiDAs7paHNuwG4vCG0YSG3jCGpeVo5ZPybTQ5xJ3d9FQ9+7hZSIFE11BcDTJpJ+b8BTSff3aikaqPafFyLnSeZHaPqCZCdLssyQGA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

