apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgC5AcpbI7j+PluATdmick4hjxAIHbMFStlvW8dZhw0waH8iP2OE+wETPCtcMdHARBL5zRH/kx5Q27AXw45aYfvVMOUB5nPt6tpeChbxwwVAFjoCDkqWokGVZrxorUEDt9MOgR63FHrqBb7FKb9Ll9j1oatHjPUYx+yoRr3IFnsePUEj6jDSWpBW+gV3OxI2pVBIopzJU6r7gXjbAqJLqpXHvZWqSg/qo2CJ9KV4UzU6tcwO/8UdJJMpnjpy1MjOavSHbbbDP3anFS0wCZrGr9OHE+et/EMCCzrSFQBuYoY5J2muPY0vzJ4zldIlH0sNoK5Eq546HIpyScZMClPliVqjRt6jEbuHD46znuX/lVbCfLXp6RQw0xU/oan+sBaVmvfpxzGvg8IbTzjdZErX4czy5Of2CQUqjRFzUAznrB027T1sQAFSxkXYxcB0l3g/7yu9KW/nZKBQ0dxAQWOzoZ79404qCl8DOlCPJwaEyFLDvljFkO3rvWTt8CoBjGeHzVULyRyf7Pu8KLIz/ikIrTKnJYczZ1muU27xn+Y/eVWV3Mvy60OSUAjNydo+7h4ekBrTB80O0Qj+H9KFxg8cG71xsfLJguUaqe5bg6cA4r4zv9Xq59j+1wuw3arp/Zgeo37+pYiUeSB6/Ksu7WAdjefmOEFMNVUCD1VNcNbyDOoSAn0BQJCBIpNtbP8GJQnpD/IAt9bDNSoOIEz7h/+vLgaCP3/RE88VlNB0QsSJ9ZOe+g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

