apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgB/3d9wHvYbjehm1CogvlUjYZqOKcvqQB7BajSJ0tmiyAFZWQr/NQCV0viiAk89Vc+R1Sy6VskeXcxxp5nv+Yg716x4pj5khPHW6IrEsORb5txpberVce918/6F2Yuz7c4gAompDKjuj/+pbVi8nyXgSsM/WDyaTq5p5fURJSczrLlAC1E1Vg+aTCppYT4QHDVT8sZYMcxZeyovlSxj+G1G9xuB9Dc3w985imHBg3l4e8+gmBlgn+HZIPzq657dmJyOasSOkoZaOUFjF5vXwE/wcHr4LrCtbwRRQGT/qDi0KpPsYGwwwIR3auLGT9vJc+jRWAcnqU/zKWUmGCKRpoHCTIiVkdLYceSDEweQjDD4sI264lIBrHXQBJ14ezTp0xznWhnQADAOjjdR4Z/6I4kx9bl7ecNKcXkMFprs0DZHQQxdyQDdmI25l9YDjzkcj7s8I9uBi9ux1HmepDfPy94t8nhPr7+AOCKkowWdWkR4XVzFVosvzaBS/0zNBRlz4oLMnbenf5/12kpmdIxnqqPWjvQJXFSfKpvePjnQrnClHZ1VykYAb35NyQbugaM34aXgASzwpxfbrYMnoWvX0nuEFp9gyoL7YoVUmRPEvw+pAqFi15DL13RMalCo73bvrrO3xn5jjvjqtbmmle34iFMB/u29tP5dMlM6fn/bST0B5X6odrvfSBQQMWTzju17+mTmnhXQ36txCa3DtiGF+aSskt4KN+Xf6Q6+yT5+1HTzAw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

