apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgBVpiYZ1DuHAPR9tknFwKgfd1oaDFax4GwdXjVsi5DmNvAuY69u5uBdAl4vuvnjpmk1JZK8aDQ9Xv2Xe1OVivJgAK041rsscp8XikMLC5APltJ0ka0TnV7uMOl/JCYF6DhjChMDke2ctmB7T1qFnuFrU9j3hsOJJ1RjgkmzRbhYYEnffTuupL+6HXJ5/WAxkquBYAZsGEjTbL16/IGVoHcmdDFQrWnNfE1lHyyk+LLzAAjgK/HgWfXHSQmoFmaNljhneeEeXRIXHSrjM2aa/n0PVaJLks5SZBhuPvgoNcNTOkqcW/eaGNA1Z5ZG53llN2pBATTGWdUNTXFmEOvx8XwxGMK8l/p8qiMqd2DulO1ec/3QRJcwWubq7R9An5sYFczGoucLfLRhJDKiYLnKLoUK5Pspl68yNpeMgdWL1YMVMoTQ3drLa5ZXr1Kux/Evn/j+JqSG4WT+zd0W2z92jzDW409zLSckeCLz0mEyLyZwhrbXJk9XTGc78zyIq/kA1yioWZh3nd3j4nsJh9R3KsZkMYnPlCd72qgndw2RXm34HzAf+YRKJTxygw6avnXPIrJ18pcaUuPUz/VMvc3SyCRYq2LTTIeFiEspyANzdMVliwNnfg4N949WPO4yxvkvEz0Knws+7w/T56KnPj8+GSFLarG9QJwQeP3F/neSaYk2q6b93v5tWT3vSZkqZ0p9hMOEp86ZIcXN99NJCS2e6269Oiqg8vOPYYhQlW59glnXqQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

