apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgANvKw0RCGIMsdygWjhn0ccTehtSgDeGFCTUdH5HjeQvztlM9nTX7qEuYqQssTlOfLeuAAqjxOiTifSONihyQEcQ8Mc/rSTualEEgYzkLx+o5Wh+2sN+v1qGcws1iWqPTsfET6WRV8cN3CrPARx7pgZppzxBTHfTevOvxqjx+3igLzdLWX6XJCVarX8CTpevAsUi+AMAbzGZWajlLQwazV3L7Fkf/BAVuXRgH3EYq8SsxAYrhL/r1clidcLZ4CRoWJYSd/zJ4VUusIKXKDM412wBvu/rdgcYOc2Kccucnbz1oCP0xixb7JwdlnfgfVmVxM3c4tanRMMwi96Npv9OT48kGu8agpgANUeblA/YKuOpHMJ1Bu28PCO11Aj3CxBFPQp44nG4TG4GjBzVhFsUL5SMTqsKBM7ePLeT9FE1fVEj+O23izI7uVe1qwhMjX3QvaYJUGQPfrsb/ByM4IBndPI9NoLglQTYze0FTziXVZ7SDUYfQM4xEl81acI3c3wGnBJf2aFdJhwYaRUsdMZegUsVRPS+P073Q3pCjzzq7BcJRGP/kLX91JNRwRlruarxGQW0s0HjbAyQtOuk30/oJGDy8D4UJ4NTCGFoID6Ei/9MQ7J/FuGUj4DU/yxYpqW5uXb1GI3iVFHgfaixPZSq9XsLfvfkKTa0Ad64ankzwNAhyerCAflqm1EQWdju7wLYcgxEQ8r2cR8kmHIEiwS7GtJZTjNeMbJqToF+uz21FJrig==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

