apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgASX6wTrbLJa3X/R1eYhqIRHHCgSXYdK1T29CBtBiU9ivDerAl/jrVoEIQyxKCEiiIcfsgUnhSE+JCl9DpddB5GSK8ZAT8le/gfR02szN7cjsKMOdVEK9F7Xt0fSbD53c0wHnuOBSNnw4dashaggkIfk7wI6Nz8KVB3kFLyo/aVG9nwNPFUB++LbH6FxXnSIFKWYyJfOeUBZSn71tYGQzxjGb1lXsk1BWHVCova6CzyUvOi1wkfleOeX/Ni62di2qvwaYi6xI82tQ26WmaYzuMwhInxq1FdXErhip9etd0pDEUs+SVD6pfZ0+uaLwXgWqgAsf6qIvjWM/cp5l/+UYcjnCqTWGNTi8rK3VVBP64l4Kd+ZtoJgNWfZ55y4wA1sl+62+phhOXCmKUNH783+BGjGUCoq/xCi4+LYcmLvcGU/eecGkYSlnng2NrDu0IRZ6ThBQFin8fzJL+ltvGTHU57mqzBtE5rj+OHLeVgax4kTw+jIweFlUUDY1pVZaFi0eF1RWj5ijw6PhTnAjLqRvO8NOUBuAYW8I99AGiT0gfP02vHrnXqpSZxwkzhxQYfUKZvDyNf1Afga1UXjXlPxmnagaw1ebzn56+xWMi0kezoBnq3WOjid72SpRkQygM2Ww7AGAibk3otxGKU2xRTd+XIVulIzduResBXDjVyD70AK6MKheyBtur0zeAIAleqT0xRHLWkHbOTWjR7Md51JjX3SC8ZkS3cJqzTToTaxKiGIQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

