apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgBqAOnJvJ4wsfFTdSuPhS63kLHKKnQG36tXlyFFkHUT3uM+mYDUQCUUbrMC7+9ev2kex63a6Xl/VOghn2UaTh/H+yik9PIKiAN+WdavWiJ7O3LtsFNBEyPdgrBwqv/ZxIMw3qBKjjbpOu+4cbFgtZL8N1NYZbNNJaT5BquOHpoYvyOAxJASIQ+nflrhimjlvtJ/Y+meYyzcihO/5X63qTaOlHf0eyTHGDY8mknDduFTkFYa1P8ZO1jSlQCqZwQl1eAU+RHvdEIjnWUwk1+JiB+t/lzqyObJ3QMCGuenMLJ7xDrv5ajA3vnGUuoGii1TsTOiGgL+y7v75V1Na0iSPu0cduXDzsGyFT762HV0WCwNJC0FquoXBotkGEv8z6mcvdewUyRpGS8pSTBs/AQuzQtuzG/yGIySbPVc2lplN2nJaNXI2uduxtKYpCI72fi2YY7yzhhMBJkfArmmAyk4v8u1ksUJ2LT1CG9h1Cd53AG+IxOvOp1izs1UXX9F33kQgXhUsl1T8OZeCqocIsWi5GGu8QHekPNXbXWBEuTbnyebuUYLFeAICzhP7/3I3sEF90T9O/dIEf/2D1cvCCCG+JrjWqTVeI60GjNf552ZX9iCCmxxvoRxN42nHXKe8O7fAI1jDVzXGv7BFWklLsQ6NMtZULnu3/+0dbzjj85uG9CeDTtn86doXJ74g7kkQVUFo1RSBCTWOBMPsVF99x5Cv2Iu0944BjWcsCARI+Hoj7aQtw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

