apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBJL0rwgEocyVnrnrmVr/y1rTkbi/yacl5h/6d+L+uJxbVjwbM96BsW4DRcTzzrnTtrfqKgm9gdBdVVSd0WW0aeZ/YVLHWe0rYdeNtPXib7oVGhMtoDT3Gyl7YGZ68a1rM4gmxt9jhcAmcW4q0tsGmJZwROynf+epiicduRdTCntdQ6U/VUW2v7mbgq2AtHSUBsvOK1yjI3MgjL1QyzDo6qS5R7mmcz2egTo0VXM03wNhAOvo8uZKH+gAFlY/Ruh6+riE3E3pu9PxXUnrewiAYkuZfey0QJr3WF16EFUsetQiRErwtXkCE0JeJNKEMqp1p2xpk7Uk5fIM5GvXe4z1dhf3cEMhfXq3GkZ8NhrrS+eALbLdbO5qNF6kOh/VqVmE3fvqg3jxuq6K9mPZJhkTuj3JMwgvHOXnX+Z1lAGwokpYqsGdlW2KFy7O9SVY6m1BTFMwomtH1h9OKytI2n0JdSOtrm2acZJ/TCORNN4iB8Y9AcFumo8J8AQpXFA65bO/SMXqiwatIOfAabBtzdsET0iPGsNmRqiEB8IEt1nLNm8odk3OTMywdWQePG1XpWY0h6ibHa942+32W354P1yD+yLjGHQKG/92ervyW1L5/JYdezIdM+MIUIfkAwtcceNAjeI+bq7oqPUD2Pc91YWX0+ZpSRPixqeoKO4CZ+fMZZuFUkwE/yIO53od5s3O0ABgMP5F0Mv/HKMTCY8AT2Q4CpultTy9e/h7YDYPVzC2cZiunJ/j7PXfVl6kg/bXQ5zV4nfvzcIYxgVgTsakWTVV97b/OpjIYd98S1eRG3PWMc5Rk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

