apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB+c/H87H24YjacbeDiDJwFnHL0twcAsxTugVbEtj5Is1F460pXt3LX90bOErVhqkTU7kVELN6do7Mn5ztbzW4vJoVk2NGgrbWOFdMz721nQ1eKx0K0y1ydDpfSt8QWJ3W24M23ry8uBUuDkX+8mK5Ikt/Q+DcRs4Y1tXeDtubXjfMxkO+L37UXIwfd/Uw1L1lNko6T82Wlae498LeeEO8oABx+mmJHzo3x25cQi2KJAx9opaurJFSShFvUTQXTTi1sHEciJi9nODXgK+fPZJ4XdXvELwIcE8iLKITfRzPcmYsDeSfveub6aa3e54JGpZCrtlOM4J9LygnlZmajKYLQE5vI9YUEctCl5vrzAtO0K01t7mzexnPr7qc8VKIw6fUDnb3P6vxm1qnwliLuRDSz1AsJ46004HNsSkhVU/6lNn4slhE0FDORlkb6/kEv6SaaEmecxCWAw+ngocLnuIBxs3VAxB1fPbTnuvEPNQ28NPm2rThSk8vdKSu5WWYny7LwjakyiJkaulScxtFNw//Lj1EcBI3bz9W6HB/Abj1zw7vg4v/3KDE1o72FE3iCMzIFs1BiQ9ZlWwtuQS7yfFYhsgroTqsYTmEhdTPzb+ysPm8gvvSLyldygZFRurrrPQKjVpi/1TtQgg9NRMx+oC75nGBwQGE0Y2ygET4L/HVDnpUmElR/AY4rAhfotwVHHc0pdwEBOeUhBN9ebDxBqwRFAz489/FN1iWVFQIQywHApZNgCUimITcgKQrT0KQZKf7aLxRj+wyHbo8v2b6gaylJvqEoXNTI6Sv5FbANhQJaB9U=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

