apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAMrSFM5hhJhzfFfjmjNyejKH1XGDxlhWvMVMBdfpRFTvBFtcLZw4hv36+/VpYxCUTqqlKUtBN7Sdi1RbmpnRteGtaCoE2pqxQvbI4vCLbK4rN46RGIBVIYs+5MJGnPVCIa6VrKXQt7Ugpp3fdKsbjbpZeOHHrHD2GLPyIcL1+D8XIXUavQ10jdCCS8IJOptVbPG8JpBeIg5X30qo8oK1PymsOSpkmL+U9stqR4/u8gB8LnHlnZ/BPvuwM/7GmwCKSxbTC1hXZwzlStm4X5Cx0ftqUKVEqpUSzNhUyNFevj/LRybmynDe0khL3H82Y41mx4zZ9y8dB4/tvZMg4btTpk+xJ4ihZsN1J/wsoAuZE58YsHA5tVUiJdtWo5UX+WSsMAvo/7/4A9doYk3wVC6NGNhWpvA2JZm+Ii+xFrl9U7r6u01ZhRDiRnNcHCYPWsnpGJHEnSgReVQVWSg/r9LpsGOklSESUZG61M6y7fa7a559NMFWNqYyG51Aqg/rw92nBv/ouN6Jd/SvB+LC1xShe01MAquMcrQD6BZA/xOtVWJBaDnbLLWrcU0OUEDvls+c/3zj2YgJxjSqE5Z6tq/rVe2jvSxZoElJNe5OVWmzFsWsQIMytwpI28KtdfI2Gc4pcDDP6BlpNS4cWBpwZPdpDCKnA3PneUBn68wC5CrPILQX9AGjS0sln7QRqJhpvZidbzwmdz9D4hkp/l7qt+ciVFmlK0kvEImyM3cGBQv8DYnW5lXIjxL8Y7eZuu+q9JWSSk9v9YKf1G/5fRdoAwnfTkYfoQc2Y/TCZM3y9xmNJC/Ys=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

