apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgDQ+/cHZbx5J2S+UlQl/2Ig8extqj2YalwRzvyke3dABoVRTUMa4Mw9zDwQYpad0hMOS8g8Cx713Hb5z6qDPs9Q2rwas7yuHfLoj/Jc94mtUV3IS3tjhC+UBkvV15bEpJkZtTdhWdvUQuDYiLE2bFI9ICiRWZ5bL3OxrjlIRYPcoZIHNDHzRWmQvI1399WN3G2dueWowUosh6n+FJuHg5bx3HXsEpqVYAY5sWb0A/rkAqQqSFk3tzhE0FGt875xHz8LPvlt61ReOSrE8n2GyIbruLNSfmRIDW6gnjbR+RGOwLK63ZxkIckMQ9IJN3oBoL0OvU3+Rhy+X/QFInEZDE6+tUOUABSkerVNB6Fk2fxHNMdWBu9frYo5TPm7eMp3GKLXHoo/OHfDSwJhLxMqt8bynkD8I5cM+AgAB0SP42KjkZJXDYpy7WRo6nWP/h2dT2YRsSbQ21RakcJMPafrlX0U2g9fwoSQFvlkjFlgnyd/Y+ARNk811DU7W+BJOdZpCRmL09m9J0eoA+YnapR0EL3MnwuYWhQieqyds4w1DfLFr1Ie0K6zt2SfuNte2u1auyYhcNc8AJ+tyE6blBoh8SKZZBdnyBIioz8CkcJe4MN9UY3bnbryQ1BwOXyF6+CgMXqTq6QXDCnUufHRzv7aYQUdFYRD8NDkJab/Ddjzq/uUdbkk+QC4ZWsN6YBwib7CDEnnHlBFKzo2DhlmuJrJqfm4LLJdvXAz0Dr9L94qvjBxWgXbfxJW+ooujixGKUy70XTohPMo2DR9YR66iR0cLl6+JLYNc4Gw7fDfanBrX3Coc4o=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

