apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB4XjOGexNV82UzhsTjpECqVdfzWDBtsONTgjLMeH7IQfVujwbZnxnwalZV0GQVaRynLcro/i/QInL4hc14/h40feGGVea9qm5D3xdmNp9/LhrcVAdJuLqtDGCPRl0UTOpoGpNq5XpClTaAwDggXd7QLCq2GlInS0fZ4/P2IISYyNrmSaUXjNUQoeO/Pbycb/dpzVSB8Y3gDuwtuc6+3xkJaoZivBgh77pE/4AOPewYQI+fSXwbG5uABdKV7vaQ+DNE5uue7v4q24l/s1BwbnKEBWv99RbT0W/cKpzvPxfZwo+Qqd31/R7zh8wbTqMFpMmPQjWmLUzVisAGTOBBy8K6sxy3/9MpRCvNv7+kRjwP4laOUkp7GpZbajilvy1JAgOi9JJqKq0WOcoNRIzZ5MVIATMCZlSx5rcSwfE6tMUE1A/awrBY8zvX46536jP9Xukd9ekEYQ0WAsFyGb3Spr02wiN6LAtXzSfDRx9RbDoDCbRTXtpKhW5MvkAcBIA61PEaUhck38y6uA8TGScu8lOxoCfWxQt86Ie90auXKh+t78IrCA/CxWo1Zop6E3zAbeY6LVpgT8WESrLcPoYFCtI0n6BwMBX44dixuQZLg1FiaapmydKDiQWeY7lEVpMHzQK+4ca7b4ZH1k0E+Fe3+8Nk5RTv0D7pyHGfTiV5xS9BS6lf9F+43aHJb2U8/AZ1qQ7PbSCXMyie7wZdRNagIz2J3WXH423LhJMFgIbRFKcwUGhHIaol6JPRrcp5jOkPdbYs6dAcYA3MDJ6Vh45R9KYyaIBqh6As7oBIwPff48Q8R/E=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

