apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCQi7nLq2G49bsnRQtyomSlvY4xGe10Sxhtmnb/EzjPNuFjHIy7AWdkZvOJQAoix4M2WICYqPBWuEPBLLQDq0kEIqJS+WE7c8Hb1czIBkyoS5jB/nzoJTy5IgGF5h1e4MvKQshby4HSBKwmgwICxqcFCId96xvikOw2Wqu5C+HZHH1mXPUnF1Yb6Pvz1IXK0EWM2x7wDLVwkYYAHXu1wztKHdqsvLHG/N+TcSZwc1zIjIEH/sXHqpwbRC1BjSz4CRMprNuJ92AfuRAZpWeVnEnqXxhHRdoNpIf/vgpA6QBZt6v2oHp3IJFNejjSVJjmh0OoCzUXtUMQEUHHuEeoNQDz10foDMmVHmyhJadoBW27trikWhScvcKkhZrSPJDHRVDtMDmkHE9LaATBWH8KUAZVON9TElGxcjeW5DgbHhy0b40EUwpoJWcPQY6mFryaY8FrcenGJRqAi5vTVTBU14dQkxA1yPAyWNUtpPr8nO6fbzHnvtop4fCeYgQBSXZFFwWTr8TVo8fwjzM5zTeI8ZHnRPOQh1OKgxGeuqWmE6rLd3dt9XR7q73SOKPtaGizGKiQQQggjkn6alpCpqFpVrGjAaHU/iFmoTAJtcvsCWzQOigaFEaqkWbA1PBs2Ff/xVlvTTxbWTnpk+/mM6AdxUTOQJ3vh9hWNraHqW/J2Y4FURFkCI8gTqjOKkv3Wod48060K2OwfvzerUqcoTNWnzj8YZZnWbrkBBUmNRCsgL+JMl/Tipj72WfJicSbw3tn5BMvXXrRjyV5BcwYdS2cy2eKfd/RNXWFu87V9/n/EVl6VzM=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

