apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCTtoLh7gvOosEP4xub3QbMAwnLh9adp8Cm1Vj1QV/jgBeSZecbN3SYngQ+cdajF1SYchzlcFujuqCeJU2pgwoYLlblcCkWdd7KCBvn8gv6wte0HoTLOq882vDTZRXAS5wWVCmJkkb9VMDw75Ihb/PGY7HdlgHLtImGpOogBtUd8IvDxxjCQoRFQAF8bL+yBFf7CJGuntpLcejoxLJb5GR/UhbDITkfc3nkdnzdgSikVQ2M/19wuQ1DKcjqx6f6FVacd3aRBJkYaOQnBXTLTtEzkvZvT4KMankOHJ1AxmkLw3jcMqtTXyRfZNxLR/UoksB6sqR1OBrKUMUgi4GZKGMbI1oeqJ0Us0vMMF5+FpSc2jj2haIcbIpR/ICa05zB6JkLzg8zSl7lCIDUqSC0ZzOMcy0x+2s7TOEMX/1dO08dEOpWrEQZWKWBuFx2VKp2K4jWZ1wxm1u5Gq9/wu4g/iv9cEhQ4tROE+UGgQaQNiEUI1iPMlNK+HnoZKYqrWSSW0RFoUYhm9ZvOajJHDw2WqvfA3SNd/kI2dDqCKoA1xfDa4FSBro5Py2jNXfVdPQfYdfES4tZ2Qtm0KKlQ6l7USIKW6PrwBSo2kFkB1AF28ICqAdDNHXctVCaypqSL/1GjQJlYZ5r6WzRCZegHirciUn8fEf7P8bHEeoaOI+I3/gjnr25KRG+FMh6pBTOkqG7bbq+NgmEpVC58j4eFpfrdZ72VOFtCx44w77IRw9NDf4m5oVWZHYXwZtcQ+o29C6bx1PPgdQH/xvWRsiMRkrrS4QHt1XGPTXn4tmm/dY93yeYEkE=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

