apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: trait-finance-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgA4/QhcF6ZlljEo6b3Nx2mssKQN9BJSvEFvi1JhM7zKlUR7LPLBLhpBctOkPYxWnaAn6al3b2/0LpOzziJq1k+goSKL0aSMDfDsZF0lLijGQJAm+Xt3FhVvCT0NFDFCTnzgVUu8HVD14ZsOa4221k8kZXsJpTNmasCMcDfITUbPRxOumIjKWKXmR5XmCOlP90DS1atcRoL6HylKaWIKtz307KZIBU8LOaUrwaTwr7h5etnA5r5KHF9IEb0B2I1sKMcp5ZaY+N3Fu0XLx22AYnVKqniHVTwOPNB1Y13jUQDwjOGgRpKco2+zKMHSs/2huQQ77yCbQOCgennqbhVKIsY3H9YpH7sQ2dEXqp1uBVUNAEfoSLpxFRsWEqgqn1q9HNlIooI2JU1sHzJhZWpfcDF6BfbWXwixJLpILQXkwIIjw1KdI2jfWyHnxpBn34zoTJ2byDy1INCL0oh2h8rbzVaXSYsZoSDyaJKPsSOcnwZerHoT0W5mNuMC3Bha0V6qNs7ymPdE1ZOTmsLcMHN1mt3yYTzaQ3MHFtEZpAFJmX1HpefHr+Ieos2x2O26pNTOSdphemiCSypSHkPCovuRio3Mjv4W1/WPdQ2EvSEDVhr7r57Vw0vBDkuOt+R6jh4ybjXWXQzX0n7L+YX5xBUqHd66VpoIyVnDLMgDTf3INl+gfNBLqS4SVdxWntWSJnAcsQKu9occpr1bHISn4ivY7vAuVY9nmtLZjsWrO5nbNGUGqIJ/+z/wNJipjhUejGl72UZqdGfYEdEKioDSwi6U71grUE0=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: trait-finance-db-url
      namespace: default
    type: Opaque

