apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: trait-finance-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAt74bjn3MX692dkyYtCJt6dDd697CN6g6wSNkFgnS/MgSXHA1i5eE77zB9dYEaUaWle7ypwgxhaGdpPYsmbrci0wAMvz0t8Jz3ksAZ5l8bisVSCJGqA/oI79gG0+ct2HJejrfLH2BkH1Wx6axBGN5p7AdI0yNROZaKrJqJhcQElna3q7iTQv4DqQ9GcfOs3XNrmKv5Ij5GzEtH3I+o4T5PCzMNmdEjMseFYzXbEG/KIt7czCyHUgXi4wmoov6yEqJ4S1AvmIzTAZLGqIZIkxi5VuzSonADDZLyXnXdxuxkHz/3fvxlKxDhXXdyhMPIi+5hgGrX/OnDPnjtlf0MXpd3Gdg4+RB5vcvST0iZxqZyREKS1DRRIAqK7rEFe56ZymEO2OUiXi1UtO7ffbBjKN1OvjuD0iRbHL5rOel6M2etvd3gWaDw5cVhN4JdSB41cbOQWYvn3FDsATce+R8Ln9W87NSw9eAbqexJUADu9sLFcnZb4wOI2Z/s/t8W1D2qfwA3U4St53WbDds0lSwH0PkpBQDUWkJCHEMXsbk1VPJl+cbVsoRU2JIvOGLrgkmdrt+IR0CtsrEidplICkXw//xZ0zTAoxRwedoWKeaezdn72F7WhYnIeb/3WwqGQedqKC1v8dW793oC2VOOicMLz2BPK0HBgCKqKdLJ9OtO4IOC7be6N6Y8i2RgROYXo2TmIN7UIyDxSi9gG9rcbMtJZokze4U7I26+BvE7TquTJ65o4EUxR8RLKda24A54cbgxcV19LzOup/W5j40/yukmUcSnves=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: trait-finance-db-url
      namespace: default
    type: Opaque

