apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgC1Z59IJCdAHagw2t3BVMOKZWCTDydFk/BgfBkOvXi6UREHD7lsUV5I4pH1c54xXieG3Hzut9XnNsFO44wjFpTtBU5UMM2i2nhmOBJyiPFHbJyFLsrZoYyDz9RZLFnpuYQuP5ZnZlp0OZMO373LxQdiRc/qNGfOBuPtnidtHBzufAd5sgo7rOo9s1/tUAQRUrm1Z2HPn459zUFpViKlsig34NpkfvFGle3SAJwk66/k3YxSoPE9M2O2se980X2VTICrsdsnGFpFzneXAHiKnmYbnqM1FVRmaU9CtwHFEt8+vpU/+RUvwXZl/fn6+Wywfu680KnKekJA8NG1pwdiPLAxHikRpOckyMtanMzZJFnnODegyX2jLtIU9DKKAmO/qDhZM3CLl9vnPBcl0Tu8jk4kRrtoECthSFgP7rhsfLx2+7Z3MyMnHCPChB+RdOAGjhg/h8tQWZhk+F9kPihGJrlcu8UJ3JAcTs8h3EnMDOpWxAi4WeCLMN4rIWabsBqlymGYKBek7pZqQeDbZdLnmn/bLrMp6RfWZS9vQbSf/3OdUdDMoDLq5yz/KbTux+JYLiJsfwBWC+AywRvhjR81Np7LXRcYOZLVsXD8aiV4EksMtdwTv4KSaaxd2CvQOI1y8vStBhsxlhuByNNtaazKzM59h3nPO/qHkg+bOjaVQEQmyfQs+lqSPVh7gQhMY6QnSrgrMzqFGTsYkCt2cP2XF3KJ1zTFOAjYW+QpG3Jcn9r3Ev6eW1cNPkycJ3ZruCp/gCYXM6IkzGhDTyQQ/zzGKT/wg/Q=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

