apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: reporting
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/reporting:v0.3.0 # {"$imagepolicy": "flux-system:reporting"}
