apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgCJ1SMCFyB7vUth6icYA/ZOi4TCd774ITzobWhmWedMyQOXJh9cJzE2wlmq1vfk7jh6z4gwcshw2dzncVqfXQEgn15PEvldD757dVFr7KYveVhRL5trkH7jVGqbiD50RXql41RUFH+GT/jf6XIIdCpcyffxeqSX1RopoVMllZ+KdhxjGA154vcGqOdxXYhkMKjN/pl+1OAVcRZPsJ5TaPO6LpHzu6F1YOXSgazIXHfIiNKXS+yVdpZgLL0Bl2stL7vKf0Em2hd6rjSUFugik6ZJyATuiuVnRsQDywzEUgJ+345Gp0Nv/7XAEcFWSvGkNPfgldtbzQOLWC9I50q2Tk4JL5DnRY81IlrWZl9xUwXFWle2o5kUKXyMON+R4iHwrVz8cPBn/NQOPrq1wBSSU0NUmwIAxAwy2skyB0uyOvq54FCWGZyJM9L1PUMBGV06UpV4OT8Dt5sYVLGq3s4d6JGjF5f3AZfTkXnYV3fxEMo8iiDQXQFVt2RJOP/NEu4F8WRYXeVqPxH2m16VdxeyQcfZ+peI3ZuVPx4grD8OEdMpR6VeYgLkY8LtfsZTWw8kBovl/hzE9ae0Hr1IBj3PTJb4EiGMbbAWobJNw4XReUgZqzpI+ePofk/0STtmzAJ+DefQrw5eACfYDvok/36SaJwdosPUpFqTMnkQUW0z93pIzXr3iqXMZKRCdXdx/Ik3P7+Qas76pUHTyO77liTPiim6uZdD8Q==
    ALPACA__SECRET_KEY: AgA9PzYWvc5iWdlUdKR0og9EJcl0+EzDuFrMYFb45O+ScPmlfuOeS5td6f/UGBaFyzJzUghV7boXtb+MMdk/FJYcWHR/LRI7tyCA4pabPQXbgm7q4Ibm8rDHMRp+MgqJAjfXEN0D/j584HWLSeFnXVz4Ssm+R8e3C5SBEWfWOt7LKVJnY6DDmf7tvAFgU5dtcbHDQgNd/OnSCXZ97Eigg+a4FvATbH+/mMGFkesI8ZKum982D7nsdgqbBpymveG72MlkNVVvhFsNHgKcztXpUNghQa2t6brT/gwQgss9c2DoUOTmUhQjH7Fo9vpW+s7KBIBbmLLP3VfIpHnfRRFVkLq8PI1zNCG8dO8UCKtXEggsfflRwpBYcmBwrRCZ3yql0nn416wpUGGVf8rdtuV8UvQ5y60yH3pOw0sxaCU1s36WAM5YjpaTIBGYmOKDxTqU1SrWvfmqcwiReTIsGmLfFneWjbayv4Lo4BcXj2NNIx+xHJmt1/pc5j5uvy9b6ubu4Cdov8pLlNTfgvqtPmK1FoZzOiqbaJPOmwA2OSQB7g1Ih6DuozAW4igWs4gqlNixiKYeH8xiuFrkCEp7weW7nczzrWhrr2zZXfyjU7ryxvtzJfiiBUIFciLHS5Fr45S5QeKVLSvV8WnPYFJ0n1ekUMR6lLU02kQ6XHXW6OEtkb23beabahQfKTW8qptN67mqNzXJrwvYtlAq4nVXzYcEsiPReM7GrFCFdsgnPH8xs9sOQJd7SG0jZXYv
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: alpaca
      namespace: default
    type: Opaque

