apiVersion: v1
kind: ConfigMap
metadata:
  name: alpaca
data:
  ALPACA__BASE_URL: https://api.alpaca.markets/v2
  ALPACA__STREAMING_URL: wss://api.alpaca.markets/stream 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
data:
  KAFKA__BOOTSTRAP_SERVERS: pkc-4nym6.us-east-1.aws.confluent.cloud:9092
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgB0lKFns458zbQzGZ+Z0rxMNmaHRsA+MjHj33nhUgp+OcMV8N/b60xdhGRof3YLs/g8OcI1klm87qRxwR17GD4GVZrUcvU/O62f1E/e2P2diku46B8RBumXxm4pLxUI7mfLlH4WdPPUDhqrz1UL6UAkVuaTU8047VREiiKGS2dVkXFcQ/qVdABo90gc22NQ5yc6mqpIFnrSVbqInFg0DLhbbdWKByuFWaaFPOSpbKKB0QsWPivuHBX4Z+RLJ3PD1O+wfKNvItFaV+WVotVTpCaBLsYQNsLhmfQwEQUjWTIfj7sG2uDtYQJ2wG81I5YQ8eh0OhCM/kau+qSpKR7fvD4w7ZUN7jBUkYLnSyyYxj94ES7Sk/i6y9hPy3jqARj1OwF4pi3VG/8RykjzLyYVm2o0AFrPGmYt9x8NDGUJhhnOtmce84RKJwL9qXO1MUJptAYBAi9KPdc0k03jG6hgO1me1wCzi8Y1PxZUJFtZTQJ7c4c75TeBk9xSiREqfudAhSuV+KZ6SIhjaXWnIsqWuSE0yZ3BZt7ZRbXGHT+6vzat1l6BofrwIS6OxKnHj17jipMp8NCayW9iu7Xbza/yi3VPKYrJSX1qDv50XRdsZuuFGsL408qIxApidyzSgOFdvzcOsXA9NbjvdgIwe38BKW++RYm/BOcz6Q+oy/i8RAfHWi6gGJwjzEmInmceD5NLYz2UiBfEWeEIVLQuROdyK/y+dKEa+Q==
    ALPACA__SECRET_KEY: AgA7JvQsqB2nxbESUj4y4PwjJ6xK2MnVM7S+nRhQ53d3lpWpT4fthRa3Aiv0+6SjrJ82l0AA6Fc3msvxhwCQ381cOnalGSBECaeL5Wg8YsM7KK1GotpMIdkuJLgj4BbJ+0UxlhX3pk4i88pKkTuRCEq/A7McTmIgVvWxE5P4kUqjQ2OOIKPkgymlS8yEM1E/EDHO3b+a5RCQ+eALJdzz+kIAH/JqzaBc4ntmGLlPMAeiHUvRKBl7R5Zc2ozSHLlaZgm0DlUfmqWHBrlg2gSZ5zrvRHjXs1ch0+TRBTaYKyVcjzPV77CJ+EG+SRTSBUz6fshe4fHmXD7iGYMtPGl0NC3Ho5gmv9Zi1OmYdFI9zH9jcxNZD32szFeMd8H8Q0rygyLlTNIC6cuUzLtqL1hrx9fCbYMBkEe4tbNDy6HzV1IjwEUT5grCx6QrS3XSC4aUsMw13bP1I62+gl0uOjZ71bUPvOeMjcnd6w1WZacg+Z8mwztPpLNdoV5UdeoDc4WL69Am0I1ka8ZM0MMvpuOt8PC4hrBZme1royUmThrZ3tsZ9k7jdd9bdLv05Qo3MeWWrCfPo3gGvReka9LclrPSr/ZFnB2sxFk+PchiwQBrGnfJgwkO6XS5XUXeFMToyFqmWyZTZ1Iq5tQTbrKlz9GpFw7mUc0BLVcNpjCbawYpTI0cH4waj/twMXctsEgmshZMAjFwnaMV3nggX9o8fHwEZLw5dkzw6Ad89T1fTH8qY3m6ytv7g70MS7Og
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgAq8dgkLPkDNxjowy4yzOHEwwT8Ij0qkghTcL0wBLOrlnJjj4ChaskDJKSxI2UTpf1vcsdSS2EIxqJd4/XL9hnsvozuUNMbKmUnDQMZJKHzgSevKetPFga/Iq3ixhGqMz4JqSUOY4Ft+9knZhiWUz6d6lSnrHxNG/OE/xuc92hBZJAtYJtQMXF3SUi3Q13Y0/0JZVLhMH7SHVnmcd2HVYxFnJ3MAgz0kWxv62S8nC4jrXeiNfcF5QslJVNgDZPKT3uC6eI8lW62JLBaTY43+XrsvWqqxGcFYfxoKVfyYuqBxoUKLQp0icMh+Zxq0Va3bzbl4FNyK9YqNsY7fX1vD97SPgnAw5WN0PwFeTqqGfacLFEy9KRNP+0Km3c6AhZfxaE7UCm5YB6QwGcL45zPBp5iwPT4dpS2HJU/JQ5XrNDPlYUV3nnMXoIAJ2ooofP44vmAEn0caVtwVZK7R8hvuqvPm12QTYuN5uO2vLHdcoA5OJPWd8Cq5VLmyNHHtA9cpejtzLpuMWdEYk7TGSAsePxgxed6IjSTfQ6euByBODIQAQElIggRk5iW/2JDrtASGc8sV/Cgq3jr2fj5MTlvwcfwdYur1TA10BO7pN81BahXjeKaVM6eQXE0rUoxB5Vcc2eQCk0c6JeCTTbb9kkBqbx7CKM0Gh5r5FZRPKlPm7Wvl3R130cqDOYdjXIdg3+HKJWVEfXTcHB+C183kFkI88m9kHWS2Hy4ZpOl9ZIXzmaYpa9pMg==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgCDXfLy34HNiB/fTq//PIbvAVSB6Lrfph9digSKIHhUpsZzReJO+ASnyGFNh2rGSR5hGxp8p3H7ixj1wcAJGWKFTBdeI/6EbBHy4Ju/uH7LwI8HAAxVgvNATKFEL7PPa0fQ2IX3WgpO2ccbWZV58kmj3hkInr8pnZ0JGKyS+bYU4VzKuqVrr5aDtGSecmqEjDkm66+v8xQO6kLX8I7UakBgM/TflXn+VbwCi0LzPun1ZYgxs1V8k6k8O/350JVMAWRq43FR9Eennsi2v8mMmhNtd/0/tcZZAgmL3IZkGD+KMwbRPSW/f4H7CdKuT+EEEoYlA+OQs7QmbtLGdodejPPkmQTRrC6Y3MWo+KsY9xueBqp5K7Ctdi7+TJ0eJZqbX/wvqgU3i6jYruQUVm439q3vUPoFQYRhnhY2zKTSocr+8A34lMSZWpbpbK+ve7EUtERXWsttqgBQWJrL4y5r8bc1ATKEmndFsBxIXbi2fAjcqITlcSROnuq0g4KPYC9Q1SeVtp16sKqd7bxYknngY+J7HhYS/IkzlgsuQjl7Ie2xzj2xGNa6VTfm/Oy6epM/h5ZIGs9EdIMpv7COIReWqp07RX4ZyPIpRj3KqQbRnj3EqXmq5DGVFlVpNIWXd7TQs8uAQUc6jN5XQyEUTeBONI6/OkxWW/CL2QRCYMgH+rlFVTLuGmoeraVeCb2nvwIWKEWLK+walS35919NwTNbwuPUIcGp3Q1gJjfQqSphKnXnmrXbNzCocBl85gSXHPCgRCvWrJwX24QvndIPH1S5nukS
    KAFKA__SASL_USERNAME: AgBAMvwyvZGEs7pS1RXKEMj/KrUSTZkd3SCIZUgSKU0UG0bpbwmWDYrF3xzNsbUwLX+z3IR+WrFBPnjtSxjYokT3rVmPuZBpfoKG+L5ity8hf1yJwnx4s9IZZFcO/Ep3Hsg89V7Kvi0RGkhpX8XDclEeLiMfLjyOjdDOQIye/67lZbqJT/EMbOiEjy+xhAlLJUi+tAL/I88zMKCAUMltwu03sggPDU8DRubQI/WrL35eG0GNQ3bP+N46Slhjm636ZHja+u86MDClTOC5Fyk0mGo5+vg1m9otwB0Na8Gw8X1TvhSKJ7EEKwLgrSJWydf9LJQU+WO7YAPhrsHJDkatkOYUwlbN/nclqKXSRctkKW4Inltew+xhdNFGoGmynq7NrkVakm9rJv8BtI3NWhWmyXGaOrsBplG3WW7VKicMdIyMma9ZIW1TzPTiLQVm1jFXoXItHJUkqGFeR/awI161moobuC2J6ftCVXmfmy1VHFak7gUji4cDkN/0vLHSjd4z2Jq4sdYJ5Aoq4fp1P3MCKUQBjNY9VOxIO9xuEYZROPIU6Qj/gh5Kh/EKH2WBVoDh08gDToge3fDutneqcps0zDdBEhVSyAG80Dxn8hSBXokf5bwRh7bZ0AeJ7ijddEPTy1PhOJCoOJvP5vDJx5GnaLPWsNFRm3Bunv4F0F5loeuSoC+RjC85MqyZdu6wEgY9URFc7B50B1tzIItorUD08ZdM
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgAeRIxwVfVKU2J2sAK6t1ounJM9JzK58/n3m8e7sM6Me+eaEHzi3Czg3SRjuDvtBXR7Xme2+jmHhWw3oeO5IwybDfA1nlXotj4NOAOaPn8nlr82dFvwvTTscIQS2FJcD3RlcphI2LPoapmOpbUojdIB9Yf95b6co704vYU1Up59BYlDQTXo9Nm9hOeCVBpIIrTmxBqwSsGuF0kpG/gC4VFIyAQe7kTuWOJNR09t36I9PHWMG3kVOsOx3Inv82RBwEf6mGqR4ePb0XOHEo3fsphak5pGe7JTaasv8pmQm5xxSl50JghFSkLK5yiz7Urk3ELV+v6tV5vOp1CosIc+lqe34CJA743uSBlOKmWZpsB9tgJxQM80RVEc59WArmPH72xF8WHQPQH0b6OAww2BkHgFKO/91uqPvDKota4v6SKk1D/S3o8+kNTwSPGPYbAayjviraqH9dfqnOnxLs8R2HwUGjoRSx9Et47N4ZrHZdYL7xoKKq61zQ3qIQIVx3vZzrrIsb0Mb3m9JbyACmU3PWT9Qb03uPHvYJu70eAkfsR6Brvkj7RRzzSpudduGwuPcszFvfu0sv2qFsbwWJPfTLVeQQpXwl7pLMM8kKvg+jDZoZe+YQ0SECH/Ictdr+D523pVNWeugJablo20/bYnxU0VfN5fkad8InJET407aXxsaWpTfzS4vWVnC6r4LctVlCWVvzBAqhREiOxWcM8donaUj1ruqjiwoXrZKYx0LaPV9g==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCCAmQOWrCv5IwEXH26oGCNrfaO2dmWMV2/jsyuGf+oHZT3wszl64duip8DgbPfOAs08lXrdUdhSlswWhAVGwCVtKeJIPa2hqKn/8GTDeeMxYfHAvV4fexmlunTGD/xnzkmiXXF3U1HLPN/Skcl4CxAIe0lf4KIznYxQZa64CJ/qPAXvnQqWw6bAUh+66MR7xwJgbpRY8JHObIvUdhygsa3zj/KCJuWSUStdAM9KljRUKDmYOsYm/IRyzPQ4laMrCmTA7KeR0X7PV9D+HqJdMIjlnA3jJNPiY1DNkjm21SGqXhHP8QhcApggV38LFQ5QGdiG2pv0fDW9pFyuIuvbWflwb/qtfVxqo/mveWKA+26RBEuYFSbYwbUUN0Mbc55meG/ZMHObtX+OVq3w0I/JuJJfTSzvrvfck7d8zJMh40+el5yvnGFBEIZgl6rv43kVzwNf622e9EUBGVsWOLNuIKi1SRFWYdUFxzZGo0MnxZBbDNYKfHFfa6IZSsLMNU3ACop1fKNpqmf7W3x9uH4+Z31s2Z6hUTNlnmhiTVR4maT+ZaX4M9CRpXBKAdB/ykIlFzDW9gDtzASDTf7brEQgpdnaxTMrrrboO1IfZIkfaVt2QgvQuq9zbB7kYvcaWC4nXuP9Pmk5wRES7WmQtgpxZjHPY0qU7uoqg5E0l3V7pLBJ7p5RnWtxAfTuepcS7X4RhdkwFPDAueRJ5dkXBgzK2vnWO5Q4r411xYoSktBZxTt+2bvopMXUVmLHRkfkqwT/eGTdQsrkr+C+ry9FFGwvB6fUhDFSbkO4/1hRnj+l3m6+WM=
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rds
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAEPvytUY/YSoQSRvh/6nE01z7z7BArXiNDtP35GTRPh/bcq0VcW+BmaQK3fkXEEXVRwkTw1kYnaSgN9sOYa1h8UtroSiPMEtlSLaRm7wTNcjCzf0NHgZRoJJ5HZNICh61aX9FaAihGfdXWSdkWSRbzx0JP7Q88igSDhFKBS2iOl854HFNj6/Aj7Ne9WOq1GpxqwbMZ4Vn5EhAfTUsm80TRN7DDVTUwuPIayhiLVdy1wLPnMoKKz+bgQJhq7IKEDrdVwGsHDbj1Z5aWBywLdXNT1Wkfzs0cRsjAfXYt/4qXvBsTrBzsheA2LssHNFM6YN6lt5nDiGoZkeP4uYDlG/CKaawxCyS/rIOHLNEIRVCnMH10zz1LHzrp2E3X5zdkDFN1uEIJii9VFR3ZdtEIP2lUUGptRev03DdA1GBJ6d21/D/B/2qAUyB8kOnOcrLutlbenK4dNHFlbFPjcpMPwb2NKWFjTpIk2IL8m0VoPSvXEDi8QQABpo1AXDLNoHP9TZ3larFVFyddIFyIXpQRi30VdEs7hnkZVgd9Qg7LkF6ORPWW+yKLAVsxjtn6an5NuVivnaZCvis8Rwv0ii+uPibHbiYOMG/QdXeZr7WdgBtqYg0W5OmSjN0yr8N0j3ejpMeCTs2GT9+0puGMp1Dn0+D5VnkHkt67tS++w9tqjqO8O0o2Zxu7oxHe1QPSQnhpSbU9iSd8Q6EJKrNToV5LICxlrsQh9PA0kZaiY1ysY+4igUSEZ6ZxKlPFuVIrWOzh42JlokHe+YYabqRzJ55AZeBNkVJGng2q8YLG4N/kzVCewX6emsLx0XomWTIUx/E+XQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rds
      namespace: default
    type: Opaque

