apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgCEMhGOH6ockHNXW/cOMwgDW6f5dRh73x1+pXFxqj5d4VBywAlplCZ90w/B6WZd5A6bzbsPeuvxKiNuBDL05nxETxFwObSW5/t7wF3A8H33Qda15APQZHkMNh8I2HhMZ4WT0PBKEYeIeTtjEgtu/CzIEk/s1kfFJpMW8c8F/XtDULVcTqPY23Kg9P9xghGcVTtPIcCJOkbXcsOUhE+iW64fNT8REX/JmszlHaW6G8m1wKShRBSI3d7bpZrrce4YOMQhyDHfTacuxKj6mG8ZT6aWHDn966i45Aqr4ef5jGuw5789PNEeB9k08PJ5McF5UCRYgUrlSNY/gF5OO5GkkIX5IivRlnHB5HuTkDILBfqPJXALsCxoX6L08su9G8URaL7SMg+LzMmBGYUDe0mQxJliJAi84K9KNmNVNIHX+ZSPrJQX+rrdtMOnSo1MFSRq+0gZkst6dZ3rU/2RmZgbQICnH4E/0ciA17KjAkMcXIOFEPV4mrvEXR4zV7fAEXN9SPvZsX7lqlbFg2efOeihuZRsPZyiWycsKzFzBMX0ToSJVEmAcshsoWP4ksOCmrcFj1mX4JXHCxO8ka4u7VbxixjP6SHAlUTpTxWOFPCRWCw6vcb7UjqsfOJz+JvsBYxhMcnPhZ+64SnugtlTEzRVyN4SXrPDjbAUNm269Fuy3ySXSceAFtPwCZsymsQ2+iVADJE01+OWNFKIBsFle14gVWxZN3FMW+b1AVRed7qlaHQrln9RYQa5rrQvxud+9h9QFFKjGPitlWWcGMQ/0TpZdVIM
    KAFKA__SASL_USERNAME: AgBdb7UFkDhGMkbJAp41wozNC0ilc5gt2NsjPnoe4RB6ERqo3Q97GbZFw5I9pxaCcgVg4+uinQL2APL8E4kHnTVKKESpRiX8pAgiaGSDBF6L14xyhTBX2qyQfNCxBZeM0byXTLVDKucTCWxRR2R7Qn7s6HKzB79CtLQ3iri1meXP7n7SdKAIeFrdn6n9/jvO+ruPZRFm8peIOj/FBAKc7JBiqHbKP5uesg1ANS3rlJo8/WgkZyxuJGv55gNN9pfhFXQzBsIZpTRWTm62DJW8kMf3lJH6T8QB+upC+MuPT5ZNL+Hh8ab/ztnSgR/zqYuI9OnaQJf72GC+FVcKQIbnTwmbHlhyN9/W9cqH4yGfo9Cv119/Xa+/uM1uj6CH4JQ9FB7cIABiUvXFr96k9/IzTsyfvHDKMgXc1aVpNIAJh83+ifKCXfEBrlO9WWPxqaSg1NP8mRX1lxw0oM0IQOOXxcLyGQ6jAJP2cPmg+CzzZVMjz1+gEKq0DTEuNB6scCZJoprYuJ4ubcP7pNWxFFaOj5Y8rdCtcy+M/tFJX5IB+f+UyP8cfO/DxhE5VI4K3a5e/yGaZIAx5etD6Dl4i2q91koCtswO1474WvULMtAF0MwwCk9juuIo3wf4jgsiVLHV1ZUPrgn+LweQsEtxcJAgOLiD7EW4T0oUYchRoR/XTUsNwMCh/zdDnhHY7DasmIKbPic7Bz+YT6Unm+ozDGxjNOC3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

