apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../base/sealed-secrets
    - ../base/ecr-credentials-sync
    - ../base/config
patchesStrategicMerge:
  - ecr-credentials.yaml
  - config.yaml
