apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alpaca-data-relay
  - ../base/sealed-secrets
  - ../base/ecr-credentials-sync
  - ../base/cronjobber
  - ../base/config
  - ../base/trader
  - ../base/timekeeper
patchesStrategicMerge:
  - ecr-credentials.yaml
  - config.yaml
