apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  env: live
resources:
  - ../base/sealed-secrets
  - ../base/ecr-credentials-sync
  - ../base/cronjobber
  - ../base/metrics
  - ../base/postgres
    #- ../base/monitoring
    # - alpaca-data-relay
    # - datastore
    # - double-trouble
    # - jump-diffusion
    # - microprice
    # - order-manager
    # - polygon-data-relay
    # - reporting
    # - risk-manager
    # - secrets
    # - tca
    # - timekeeper
    # - trader
    # - volatility-harvesting
configMapGenerator:
- name: alpaca
  literals:
  - ALPACA__BASE_URL=https://api.alpaca.markets/v2
  - ALPACA__STREAMING_URL=wss://api.alpaca.markets/stream 
- name: kafka
  literals:
  - KAFKA__BOOTSTRAP_SERVERS=pkc-4nym6.us-east-1.aws.confluent.cloud:9092
  - KAFKA__SECURITY_PROTOCOL=SASL_SSL
