apiVersion: v1
kind: ConfigMap
metadata:
  name: alpaca
data:
  ALPACA__BASE_URL: https://paper-api.alpaca.markets/v2
  ALPACA__STREAMING_URL: wss://paper-api.alpaca.markets/stream 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
data:
  KAFKA__BOOTSTRAP_SERVERS: pkc-4nym6.us-east-1.aws.confluent.cloud:9092
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alpaca
  namespace: default
spec:
  encryptedData:
    ALPACA__KEY_ID: AgAqj6gtguQ6Oe4MrB0MKqWKDmiwsZ/MGt2QMgmZjG6BTbchE+GFN3UTYh4oNARyHunF1EBl2jvWkEKU/tvZV0mo5pDw4tBWLo8fjYtGTbXg2iHW1F0CcAQqDz6utwKhyfhv2jSs64LfqMTQqI3leOWvlQNgjSh4OGCp0eQ/01HKfV9JPznYizuOZSj3qWOOzS7slUlgQcOoO83x2Nrs6TH1wN3AnP3EfQ9PuHcTUyQt8VBpbTh2QJDtggwhLToMtLm/0N9pTdBcV2/3ES7dvmbna8tr4VnPhWk8QwTZerpsox088UCP8ynomYxPH+BKsOnXbF/LZ22jw+L9wOxtQGMBCxCploCkmJs3LUCE6HMM83U7xYsXwa8fQimPaLW5BWco1lncNyvXrCOOzx7idgGVdKSAdQks0wwE+JuDWxIebzPiKXaDEtcCB5YPI2fGzmYxOK9F3JeFzZorMNiujHP9WXJa+gi6Sv7wGmNu7pVWox2/LgByJwLWqQQr/14tG4ppLwMNe4u/RE1w2y3Y1F2aBCgf+P7UxhMETOyK2+MZ+THWDOl18AwpwqyEyUglg519IhPxW26zvFejRVfM+y1ZzukgWW/K7eVHiu8iA0DJOMNPlzMmlNPN5pzRfnUWLNjzrJJqEKcDPUnDjt3fPPOblFLB1CYOcplWSozvToV4uBb1Qm6i8szFz1NpXbnxSCZWvwUN9pBspXO2VzxMHXP9IkfnKw==
    ALPACA__SECRET_KEY: AgAI+Jhw+blZ7IsNUhWSfRiis8itsbJAQ5UE0I8t4z+FQj1o0h+BjlugzAoZQtJcA3Jq+asFiUIpPgZkqhUdG0YRtsZONVhPqFENzygS6J8k7bkVg/OhMw0RDItpMgG7EQYnPw4A6k5r3D8gi5XdmH9tS0kV/hhczWV5A9FKUCLizjVsutvux3OwViij2zdp63vMvSLO5ZhYtln2mHetHsNpf7trvyYQUYtlq5BKiMnkzJI3Je6qWF9pCgjP/qpJwM72hutjqa9rmNyqwfFTqMob4vnd4HMB/4eP6qzIzR177mXLTcmA0Oq+vBgObNPYSXwveAAPOB7a/+CstGBQ2TDHBThLu16OE41k8ZssDI31JT6R2EwDPu52JYg5oqxg3P8cXoETkaxnuCPs1hVRGv1Jl8K7/e5StK3nML4ZWH87yq5CsLG6tcR+we7SZZ3zT2cHHlEi0RwRxWFlo+ozw4jSSET0FTQ6NELIz+0xP6tU2XDSZ/lqyDoEmyRly3uutJbJro6cdjvCvAJl9hErx5vKhooZ+Y4z2z4z7YjzxX0gFrfqfOUD4xPbsiNKEKo6fbm39qMsC85wJdWBxn3cAfeJMRdRJKFQiDGPgl5Q7ABJPbUDZzAvljD8fDBwXZ8ujRL1OfvQ0mBT6eghuzgjS9FZK2Khw0QidR0AIVt8fDE1mbXs+QCHnoLmO5Ntxg4bcF1jaSZWPNK6EhELh0Q1Ed/pRuQJqCjkJivFnJarBGNjijmPw9KGAZDc
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgBTFDzzMB3B4ZLXM2D+BjHum3WUyai26j5H+Ey2vE42OW2pEW0ymffKfolR3J5vxvZZgMPQlSp2oxduZW0YnaaPDI8Q+0TsgscK6w1NahTPCQ2C1eN92S8/t9xM5VxMu1AYAE5ewETBpwF7HOSfWs8/QFSFy9T24GYtk481dJNHdgXdy6VB94p6qgomqmw4R8IVbjtuIgEFcLShIb8l4JDy7fd987L9i3W9MvkvLeBSyXGUgsASVdm2KQFGgXQmVIJyBJgxAkqalwu+9ubJspIoX1uy7HPUExULcUrdw1PXBS0MyoUMpOmxgbnt20dj6nWv4JRk1c7J+gHZvoUBL573B5AsL8oAZPUdZ0dW+M8CrCxy+DHGt9JewDYyqLWd9IJwWZz7GC8+sIT1JJdngQs7tyeL+vDvbHSeoqwqIaiFAqeYagCTUnE5OJoh5+YB6ta6RN5I1P8ISNDjTqxcKq4Mcpgr6x5HhlmKExS5gNSLZ+jFAQOe63lqD5cckkXWDwtXkEmLsS91Jt5npomgDHkivSjbQk3p8oyEDJZj5dh6P6D2cqFaFrgTkLWlaeI11zu6CGYgl9QGj2FHp1Cn0RSbOc/iaPlY6KjmdtmGjSfX6XJrUt8eLYvW9mTgf/nyiW+SmbshKgPGN1ViguZ5/67rqgo6Kr+xuuw61cajMDEBO4TMPSTT8MCpPUvVAc9rY/S8DpTNLGcuk+RvDm0Eh7DOOO9sru5YBBEaeW6gLD6T9cdnZA==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgBJv7okAtAl0x0qGfMwBkFi3fcV1JiuGlXDV0khoHm+Fia8bZAs5QWXYhj68FqJCPPJvUdEMJc5ELlWm0cCJu8/7DUpUkuKaOPHX5jeIg6M1rOh5eTFl9NWes2ecL1rlqZdLW+U2mJj97q24sf/o5uTzA+2lfWHoJcehFX+zrkj4bHI22+bNPItKuuc2CFddX8ob92rxjB8/KgtoGEAyJdbdrvfu4Oo+mmHUfZ93bhZqDeaGJFe/KY8MT1H2KqtUR26+JbuLc3rUpNaIBBYmYjKQX/ulCV7L6dlJwzEFoL/RxkRXuVSMmrXnYMgsS2j7EKfQiYJJZ3Q3GDImPM1m3RugXOkr1Sm7XyRxjmubwVRNxbOmggB5wqbIIJOia72psRcNQoVWeC8lv5tDAAbFWncc/pTXcv7wosXR3+Z9DxmRjtR008sEib/BE0BTWN9fkMoo+akxLN6tvkEjUGmluGw7pPj7adgpqZ92+fe/DTQw9dZnRcxmhCDHMISHVwPl8iCDT3tj/NYnewIQkETBjIH23bCaO+5IcWLq+67r1NodJ0DMTZ0rk9qKaDIdEt/eryDhG6rEZmqmFbQGkCIZdh59UIKeA9P+EHRQf+R8q2PBoUUo7gcTW9hVJ9VSG7xFyEObSKWpsxiu//H/YsMf4ZxyXkgoNxs0TvY1sQgPHCVjXE145uyxVCCN+98cYRspeTiNHQTfamb7vb/9ilE/O0RSEdSmAZP5vbRvogoad6ue2Yaggi7T+9dXRK5o9wXPQP0P/EoHurN2z/OYXZtti+U
    KAFKA__SASL_USERNAME: AgDFtVcXDxg2HeN9akUmnSqx7YcUgxQGZpSSi68/SN064ww82I2vbvhCIAS//z1trAOJeDuXOElg/HBe080j/3wm1zvDvkz51dxWbjCYG4EWERtks6auTBf/1czbWLyUyVvTrbkxXLsly+n3ze8dQ2IOkQ23BBY8QvxNV05O19tVVaBPE+WP4zbPdngpPPQIlPcO05Wma9Kqnr6/aj7LWCz+5lVF6cqPaPoC6NaMOrPD1iLt0GLiUMxq+QL6iK+wzF4HNfQFdiybUiFsAndPCI3UojsQzA5wISrEBYvmntn/ctImlI69yRddygpDhSGePcaN/TupeQBwCud3B7wCadp1H8HHL2304dbKVgtHWtxoWntAV+PNJjZBF4ZackZ8nodvgFGHyNRCSMN/g3XsecVo0N+pTodLtzEcgQ1nlnaj5Wn/4/HwJIQPkz9ruvNyrBvRyjyrjkPDA9ff32kbSgpBQFtq7iwJFANeXMfnRLncwv2FNT4rgxF/V1iMVoT+DifFzlje2xscU6iha9gezqMb3jAI3pRyYG3nkU2jgjQyGVj/Kg2rQJdZpEAXLtICgB2svb6h3jy+hFo+iMKsPJGAUWnK/ezlNJqSZASKpNb6bh0N/sGA2QlHX9OJTJ6VNR5mcs4y643yZso8ghH+CF/QWEZ0QjN8pNstNVkTFTOp1GZA8Ik9avFzqhZvpQUb+1FWaKjrIy1ynzHvRjEVRNlQ
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgCtKi7SVeDNMCDbg6FEUDbERZVjRWFfZ0kziQ2sJE1C+TYQi5AyA9m4Sa7kyPReADnsJ9v2+XLeS9dyFxlNDawJ804CVxKISzPXW09S4uIyWTHBtD//3zNV9TIVSc6G25WaMDoMO5walhs7Qrx0Q8ENp4MueZnAllnU3eKVPoBVtV0EpRlIcrUT8Q3R/JkBeuzyUadOrX0kZMi51Qt678LOGV4gsqZwp/XG7sI9Wozr3hwjAkvF7YuxG/DsW4ii9GFaT7xLKtezme7zPGPM1JfVIxrlFf503OckGZ0Sv+FvV9+un9PatguSVa3zS4tRyMjk+vX2w+juW8IS1GgfXUefW/hP1mr68tuqeHPTjbV3IsA6/SdR3D4cxPRRhwMfNsuBMIOsem079XjkOpO2ez+uSfvRvzi7dt6pKIawqFI03+pDTHOmW6+xzlnxMWqgekMfyLgyPQb64T9GynI/eBL7x8+ww0PbscnCsubj9EWFCeqHO0xWWIu+eZ0sFVUPxzCBTHDohLc9/HOIn9rQi3l7PJZipI3PinhFEOc6wG7eNYqFkMMAn587MwmWKsczjmhvNrycMf04Sv3y3uaSlX2NOhoEV3wg/VVSZ8OYuXrFXXoZvPZhgqicBLKWvJ61sslhZyrnxDwOKXUII7YgWfzccW8HpBrY7poqTFVgllIB0URQFj5C0I98EpNcUzUh0y9pSG43DehFJNLz+zXqJ9eSTEg7cbaghoywap0881bLaA==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBbGKmT+cHFdHherF77hNTUprgWMm4QAxedbvwKZJntcSOBNwqMk+MEbW7Ye3aA3lK0iQsE7q/PTCjdIMlt0zezS8unEzKGYD2cCBjpmddOifL2kYx/pU69WcgTghxRZZaHV3uNGL1bpF3DFe/22XvJkYU9j5yJLWEMKto6En84DNHGMRoPltw3zpx3ird/pWmEGt+cKxrnTsOsdILPiMVPdgdeg3IYnU3LvaMUm9GMv/egoO3nEGuy8DMvfdyWdzQE87/uclsjkYy+XerDU0n5O+dcRkfcQ+JrjnE7z5Z0zl7f5fIIgiMJPxpy7lpAA5HQcDi3j4FQ5hJIi7UgleFI+wOxcQp5BdY11WQ7XRhgi7LFMncrgOxEq4nrSBld3LBiuBxsSS1vMYC3dKbZI/O7jTUzEe6VgXgS4m1d8ZjlTev48nbhnybTJLf91HT0WywMqy6PhlMf3TF8/rX2UIOcXoSij8joaLIqQpcagc09IH6DPAhHHmXll6GPEoEVZwLUtsmdd6ptS53bse6QidEqwjmRUu/88iYOH4ACR86Z9vJ9fbH4sI2tx9dmxOJVjsY4Su8sdiZEDXv29OwvynX0Z8KMVW1QR1YFe0wX0sHBl8lwob/n+vKTMnj3LsRBBAzQn7SmasIHFlCocq6F1Ak8dF1Mq16vjo8PWwS2GtZm+q58XYwYUjIZskEuWTt3UzI/cV3Fdai5BwqjWfofvM+1b8tYVkD1HwGg11hsyigvBnCYsC/ZI92VB2Yre4HZRq33v7OB9WEThlXxbKD8aGF5yWBvtet87+9GSUw9o8/OWKQ=
