apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alpaca-data-relay
  - double-trouble
  - ../base/sealed-secrets
  - ../base/ecr-credentials-sync
  - ../base/cronjobber
  - ../base/config
  - ../base/datastore
  - ../base/jump-diffusion
  - ../base/metrics
  - ../base/microprice
  - ../base/monitoring
  - ../base/order-manager
  - ../base/polygon-data-relay
  - ../base/reporting
  - ../base/risk-manager
  - ../base/tca
  - ../base/timekeeper
  - ../base/trader
  - ../base/volatility-harvesting
patchesStrategicMerge:
  - ecr-credentials.yaml
  - config.yaml
  - risk-manager.yaml
