apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../base/sealed-secrets
    - ../base/ecr-credentials-sync
    - ../base/cronjobber
    - ../base/config
    - ../base/alpaca-data-relay
    - ../base/datastore
    - ../base/risk-manager
    - ../base/trader
    - ../base/timekeeper
patchesStrategicMerge:
  - ecr-credentials.yaml
  - config.yaml
