apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sealed-secrets
  - ../base/ecr-credentials-sync
  - ../base/cronjobber
  - ../base/config
  - alpaca-data-relay
  - datastore
  - double-trouble
  - jump-diffusion
  - ../base/metrics
  - microprice
  - ../base/monitoring
  - order-manager
  - polygon-data-relay
  - reporting
  - risk-manager
  - tca
  - timekeeper
  - trader
  - ../base/volatility-harvesting
patchesStrategicMerge:
  - ecr-credentials.yaml
  - config.yaml
