apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../base/sealed-secrets
    - ../base/ecr-credentials-sync
    - ../base/cronjobber
    - ../base/config
    - ../base/alpaca-data-relay
    - ../base/datastore
    - ../base/microprice
    - ../base/order-manager
    - ../base/polygon-data-relay
    - ../base/reporting
    - ../base/risk-manager
    - ../base/tca
    - ../base/timekeeper
    - ../base/trader
    - ../base/volatility-harvesting
patchesStrategicMerge:
  - ecr-credentials.yaml
  - config.yaml
