apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: flux-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCN7+sJr9r6ncK2A5Um3FgG+lxCm4bnEPMWHbsL30iSYQsH8+TZEns6mm3rWIfGxHwG81ZH5HvL5otwnmMBHKnDtvFbHDmp+bi+nZZsUBlY+E3C9KwoXzH32K04XJiWn64eZTAlGdQ5G4WtBdxtQniyQAZAAuGt4Lqo1MlyrB9z0vZ212Pd/SOrAobg2Ch13FM4myYE7rLxxfbOLj2RqGfe2OJzzNipE/dYtFkKvoctgXRCZvjcGb8iI8I6LuCjcg33+qlPxPqv8YiJc3GWyPpXtxUZP9/3352IUpaojc0zU84GSRZTIfXxxFTr+VhOaYrEb+2QX1BLCxTyeeOvIGX5LbeJsWgvOogEDSrXqjkcT0DFBnEcV4iS116OiBdzqW0rHfdJk8OexqaVe+EAVg1XCGhIMqNh6VxhLT4vu9rxjpklYyyxcmmX8O4x3EGIM/3gkeN4/9sDewp9bkp4/QWVgGy97fSP/bBQpmtojaYwiQdncDb3/bFnn1TW18kIdn3BomQ2AWQL8ApAs+XPw1snF83JJ9bq2Jn24EnFx0nkZVGACI+ixSCRE7EI19KTpswkYuWIb5WNWP95IrxVx8tyEgieL/TZ4kuRskQI8YE7fJ/JKGAEfNMNa59uG0MAxq4m9JV+i6a2bCyTmtL5HhPHscnoYt3jQSWgcKy8UQh1+kcCn3Cxyrdc8R1srcQJgJ8u4I5qNm/aX76H1rSN657O3NLq8w==
    AWS_SECRET_ACCESS_KEY: AgDPrEXnUSs4Zcm+753PT4mb0V4d6n/GCGDzjJAX9yTdkmS5XezSFm1afiQ9cUcC02syQ3qzyEyHxX0VMoe1a5X4vNvkZalJLARKjzyzfV79un+eUJPLCyvVZcI0kVzNKtT2pYsnVZmUj1fdzITkGu8/PdmpEvrLeuJiwQS2Bwls1eOcLGcav7rGjJ6If9vMZUbinw6TzzJ2FROMjiM8WsC6E/mYndtL5lW5ENtc3ETLG7RsLXdTUZvo1GQeuGfcsce89fd2+PHpu6eY+Zpdd57xhU1aBRQjcxmDiOxDhqb7Q91AISGQhD+EZAc1cFLeOk1sCn9SsV4qfvTpI61gsFLFpRsUTfpbpxkSSTJGw1SNLvqVIZKrvA+gh8TlmpdaBy0EfjNUAco5GYUqjp85AkQpUmojbzrTrllBuZfFP2EVv3JwGgxfpKnNPeT332PrSEOSTtmi43khPNCVWm1MRY7miGmXwcvs5D67okeqcYU797AhgwI2O6AJNOjdWAK1Xn7KgBfxj7a31WfDqQPrdwGSwZfQ4ssBF3nwzr7qDkJ859StqC8QIZI6eycCvvw9uYkXTuNBU9yC4SNfoyefIvbC9SghRnXn+T8rYX4halnPC60En2WqLqnK95t+0Dz2EhdPMJ2K8YscynoNqTZ9Bj79u3ClUnd0GlvSHiRenvP+RExz/1uOD9aipGmVXrFCYR7JqJLmkX11xq5JetqyqHOY37rIH0nP7lMeprAxBHJBGrl7iH9YXYUe
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: flux-system
    type: Opaque

