apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBGuZJT8fpcywJ5mduRy9VJQ79CyD4yNqEuirwf58ea3y72SWKrholxelgW7R5U12P+z+RpNZchMMhCt+RqEhk2yD69xXTdhjIHTVs3yCWsRQ+JWFZeVP0OrdawCh7/gm9mkBL84ayJ8qgTey4JFF0t39DxbXlJeLXhhlDZxyCFYLEslllMnu8eA0GMWg217GDtc/rQB1CkQSwk/H2fw8tFnZPugQjccnJPAA++oaVWcZoBm1bWibvpt41yXJP7vRleUoUWeUjAe8dYxzhMnZWYSvE0VlLuOGE47iLcHFWoN40tHXGa8UmEAFCK195sxB41RU8HMdDw6PAFOzBfBn08neMxajqXF2QuzWquiqVo/w9FVi/w7IWfAeja4b/sT9OiHMtujDDOnRewESuugcjzNpjulMn3ncm/76ZEN258i0zc4NspyMe7+py/zdGRn+l+Y5KRPtVyuv1/utYorj4tvBU7mIVK9K/4C/l0bMC9VbKc2JnZ17dBFcFcteJSBWj8wWB2jV4aZK0bMytTLr/KDjh7XsaQQ6cqZg/tlKvhljiUo0oZXKWGEuiJfFDEJQbT2NvWfKpBVRN9paX7KApbYacV6HcfPdLvFVWopFM9LSoWY5VWavJfVx+GcPabGlc5sEUfMsaagFQuV6tGP7rpPPRe+LyPDtSrRk/7MX0tEagx98mdknPajibVtE61Ieh6Gv1frCl5nwTJflFt0ER442E6dQ==
    AWS_SECRET_ACCESS_KEY: AgDgP/id9HRBLD/3HCQ4hGzkbUCqj9s0lvrfhqXrjt9HlrPpB59LtqTng+PlJwFlRULnSSBZTbLsbDSagmTP0+G07rTCB+7p7SZagX+0AmpfN+we8eM3+YHDkzb0E6+ZxX3cXEcOJNr38fxWfX0NXihHL7GD7KpUJkOIVylqH/Yrc6iSh3YY5Um+VyITHtsEnFImYwGNr1ROHTrDDF0t375TzzWD5xnEeNFAjPpzsciyu+wKp5XEoLHgl3JtNc6CpA5UH3JAd8TG5zh+rAlJTd5nZg1cV4W5Ez0lSb/MxncsHXhmi6xsAjiBXlEsqvsUrWWNc+5OxBolMh+IUuUuwVy3Tj4jrP6jVmx8dDVHWAoE4RU9+9pcYG1zYcERk9aYKKpr71/WrkJrvhA1fRZ6gcv6dLKK+R4BnQhKVo13iFQGgtpvVFatTFFe7vD6ppD/cHAR1mnk5x0wFouy0jK0k+NjtsIyerpx2AcQJaawfg/7c1zJASHagVMEq5YlTZEtoR5G1dqhO/go6YvhSrn0/0nre3m45rBcvgLw42ftU3sxa5gOMNaXUf3E5WapkFIgKZ6VpNIQdUmlOStSp31O1msDXfQ+Z6HilwzNCsW5h4786+bQmkOxJGgWpOL65BX4ASt0mEsgwlNHX79wR7Hw1OBuWsVSPLm9B+EX+CrD5mtYf3au9ycJwdk0bHg7vDZyZUw4Vzta74SrHTIImzlR3yjgc+N/8eGBRaymjmuCCvmKL7BIXKU5YLmG
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

