apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: aws-flux-credentials
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAi7Nw1s79LOCD5j2xSjdSN9uLL2InEm14lYv3e/KopxCtNqJMNiDL/VgLEy+zrMMjep3IAFEig0z1yA2FZCEW+I0FnKFDffFBsxhzQJtdhKpbbS8x/9l+/ewQT5NPpEC+RdZCFB+gSqFPyVCfAliXIxj5u2UVB/YP1KYexsZzkL78/lRq1iX/GcsWOlifMblANNgPUkwzvsMm3zK+beMPYLoq0Wj2RMtVXC071TCcOjBIkbnH8DBvNed8ylWnoBuAd+7BtH+DZYAOtyeRlvAVE3j777XSpcP/Y2zusy6fbkZGQoLMOyZHfZmIA14JtCfzrrf2853b95gcqh4Xyhrh36trxqYhFBPc3aBfGvy+bkLF2K2MPq/Sg7nEgCJWuppOfdKLE0+rI+YnHA/3SxXEg6a/Wg5aSoCqu5yETNChaGi/aJ7Sma/axY2mElwUGz4t+bi1wy2DzXP3vbl77jijIl1fzbb5uRd7atTNASKCpFrJKcdVgvw06tCIQpXiVR30/UjYG/SC+0Y/tI0N+yVyS7cunixJBt6gmjxjfAdO/76utbyC47Myr77sKZjz7LBCqU7H2+e13GgLxt9fLewvOcajaySBp2fvMi5FzIhvEURj88B3M0YZiOOqEz6etdDoTVBuTyPNGOdt8wgUrINAoIcHy2YJBwwM4YbiREQulOcl4fbbfAG5Z2cK3Ldkh2h2r6xkpwQYFmvvZQLMRuiMd2d77TQ==
    AWS_SECRET_ACCESS_KEY: AgAJPBSOqTZheULZDeIUS8fqUiu5RWSvTalbN51n0Y006QVrUj9TclpZ9/EWBKVJalV9Fp6hcAL/OsvMshtGtNwGNyc8l4ra6MEGxakhlVTUlqA4LrgylMWDGmch1UgBiHhQe/K3zF8NJ6MbkW0cmM6Jlq18+BHdjoSGcuMoq2GDPOknVD24TTGYWSgdVHZGGsdHSSXGFgDlgyirtuHKwQO+1xJIcQzqIir49kyj0xbmVRSa86o5q29sxXxII241ANh1IdY8kDYjad3zw+I7izf6u2pyFyIM516flogfY5uwMREvqpAKUXPT/vCfX5MSwmYBctdVMhlHxLQtCGotUzrQCMFWY03rQLzkORQT0MbG62oVyvKVS1zYoKH54cAF8vQQcuXOpA8A2rMHyQCoYPjfNUetVQRlJaasecmzIJTLqbpV7w9M07A3fnpOcvVIy5UOIKhpRHefHLYcZW5zUOvBbtP/U5Ewt8Ll+UPE28FpMrDzbsBswegkfBOJBHzhJm+sW0ng++O8L91LG6UxHXPH2xFx2bvb1arJFpGtMmY+ZbW6p7rpXQyAgiWUDKkhT+SbWq6ayP5pYMQIvviEnJT5dRTsx7YwSL/+xCrp7dnAARZqmTo7A6a5sXK1OXDihVnznocQa5mflN8QbKchscuN+9yS1KEtTlc/rhcSieCv/tcvUpwsR8sPW7JIoIU2G9TJluM+Gk3F3gRxMRlrtsTW8kRnyzm3vKkm0IlNsiPZAhVFjCVi4ReX
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: aws-flux-credentials
      namespace: default
    type: Opaque

