apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: datastore-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAlUQ+5DIe4UiLmr24Y4mgxt8oGom1XhHofRTpuwJdN2GSH6FlovHjYOCwGIo3OvX4qyh3+I5KMxCsaKTzSMwTqWV5cIqUT8KOsUI21ZKaA9gtL3bTNw/J2Wrr35iEHjqpF6rKmAGT3VKuvcCCjqv10QmIAMeK21qD5K9B97Cv5bJRR7ldg5kFphLCrTQIPrVdR+FcVxQrH+EM+l1yOYFqZosbl6ZmfENMCFHPSNtGKD2R5a4JcfU/WmytQB2ocYD8iMEN/JxFiYZc3NiiQHFdM7gEF/72/jsbTu7+Z8bD1j/UxnJXEeIeSoqfIvYPk6cHOWVaxiD2DgaKmBzIqY9TQdQorek1LgnMRDYG5zBqWbibwmV01deNXJOMKwO21O+5ru6n7HiuHXf7d19QyKRr+83Q/04hH3ZdTSOlyS/fwgpRR1+DquAKFYvBWOsClJ32vGi3eMy7q/5ICgWuR0etwggPj2Ng0XatMXRg8/x16JAgZY62Vfq5Ae44DWSrpmhv3FPQh+BFdaUsym0Ok0+3j7nrGUs4YprNhnD1KC9IsgbeRwERkIzEiFWA2o9FwWlXhHjq3Ll2mqhj1zxYHebT5oSbLhAPLy1lMZgQ9SyXZr6rIv9aPH8AlH1sTRheOoxDanIFPiwKkNm1VB3YqT9UW1DgsChYQXLhC/9ASWE8YE76JP7qwP9/MwYxBgpycVTmr++LOgtlmRar5t3UkMggdGFQUAaRgwE5aR19zLeo7w6WPJgKHxyYF7nlYir8Fv4BZ3JfT1vAJt8f0od+7jA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: datastore-db-url
      namespace: default
    type: Opaque

