apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: iex
  namespace: default
spec:
  encryptedData:
    IEX_TOKEN: AgC/0YoW4CEiJH3Wh0N2UMsbZk8bKk4YOLZjFLieRhnWjuzTfeaVu/QMfcGESX6m2DqMW68TKP5/OLooYfUFRE0vmFftQkmQi21tGMOUTqtf489Xo3kKQvwnU1dLo6kFrnHFIrbQ9imCIL1HOF7/pR9FKllH/PInd429uNiRvXB5JCwe0gfuEgk47iODkZ9Ir4Q3RNdneXsUsuERI4BztiOQRWO6QvpREObY5ksCqUH4zlQJnT/RJWMb8wMMoGSpfmzwOCIrRmCAWcTJhz3324NeMRGt/8a3RGyTcxHqPF6iuzVDZzYGortD2YZGpeASX0PuScLib48sT1IIExUgDR88G5mIXyOJBvhEj4OdIbSnMuh4VFRPZLg5yKlhmEIyDZ64CEkLG3F9u2NSlQRGD/t/MMTP1dV4fHokO9QiIzN0ag0635lan7DPSbzMf7N/tTDoTMAmQmqhMfF2SNlMTpO4HGuhoVOqrEiiE6/TnTgA6JyUa+r2KrpOyKys/sZTiE6w5vuFe16hVL7On9/E2k+m9JZRCKSSD8PK4EUm0qIrl+gM4TMYnBOvpLSFJkUEoXl5akLPAXs4MP9ZeLLH8zeryNM1cwEvk3TO9ewV0gDv7QqN4l7/ZrJLdoao1Z97rLcmUdTlxwynsWVKUCcgKFKWfL5r/ymRYCRE+NKBQE2hw8u7b6v5pSE7PZZVx0exzg1RCZd99AY8YJ9GjL5mJPt4unFn0rMVQKksa8BEiVMTBLrY2w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: iex
      namespace: default
    type: Opaque

