apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: kafka
  namespace: default
spec:
  encryptedData:
    KAFKA__SASL_PASSWORD: AgAEg++CA2D5BZvrx1uRLMLJB7McVSQh+XDaHlgZqiyAU1uMHYGKeDEugFmLOayVK10zM/Gei5iT/gM+rmK4CPJuvjrUNJTmRiiGkEA5RZNNAXWWQ7gcpnV8WLYcf1Eqs0vRq9kq+7mvEG2T4oX85zz3n0DI860xJh8ddbexxWApS4spVGStx0NUUb2jsv3OYPEA2GcKSsEVQD2HPq/bPKmbnl9cNFr13/GHLl3eztRCExh2lxHdgOfeKVt4eMs8aGZcZjOQ+JL7JYgEdX4U4aZ/E6nJUuONlB3z5F02HiJr9RgqQYnIiCShfSDdkeQRifvU3s8rq8q/u/BziN2cxRMWxwNG0CyVqSdNkx+sRch+hJ1UErqsiOJhLpFQUGusO/Rv+wQk2pcIs7BItEiBwH+WnLg0zebJzOK+KEO8SZ1rzk+1Hek6H+fIY0XeDa/IU0eb3NvxBbOirzW2odo8fQjYNEswXjCvY0S5Y9+zJDAxYXxbpAD6j1cCZe8Ysn+6dfmYQ4IvjJio6wr/JOWeRt040FcW3JLr/3lQhcXnN13mdVQ6d0srKfZ+xlT5jMrXzGX6yGfUm62S8cabLik8cg98NiTirkWNzLze5nrlSuWAWJvpV70j+Q+EGubUsK2fcbNTUo3r5bZv7yqB8svKopSaz9hssok28svVeJp+K3d/YpZ8Eiuw9IIt+VoKjkm4UGWIurL7lFeDJ4l1LFc9S1QKCaOlRRodIaQ1AkVSWg7ebvTDtWKXFze4HjW/Yxcz367BRq0rhX+lVHvagktbyBKJ
    KAFKA__SASL_USERNAME: AgAJcH7zTaRf8KeO8zD1jPPN/8ztrxVoZqPQ9Jf1KLnxuYOHN4AlKP+d5EJmFoZ5nwy912DZkrYVhzXmRJv9einSobC7uBqS8JQfEr1JsS8ExOfq52V5S30j7QTfO5JjB8hV3U9XV06mTkmofWXbfTgff/ESSM3porcqhiqaat0PmijQJkw4AYOX86/LMJAjYGXvPwcnqUu6tQGxBU4HVQG8sx1M7Ysj3ZOZoNhGjNLx1gOhYkNlrhf8y/cCEf3wsmhMAlDfbGL25A33GR75AGwpX7daF1SRrjIZdfkIVQEftBWeK6MGzbeXeclI10XLLINW3yURFgszmlLjqVX40pDCMRvouSxGYUoiPfAbkbmTc5oW/i2om3snJiqQ8kapI5IkvH5ebF2lmGX3mPXF6qxNfWo+71QhFDb4RAKQJpTjw/9rRS+X+9WVHtAR0t4woiDAeIYFUtz/MPQs1Xircviuh6mN2V3/TFBcHIb/441S5LIXRoGeThQllu2kLt2sMksgRWfzN6W6rphbZ7xSWY6CKPJTZ4oCC1gRhPzJzVJeW1ivw1iQPl1Nbz6OWuqTAD18M4qGl4KqLWyPpxi6Nt7Ya+ZW67OPZWgaJDpgWAQZjanOWuoeBYgiLD5VCMBWpxswcPue7ee0q0HFR+8cxska+l/R0nBc/2rMB0aGXi7IJLAGt0wYGnVxkSr7Wqfpx2DIZRUxovvi5ej5WDR0MxUt
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: kafka
      namespace: default
    type: Opaque

