apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/config
configurations:
  - configuration/sealed-secret-config.yaml
configMapGenerator:
- name: alpaca
  literals:
  - ALPACA__BASE_URL=https://paper-api.alpaca.markets/v2
  - ALPACA__STREAMING_URL=wss://paper-api.alpaca.markets/stream 
- name: kafka
  literals:
  - KAFKA__BOOTSTRAP_SERVERS=pkc-4nym6.us-east-1.aws.confluent.cloud:9092
  - KAFKA__SECURITY_PROTOCOL=SASL_SSL
secretGenerator:
- name: alpaca
  type: Opaque
patchesStrategicMerge:
  - alpaca-secret.yaml
  - aws-flux-credentials-secret.yaml
  - aws-flux-credentials-secret-flux-system.yaml
  - database-init-secret.yaml
  - datastore-db-url-secret.yaml
  - iex-secret.yaml
  - kafka-secret.yaml
  - ordermanager-db-url-secret.yaml
  - polygon-secret.yaml
  - slack-secret.yaml
