apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ordermanager-db-url
  namespace: default
spec:
  encryptedData:
    DATABASE__URL: AgAqYd/eUWwwz6+OlZpqYNna6pbsBakrFbA/q5YUfRgN8SYZUPYMZbL6pKfzUbTpm3H2EjgX0RP274x7FP1dUAgAC9VuIDOhDfLSiMRRNgSuz2/8T/1D7ZI+nq6w/3C5k5VpGp32BoEbE9H3lpEas2fTiE8GhninswTMxNzY3+wddKlZ0hR4BIepgenPjGhwPI2ldKWT96LvTfIoXB+NwtYSlZDS4fAN9sbWxtUY62B0K9T7GGUUBI+aRSs1dPt+JdIw+w0yTNR7BqjXqXEMuHDJvqZnYK69DX/6K0w7Iv5Y9xqtr/CMod6E+UULPidlGTMpUgAciHErFBXOMZ0ipPo6DzkKFvoRzW/cgkWaJbIPfYBAI94RpyR5YDy1x14ACTpbISrnoJihZfqWm7GsBC6sN78VVE5T/ogMf7ldWZCi7+8O41EPU8L8pDWHheL1PaIo37iM7Phwmmf19Sy7tzC1EsBb+HGOP6WORrxgYSpeQ1A1kek2zUGnSmpiI6vnf2BQRcCDdE/SIbQErBuGsIg4QDGiTYXts8yeSHPX7nX3TstPL14PldQXk5CHVW2U3xqSGjivOo6m5JL5mu/0ruRp5WU/nSvRx7a3WlsojgUT10zwiGdDDct064ClkP4MLLCkkitHcBO0dWyb3taxNm+9CxeoeqzpVUXtQMQjSsl6oz/uNgaSVPJLEVMi8t/qdODgagRFuvSk3qZWnDfv7og2PXriG3lT6bM+T9OWETcGVuKmWTlu7XSNxbS81olGZQvw67a0fifgIobiZgbetwbnKA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ordermanager-db-url
      namespace: default
    type: Opaque

