apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgAURq3Kr9kf8+aOVlQp5/BfMQpyfaCv9AY4ILbvPwwzvhmwXbLKGyA4j4jDfdugRCVOl75ldu4NSF5EFeJnmyluerGy6e2D9Nv0xXkL+FW7nwXysf18p05re999hynzdOf6G5JpdnuY1G20TJbDffpExt3Au6fiOtHQzgIsD/8kBnRr7cWM9ad4sDzuRmtmtO79bP7zI0nyr6dQs0cBk5CA8jEcp5WwgQHN0MSIC2pxBJOopkI2/2u3vmYsmoz9TTH4LO/E6ROCHU2TqUhO08PIq6Uds69EnRArNrV24HLtDNU6KBSWH2GrHkfw8/NnrFut1ARxmjx2/gVjjLhsYIADIp/7riiU7Mav2f6GD0895fEsu1C51dO1sotGHTCyD2FackYYx6KodqYJ0KOPGss721MlspFiGDJBeqj2J9+sbbNv2R6j8OkJqH+1JgLj41wAJu8PN+8rpByR+srDXfKvJJK3N0/TOFIDaJWkltx7WQRXFh4a5SX55tP6aW1CA5iLVJsF0+vzKReRagAMWhjeaexdv0t+N6hQqMav4qGjR4ufmPo3vuZkJwsjheWJV0ANT9ylAlU0lj62FFb92qB5Uat1H+UIksg4ORiD2pVjPxenY8ylCJa2olKI7caDsP32vodQ1gWch4cpBf/biHtUYEjO6cQVZSOs0MYqUfufAUhPKS2krMZu7yAX7OvSRnJcdt6oHCtX8BNr+8gIYuC3o8j7Lh9eHzjVaaAB2fgvtw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

