apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgBDrv1vm8GQhsks4WtyplAB79KFWikkIQ2Mxh5xTVtrbocWl81S63b6W5oJFWD4pok4mwQq0SAIZaPgpGpvvKRSMtbaLlHad0BsqV4PHz/yY0Qzz87QA4IF/XfFbZMTS+7iUZT/sbWkw2bzJns+axtSsauyjonfvp0l3UDvrwJQ+l0DgO7jeF3ilWoNOVyzLWhLiZYimh7vs9bXIVUs22uMnLAaF44m97WXZQICv8TVl6+ZvUdZxVgs+dZpjPJqDzPtTIkFPO/h94WWO3e3MMEBYXbGrD8eN7L9QeL2Ym/b4g1+zr+2+dQADMxbUtIITD+DoUahQvke6+gckqYxa6aY+U7qxkvJ2TiVglIhMEsD+O+O7nOCM4IfHq+LjhqXiETMopFUAbQS7zbqHqr8Hs7l3UaK9wSfN2kW1NW8h3DX6DTHB5YEizWf8v2BdwaIcm+WLPOeH6nSta0Li7dpMOr45Uq8z7EGO3BWji29gVJo1owGaelJvM7WDM9/hvPdGpDCKkKzC1+/m5L4iD2WgYedY75/bARQnLieLfVBxPfFAko28ZHVJvo/d0ylz1K+qZEDScPLjzvam1KAHIi4LMqIzh1q47nX91XdqwRRnDHniye81BD9kGjDBTYsz2VFoC/UgrKJRU/wktsrlO2D2+ogsf6Xp7e2me1iioiqL3CgNeQidLcf336cgUq/n0hm0YCB0ZwUMiyvbt9oxEcAMixIW5XF1SDEeTnXunCi8MNF3g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: polygon
      namespace: default
    type: Opaque

