---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: polygon
  namespace: default
spec:
  encryptedData:
    POLYGON__KEY_ID: AgCtKi7SVeDNMCDbg6FEUDbERZVjRWFfZ0kziQ2sJE1C+TYQi5AyA9m4Sa7kyPReADnsJ9v2+XLeS9dyFxlNDawJ804CVxKISzPXW09S4uIyWTHBtD//3zNV9TIVSc6G25WaMDoMO5walhs7Qrx0Q8ENp4MueZnAllnU3eKVPoBVtV0EpRlIcrUT8Q3R/JkBeuzyUadOrX0kZMi51Qt678LOGV4gsqZwp/XG7sI9Wozr3hwjAkvF7YuxG/DsW4ii9GFaT7xLKtezme7zPGPM1JfVIxrlFf503OckGZ0Sv+FvV9+un9PatguSVa3zS4tRyMjk+vX2w+juW8IS1GgfXUefW/hP1mr68tuqeHPTjbV3IsA6/SdR3D4cxPRRhwMfNsuBMIOsem079XjkOpO2ez+uSfvRvzi7dt6pKIawqFI03+pDTHOmW6+xzlnxMWqgekMfyLgyPQb64T9GynI/eBL7x8+ww0PbscnCsubj9EWFCeqHO0xWWIu+eZ0sFVUPxzCBTHDohLc9/HOIn9rQi3l7PJZipI3PinhFEOc6wG7eNYqFkMMAn587MwmWKsczjmhvNrycMf04Sv3y3uaSlX2NOhoEV3wg/VVSZ8OYuXrFXXoZvPZhgqicBLKWvJ61sslhZyrnxDwOKXUII7YgWfzccW8HpBrY7poqTFVgllIB0URQFj5C0I98EpNcUzUh0y9pSG43DehFJNLz+zXqJ9eSTEg7cbaghoywap0881bLaA==
