apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgA/BWW4K09L06/gBUN+sYYhldcrMzSJl0lr43KopwzwVyqXv+81BVrDxlXm/0BNovgrwnZVKieSPkV30kRLA2rYcN6rUXQ1uK73E7a9vY0EciTC/NqVNccH6ZOuG94/bHzlBXPE0rQqYa8If+FsR+HD2VADz+gHxGsI0qiXAf88+nYXwJwb3Q0qb8RK/0QdrLMOkRBKK0INy17lE9g9fbyVX4DmO4lMQgl8158QT+ebebhxQMnn1IvomypyH23xB6YmynNFhyjQWmFxvSnUEXv2KGY8FARa2aM+SPgtnuRu4gwOp66UV1p+sVWOxqU2TnIIWSGMZp0pZPibxAZ2SToWYKSUjmGScbqdwMCCGnkR4arZcVzTsKEP61jO+8+OJxVjEHQPFfLV3fNnjHnUqM5ayVlW5H74ZJ+tUee9x63MHN5d/ioPKl3LWLDaGHXamLPHhXXB5cJnTt9J3xaFmPOsf+YFqDg5dUNPVUT1NBn0Cg0WOi0GGQCTgJxYKdyD2WZIViZB7DSa2FQNS/oeYLpxQZwpu4EaMN8T1nEBvPqUAJkYm9GqEs+axkFmgHdTNQE1Z4hvBFym44npbTztEv3asbB0UCkmPzASVZAcy5FCF0g8ga4VlZebN6ckrJVXLP5yZqAVbfCxHM9a2jaMAeGKDUwxwRGSup18iZVRQCp8lGWIcRk9qttnjjGF7wlCjvvOBCMYwSKXBlEMietNVr5HJobgVb0oCv+ncia7qzxwzB3ojTVIZup4nEu7ETZL9X8kBW/d9oISZEMz4hGvt88WGu/yOTXxxxV1rceP10ulL3o=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque

