---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBbGKmT+cHFdHherF77hNTUprgWMm4QAxedbvwKZJntcSOBNwqMk+MEbW7Ye3aA3lK0iQsE7q/PTCjdIMlt0zezS8unEzKGYD2cCBjpmddOifL2kYx/pU69WcgTghxRZZaHV3uNGL1bpF3DFe/22XvJkYU9j5yJLWEMKto6En84DNHGMRoPltw3zpx3ird/pWmEGt+cKxrnTsOsdILPiMVPdgdeg3IYnU3LvaMUm9GMv/egoO3nEGuy8DMvfdyWdzQE87/uclsjkYy+XerDU0n5O+dcRkfcQ+JrjnE7z5Z0zl7f5fIIgiMJPxpy7lpAA5HQcDi3j4FQ5hJIi7UgleFI+wOxcQp5BdY11WQ7XRhgi7LFMncrgOxEq4nrSBld3LBiuBxsSS1vMYC3dKbZI/O7jTUzEe6VgXgS4m1d8ZjlTev48nbhnybTJLf91HT0WywMqy6PhlMf3TF8/rX2UIOcXoSij8joaLIqQpcagc09IH6DPAhHHmXll6GPEoEVZwLUtsmdd6ptS53bse6QidEqwjmRUu/88iYOH4ACR86Z9vJ9fbH4sI2tx9dmxOJVjsY4Su8sdiZEDXv29OwvynX0Z8KMVW1QR1YFe0wX0sHBl8lwob/n+vKTMnj3LsRBBAzQn7SmasIHFlCocq6F1Ak8dF1Mq16vjo8PWwS2GtZm+q58XYwYUjIZskEuWTt3UzI/cV3Fdai5BwqjWfofvM+1b8tYVkD1HwGg11hsyigvBnCYsC/ZI92VB2Yre4HZRq33v7OB9WEThlXxbKD8aGF5yWBvtet87+9GSUw9o8/OWKQ=
