#!/bin/bash

list_files() {
  if [[ $1 == "paper" ]]; then
    echo {secrets/*,secrets/paper/*}.yaml
  elif [[ $1 == "live" ]]; then
    echo {secrets/*,secrets/live/*}.yaml
  fi
}

for env in [paper, live]
do
  files="$(list_files $env)"
  for file in $files
  do
     without_prefix=${file##*/} 
     kubeseal -o yaml --cert secrets/$env/live.cert < $file > apps/$env/secrets/$without_prefix
  done
done
