{
 "title": "Double-Trouble",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "asset1", "label": "Asset 1" },
   { "name": "asset2", "label": "Asset 2" }
  ]
 },
 "panels": [
  {
   "title": "Band ratios",
   "type": "logs",
   "gridPos": { "h": 28, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"double-trouble\"} |= \"band_ratio\" | json | line_format \"{{printf \\\"%4s\\\" .fields_asset_1}} - {{printf \\\"%4s\\\" .fields_asset_2}} : {{.fields_band_ratio}}\""
    }
   ]
  },
  {
   "title": "Band Ratios",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time({container=\"double-trouble\"} |= \"band_ratio\" | json | unwrap fields_band_ratio [5m])"
    }
   ]
  },
  {
   "title": "Top 3 band-ratios over time",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 17, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(3, avg_over_time({container=\"double-trouble\"} |= \"band_ratio\" | json | unwrap fields_band_ratio [5m]) by (fields_asset_1, fields_asset_2))"
    },
    {
     "expr": "bottomk(3, avg_over_time({container=\"double-trouble\"} |= \"band_ratio\" | json | unwrap fields_band_ratio [5m]) by (fields_asset_1, fields_asset_2))"
    }
   ]
  },
  {
   "title": "Position Intents",
   "type": "logs",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{container=\"double-trouble\"} |= \"Sending intent\" != \"Zero\" | json"
    }
   ]
  },
  {
   "title": "Stock price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 28 },
   "targets": [
    {
     "expr": "avg_over_time({container=\"double-trouble\"} |= \"band_ratio\" | json | fields_asset_1 = \"$asset1\" | unwrap span_price_1 [5m]) by (fields_asset_1)"
    },
    {
     "expr": "avg_over_time({container=\"double-trouble\"} |= \"band_ratio\" | json | fields_asset_2 = \"$asset2\" | unwrap span_price_2 [5m]) by (fields_asset_2)"
    }
   ]
  }
 ]
}