---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: polygon-data-relay
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Overmuse/polygon-data-relay

