apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: timekeeper
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: timekeeper
              image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/timekeeper:v1.0.0 # {"$imagepolicy": "flux-system:timekeeper"}
