apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: datastore
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/datastore-server:v0.5.0 # {"$imagepolicy": "flux-system:datastore"}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore
data:
  DATABASE__URL: postgres://postgres:0Fq0C*F6DtAb^Ks^HsxdhZln@live.czn6pu2ebanr.us-east-1.rds.amazonaws.com:5432
  DATABASE__NAME: datastore
