apiVersion: apps/v1
kind: Deployment
metadata:
  name: polygon-data-relay
spec:
  template:
    spec:
      containers:
        - name: polygon-data-relay
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/polygon-data-relay:v1.4.0 # {"$imagepolicy": "flux-system:polygon-data-relay"}
