apiVersion: v1
kind: ConfigMap
metadata:
  name: timekeeper
data:
  KAFKA__BOOTSTRAP_SERVERS: paper-trading-kafka-bootstrap.kafka-paper-trading
  KAFKA__SECURITY_PROTOCOL: PLAIN
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: timekeeper
spec:
  schedule: "*/1 * * * 1-5"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: timekeeper
            image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/timekeeper:v1.0.0 # {"$imagepolicy": "flux-system:timekeeper"}
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: alpaca
            - configMapRef:
                name: timekeeper
            - configMapRef:
                name: alpaca
            command:
            - /bin/sh
            - -c
            - /usr/local/bin/timekeeper
          restartPolicy: OnFailure
