apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: kafka-paper-trading
  labels:
    strimzi.io/cluster: "paper-trading"
spec:
  partitions: 1
  replicas: 1
