---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: trader
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: trader
  policy:
    semver:
      range: 1.1.x

