apiVersion: v1
kind: ConfigMap
metadata:
  name: trader-cm
data:
  KAFKA__GROUP_ID: trader
  KAFKA__INPUT_TOPICS: order-intents

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader-deployment
spec:
  selector:
    matchLabels:
      app: trader
  replicas: 6
  template:
    metadata:
      labels:
        app: trader
    spec:
      containers:
      - name: trader
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/trader:v1.0.0 # {"$imagepolicy": "flux-system:trader"}
        envFrom:
        - secretRef:
            name: alpaca-secret-1
        - secretRef:
            name: kafka-secret
        - configMapRef:
            name: trader-cm
        - configMapRef:
            name: alpaca-cm
        - configMapRef:
            name: kafka-cm
