apiVersion: v1
kind: ConfigMap
metadata:
  name: trader
data:
  KAFKA__GROUP_ID: trader
  KAFKA__INPUT_TOPICS: order-intents
  RUST_LOG: trader=debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader
spec:
  selector:
    matchLabels:
      app: trader
  replicas: 1
  template:
    metadata:
      labels:
        app: trader
    spec:
      containers:
      - name: trader
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/trader:v1.0.3 # {"$imagepolicy": "flux-system:trader"}
        envFrom:
        - secretRef:
            name: alpaca
        - secretRef:
            name: kafka
        - configMapRef:
            name: trader
        - configMapRef:
            name: alpaca
        - configMapRef:
            name: kafka
