apiVersion: v1
kind: ConfigMap
metadata:
  name: microprice
data:
  KAFKA__GROUP_ID: microprice
  KAFKA__INPUT_TOPICS: quotes

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microprice
spec:
  selector:
    matchLabels:
      app: microprice
  replicas: 0
  template:
    metadata:
      labels:
        app: microprice
    spec:
      containers:
      - name: microprice
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/microprice:v1.0.0 # {"$imagepolicy": "flux-system:microprice"}
        envFrom:
        - configMapRef:
            name: microprice
        - configMapRef:
            name: kafka
