apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trait-finance
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: trait-finance
              port:
                number: 8011

