name: Deploy

on:
  push:
    branches:
      main

jobs:
  Terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: 'terraform/aws'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_TERRAFORM_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_TERRAFORM_SECRET_KEY }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: 'terraform/aws'

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: 'terraform/aws'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_TERRAFORM_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_TERRAFORM_SECRET_KEY }}
