apiVersion: apps/v1
kind: Deployment
metadata:
  name: double-trouble
spec:
  template:
    spec:
      initContainers:
        - name: double-trouble
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/double-trouble:v0.4.7 # {"$imagepolicy": "flux-system:double-trouble"}
        - name: process-data
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/double-trouble-jl:v0.1.2 # {"$imagepolicy": "flux-system:double-trouble-jl"}
      containers:
        - name: double-trouble
          image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/double-trouble:v0.4.7 # {"$imagepolicy": "flux-system:double-trouble"}
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: double-trouble
  namespace: flux-system
spec:
  policy:
    semver:
      range: 0.4.x
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: double-trouble-jl
  namespace: flux-system
spec:
  policy:
    semver:
      range: 0.1.x
