apiVersion: cronjobber.hidde.co/v1alpha1
kind: TZCronJob
metadata:
  name: jump-diffusion
spec:
  schedule: "30 09 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: jump-diffusion
              image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/jump-diffusion:v0.4.7 # {"$imagepolicy": "flux-system:jump=diffusion"}
